### ISSUE TITLE
Important bugs and Suggestions

### ISSUE THREAD

**Issue by Karkande** [kangarko/Boss#10]
The plugin is the best for customize mobs around the world, but i find some bugs:

1-The particles of the boss region are still seeing all the time (unless you restart the server, the solution would be a 10 seconds view of the region using the command '/boss region view name')

2-The bosses dont spawn in any region (boss regions, woldguard regions, recsidence areas) https://imgur.com/a/tAls3 The error that isn't recognizing the grass when in the region there aren't blocks of grass

3-The skeletons dont shoot arrows because the item in the hand is not recognized https://imgur.com/a/uklLP

4-(Suggestion)  In the chance of a boss in a world, it could be more friendly up the chance in 10% to 10% with shift + click

5-(Suggestion)  A skill that let de boss teletransport to a random player with a certain chance

Is there a form to talk with you about suggestions,problems and bugs? Because the discord link in your spigot page is broken

Thank you for doing a great plugin.

**Comment by LogGits** [comment]
Discord: https://discord.gg/cC35PMz

**Comment by kangarko** [comment]
I have fixed Discord link.

Thank you for the notices. I am travelling to the outlands tomorrow so I won't have time to catch up until the next Tuesday, 2nd of October. Thank you for your understanding.

**Comment by Kimskell** [comment]
Does the attack damage count not for bows? I want to make a skeleton boss that shoots arrows that do more dammage. Power (I - V)  bow is also not working on the bosses.
Suggestion: If the boss gets dammage, than teleport him a certain blocks right / left or behind the player (if possible / no suffocation in walls etc.). Than players can not bounce off en hitting the boss over and over until he is dead.
Suggestion 2: **Drain life** prom the player to the boss if players are in a certain radius of the boss. So player losses 1 heart and boss gets 1 heart.

**Comment by kangarko** [comment]
Have you tried giving bow to Skeleton's as their hand item, and applying vanilla enchants to the bow?

Thank you for the suggestions :)

**Comment by kangarko** [comment]
@Karkande, I am sorry for the delay, here is my personal response:

1. I have fixed this in to the next release, good notice and thanks!
2. The "item not recognized" is unrelated, it is an internal debug for me when I was developing the menues. The Bosses will spawn if you enable Timed Spawning.
3. Fixed. Good observation. Skeletons cannot have nothing in their hands, so if you did not specify the bow manually, the bow that you would see was fake and wont function. This has been fixed.
4. Sorry I don't understand?
5. We recently added skill "Enderman", I think you will find it useful.

Cheers!

**Comment by Kimskell** [comment]
My fault, power (I - V) bow's are working fine. tested it some more. In the first place tested it with full iron on the player with only a power II bow. I thought it was not different in damaging the player. But is is a little bit. Power V test was more clear. In full iron 12 hitst with a normal bow and 5 hits with a power V bow, before the player died.
Thanks for this great pluginn. I have more idea's, but i will test it some more before dropping them. Maybe a few are already reachable with skills etc.

**Comment by kangarko** [comment]
No problem, cheers!
