### ISSUE TITLE
Minecraft 1.18.2 - Boss 4.3.2 - Error to change a skin

### ISSUE THREAD

**Issue by louanfontenele** [kangarko/Boss#1008]
I have/found a bug.
Whenever I create a boss npc, when it spawns it creates a new npc, for example, it creates 0, if I create another, it creates 1, and so on. So how am I going to apply a skin, if every time in Citizens, it creates a new npc?

**Comment by louanfontenele** [comment]
I also noticed that the custom skins reset, it only gets if it's a player name, but there's no option to add a skin via url not even using Citizens, as it always creates a new npc.

**Comment by louanfontenele** [comment]
If you don't have this feature (custom skins by url or name), it's very interesting to have it, the fact that you can add custom skins is a huge differential compared to other plugins

**Comment by kangarko** [comment]
Thanks for your question! We only support changing skins if you create a /boss new player and then give your Boss a custom Alias. All existing Bosses should get their skin refreshed.
