### ISSUE TITLE
Boss

### ISSUE THREAD

**Issue by LadyRayvyn** [kangarko/Boss#1011]
Hello! I paid for Boss years ago. I was sad to see it no longer being supported but when I saw that it was elsewhere I got excited again. However, I have filled out that information to get the upgrade for it, and no response. It's been months and I just did it a 3rd time.
https://prnt.sc/Nsteewsxfzcf
that is a screenshot of my owning the plugin. I hope to get this resolved because I loved that plugin and my server is not the same without me freeking out my players with a new nasty boss!

**Comment by kangarko** [comment]
I apology, please email me privately at matej@matejpacan.com with your MCMarket username from the email address you have applied to - I will check on my staff member doing the verification why you have not been added and add you personally asap!
