### ISSUE TITLE
1.18.2: When copying bosses from another server they cease to exist

### ISSUE THREAD

**Issue by KorweyKristof** [kangarko/Boss#1015]
Hello!
I have set up a test server and made my bosses there, but when I tried to copy them to the main server they didn't load.
I tried copying the whole boss folder as well but no luck. I'm using Boss 4.3.3.

**Comment by kangarko** [comment]
Are you using the same server version and distribution? Such as 1.18 vs 1.18? And Paper vs Paper, not Purpur vs Paper or anything else?

**Comment by KorweyKristof** [comment]
I'm using git-Purpur-1597 on both

**Comment by kangarko** [comment]
Try only copying Bosses/ folder when server is stopped. Post me the console log when it starts with Bosses migrated.

**Comment by kangarko** [comment]
Thanks, will be patched in the next version, just looks like some of your drops were null. If you will still have issues then send me your Boss3 old folder and I will migrate it for you :)
