### ISSUE TITLE
Remove minions on boss death

### ISSUE THREAD

**Issue by bipedd** [kangarko/Boss#1016]
**1) How it would benefit others? (Not just you, but 1,000s of others people using the same plugin.)**
I believe it would benefit others because of the fact that after killing a boss the players don't have to kill 30 minions which can be a bit overwhelming.

**2) What would happen if we won't implement this feature? How's your server being affected?**
It's more of an annoyance than anything. Personally, I have it so bosses spawn in an arena and when there are bosses spawning their minions everywhere it gets to the point where it's a lot, and could possibly create lag. I also think it makes more sense that the minions would die if the boss did.

**3) If suggesting something new - Can the old system be modified/improved instead?**
Yes, I believe this can be an option that can be turned off or on for those who want it on or off.

My suggestion is to have it so when a boss dies, its minions also die. This could be a setting that can be turned on or off for those who want it enabled and for those that don't.

**Comment by kangarko** [comment]
I understand and thank you, however for the next 1-2 months I'm unable to take in more suggestions because I work on my coding class. Thanks for your understanding!
