### ISSUE TITLE
1.18.1: Tools slots now saving metadata, but armor slots still do not

### ISSUE THREAD

**Issue by ReasonFoundDecoy** [kangarko/Boss#1018]
I updated my Boss plugin yesterday and was pleased with the fixes made, as the custom weapons on bosses now save upon restart. However, the 4 armor slots are not saving metadata. Specifically, I have bosses with heads from Heads Database and leather armor that I've dyed but after restarting, those items have turned into generic Steve heads and regular leather armor. I've checked console and there are no errors to report.

**Comment by kangarko** [comment]
Sorry for the delay! Investigating asap

**Comment by kangarko** [comment]
Sorry for the delay! Investigating asap

**Comment by kangarko** [comment]
Thanks, will get patched!
