### ISSUE TITLE
1.17.1: Performance issue. Lag spikes when bosses are spawned

### ISSUE THREAD

**Issue by ElFlyGod** [kangarko/Boss#1020]
Boss version: Boss-3.11.0

I have a custom plugin that spawns Boss mobs, I don't use any timed spawning, limits etc from the Boss plugin.
Every time a boss spawns there are lag spikes from the Boss plugin

[20:33:15 INFO]: [Boss 3.11.0] Spawn NOB_NIGHT_LURKER took 103.29 ms
[20:33:15 INFO]: [Boss 3.11.0] Spawn NOB_CREEPER took 52.04 ms

Here is a 10 minute long spark report with only ticks over 100MS
https://spark.lucko.me/rSz896eVdb

**Comment by kangarko** [comment]
Thanks, however we no longer support Boss3, please upgrade to Boss4.
