### ISSUE TITLE
1.17.1: Lag issue on Boss 4.3.3

### ISSUE THREAD

**Issue by ElFlyGod** [kangarko/Boss#1022]
I have updated to the latest boss version as requested.

The lag still exists. https://spark.lucko.me/Ihc6hqVswy (10 minute spark report for ticks over 100ms)

I was told that the issue is caused by boss checking for vanished users trough essentials

I need a way to disable this feature as i dont even use essentials vanish and its causing tons of lag.

**Comment by kangarko** [comment]
Thanks, investigating right now. Looks like Essentials issue, connecting to the internet to look up player info, let's see if we can get the player in a more effective way instead.

**Comment by kangarko** [comment]
Thanks, I have removed that call.
