### ISSUE TITLE
1.18.1: Slime and Magma Cube bosses do not respond to customized health value

### ISSUE THREAD

**Issue by ReasonFoundDecoy** [kangarko/Boss#1024]
As title says, both Slime and Magma Cube bosses don't respond to customized health value, no matter what size you make them. This issue is easy to recreate, just make a new boss choosing a Slime or Magma Cube and change the health value to any higher number and then look at it's total health after you've spawned it. I've a feeling that they also don't respond to having armor bonus and/or armor toughness either, but this is harder to determine.

There are no errors in console to report.

**Comment by kangarko** [comment]
What's your /version command output please?

**Comment by ReasonFoundDecoy** [comment]
> What's your /version command output please?

Server: Paper(216) 1.18.1-R0.1-SNAPSHOT

**Comment by kangarko** [comment]
Sorry, this appears to be caused by the server not recognizing higher values for said mob types, eventually you can check with your spigot.yml or paper.yml file if you haven't imposed a limit on that (not sure if there's anything new added since 1.18ish)

**Comment by bunnkywhat** [comment]
Our current spigot.yml settings are: 
![image](https://user-images.githubusercontent.com/6545569/162337452-26a71e5f-470c-4b1b-9b06-d40e6e385e5d.png)

**Comment by kangarko** [comment]
That's too high for the game limits, not sure if the game can handle it other places than Spigot since it was never made for such  large amounts
