### ISSUE TITLE
Boss Plugin | Citizens IssueMinecraft Version: Issue Title

### ISSUE THREAD

**Issue by itsdvd1** [kangarko/Boss#1026]
Hi, I have realized that the hp normal monsters such as spiders, skeletons, zombies, etc. are different compared to citizens in the boss menu. For example, if you set a spider to 2000 HP, it will take a very long time to kill with a sharpness 30 sword, but if you set a player npc to 75 HP or 2000 HP, both of them will  still get 2 shot from a sharpness 30 sword. I'm not sure if it is due to the fact that Armor Toughness and Armor Resistance is not a factor in the attributes, but even maxing out resistance keeps the citizens monsters as a 2 shot.

**Comment by kangarko** [comment]
It's due to the variations in attributes, you'd have to test the damage and adjust manually for each mob.

**Comment by itsdvd1** [comment]
> It's due to the variations in attributes, you'd have to test the damage and adjust manually for each mob.

The only attribute modifier for the NPC mobs are damage, so we can't really change the armor.
