### ISSUE TITLE
Add an attribute so that the mob cannot be tamed

### ISSUE THREAD

**Issue by NewJeb** [kangarko/Boss#1027]
I make legendary animals with your plugin. Based on common mobs, including those that can be tamed.

1) People will not be able to tame bosses and attributes will not fly from them (namely health, damage, name)

2) Then people will be able to tame bosses and they will lose all the settings.

3) Of course, you can add this function to the attributes for the bosses.
![2022-04-07_01 20 02](https://user-images.githubusercontent.com/50917369/162081896-85b4aff2-9dfd-4302-a453-94bf0f99f751.png)
![2022-04-07_01 20 06](https://user-images.githubusercontent.com/50917369/162081900-c9cbe8a0-3350-4e00-aeeb-35cef45cc339.png)

**Comment by kangarko** [comment]
Thanks, I'll prevent taming of Bosses starting the next version.
