### ISSUE TITLE
Boss Spawn Egg Customization

### ISSUE THREAD

**Issue by Bossimal** [kangarko/Boss#1028]
Hey, I was wondering if you could add the ability to customize the Boss Spawn Eggs (The actual item, Not the one in /Boss GUI) It would be nice to be able to edit the name & the lore on the eggs since they are being given to players to spawn the bosses.

1) How it would benefit others? 
It would benefit others because most servers give the boss eggs to their players so they can spawn the bosses themselves. On a lot of servers Boss eggs are a crate reward or an item that drops so being able to customize the name and lore of the egg is essentials to any server that gives players the eggs.

2) What would happen if we won't implement this feature? How's your server being affected?
Its not something that will harm my server in anyway or anyone elses, its more of a quality of life feature that would be nice to have

**Comment by kangarko** [comment]
Thanks, also apology for a late response, I will implement this shortly or in the next few versions.
