### ISSUE TITLE
Cannot edit the boss death drops based on damager!

### ISSUE THREAD

**Issue by itsdvd1** [kangarko/Boss#1029]
Error:

08.04 15:56:55 [Server] ERROR Could not pass event InventoryCloseEvent to Boss v4.3.4
--
430 | 08.04 15:56:55 [Server] INFO java.lang.NullPointerException: Cannot invoke "org.mineacademy.boss.lib.model.Tuple.getKey()" because "tuple" is null
431 | 08.04 15:56:55 [Server] INFO at org.mineacademy.boss.menu.boss.DeathMenu$DropsMenu$PlayerDropsMenu$IndividualPlayerDropMenu.onMenuClose(DeathMenu.java:456) ~[Boss-4.3.4.jar:?]
432 | 08.04 15:56:55 [Server] INFO at org.mineacademy.boss.lib.menu.MenuContainerChances.onMenuClose(MenuContainerChances.java:328) ~[Boss-4.3.4.jar:?]
433 | 08.04 15:56:55 [Server] INFO at org.mineacademy.boss.lib.menu.Menu.handleClose(Menu.java:1064) ~[Boss-4.3.4.jar:?]
434 | 08.04 15:56:55 [Server] INFO at org.mineacademy.boss.lib.menu.MenuListener.onMenuClose(MenuListener.java:63) ~[Boss-4.3.4.jar:?]
435 | 08.04 15:56:55 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1001.execute(Unknown Source) ~[?:?]
436 | 08.04 15:56:55 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
437 | 08.04 15:56:55 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
438 | 08.04 15:56:55 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
439 | 08.04 15:56:55 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
440 | 08.04 15:56:55 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:1507) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
441 | 08.04 15:56:55 [Server] INFO at net.minecraft.server.level.ServerPlayer.closeContainer(ServerPlayer.java:1598) ~[app:?]
442 | 08.04 15:56:55 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.entity.CraftHumanEntity.closeInventory(CraftHumanEntity.java:536) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
443 | 08.04 15:56:55 [Server] INFO at org.mineacademy.boss.lib.menu.MenuListener.onMenuClick(MenuListener.java:102) ~[Boss-4.3.4.jar:?]
444 | 08.04 15:56:55 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1000.execute(Unknown Source) ~[?:?]
445 | 08.04 15:56:55 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
446 | 08.04 15:56:55 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
447 | 08.04 15:56:55 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
448 | 08.04 15:56:55 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
449 | 08.04 15:56:55 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:2891) ~[app:?]
450 | 08.04 15:56:55 [Server] INFO at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:55) ~[app:?]
451 | 08.04 15:56:55 [Server] INFO at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:11) ~[app:?]
452 | 08.04 15:56:55 [Server] INFO at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[app:?]
453 | 08.04 15:56:55 [Server] INFO at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
454 | 08.04 15:56:55 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[app:?]
455 | 08.04 15:56:55 [Server] INFO at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[app:?]
456 | 08.04 15:56:55 [Server] INFO at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1450) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
457 | 08.04 15:56:55 [Server] INFO at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
458 | 08.04 15:56:55 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[app:?]
459 | 08.04 15:56:55 [Server] INFO at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1428) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
460 | 08.04 15:56:55 [Server] INFO at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1421) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
461 | 08.04 15:56:55 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[app:?]
462 | 08.04 15:56:55 [Server] INFO at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1399) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
463 | 08.04 15:56:55 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1310) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
464 | 08.04 15:56:55 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[patched_1.17.1.jar:git-Purpur-"08dd6c7"]
465 | 08.04 15:56:55 [Server] INFO at java.lang.Thread.run(Thread.java:831) ~[?:?]
466 | 08.04 15:56:55 [Server] INFO [Boss] Boss 4.3.4 encountered a NullPointerException! Please check your error.log and report this issue with the information in that file.
467 | 08.04 15:56:55 [Server] INFO java.lang.NullPointerException: Cannot invoke "org.mineacademy.boss.lib.model.Tuple.getKey()" because "tuple" is null
468 | 08.04 15:56:55 [Server] INFO at Boss-4.3.4.jar//org.mineacademy.boss.menu.boss.DeathMenu$DropsMenu$PlayerDropsMenu$IndividualPlayerDropMenu.onMenuClose(DeathMenu.java:456)
469 | 08.04 15:56:55 [Server] INFO at Boss-4.3.4.jar//org.mineacademy.boss.lib.menu.MenuContainerChances.onMenuClose(MenuContainerChances.java:328)
470 | 08.04 15:56:55 [Server] INFO at Boss-4.3.4.jar//org.mineacademy.boss.lib.menu.MenuContainerChances$1.onClickedInMenu(MenuContainerChances.java:91)
471 | 08.04 15:56:55 [Server] INFO at Boss-4.3.4.jar//org.mineacademy.boss.lib.menu.Menu.onButtonClick(Menu.java:1048)
472 | 08.04 15:56:55 [Server] INFO at Boss-4.3.4.jar//org.mineacademy.boss.lib.menu.MenuListener.onMenuClick(MenuListener.java:96)
473 | 08.04 15:56:55 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1000.execute(Unknown Source)
474 | 08.04 15:56:55 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
475 | 08.04 15:56:55 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
476 | 08.04 15:56:55 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
477 | 08.04 15:56:55 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
478 | 08.04 15:56:55 [Server] INFO [Boss] !-----------------------------------------------------!
479 | 08.04 15:56:55 [Server] INFO [Boss]  Error clicking in menu IndividualPlayerDropMenu{}
480 | 08.04 15:56:55 [Server] INFO [Boss] !-----------------------------------------

</body>
</html>

**Comment by kangarko** [comment]
Thanks, will be fixed!
