### ISSUE TITLE
Please Help

### ISSUE THREAD

**Issue by iLukeTV** [kangarko/Boss#103]
I bought the plugin, but when i move it into my filezilla it installs, but no folder appears. So when i restart my server. it says the plugin is in there but i cant use any of the commands

**Comment by BlackGamer000** [comment]
Errors in console?

**Comment by kangarko** [comment]
Please post me your start-up log uploaded to pastebin.com

**Comment by kangarko** [comment]
Closing, no answer given. Please comment below if your issue still persists.
