### ISSUE TITLE
1.18.2 paper: Boss not saving death

### ISSUE THREAD

**Issue by RAPHAEL599** [kangarko/Boss#1030]
plugin version: 4.3.4
Sever: Paper version git-Paper-283 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: f8e8d6c)
You are running the latest version

Boss config: https://pastebin.com/qqNSJ6Sj
Bug Video: https://www.youtube.com/watch?v=ylDrab2qnnk

**Comment by kangarko** [comment]
I apology for a late reply, however we do not respawn Bosses on death unless you have a Spawn Rule configured (this is not in your Boss file, rather in spawnrule/ folder). Also check other plugins or try removing the Boss using /butcher command or by our /boss remove command to see if that problem persists.
