### ISSUE TITLE
1.18.2: Boss equipment does not save metadata

### ISSUE THREAD

**Issue by AstolfoDev** [kangarko/Boss#1034]
Hello,

Currently when I give bosses equipment with metadata such as playerheads or dyed armour after a server restart they will lose all their data and revert to default items (heads to Steve heads and dyed armour to default leather armour).

I want to also note that they still drop the items with the correct metadata but do not wear the items with any metadata.

Please see my debug file attached below.
[debug.zip](https://github.com/kangarko/Boss/files/8501311/debug.zip)

**Comment by kangarko** [comment]
Thanks, should be solved after the next release.
