### ISSUE TITLE
1.18.2: Drops with special names and lores just vanish

### ISSUE THREAD

**Issue by Korwey** [kangarko/Boss#1036]
Hello! Ever since the last update the drops have been pretty funky. In previous issues I've reported that I can't exit the player drop menu, which is a pretty big issue, because I can't edit drops. After I updated the plugin to 4.3.4 items with custom names just vanished from the drop menu. I would love to see these fixed, because I've been waiting weeks to use this plugin and in it's current state I can not.

**Comment by Korwey** [comment]
P. S.: I also tried editing these in the boss's yml, but it only accepts edits from the gui.

**Comment by kangarko** [comment]
Thanks, I'll attempt to fix that in the next version :)
