### ISSUE TITLE
Spawn Holograms

### ISSUE THREAD

**Issue by MilkAndCereal121** [kangarko/Boss#1037]
I'm currently using DecentHolograms because HolographicDisplay doesn't run in 1.18.2 version of Minecraft server, The problem with DecentHolograms is whatever i spawn the hologram gets stuck where the npc/boss spawn.

Photo:
https://ibb.co/2j1zdLR

**Comment by MilkAndCereal121** [comment]
nvm it does the same on HolographicDisplay

**Comment by NewJeb** [comment]
HolographicDisplay is on the new version, download the build https://ci.codemc.io/job/filoghost/job/HolographicDisplays/

**Comment by MilkAndCereal121** [comment]
man i have 1.18.2 i installed what you asked and still nothing also it spawns npc's that i used as a test and i removed them now i even removed the config and the plugin and re install can you fix the hologram issue when i kill an boss or when they spawn

also when i had the 1.17  we didnt have any issues

**Comment by kangarko** [comment]
I am sorry but I believe this is just an incompatibility, but I can give Boss plugin free to your hologram plugin developers so they can adjust it

**Comment by MilkAndCereal121** [comment]
So how can i fix ncp's that i have removed and they keep spawning on restart like 30-50 of them

And how can i remove holograms out of the bosses

**Comment by kangarko** [comment]
Boss plugin does not add holograms, I am afraid you'd have to speak with the dev of that plugin, just tell him to send me an email to matej@mineacademy.org and I'll send him Boss jar

**Comment by MilkAndCereal121** [comment]
Btw i'm interested for Java/Spigot lessons, Can you give me your discord so we can talk there?

**Comment by kangarko** [comment]
Thanks, please sign up for mineacademy.org/project-orion, and I'll send you an email once we re-open!

**Comment by MilkAndCereal121** [comment]
so the zombies hologram works but npc holograms get stuck where they spawn! fix it
Minecraft Version: 1.18.2
HologramDisplay Version: newest
Boss Version: newest

**Comment by kangarko** [comment]
Sorry but it appears that hologram plugins are unsupported with Boss at the moment, we are looking into the issue but for now you can just ask your hologram plugin developer to send us an email so we can send him our plugin for free to hook into our own API and add a compatibility bridge.
