### ISSUE TITLE
Purpur 1.18.2: Getting EntityDeathEvent error.

### ISSUE THREAD

**Issue by alechretien16** [kangarko/Boss#1039]
Hello good evening. I have this error in console when killing a mob "Could not pass event EntityDeathEvent to Boss v4.3.4
java.lang.NullPointerException: Cannot invoke "org.mineacademy.boss.lib.model.Tuple.getKey()" because "tuple" is null".
I don't see it causing problems but it's annoying on console.

**Comment by kangarko** [comment]
Thanks, will get patched today.
