### ISSUE TITLE
Purpur 1.18.2 - Boss type Husk error.

### ISSUE THREAD

**Issue by alechretien16** [kangarko/Boss#1042]
When making a Husk type boss in the "Custom Settings" section there is the "villager profession" option, logically it should not be there and the boss does not work correctly, errors such as:
- When choosing a profession it does not load, you have to exit co "exit".
- When leaving and spawning a new boss and wanting to kill it from the gui or with the command it doesn't do it, it doesn't appear in /b find * either.

**Comment by kangarko** [comment]
Thanks for reporting, will get patched asap!

**Comment by alechretien16** [comment]
> When making a Husk type boss in the "Custom Settings" section there is the "villager profession" option, logically it should not be there and the boss does not work correctly, errors such as:
> 
> * When choosing a profession it does not load, you have to exit co "exit".
> * When leaving and spawning a new boss and wanting to kill it from the gui or with the command it doesn't do it, it doesn't appear in /b find * either.

https://ufile.io/prgou903

**Comment by kangarko** [comment]
I am so sorry, Husk profession changes are not supported unfortunately :/

![A](https://i.imgur.com/iCssTaG.png) as per the docs https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/browse/src/main/java/org/bukkit/entity/Zombie.java#52 since Husk extends the Zombie class.

**Comment by alechretien16** [comment]
> I am so sorry, Husk profession changes are not supported unfortunately :/
> 
> ![A](https://camo.githubusercontent.com/a1deb74e490014280688fa8ae0d7b562c55c5c7f89042adea053cf40c2313584/68747470733a2f2f692e696d6775722e636f6d2f694373735461472e706e67) as per the docs https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/browse/src/main/java/org/bukkit/entity/Zombie.java#52 since Husk extends the Zombie class.

That is not the problem, it is that a Husk-type boss is bugged when that change is made, it seems to me more of an error that the change of profession to the Husk should not be.

**Comment by kangarko** [comment]
I will patch this error from appearing in the next version.

**Comment by alechretien16** [comment]
Excelente :D
