### ISSUE TITLE
Purpur 1.18.2 - NPC hologram error.

### ISSUE THREAD

**Issue by alechretien16** [kangarko/Boss#1043]
When spawning an NPC type boss the hologram stays where the boss spawned.
I use DecentHolograms as a hologram plugin.

**Comment by alechretien16** [comment]
The only way to remove the hologram is with /citienz reload, I've never used Citienz, download the free version offered by SpigotMC.

**Comment by alechretien16** [comment]
I just noticed that this error only occurs if the boss has a colored name, only then.

**Comment by kangarko** [comment]
Sorry but this is a major incompatibility with your holograms plugin, we unfortunately can't support every possible plugin but that developer can contact matej@mineacademy.org to get a free license for Boss so that they can support it.

**Comment by iGabyTM** [comment]
> Sorry but this is a major incompatibility with your holograms plugin, we unfortunately can't support every possible plugin but that developer can contact matej@mineacademy.org to get a free license for Boss so that they can support it.

I'm 99% sure that in this situation, you should add support for that holo plugin (just like I guess you do for the others) because YOU are using their API, not the other way around lol. A simple "can't bother to do that" would be enough 🤣

**Comment by kangarko** [comment]
How I am using their API? Boss4 has its own API and a set of events and we're simply listening to Bukkit events for the most part.
