### ISSUE TITLE
Purpur 1.18.2 - NPC error on name when died.

### ISSUE THREAD

**Issue by alechretien16** [kangarko/Boss#1044]
When killing an NPC-type boss, it appears in the chat that the player killed "CT-267888...", instead of the boss's name appearing.

**Comment by alechretien16** [comment]
I just noticed that this error only occurs if the boss has a colored name, only then.

**Comment by alechretien16** [comment]
> When killing an NPC-type boss, it appears in the chat that the player killed "CT-267888...", instead of the boss's name appearing.

https://ufile.io/prgou903

**Comment by kangarko** [comment]
Try without your hologram plugin please.

**Comment by kangarko** [comment]
I am sorry, but I can't reproduce it with the latest dev build of Citizens2 from May 1st and Boss4:

https://www.loom.com/share/3add7fc4e8a74437bd58c91d8c62b34c

It's likely a setting in your Citizens plugin or some other plugin controlling death messages. Let me know if I am doing something wrong please.

**Comment by alechretien16** [comment]
> I am sorry, but I can't reproduce it with the latest dev build of Citizens2 from May 1st and Boss4:
> 
> https://www.loom.com/share/3add7fc4e8a74437bd58c91d8c62b34c
> 
> It's likely a setting in your Citizens plugin or some other plugin controlling death messages. Let me know if I am doing something wrong please.

This happens when you create a new boss of the NPC type, and kill him, update to the latest version of Citizens that is in dev, and my problem persists, when I spawn the boss I do not place any command as you show in the video, should I?
I also see that your boss is a Husk type initially.
And no, I don't have any plugin that handles the death message. Also when killing the boss in statistics it counts as killing a player, which doesn't seem bad to me. Sorry for writing so much, using a translator makes it difficult for me to find a way to understand what I say, I only speak Spanish.

**Comment by alechretien16** [comment]
The error only occurs when the boss has a colored name, speaking of the NPC-type boss, and this error appears that I already reported to the creator of the EpicBackPacks plugin.
https://pastebin.com/z5WQf4rx

**Comment by alechretien16** [comment]
I use a boss of the NPC type to be able to do it as if it were a character, if I select a zombie and enable a skin with citizens, the skin is not placed on it.

**Comment by kangarko** [comment]
Sorry but the error is related to the EpicBackpacks plugin. 

The fact that Citizens plugin creates the fake Boss entity as a Player may cause incompatibility there as well as in your statistics, there's nothing we can do about it since that's the entire principle of Citizens. That is why maybe the death message shows as if a player died. 

Where is that death message coming from? Try finding what causes it. 

Or you can install ChatControl Red which I sell (I can give you half price) and has custom death messages that automatically ignore Citizens NPCs.

**Comment by alechretien16** [comment]
> Sorry but the error is related to the EpicBackpacks plugin.
> 
> The fact that Citizens plugin creates the fake Boss entity as a Player may cause incompatibility there as well as in your statistics, there's nothing we can do about it since that's the entire principle of Citizens. That is why maybe the death message shows as if a player died.
> 
> Where is that death message coming from? Try finding what causes it.
> 
> Or you can install ChatControl Red which I sell (I can give you half price) and has custom death messages that automatically ignore Citizens NPCs.

I understand, I think that a solution in any case, could implement the "custom death messages" that CMI incorporates, which I have disabled. Thank you for replying, I have no doubts on this topic.
