### ISSUE TITLE
1.18.2: boss doesn't die

### ISSUE THREAD

**Issue by RAPHAEL599** [kangarko/Boss#1047]
Whenever I restart my server the bosses that should be dead come back to life, and there's no spawn rule.

Bug Video: https://youtu.be/9QiFO6UmllI

[latest (2).log](https://github.com/kangarko/Boss/files/8597760/latest.2.log)

**Comment by RAPHAEL599** [comment]
Config: [](https://pastebin.com/6f8ee8SE)
Boss: [](https://pastebin.com/wXwv8UDA)

**Comment by RAPHAEL599** [comment]
Boss: https://pastebin.com/wXwv8UDA
Config: https://pastebin.com/W4dfbLXK

**Comment by RAPHAEL599** [comment]
And I noticed that this only happens if the boss is a citzens NPC

**Comment by alechretien16** [comment]
> And I noticed that this only happens if the boss is a citzens NPC

same problem :/

**Comment by kangarko** [comment]
Thanks, investigating.

**Comment by kangarko** [comment]
I do apology, I have found the cause and fixed it!
