### ISSUE TITLE
Make a boss immune to projectiles

### ISSUE THREAD

**Issue by MausEsE** [kangarko/Boss#1049]
Is a small improvement but would be nice if in the next boss update you could add this feature.

**Sometimes the bosses are very easy to kill if you have a bow with power 5 and infinity.
The idea is that the player can´t hurt the boss by shuting him projectiles like arrows, eggs, snowballs.
No matter what the boss can´t be hurt by crossbows, bows, or anything you can throw and make damage.**

That would add one more difficulty when fighting a boss..
The player needs to go with a melee weapon to defeat the boss.

The boss is harder to kil, and that motivates the player to continue fighting.

Thanks!
Hope you read this!

**Comment by kangarko** [comment]
Thank you very much, I have put your suggestion down. Due to excessive amount of works on my online training program I am sorry but I am unable to take it on at the moment.
