### ISSUE TITLE
Paper 1.18.2 - Ender Dragon Boss not taking or giving damage (Can't find attribute minecraft:generic.attack_damage)

### ISSUE THREAD

**Issue by MarxminSD** [kangarko/Boss#1056]
I recently installed Boss today, and created my first Boss, of the Ender Dragon mob. Everything seems to work correctly, however, the boss does not take or deal damage, and there is no display on the action bar when I hit them. I have tried having the boss attack other mobs, and he will target them, but not deal damage.

My steps taken are as follows:
1. Downloaded the latest version of Boss from MCMarket
2. Stopped server
3. Uploaded .jar into the plugins directory
4. Restarted server
6. Created first boss, of an Ender Dragon type. 
7. Enabled Citizens functionality
8. Added players as target
9. Spawned boss
10. Boss is invulnerable/doesn't deal damage. Errors that spam console: [pastebin.com/UuutTU6T](url)
11. Kill boss with/b butcher
12. Boss nametag remains here (weird-side-bug?):

![image](https://user-images.githubusercontent.com/96161173/168686942-ac33f6e5-8d61-4718-980b-9f50141aab06.png)

Debug.zip: 
[debug.zip](https://github.com/kangarko/Boss/files/8704164/debug.zip)

Log (too large for Pastebin):
[latest.log](https://github.com/kangarko/Boss/files/8704163/latest.log)

**Comment by kangarko** [comment]
Hi Marcus,

As discussed via email, I will fix the still AI of your Ender Dragon boss(es). I apology for the inconvenience.

I can see here that you're mentioning one more error, that is coming from the Citizens plugin and you'd have to report it there instead.
