### ISSUE TITLE
Paper 1.18.2 - Bosses not using skills

### ISSUE THREAD

**Issue by MarxminSD** [kangarko/Boss#1057]
I recently installed Boss today, and it looks like Bosses are unable to use skills. It seems to occur with all entity types (that I've tested), and produces no console errors. I've attempted restarting after making any changes just to be sure, as well as waiting 5-10 minutes each attempt to wait for one to activate.

My steps taken are as follows:

1. Downloaded the latest version of Boss from MCMarket
2. Stopped server
3. Uploaded .jar into the plugins directory
4. Restarted server
5. Created two bosses; one Ender Dragon, and one Zombie
6. Enabled Citizens functionality
7. Added players as target
8. Added and configured skills (with shorter delays, for testing)
9. Spawned boss
10. Zombie boss appears to function properly in every way, except for triggering skills. No errors are in console.
11. Ender Dragon boss does not take or deal damage (see #1056), and skills are not activated either. Removed skills after to see if they had any effect on 1056.

Boss Folder (compressed):
[Boss.zip](https://github.com/kangarko/Boss/files/8704203/Boss.zip)

Latest.log:
[latest.log](https://github.com/kangarko/Boss/files/8704204/latest.log)

Debug.zip:
[debug.zip](https://github.com/kangarko/Boss/files/8704206/debug.zip)

Plugins:
![image](https://user-images.githubusercontent.com/96161173/168950006-582c01b9-4bb4-49b8-baa5-0867a5186867.png)

**Comment by kangarko** [comment]
Hi Marcus!

As discussed via email, please set Debug key in settings.yml to [skills] and restart. Let me know below what console messages appear. I recommend only keeping the Test boss to avoid console log spam.

Your ZIP file had Falkor boss that had no skills, only Test boss had skills attached to him.
