### ISSUE TITLE
Minecraft Version: 1.18.2 | Title bug

### ISSUE THREAD

**Issue by essolar** [kangarko/Boss#1058]
When I summon a boss and then kill it, the title remains in mid-air, I tried to use the hidden and with that it does not stay floating but it does not show the boss title.
![imagen_2022-05-17_174220626](https://user-images.githubusercontent.com/83976499/168914914-cff2c5e0-72bf-47e3-b83f-223be0c31b80.png)

**Comment by MarxminSD** [comment]
Same issue here, on the latest version. Are you using TAB perhaps? I am, and thought it might have been the case.

**Comment by kangarko** [comment]
Thanks, this is a TAB incompatibility and I have already opened a ticket with its developer. I recommend you reply to that ticket and upload your config.yml from your TAB plugin.
