### ISSUE TITLE
Tammed pets mcmmo skill

### ISSUE THREAD

**Issue by PortGasMC** [kangarko/Boss#106]
When players had a tammed wolf and when they go and kill boss 
The pet "wolf" is been ignored by the boss and the boss doesn't kill the wolf 
It's like easy kill using tammed wolf's
Using:
spigot 1.12.2
Mcmmo

**Comment by kangarko** [comment]
Do you have Fight.Auto_Retarget to true?

**Comment by kangarko** [comment]
Fixed.
