### ISSUE TITLE
1.18.2: Disable skeletons shoot each other

### ISSUE THREAD

**Issue by radiant-ai** [kangarko/Boss#1065]
Hello, is it possible to disable boss mobs with bows to attack each other? They seem to disintegrate each other without hurting any players running around them.

E.g there are two boss skeletons in arena, a player stands behind one of them and the other one shoots accidently hurting its friend... After this they start to shoot each other until one dies.

This makes a mass spawn of skeletons pretty useless as they kill each other..

**Comment by kangarko** [comment]
Thank you, I will make this change.
