### ISSUE TITLE
Another spawning suggestion

### ISSUE THREAD

**Issue by znoozer** [kangarko/Boss#107]
I was just wondering, is it possible to just spawn Boss to world without player being near region? Because what I wanted, is Boss just respawn after certain amount of time. I found this setup Chunk_Radius: 3 but it didn't exactly do what I was hoping. 
At this moment max distance to region and boss still spawns is ~80 blocks.

Things I was hoping:
>Player is somewhere in the world
>I have region setup somewhere in the world
>Boss spawn after certain amount of time without player being near boss region.
>Player can go to region and kill boss
>Repeat

If it is possible to add, it would be really nice. If not, then I just have to live with it. 

After all 5/5 plugin, thx for making really great plugin. :)
(Sorry for bad english)

**Comment by kangarko** [comment]
Can you use a Command Block that will execute the /boss spawn command?

**Comment by kangarko** [comment]
Closing.
