### ISSUE TITLE
1.18.2 - Bosses unable to spawn on negative heights.

### ISSUE THREAD

**Issue by matipoirierg** [kangarko/Boss#1074]
Hi, I'm currently having trouble with mob spawning in caves with negative heights. First of all if I set a negative height range like -50-40
the plugin will detect it as -50 and -40 so you have to use -50 - 40 instead (with spaces). The second main issue is mobs aren't just spawning tried with the REPLACE and ADD spawn rules, but it just won't spawn the mob I set to spawn. Using 4.3.11. Tried the spawnrule with height set to -1 and the mob spawns just fine.

**Comment by ElBananaa** [comment]
Related to #1061.
Seems like the issue hasn't been fixed.
Kangarko will have a look when he comes back ;)

**Comment by matipoirierg** [comment]
Yes, I opened a new issue instead of using the old one because at least now you can type negative values.

**Comment by kangarko** [comment]
Thanks, I am home now, will address in a few days or sooner maximum. Thanks.

**Comment by kangarko** [comment]
Thanks, I will fix that!
