### ISSUE TITLE
1.8.8:  Boss Spawning Limit not working when the server restarts

### ISSUE THREAD

**Issue by zPopCorn10** [kangarko/Boss#1077]
Basically if a boss is spawned and your server crashes/shuts down, when starting again you'll have 2 bosses even if the limit is 1

Boss Folder: https://www.dropbox.com/s/jvcb8wh479bpp5a/Boss.rar?dl=0

**Comment by kangarko** [comment]
Thank you, I am reviewing your issue and will get back to it in a few days asap.

**Comment by kangarko** [comment]
Thanks, should be fixed, there is however a chance to have two bosses still, I need to review this more but there should not be more than 2 bosses.
