### ISSUE TITLE
1.18.2 bosses riding settings reset every reload/restart

### ISSUE THREAD

**Issue by VaapeMC** [kangarko/Boss#1078]
<!---
When I set a boss to ride another boss, it will work and the boss will ride it next time it is spawned. But when I /boss reload or reload/restart the server, the ride is reset to whatever it was when the server restarted. This will happen to some of my bosses but not all, I have attached the bosses it does not work for.

This does not happen when I put regular mobs e.g. creeper as the ride. Only happens when I set it to ride bosses

I want to get in contact quicker so if there is a discord I can join please send an invite.

[Boss.zip](https://github.com/kangarko/Boss/files/8943241/Boss.zip)

I haven't tried all of them but
**Bosses it doesn't work for:**
AngelOfDeath
Frostbite
ColumnOfFlame5

**Bosses it does work for:**
InfernalSpirit

**Comment by VaapeMC** [comment]
When I set a boss to ride another boss, it will work fine and the boss will ride it next time I spawn it. But when I restart the server or /boss reload, the ride is reset to nothing and they won't ride anything.

This only happens to some bosses.

When I set a boss to ride a vanilla mob, like enderman, this works fine and will remain as the ride even after reloading.

[Boss.zip](https://github.com/kangarko/Boss/files/8943261/Boss.zip)

I have not tried all of them but...

**Bosses that setting ride doesn't work for (it will reset the bosses to ride after restart):**
ColumnOfFlame5
Frostbite
AngelOfDeath

**Bosses that will work as intended:**
InfernalSpirit

Weirdly, for ColumnOfFlame5, it already had a mount set as ColumnOfFlame2. I cannot add any different rides as it will reset on restart, but I can add more ColumnOfFlame2 riding each other and this will remain through restart.

**Comment by kangarko** [comment]
Thank you, I am reviewing your issue and will get back to it in a few days asap.

**Comment by kangarko** [comment]
Thank you, I am reviewing your issue and will get back to it in a few days asap.

**Comment by kangarko** [comment]
Thanks I have fixed that problem!
