### ISSUE TITLE
Bosses can't wear Armor/Weapons

### ISSUE THREAD

**Issue by IamCursedd** [kangarko/Boss#108]
Hello,

I really like the plugin. Its been amazing so far, but i noticed i cant put any armor/weapons on bosses like zombie and the skeleton. everytime i put something it would just dissapear and the item would also be gone. 
Also, is there a way to increase the damage from skeleton bosses? the arrow does not do any damage, even after i've changed the attack damage to 100.
No errors or warnings are popping in the console.

I hope to hear from you soon.

**Comment by kangarko** [comment]
What is your server version? Please ZIP me your Boss folder with the Bosses that have the problem with disappearing armor.

If the Attack Damage attribute doesn't work, perhaps you can give the Skeleton an enchanted bow with Power 5 or even higher? If that won't work, I am sorry but then it's not possible with the current system.

**Comment by kangarko** [comment]
Closing due to no answer, please comment below if issues persist.
