### ISSUE TITLE
Minecraft 1.18.2 - Citizens NPC bosses not keeping skin changes

### ISSUE THREAD

**Issue by Britland2** [kangarko/Boss#1080]
Hello,

This is just a simple repeatable bug. When spawning an NPC Boss, select them, and changing the skin, once they die (or you kill them via the spawn egg) when they respawn again they don't have the skin you changed it to.

I can provide a video of this if need be, let me know if you need any files as well. 

Thank you!

**Comment by kangarko** [comment]
Can't reproduce, check if you're on the latest Boss and Citizens versions as well as the latest 1.18.2: ![a](io.lumine.mythic.bukkit.utils.serialize)

**Comment by kangarko** [comment]
Can't reproduce, check if you're on the latest Boss and Citizens versions as well as the latest 1.18.2: 
<img width="1037" alt="Screenshot 2022-06-26 at 13 16 08" src="https://user-images.githubusercontent.com/1918426/175811932-3cfb4ef3-a1d0-4429-8aba-23945150ceb3.png">
)

**Comment by Britland2** [comment]
I am using the most recent version of Boss, and of Citizens. Here is a screenshot of what I am essentially trying to do:

![image](https://user-images.githubusercontent.com/108083145/175826575-126672d3-2c78-4bfc-9164-249c81148aa0.png)

Here is a video of me trying to do it:

[https://youtu.be/8TaeYJt0CfI](url)

**Comment by kangarko** [comment]
If you use /npc then Boss plugin won't add custom skin. You must select custom skin in Boss > Settings > Citizens > Skin menu.
