### ISSUE TITLE
Mob Boss Error 1.19 getting ReflectionException error

### ISSUE THREAD

**Issue by MindMasterz** [kangarko/Boss#1081]
Any menu that toggles an option by pressing a button, as opposed to entering a number in chat gives an error like this: And doesn't open the menu. 
https://pastebin.com/Lwaz1eL2

**Comment by Michael-A-Sloan** [comment]
I can confirm this is happening to me as well.

**Comment by Michael-A-Sloan** [comment]
Attached is my debug:
[debug.zip](https://github.com/kangarko/Boss/files/9024205/debug.zip)

**Comment by kangarko** [comment]
Thanks, will be fixed.
