### ISSUE TITLE
Name and lore

### ISSUE THREAD

**Issue by D3BoxOfficiel** [kangarko/Boss#1082]
I have a problem, there is something written in the changelog that we can change the water lore and the name but there is nothing in the documentation or the config for the name, what should I do?

**Comment by D3BoxOfficiel** [comment]
![image](https://user-images.githubusercontent.com/38442389/177009386-74cebb5f-2c8f-4419-87ac-24fb3ffb1444.png)
dosen't work :/

**Comment by kangarko** [comment]
Please only use the in-game menu to change the egg appearance. You'll find this in spawning > egg for your boss.
