### ISSUE TITLE
1.12.2: Some Bugs

### ISSUE THREAD

**Issue by TeQTabanca** [kangarko/Boss#1088]
### 1- Citizens Issue::
- 1- I'm creating the Citizens monster. but it doesn't attack anyone, I tried every way but it doesn't do anything. But after using command "/npc target -a" it attacks.
- 2- "Enable Wander Goal?" When I enable the section, it gives an error in the console. In addition, when I try to set the "Wander Radius" section, it gives an error in the console.

> [14:01:48 ERROR]: Boss 4.4.2 encountered a NoSuchMethodError! Please check your [`error.log`](https://www.dropbox.com/s/8wvxlzkgvrhe3lf/error.log?dl=1) and report this issue with the information in that file.
> [14:01:48 INFO]: java.lang.NoSuchMethodError: 'net.citizensnpcs.api.ai.goals.WanderGoal net.citizensnpcs.api.ai.goals.WanderGoal.createWithNPC(net.citizensnpcs.api.npc.NPC)'
> [14:01:48 INFO]: at org.mineacademy.boss.hook.CitizensHook.update(CitizensHook.java:134)
> [14:01:48 INFO]: at org.mineacademy.boss.hook.CitizensHook.update(CitizensHook.java:88)
> [14:01:48 INFO]: at org.mineacademy.boss.model.Boss.updateBosses(Boss.java:552)
> [14:01:48 INFO]: at org.mineacademy.boss.model.Boss.onSave(Boss.java:536)
> [14:01:48 INFO]: at org.mineacademy.boss.lib.settings.FileConfig.save(FileConfig.java:1258)
> [14:01:48 INFO]: at org.mineacademy.boss.lib.settings.FileConfig.save(FileConfig.java:1238)
> [14:01:48 INFO]: at org.mineacademy.boss.model.BossCitizensSettings.setWanderGoalEnabled(BossCitizensSettings.java:177)
> [14:01:48 INFO]: at org.mineacademy.boss.menu.boss.SettingsMenu$4.onClickedInMenu(SettingsMenu.java:263)
> [14:01:48 INFO]: at org.mineacademy.boss.lib.menu.Menu.onButtonClick(Menu.java:1046)
> [14:01:48 INFO]: at org.mineacademy.boss.lib.menu.MenuListener.onMenuClick(MenuListener.java:96)
> [14:01:48 INFO]: at jdk.internal.reflect.GeneratedMethodAccessor238.invoke(Unknown Source)
> [14:01:48 INFO]: at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> [14:01:48 INFO]: at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> [14:01:48 INFO]: at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
> [14:01:48 INFO]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
> [14:01:48 INFO]: at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
> [14:01:48 INFO]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
> [14:01:48 INFO]: at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
> [14:01:48 INFO]: at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> [14:01:48 INFO]: [Boss] !-----------------------------------------------------!
> [14:01:48 INFO]: [Boss]  Error clicking in menu GoalsMenu{}
> [14:01:48 INFO]: [Boss] !-----------------------------------------------------!

> [14:02:15 WARN]: [Boss] Plugin Boss v4.4.2 generated an exception whilst handling conversation input
> java.lang.NoSuchMethodError: 'net.citizensnpcs.api.ai.goals.WanderGoal net.citizensnpcs.api.ai.goals.WanderGoal.createWithNPC(net.citizensnpcs.api.npc.NPC)'
>         at org.mineacademy.boss.hook.CitizensHook.update(CitizensHook.java:134) ~[Boss-4.4.2.jar:?]
>         at org.mineacademy.boss.hook.CitizensHook.update(CitizensHook.java:88) ~[Boss-4.4.2.jar:?]
>         at org.mineacademy.boss.model.Boss.updateBosses(Boss.java:552) ~[Boss-4.4.2.jar:?]
>         at org.mineacademy.boss.model.Boss.onSave(Boss.java:536) ~[Boss-4.4.2.jar:?]
>         at org.mineacademy.boss.lib.settings.FileConfig.save(FileConfig.java:1258) ~[Boss-4.4.2.jar:?]
>         at org.mineacademy.boss.lib.settings.FileConfig.save(FileConfig.java:1238) ~[Boss-4.4.2.jar:?]
>         at org.mineacademy.boss.model.BossCitizensSettings.setWanderGoalRadius(BossCitizensSettings.java:186) ~[Boss-4.4.2.jar:?]
>         at org.mineacademy.boss.menu.boss.SettingsMenu$6.onValidatedInput(SettingsMenu.java:350) ~[Boss-4.4.2.jar:?]
>         at org.mineacademy.boss.lib.conversation.SimpleDecimalPrompt.acceptValidatedInput(SimpleDecimalPrompt.java:99) ~[Boss-4.4.2.jar:?]
>         at org.mineacademy.boss.lib.conversation.SimpleDecimalPrompt.acceptValidatedInput(SimpleDecimalPrompt.java:84) ~[Boss-4.4.2.jar:?]
>         at org.mineacademy.boss.lib.conversation.SimplePrompt.acceptInput(SimplePrompt.java:184) ~[Boss-4.4.2.jar:?]
>         at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:228) ~[server.jar:git-Spigot-79a30d7-f4830a1]
>         at org.bukkit.craftbukkit.v1_12_R1.conversations.ConversationTracker.acceptConversationInput(ConversationTracker.java:60) [server.jar:git-Spigot-79a30d7-f4830a1]
>         at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.acceptConversationInput(CraftPlayer.java:1118) [server.jar:git-Spigot-79a30d7-f4830a1]
>         at net.minecraft.server.v1_12_R1.PlayerConnection$5.evaluate(PlayerConnection.java:1250) [server.jar:git-Spigot-79a30d7-f4830a1]
>         at org.bukkit.craftbukkit.v1_12_R1.util.Waitable.run(Waitable.java:24) [server.jar:git-Spigot-79a30d7-f4830a1]
>         at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:758) [server.jar:git-Spigot-79a30d7-f4830a1]
>         at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [server.jar:git-Spigot-79a30d7-f4830a1]
>         at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [server.jar:git-Spigot-79a30d7-f4830a1]
>         at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [server.jar:git-Spigot-79a30d7-f4830a1]
>         at java.lang.Thread.run(Thread.java:829) [?:?]

> [14:06:46 ERROR]: Could not pass event PlayerInteractEvent to Boss v4.4.2
> org.bukkit.event.EventException: null
>         at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[server.jar:git-Spigot-79a30d7-f4830a1]
>         at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-79a30d7-f4830a1]
>         at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [server.jar:git-Spigot-79a30d7-f4830a1]
>         at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [server.jar:git-Spigot-79a30d7-f4830a1]
>         at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:235) [server.jar:git-Spigot-79a30d7-f4830a1]
>         at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:458) [server.jar:git-Spigot-79a30d7-f4830a1]
>         at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:955) [server.jar:git-Spigot-79a30d7-f4830a1]
>         at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) [server.jar:git-Spigot-79a30d7-f4830a1]
>         at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) [server.jar:git-Spigot-79a30d7-f4830a1]
>         at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-79a30d7-f4830a1]
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
>         at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
>         at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [server.jar:git-Spigot-79a30d7-f4830a1]
>         at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [server.jar:git-Spigot-79a30d7-f4830a1]
>         at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [server.jar:git-Spigot-79a30d7-f4830a1]
>         at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [server.jar:git-Spigot-79a30d7-f4830a1]
>         at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [server.jar:git-Spigot-79a30d7-f4830a1]
>         at java.lang.Thread.run(Thread.java:829) [?:?]
> Caused by: java.lang.NoSuchMethodError: 'net.citizensnpcs.api.ai.goals.WanderGoal net.citizensnpcs.api.ai.goals.WanderGoal.createWithNPC(net.citizensnpcs.api.npc.NPC)'
>         at org.mineacademy.boss.hook.CitizensHook.update(CitizensHook.java:134) ~[Boss-4.4.2.jar:?]
>         at org.mineacademy.boss.hook.CitizensHook.spawn(CitizensHook.java:68) ~[Boss-4.4.2.jar:?]
>         at org.mineacademy.boss.model.Boss.summonEntity(Boss.java:905) ~[Boss-4.4.2.jar:?]
>         at org.mineacademy.boss.model.Boss.spawn(Boss.java:838) ~[Boss-4.4.2.jar:?]
>         at org.mineacademy.boss.listener.PlayerListener.onClick(PlayerListener.java:250) ~[Boss-4.4.2.jar:?]
>         at jdk.internal.reflect.GeneratedMethodAccessor507.invoke(Unknown Source) ~[?:?]
>         at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
>         at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
>         at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[server.jar:git-Spigot-79a30d7-f4830a1]
>         ... 17 more

- 3- Even though it's a monster, nothing happens when I click on the "Targets" section.
- 4- I clicked on the "Riding" section and selected the "Mobs To Ride" section and added the egg of the skeleton horse, but npc does not ride the skeleton horse. Additionally, if I enable the "Kill Riding On Death" episode, the creature it will ride will not come. Finally, if I enable and disable the "Kill Riding On Death" section, the monster it will ride will be spammed.
![image](https://user-images.githubusercontent.com/89253304/178991218-b762fe4f-3bb6-4c3d-917b-d79f20b09dec.png)
- 5- If I enable the "Random Equipment" section, nothing will happen.
- 6- I set the NPC's health to 1000 but its health remains as default.
- 7- Most of the features in the "Custom Settings" section do not work.

Minecraft Version: [CraftBukkit version git-Spigot-79a30d7-f4830a1 (MC: 1.12.2)](https://www.dropbox.com/s/gerx5gu4s7xmy7n/server.jar?dl=1)
Plugin Version: Boss-4.4.2
Citizens Version: [Citizens-2.0.30-b2609](https://www.dropbox.com/s/7042xe7euyeijop/Citizens-2.0.30-b2609.jar?dl=0)

### Note:
**These are the errors I'm seeing right now. If I find any other error, I will write it under this post.**

**Comment by kangarko** [comment]
Unfortunately it looks like Citizens integration won't work properly for such an old MC version, please consider upgrading to at least 1.16.5+. Try not using Citizens for the bugs 5-7. and it should work. I apology for the inconvenience.
