### ISSUE TITLE
1.18.2: How to ignore "Location_Spawn_Nearby_Player_Radius" option?

### ISSUE THREAD

**Issue by Dagrond** [kangarko/Boss#1093]
So, I want my boss to spawn in given time in given location DESPITE that there are no players nearby. I want to spawn it anyway. There is config option:

>  Spawning rules that automatically summon Bosses at a given point will only function
>  when at least one player is in the given blocks radius. Defaults to 30 blocks around.
>  Location_Spawn_Nearby_Player_Radius: 30

But I cannot disable it. I've tried to set it to -1, 0, or 99999. 

TLDR: I want my bosses to spawn without checking if there are players nearby. I want them to spawn anyway, even if there is no players on the entire server.

PS. I know that I can do it by executing spawn command at a given time, but this is not the point. This plugin costs $35, so why should I use external plugins to do such a simple thing?

**Comment by kangarko** [comment]
Thanks, from the next release this check will be disabled if you set it to -1
