### ISSUE TITLE
1.8.9: Magma Cube boss can't be killed

### ISSUE THREAD

**Issue by bnjdg** [kangarko/Boss#1095]
When a magma cube type boss is spawned, it cannot be killed unless it is killed using the boss menu.
Here's a video of it: https://youtu.be/SPhEpx6C9dI

Here's the boss config:
https://pastebin.com/gM3wwYum

Attached is the boss folder
[Boss.zip](https://github.com/kangarko/Boss/files/9276435/Boss.zip)

**Comment by kangarko** [comment]
Your health is too high > Health: 5048.0 > set it to a lower value such as 25. Minecraft was not designed for such high healths and may glitch out completely when using them.
