### ISSUE TITLE
paper1.19.2 : About BOSS GUI sorting problem

### ISSUE THREAD

**Issue by qwe938775** [kangarko/Boss#1096]
Before my BOSS gui created Level1~9 in order and arranged them in order with the monster type, why is it now, all the orders are jumping randomly..

Is there a way to get him sorted correctly?

Or can the GUI be changed to sort by monster type, so that having too many bosses will cause trouble in searching because they are all crowded together.

**Comment by qwe938775** [comment]
Yes, I will post it again in a few days, I hope it can be classified by mob type

**Comment by kangarko** [comment]
I apology, for now the menus are sorted according to the load order, which sometimes may jump randomly, but I take this as a feature suggestion when I have time.

**Comment by qwe938775** [comment]
Thanks you
