### ISSUE TITLE
Minecraft Version: 1.18.2

### ISSUE THREAD

**Issue by SalvatoreZx** [kangarko/Boss#1097]
Hello i made some vanilla mobs to spawn and i place a spawner they doesn't spawn like they should do

Also i got RoseStacker is that a problem?

[Uploading Boss.zip…]()

**Comment by kangarko** [comment]
Hey!

Correct, any mob stacking plugin might cause major incompatibilities. Please remove it first before testing Boss, unfortunately, there is no workaround we can do since those plugins remove our nbt tags.

Your Boss.zip file did not get uploaded, if you still need help upload it below.

Matej

**Comment by SalvatoreZx** [comment]
[Boss.zip](https://github.com/kangarko/Boss/files/9385583/Boss.zip)

**Comment by kangarko** [comment]
Sorry but that is not uploaded using /boss debug as we instruct... anyways, I am confident that it is caused by the mob stacker plugin, you'd have to remove it to get Boss working
