### ISSUE TITLE
Boss Spawn limit

### ISSUE THREAD

**Issue by OnlyMatty** [kangarko/Boss#1098]
Hello, is there any way to restrict the boss from spawning, when one is already spawned?
I can't seem to find any option. 
Thanks in advance for any replies. ❤️

**Comment by kangarko** [comment]
Hey! You can configure world limits or spawning radius limits in /boss menu <boss> and then Spawning menu, see below.

You can also customize each spawning rule to limit the boss count it does spawn.

![a](https://i.imgur.com/BsyupFB.png)
