### ISSUE TITLE
Bug with drowned

### ISSUE THREAD

**Issue by Dagrond** [kangarko/Boss#1099]
So, it turns out that if the boss is a zombie type, and he will walk into water, he gets turned into drowned (vanilla behavior). After turning into drowned, the plugin no longer recognizes him as a boss, so he will not drop items, use skills or anything what is related to boss.
I think that there are 2 ways of fixing this:
1. Give an option to prevent turning boss into a drowned
2. listen to spigot event CreatureSpawnEvent (and then SpawnReason.DROWNED) and make that boss plugin recognizes the new entity type as a boss.

**Comment by kangarko** [comment]
Thanks, I will cancel EntityTransformEvent completely to prevent this, but also other breaking changes. Thanks for noticing!
