### ISSUE TITLE
[Suggestion] Spawn minions over time

### ISSUE THREAD

**Issue by Kimskell** [kangarko/Boss#11]
It would be nice if the boss could spawn some minions occasionally (in a certain time period).
For example: Skeleton bosses spawn a 1 to 3 normal skeletons every 30 seconds in a 10 block radius.

**Comment by kangarko** [comment]
Thank you, would you like this is a skill?

**Comment by Kimskell** [comment]
That would be great. And then the minion of the same kind. So skelleton bosses spawn skelleton minions.

**Comment by Kimskell** [comment]
Question: Can you change distance in witch you can see above head boss names? Or is that something you set in world settings or spigot settings. Now in my server/world  the boss betrayed himself by being visible at a long distance. It's a bit of a shame if the boss is a shooting target. Above head name is super but from the distance he can attack the player. Maybe better some less.
Or is it possible to make a trait so that the boss can only be defeated with handweapons?
Sorry I ask you a lot. But during play and testing this great pluginn I come up with a lot of ideas. :P

**Comment by kangarko** [comment]
No problem, I will add it as a skill.

However, I cannot manipulate with the display name - this is something that your client renders.
