### ISSUE TITLE
1.19.2 - MOBS conversion problem

### ISSUE THREAD

**Issue by qwe938775** [kangarko/Boss#1100]
Sorry I can't find an option in the new version, the vanilla MOBS has a chance to convert to a boss instead of creating a random boss option, I remember there was this option before.
please help me thank you

**Comment by qwe938775** [comment]
There's another weird phenomenon I'm not quite sure about..
Set multiple bosses and he will disappear quickly
Boss disappears instantly in water TPS is greatly affected

https://youtu.be/tkRnxwTGXxk

![2022-08-25_234114](https://user-images.githubusercontent.com/71574471/186710004-e73f9875-3932-41d1-8cad-2a010da3a3a9.jpg)

**Comment by kangarko** [comment]
Thanks, as for the first question, you need to create a new Spawn Rule and choose "Replacing Vanilla Mobs" and configure the chance to convert the vanilla mob there. I will increase the performance of canceling mob transform event when in water, but I am not sure if i can change the flickering bug, seems to be caused from Paper/vanilla imho.
