### ISSUE TITLE
Paper 1.19.2:Boss out of his region

### ISSUE THREAD

**Issue by OnlyMatty** [kangarko/Boss#1101]
Hello, I am trying to keep my bosses in their region, but they do not listen and go their way.
I configured everything right. _(Or at least i think I did)_
I did not use /reload and I did restart my server but even that didn't help. 

I will send here link to my Google drive's folder, where are some images that might help you with my situation.
_(Oh and yes, I do have Citizens installed)_

**Google Drive Folder:** https://drive.google.com/drive/folders/17Dp3sAIpC6nEn4M9WzK5VWAuUSWsk6WT

**Comment by kangarko** [comment]
Apologies for a late reply.

Open your Spawn Rule settings, navigate to Regions, Enable it and keep it on Whitelist. Now Bosses should only spawn within the region you selected: https://i.imgur.com/8kVWmTN.png and not otherwise.

**Comment by OnlyMatty** [comment]
> Apologies for a late reply.
> 
> Open your Spawn Rule settings, navigate to Regions, Enable it and keep it on Whitelist. Now Bosses should only spawn within the region you selected: https://i.imgur.com/8kVWmTN.png and not otherwise.

The problem is: I have everything as you mentioned, but they still wander off from their regions.

**Comment by kangarko** [comment]
Can you please do /boss debug and upload the ZIP file here? Mention which Boss and which Region is it.
