### ISSUE TITLE
Paper 1.19.2:Error 

### ISSUE THREAD

**Issue by OnlyMatty** [kangarko/Boss#1102]
I got an error while editing an NPC boss.
The purpose of the boss was guarding a house in overworld from monsters. 
When I wanted to edit the Boss's potion effects, it closed the menu and some error popped up in my server console. 

So I wanted to ask: **What does the error mean and what is the problem that caused the error to show up?**

The error log: 
https://pastebin.com/AZtBkA1c

**Comment by kangarko** [comment]
Thanks, this error means that our hook is outdated, I will fix it by updating.
