### ISSUE TITLE
1.16.5: Npc boss teleports on targetting players 

### ISSUE THREAD

**Issue by TheHunterDude** [kangarko/Boss#1103]
I have a Npc boss using citizens plugin.

the targetting players is on as well as the kill target and target goal.
but when a player attacks the npc starts teleporting al over the place and randomly hitting.
like it installed a hack client.

what do i do to prevent this from happining?

**Comment by kangarko** [comment]
I opened an issue on Citizens' page on your behalf, let's follow up there.
