### ISSUE TITLE
Change per location

### ISSUE THREAD

**Issue by Greazi-Times** [kangarko/Boss#1104]
**1) How it would benefit others? (Not just you, but 1,000s of other people using the same plugin.)**
Now you have to make spawn rules, again and again, every time the possibility to make just changing the chance of spawning per location would benefit everyone.

**2) What would happen if we won't implement this feature? How's your server being affected?**
Well, now I need to add multiple spawning rules for just 1 area which is insane to do and time-consuming. Being able to change the chance of spawning at a specific location would be great to have and easier to use.

**3) If suggesting something new - Can the old system be modified/improved instead?**
This doesn't require any new feature just modifying the existing system

**Comment by kangarko** [comment]
Hey! You can customize the chance using this icon:

![a](https://i.imgur.com/K4LoLtm.png)

And that is possible to customize per each location.

**Comment by Greazi-Times** [comment]
Aaa thank you didn't knew that also applied per location thanks
