### ISSUE TITLE
Disable spawning rull

### ISSUE THREAD

**Issue by Greazi-Times** [kangarko/Boss#1105]
Like the title says being able to disable a specific spawning rule would be great.

**1) How it would benefit others? (Not just you, but 1,000s of others people using the same plugin.)**
Other people don't need to remove the setup but can just disable the region from running without changing any settings

**2) What would happen if we won't implement this feature? How's your server being affected?**
Well it would mean that I have to do delete it now and save all settings somewhere and than once it can be used again remake the system

**3) If suggesting something new - Can the old system be modified/improved instead?**
The current system can be modified

**Comment by kangarko** [comment]
Thanks, implementado.
