### ISSUE TITLE
1.16.5: Custom boss skills registered through the api get wiped

### ISSUE THREAD

**Issue by Firosee** [kangarko/Boss#1107]
Custom boss skills registered through the API, using BossSkill#registerSkill get wiped from bosses after a restart. The method stated in the wiki does not appear to exist. 

Any fixes?

**Comment by kangarko** [comment]
Thanks I will solve this in 24h !

**Comment by kangarko** [comment]
Unfortunately there is no workaround for /boss reload wiping out custom skills, you might just need to create a custom command alias in commands.yml of bukkit where you run /boss reload and then /yourplugin reregisterskills and do it manually to improve convenience of this.

What were you referring to in the wiki?

**Comment by Firosee** [comment]
@kangarko

**Comment by Firosee** [comment]
Hey @kangarko any updates?

**Comment by kangarko** [comment]
I apology for my absence, I will get to this in 24 hours

**Comment by Firosee** [comment]
> I apology for my absence, I will get to this in 24 hours

Okay thank you

**Comment by Firosee** [comment]
> I apology for my absence, I will get to this in 24 hours

Hey - so any update on this..? Sorry for being pushy i just cant use the plugin without it

**Comment by kangarko** [comment]
Yes I am here, please see this quick video I recorded for you and use the next version I am about to release :)

https://www.loom.com/share/3dad38ce73c248e287fc415f53e0a041
