### ISSUE TITLE
Boss Respawn Timer

### ISSUE THREAD

**Issue by Miryex** [kangarko/Boss#1108]
A Placeholder or Command of some kind that shows the remaining time untill a Boss respawns.

1) How it would benefit others? (Not just you, but 1,000s of others people using the same plugin.)
- Every player could use the command to check when bosses will spawn

2) What would happen if we won't implement this feature? How's your server being affected?
- Everyone has to remember every Boss Respawntime by heart which is annoying and provides a worse user experience.

**Comment by kangarko** [comment]
Thanks, going to consider however due to time constraints we're not open more new suggestions at the moment.
