### ISSUE TITLE
1.19.2 How Do I Get The Plugin?

### ISSUE THREAD

**Issue by IAmOrion15** [kangarko/Boss#1109]
1) 1.19.2 Restoring The Plugin

2) NA

Hey Kangarko! It's been awhile and I am very happy to see you are still continuing development on this plugin! Anyways, if you remember, I am an old user of your plugin (you have my comment posted at the top of your forums which I love!). But it's been awhile and I got a new computer and all my files have been deleted including my old Bosstm file. Now I am in need of the plugin again and can't seem to restore it? Is there anyway I can get it back somehow? I am not sure if I was only using the free version, but I think I updated it to the premium version once you transferred over from Spigot. Anyways, do you have a free version working in 1.19.2 or can you help me restore the latest version? I don't have the login to the new website so I am not sure where to go from here! Thank you for your time and can't wait to use your plugin again! :)

**Comment by kangarko** [comment]
Please see https://mineacademy.org/boss :)
