### ISSUE TITLE
Allow Spawn Chances Below 1%

### ISSUE THREAD

**Issue by Yhenko** [kangarko/Boss#111]
Hi, first of all, bad english, sorry Kangarko! xD

Can u add the option to set % of spawning above to 0? Like 0.25? Thx!
And another:
Can i add commands when a Boss is killed? for example broadcast [Player] has kill [Boss] or someone what i want? Bad englishhh xD! Thx for this plugin! ♥

**Comment by BATHSALTZZ** [comment]
i would love to see this added also

**Comment by kangarko** [comment]
Hello,

thank you for the suggestions.

I can add a more precise spawning chances soon.

You can configure the commands on death already, check the Boss yaml file or https://github.com/kangarko/Boss/wiki/Common-Issues#how-can-i-send-custom-messages-or-commands-when-a-boss-diesspawns
