### ISSUE TITLE
Bosses executing commands on timer 

### ISSUE THREAD

**Issue by Eldilor99** [kangarko/Boss#1111]
Hi, I think that timer for commands would be a great addition to boss. What I mean by that is a command that you set up for a boss which is executed for example every 15 minutes. In my case I would use that to remind players that a boss is spawned and where, but I think that it can be used in a more creative way and would be useful for many boss users. 

Thanks for your time and consideration! Have a great  day.

**Comment by kangarko** [comment]
Thank you! I think that would be a great thing for a custom skill since skills are executed after some time. Would you be interested in a "dummy" skill that does nothing but only broadcast message to players in range or runs commands in certain intervals?

**Comment by Eldilor99** [comment]
I'm most interested in something that would run commands in certain intervals, as I think skill requires target to be executed?

**Comment by Eldilor99** [comment]
Moreover I would use that to execute broadcast command to let know about boss position to everyone on the server.

**Comment by kangarko** [comment]
Thank you, while it sounds very handy, I dont have time for this atm, but I can return to this when I have
