### ISSUE TITLE
1.18.2: Citizens NPC health not working

### ISSUE THREAD

**Issue by Korwey** [kangarko/Boss#1112]
Hello!
I made a Citizens player NPC boss of which I have set the health to 2000. That's good and all, but when I spawn the boss it has the default, 20 hp. All other Citizens enabled bosses work fine but the player one.

**Comment by kangarko** [comment]
Check your spigot.yml max-health value and try increasing it. Probably those super high values wont work correctly with Minecraft, what about 512 HP?
