### ISSUE TITLE
1.19.2: Worldguard regions not selectable

### ISSUE THREAD

**Issue by mrcoffee1026** [kangarko/Boss#1113]
Talked about this before the big upgrade and it was no big deal back then:  need to includde worldguard regions on the region list/blacklist.  I'm aware there's an alternative way of specifying regions that only Boss knows about, but I do not want to have to recreate every Worldguard region I have just so I can blacklist them on this plugin (if the region exists: I don't want bosses in it.  Everywhere in the world except for those regions are fine to have bosses spawning in them.  I had to get this fixed on the prior version also and it wasn't a big ask then, it shouldn't be one now either - I don't believe.  Thanks!

**Comment by kangarko** [comment]
Sorry I am not sure if I understand you.

Are you saying that some wordguard regions are not selectable while others are? Which ones are not selectable?

**Comment by mrcoffee1026** [comment]
NO worldguard regions are selectable.  It acts as though I have no regions to select.  All I can do is recreate regions within Boss itself... which I have no interest in doing.  I want to select existing worldguard regions instead.

**Comment by kangarko** [comment]
I am sorry that infrastructure is completely missing from Boss 4, I probably forgot to implement it. Need few more days for that since it's a bigger update.

**Comment by mrcoffee1026** [comment]
Awesome we'll look forward to that!
