### ISSUE TITLE
Boss - Reinforcement Feature

### ISSUE THREAD

**Issue by Latenciiii** [kangarko/Boss#1116]
Good Evening,

Basically would it be possible to amend the 'reinforcements' that a boss spawns in the sense that,

When the main boss spawns i would like there to be 3-5 other skeletons/zombies that spawn with the boss all wearing armour and a sword? If this isnt possible even some changes to the reinforcements would be aweosme!

Thanks!

**Comment by kangarko** [comment]
Hey! You can add a Minions skill or configure Boss reinforcements on death in the Boss Death menu.

**Comment by Latenciiii** [comment]
Yeah i get you, but i mean when the boss spawns that then the other skeletons/zombies spawn in with armor on, ill have a play with minecraft and essentials commands to run when the boss spawns!

**Comment by kangarko** [comment]
Yes so you can use the "Run Command" feature of the Boss plugin to execute a spawnmob command at your liking when the boss dies.
