### ISSUE TITLE
1.19.2

### ISSUE THREAD

**Issue by Latenciiii** [kangarko/Boss#1117]
Hi,

Quick question, placeholder api integration? ive looked around cant see it in the wiki on Boss or PAPI ecloud however when you reload boss it hooks in to papi?

Thanks again!

**Comment by kangarko** [comment]
Sorry this is unsupported for now, but you can let me know how you would like this integration to work and I add this to our roadmap.

**Comment by Latenciiii** [comment]
If you have a boss thats currently not spawned,  it would be cool in a placeholder to have %next_boss_spawn% and %boss_name% as placeholders? would be cool!

**Comment by kangarko** [comment]
How we are supposed to get the information about the next boss spawn? From what spawning rule? There can be 10s of spawning rules. Also how we are supposed to get the Boss' name?
