### ISSUE TITLE
1.19.2 PaperSpigot

### ISSUE THREAD

**Issue by Latenciiii** [kangarko/Boss#1118]
Hello,

I have setup mobs spawning, and i have piglins and piglin brutes wearing armor and swords and stuff, however when they spawn they shake about, which im guessing is how they should be because of the armour, but then after a certain amount of time, they remove the armor and weapon? i looked in the custom setttings for the particular mobs and they have no option to turn it off, not sure if this is a bug or intended, just wanted to check!

Thanks

**Comment by kangarko** [comment]
That's not coming from Boss; it's either Citizens integration or some custom plugin of yours.

Also Boss does not make entities "shake".

**Comment by kangarko** [comment]
Possible, I haven't had the chance to test on 1.19 with the newest mobs
