### ISSUE TITLE
Give non hostile Mobs hostile AI 

### ISSUE THREAD

**Issue by BATHSALTZZ** [kangarko/Boss#112]
I wanted to add some new animals to my server like a sheep named Ram that attacks players and has knockback/throw skill. Cows named Bulls with high hp that attack players etc. so farming animals can be more fun for my players. Is there any way to add this?

**Comment by Yhenko** [comment]
i tried, a killer chicken but i cant xD, it would be awesome! Add animal bosses

**Comment by kangarko** [comment]
Hello,

this has been discussed before and unfortunately we don't plan on adding this right now. More information: https://github.com/kangarko/Boss/wiki/Common-Issues#can-you-make-animals-aggressive--add-better-ai
