### ISSUE TITLE
1.19.2: Any way to set a permanent skin ?

### ISSUE THREAD

**Issue by mdanhier** [kangarko/Boss#1121]
Hello, I'm wondering if there is a way to apply a permanent skin to a Boss.
I could pick any skin based on username found on some website but what if they update their skin ? Is the only way to do so buying as many accounts as skin you need?
Also, tried /npc skin on the boss and it won't keep it on respawn.
I tried setting another skin on my account, applying the skin to the boss, reswitching to a new skin but it updates the boss skin too.
Why can't it work by uploading a skin through an URL like Citizens? (because it uses Citizens, right?)
Thanks you!

**Comment by kangarko** [comment]
Sorry for the delay!

Hmm if they update their skin it will be changed unfortunately. That is the design of our system and is intended to load the skin from Mojang.
