### ISSUE TITLE
1.17.1: Is there a way to remove the threshold for top damages

### ISSUE THREAD

**Issue by Jennifxrr** [kangarko/Boss#1122]
When giving the top 3 damagers items, it asks for a time threshold. Is there a way to make this last for the whole entire boss fight? (ex: longer than 10 minutes)

Also, instead of having to do a separate broadcast command for each place, is there a way to make it so all of the damage broadcasts can go into one message?

Also, is there a way to make it so the boss automatically spawns at a certain time?

**Comment by kangarko** [comment]
I believe you can just increase the threshold in the GUI menu. There is a hard limit due to the limitations of Spigot server.

**Comment by kangarko** [comment]
The broadcast I believe it's not possible to set that way, sorry!

Yes you can make Boss spawn at a certain time using Spawning Rules, in the /boss menu :)
