### ISSUE TITLE
1.18.2 Placeholder API ?

### ISSUE THREAD

**Issue by ClemenDev34** [kangarko/Boss#1127]
Hi the plugin have placeholder for example boss life ? Thanks !

**Comment by kangarko** [comment]
Where would you like the variable to be shown?

**Comment by kangarko** [comment]
Yes but WHERE do you want to show the Boss Life and Boss location? How is that supposed to work?

**Comment by ClemenDev34** [comment]
On the tab like :Boss life : %boss_life%Boss location : %boss_location%Le 12 janv. 2023 à 12:11, Matej Pacan ***@***.***> a écrit :﻿
Yes but WHERE do you want to show the Boss Life and Boss location? How is that supposed to work?

**Comment by kangarko** [comment]
Which plugin do you use for the tablist?

**Comment by ClemenDev34** [comment]
I use TAB Le 12 janv. 2023 à 18:45, Matej Pacan ***@***.***> a écrit :﻿
Which plugin do you use for the tablist?

**Comment by kangarko** [comment]
Thanks,

So in the TAB plugin, we should show the Boss Life and Boss Location. But there can be many bosses on the world, so how do we exactly know which Boss' life and location to show?

**Comment by ClemenDev34** [comment]
With that for example ; {BossName_location_x} {BossName_location_y} {BossName_location_z} {BossName_location_world} {BossName_life}

**Comment by ClemenDev34** [comment]
If my boss is named kleo variable is {kleo_life} for example

**Comment by kangarko** [comment]
Okay but what if there's multiple Bosses, do you want us to show these variablse for the closest Boss? Or the Boss that you damaged last?

**Comment by ClemenDev34** [comment]
The closest Boss

**Comment by kangarko** [comment]
I added it! https://github.com/kangarko/Boss/wiki/Variables
