### ISSUE TITLE
[1.19] Piglin conversion into Zombified piglin in the overworld

### ISSUE THREAD

**Issue by Dagrond** [kangarko/Boss#1128]
Hello. So, default vanilla behaviour is that when piglin/piglin brute enters overworld, he starts shaking and after some time it is transformed into zombified piglin. 

BOSS changes that, but it has some bugs.
Firstly, the piglin is shaking all the time and I believe only EntityTransformEvent is cancelled which is not good solution of this problem. There is bunch of methods that are created directly for piglins, see: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/PiglinAbstract.html#setImmuneToZombification(boolean)

Secondly, after first EntityTransformEvent cancelled, the piglin looses all of its inventory (if it has one). 
Tested on latest BOSS version, on latest paper build.

To reproduce:
1) Create BOSS of type Piglin, give him some inventory
2) Spawn newly created boss in overworld. The boss will start shaking immediately, and after a while he will loose all of its inventory.

**Comment by kangarko** [comment]
Thanks, I will use the setImmuneToZombification() method you suggested in the next releaes!
