### ISSUE TITLE
1.19.3: Skin urls

### ISSUE THREAD

**Issue by radiant-ai** [kangarko/Boss#1129]
Hello! What kind of input does the skin setting expects from me? For now I tried to use a username and it indeed uses a skin of that player profile. But how do I specify a skin url in there? Does not seem to work. If I set the skin directly using `/npc skin --url` command from Citizens it sets skin only once until Boss gets removed.

**Comment by kangarko** [comment]
Next version should accept http:// and https:// URLs for Bosses when entering their skin.

**Comment by kangarko** [comment]
Presumably if the URL ends with .png then it will work, tested with https://www.minecraftskins.com/uploads/skins/2023/01/17/frog-butler--not-an-original-skin--pls-check-the-description-for-the-original--21245201.png
