### ISSUE TITLE
Heroes Exp Support

### ISSUE THREAD

**Issue by xHexical** [kangarko/Boss#113]
Hello, do you think you could add Heroes exp support? (https://www.spigotmc.org/resources/heroes-the-most-powerful-rpg-plugin.24734/)
Ex. kill a mob and get extra heroes exp

**Comment by kangarko** [comment]
Hello,

probably not since that is a premium plugin, however I am leaving this open.

**Comment by kangarko** [comment]
We are not planning to include this feature at the moment due to other priorities.
