### ISSUE TITLE
1.19.3: NPC boss max hp resets after server restart

### ISSUE THREAD

**Issue by radiant-ai** [kangarko/Boss#1130]
## Expected behavior

- Create NPC boss
- Set hp to any value higher than 20
- Spawn the boss and see its hp more than 20
- Restart server
- Spawn the mob again and see its hp more than 20

## Actual behavior

- Create NPC boss
- Set hp to any value higher than 20
- Spawn the boss and see its hp more than 20
- Restart server
- Spawn the mob again and see its hp is always 20
- Try to edit its hp in menu
- Spawn the mob, hp is still always 20

-----------------------
Boss: `4.6.5`
Citizens: `2.0.30.2890`

**Comment by radiant-ai** [comment]
Hello. I have the max value set to 2048. I tried to give 500 to the boss.
It works fine until I do server restart. After that I need to create a new
boss from scratch to have 500 HP back.

**Comment by kangarko** [comment]
I tested it, found out that maxhealth and health is not being stored with Citizens, can you please contact their authors regarding this? All we do is call Bukkit's LivingEntity setHealth and setMaxHealth methods as per Bukkit's instructions, Citizens should remember them but it's not.
