### ISSUE TITLE
1.18.2:Boss Spawns Are Broken

### ISSUE THREAD

**Issue by zellowhuman** [kangarko/Boss#1132]
[Boss.zip](https://github.com/kangarko/Boss/files/10472768/Boss.zip)

Whenever I restart my server some boss spawn events get removed. This happens even when I do /save-all. Not every boss spawn event gets removed but a lot of them do. I checked the spawnrules folder and all the .yml files for the spawns are still there. What am I doing wrong?

**Comment by kangarko** [comment]
What do you mean "boss spawns" get removed? I assume not the files from spawnrules/ but that you no longer see the Spawning Rule associated to a Boss? Please give example which rules are getting removed.

**Comment by zellowhuman** [comment]
Oh sorry. Yes. The spawnrules are no longer connected to the boss.

**Comment by kangarko** [comment]
Aha so you can't see them anywhere in the GUI, they completely disappear? What spawnrule does it happen with?

**Comment by zellowhuman** [comment]
I believe it varies every time but I checked and "SnowmanSpawn", "SpiderQueen", "slasher", and "CultLeader" are the only ones that stayed this time.

**Comment by kangarko** [comment]
Use the next version should be patched, thanks.

**Comment by zellowhuman** [comment]
Thank you!
