### ISSUE TITLE
PaperMC 1.19.3: Boss egg with corearena

### ISSUE THREAD

**Issue by PluginRenewals** [kangarko/Boss#1133]
Hello, I have created a boss, grabbed the egg, put it in the CoreArena monster spawn block, only put in the 1 egg, but it keeps spawning up to 7-9 of them, I only want it to spawn 1 of this mob. Can't figure out how to limit it. 

I have it limited to just 1 of this mob in the world, and it doesn't seem to listen to Boss limits set in the boss config.

Thank you,

Veduz

**Comment by PluginRenewals** [comment]
Also, I can't seem to be able to create a boss region within a corearena region :/

**Comment by kangarko** [comment]
If you place 1x egg inside a CoreArena spawner, then one Boss should be spawned. Make sure the amount of the egg is only 1 and there is no other spawner nearby.  You can also set Debug to [spawning] in CoreArena settings.yml to observe what is going on when spawning mobs to perhaps see where the issue lays.

You can't mix Boss/CoreArena regions sorry.
