### ISSUE TITLE
1.19.3 : Increase GUI size

### ISSUE THREAD

**Issue by RAPHAEL599** [kangarko/Boss#1135]
The default GUI size of mob drops is very small, it only fits 18 items. Is there any way to increase?
![image](https://user-images.githubusercontent.com/73084300/217916740-8ac9a625-8895-42dd-a5e1-e126b84d09e3.png)

**Comment by kangarko** [comment]
I will add 3 additional rows to the menu for you in the next version.

**Comment by RAPHAEL599** [comment]
Ty
