### ISSUE TITLE
Boss Spawning randomly in world: 1.19.2

### ISSUE THREAD

**Issue by foxyyxx** [kangarko/Boss#1137]
I want to make my boss spawn randomly in a specific world region? How can I get it to do this. I can't actually make it even spawn in a specific position because the tools aren't working.

**Comment by kangarko** [comment]
Make sure to enable tools by setting Register_Tools key to true in settings.yml, restart the server and check console for errors as well as other plugins for conflicts and it should work.

Then it's as simple as creating the region and creating a region spawning rule in Boss' settings

**Comment by foxyyxx** [comment]
This has already been enabled and using the region tools don't work on 1.19.

If you wouldn't mind could you message me on discord as it would be easier?

**Comment by kangarko** [comment]
I don't use Discord for tech support.

What do you mean "it does not work" on 1.19?

**Comment by kangarko** [comment]
Check whether other plugins such as WordGuard are not conflicting.

**Comment by foxyyxx** [comment]
I don’t think they are but how would I go about checking that?

**Comment by BESTG** [comment]
Fixed it!

**Comment by acceso171** [comment]
It could provide the facility to translate the entire add-on, since at the moment it only lets you translate the messages and little else, but not the entire menu.
