### ISSUE TITLE
Model engine compatibility

### ISSUE THREAD

**Issue by RAPHAEL599** [kangarko/Boss#1138]
Adding compatibility with this plugin will greatly improve the visual customization of the bosses, if this trick is not implemented I will have to use the one from mythicmobs which is a shame because the configuration of your plugin is much better.

Plugin: https://www.spigotmc.org/resources/conxeptworks-model-engine%E2%80%94ultimate-custom-entity-model-manager-1-16-5-1-19-3.79477/

**Comment by kangarko** [comment]
How do you want the compatibility to function?

**Comment by kangarko** [comment]
Sure, I can DM the author of the plugin and see if we can get it to work.

**Comment by RAPHAEL599** [comment]
Thank you very much

**Comment by kangarko** [comment]
Apologizes, the author did not reply. I will schedule to follow up.
