### ISSUE TITLE
1.19.3: BOSS spawn rules dissapearing.

### ISSUE THREAD

**Issue by RiceMiceBice** [kangarko/Boss#1139]
Every time i restart the server all the spawn rules dissapear and i have to do new ones each time. anyone got a fix?

**Comment by kangarko** [comment]
Hey! I am sorry but I can't reproduce this. I created the spawm rule using GUI in-game. I tried using /reload confirm command or /stop to stop the server and then starting it again, but the rules did save.

Make sure you are not having any Boss files opened while you are editing rules. Also check console for any errors during the entire process, including restarting.

Let me know if the rules persist in their spawnrule/ folders and they only disappear from the boss .yml file?
