### ISSUE TITLE
Issue with Skills

### ISSUE THREAD

**Issue by BlackGamer000** [kangarko/Boss#114]
Hi! 

I've encountered a little bug with Boss 1.6.13 on the Skills menù :c 

Basically, my Boss Skills menù have a Mini bug.

The problem is.... http://prntscr.com/jkljn4 

The skills is duplicated and i don't know lol. ._.

Thanks a lot c:

**Comment by HarveyByatt** [comment]
I'm having the same issue and when I select them it gives me an error.

**Comment by BlackGamer000** [comment]
D:

**Comment by Yhenko** [comment]
Same here

**Comment by kangarko** [comment]
I cannot reproduce, but I assume I changed this through-out the dev process so I will push a new update soon. Sorry for the inconvenience.

Please, for any errors, upload them to pastebin.com so I can see them and fix them.
