### ISSUE TITLE
1.19.3 Citizen Bosses Errors

### ISSUE THREAD

**Issue by LucidAPs** [kangarko/Boss#1142]
Console error: https://nekobin.com/vayefubefe

Also citizen bosses option for sounds do not work, also the defensive potions like regeneration and damage resist do not work on citizen bosses.

Edit: Also the life attribute seems capped at 20.

**Comment by kangarko** [comment]
The life attr is capped from Citizens, we can only properly assert it if Boss is not linked with that plugin. Make sure you run the latest Citizens version.

**Comment by LucidAPs** [comment]
Yeap I do.
![image](https://user-images.githubusercontent.com/42933023/223992809-96922327-7903-4672-9f03-6ad607e12626.png)

**Comment by kangarko** [comment]
Can you try disabling something called Paper plugins? Or try using Paper https://api.papermc.io/v2/projects/paper/versions/1.19.3/builds/404/downloads/paper-1.19.3-404.jar before they have implemented this "feature"

**Comment by LucidAPs** [comment]
Actually something interesting I just noticed, when you first create a npc boss and you set its health to 2048, it works just fine. But as soon as your change its skin from the menu, then the hp goes and stays at 20.

**Comment by kangarko** [comment]
Can you please review if Citizens have a cap for maximum health? If they do then you need to increase it from their config

**Comment by LucidAPs** [comment]
It doesnt.

**Comment by kangarko** [comment]
It will ask the developer for best practice since I am not so familiar with their API: https://github.com/CitizensDev/CitizensAPI/issues/77

Lets follow on there.
