### ISSUE TITLE
Minecraft Version: Issue Title

### ISSUE THREAD

**Issue by PriestOfTerror** [kangarko/Boss#1143]
Plugin not working

1) Put your Minecraft version in the title.
1.19.x - 1.19.3 + viabackward

2) Be clear: plugin is not working

3) If needed - upload your plugin's folder here and any errors using pastebin.com.
here is error message from console:

https://pastebin.com/fxLMVp95

**Comment by kangarko** [comment]
Looks like Paper has updated and introduced their own plugin loader feature, disable Paper plugins.

**Comment by PriestOfTerror** [comment]
Můžu se tu zeptat ještě na migraci účtu?

Odesláno z iPhonu

**Comment by kangarko** [comment]
Ano, posli prosim na matej@mineacademy.org email tvoje udaje
