### ISSUE TITLE
1.19.3: Allowing mobs to use citizen causes problems when deleteing them

### ISSUE THREAD

**Issue by XXdaugonXX** [kangarko/Boss#1145]
When deleting a boss that has been made into a Citizens NPC, wont delete the NPC's.

This results to you being forced remove them using the citizens command to get rid of them.

Boss Version: 4.7.2

**Comment by kangarko** [comment]
This is intended. Doing /boss remove wont remove alive bosses. You can use /boss butcher first before removing.
