### ISSUE TITLE
1.19.4 npc boss hp

### ISSUE THREAD

**Issue by PriestOfTerror** [kangarko/Boss#1147]
Hi, if I set the life of the boss I'm making as an npc to 400, it doesn't work. In the menu, the value is 400, but in reality it still has 20 hp

**Comment by kangarko** [comment]
Make sure you are on the latest version. Also have the latest Citizens version. And make sure the max-health attribute in spigot.yml is greater than what you are trying to set.

**Comment by PriestOfTerror** [comment]
Bylo to verzí, díky28. 3. 2023 v 7:30, Matej Pacan ***@***.***>:﻿
Make sure you are on the latest version. Also have the latest Citizens version. And make sure the max-health attribute in spigot.yml is greater than what you are trying to set.
