### ISSUE TITLE
Minecraft Version: Your Question Title

### ISSUE THREAD

**Issue by PriestOfTerror** [kangarko/Boss#1149]
Ahoj! chci se zeptat, kde bych našel nějakou dokumentaci nebo něco o nastavení questů. (Quests + Boss) Nevím jak to do questu nastavím, abych třeba měl zabit jednoho bosse nebo tak.

**Comment by kangarko** [comment]
Ahoj, Boss samotný ako taký questy nepodporuje, ale hocijaký plugin ktorý ma questy alebo missie môžeš nakonfigurovať tak, aby používal Bossov. S tým ale neviem pomôcť.

**Comment by PriestOfTerror** [comment]
ohh, taak to pro mě teď znamená celkem problém :/ měl jsem za to, že to šlo :( ..
A náhodou neplánuješ to do budoucna, že by se možnost questů do pluginu přidala?

**Comment by PriestOfTerror** [comment]
Už jsem to vyřešil, děkuji.1. 4. 2023 v 11:53, Matej Pacan ***@***.***>:﻿
Ahoj, Boss samotný ako taký questy nepodporuje, ale hocijaký plugin ktorý ma questy alebo missie môžeš nakonfigurovať tak, aby používal Bossov. S tým ale neviem pomôcť lebo tie pluginy nepoznám.
