### ISSUE TITLE
Optimize boss.find.Boss() performance

### ISSUE THREAD

**Issue by matipoirierg** [kangarko/Boss#1150]
https://spark.lucko.me/EKL3tcZwub
I don't think a 4% consumption is good, considering that is a constant value even when there are no bosses active. I don't have any spawn rules, I just have 4 bosses that I only spawn manually using the boss spawn command.

**Comment by kangarko** [comment]
Thanks, I will add a cache for the getTag call so that we don't have to call the regex split method every time.

**Comment by matipoirierg** [comment]
![Screenshot 2023-08-09 222731](https://github.com/kangarko/Boss/assets/97362850/c9601d04-3fbf-4e82-9fbd-af502a528234)
:(

**Comment by kangarko** [comment]
Looks like CraftEntity.hasMetadata is not optimized in Paper 1.20. Plus getLivingEntities() takes 5.26% too, I have reported this to Paper years ago, still not fixed. I unfortunately can't add cache for these two Bukkit API calls.
