### ISSUE TITLE
Minecraft Version: 1.19.4

### ISSUE THREAD

**Issue by PriestOfTerror** [kangarko/Boss#1152]
1) Put your Minecraft version in the title:
 1.19.4

2) Be clear: Již mám na serveru pár bossů, ale někteří nevnímají vůbec nastavení, aby se drželi ve svém regionu. Zkoušel jsem je porovnávat s těmi, kteří se v regionu drží, ale nenašel jsem žádnej rozdíl. Čím to může být?

zkoušel jsem v nastavení věci vypínat a zapínat, ale vůbec to nemá žádnej efekt.

**Comment by kangarko** [comment]
Prosím uploadni /boss debug a napíš ktorých bossov sa to týka.

**Comment by PriestOfTerror** [comment]
Týká se to bossů: Stratce, PanStinu18. 4. 2023 v 12:05, Matej Pacan ***@***.***>:﻿
Prosím uploadni /boss debug a napíš ktorých bossov sa to týka.

**Comment by kangarko** [comment]
Vďaka. Avšak nevidím tvoj /boss debug súbor, prosím prilož ho ako prílohu.

**Comment by PriestOfTerror** [comment]
Pokud bys ho neviděl ani teď, pošlu ještě jednou z pc18. 4. 2023 v 13:53, David Hačko ***@***.***>:﻿<debug.zip>Týká se to bossů: Stratce, PanStinu18. 4. 2023 v 12:05, Matej Pacan ***@***.***>:﻿
Prosím uploadni /boss debug a napíš ktorých bossov sa to týka.

**Comment by kangarko** [comment]
Je mi luto, z emailu sa to nechce uploadnut. Vies to nahrat cez ufile.io a poslat link.

**Comment by PriestOfTerror** [comment]
Přes ten link mi to nešlo nahrát, tak jsem to hodil na úschovnu, snad to půjde takhle :)

**Comment by kangarko** [comment]
Ano ale neposlal si mi link na uschovnu?

**Comment by PriestOfTerror** [comment]
Jo, pardon :D

https://www.uschovna.cz/zasilka/JJL6RP3XRTHXJ24N-KPT/￼
Zásilka služby Úschovna ke stažení
uschovna.cz

**Comment by kangarko** [comment]
Malo by to byť opravene. Ak nie, nastav si Debug v settings.yml na ["region-keep"] a vypiš mi log z konzoli prave v tej chvili, kedy Boss prekroci hranicu regionu a mal by nastať teleport späť.

**Comment by PriestOfTerror** [comment]
Dobře, děkuji aa jak jsi to opravil? Mám restartovat server či něco, než to pujdu vyzkoušet?22. 4. 2023 v 12:53, Matej Pacan ***@***.***>:﻿
Malo by to byť opravene. Ak nie, nastav si Debug v settings.yml na ["region-keep"] a vypiš mi log z konzoli prave v tej chvili, kedy Boss prekroci hranicu regionu a mal by nastať teleport späť.

**Comment by PriestOfTerror** [comment]
No koukám na to a boss "strazce" stále může utíkat mimo region a ještě k tomu přestal útočit.  A to "region-keep" mám prosím napsat kam přesně v settings?22. 4. 2023 v 12:53, Matej Pacan ***@***.***>:﻿
Malo by to byť opravene. Ak nie, nastav si Debug v settings.yml na ["region-keep"] a vypiš mi log z konzoli prave v tej chvili, kedy Boss prekroci hranicu regionu a mal by nastať teleport späť.

**Comment by kangarko** [comment]
Ano, vypni a zapni server. Nereloaduj.

Tu hodnotu zapis do kluca Debug v subore settings.yml takto:

![a](https://i.imgur.com/qJSUnve.png)

Prestal utocit pokial je hrac mimo region? Tak to ma byt, pretoze Boss nebude targetovat hracov mimo svoju zonu aby za nimi neutekal.

**Comment by PriestOfTerror** [comment]
Stále to nefunguje. Boss stále utíka mimo region, už sice útočí, ale s tím přišel další problém, že mě boss stunuje i přes to, že jsem za zdí a 30 bloků od něj. Dokonce i když jsem v gm 3. 

Přikládám lastlog.￼

**Comment by kangarko** [comment]
Log nevidím.

**Comment by PriestOfTerror** [comment]
Útočí i mimo region22. 4. 2023 v 18:33, Matej Pacan ***@***.***>:﻿
Ano, vypni a zapni server. Nereloaduj.
Tu hodnotu zapis do kluca Debug v subore settings.yml takto:

Prestal utocit pokial je hrac mimo region? Tak to ma byt, pretoze Boss nebude targetovat hracov mimo svoju zonu aby za nimi neutekal.

**Comment by PriestOfTerror** [comment]
￼

**Comment by PriestOfTerror** [comment]
Ještě jednou pro jistotu zasílám přes úschovnu, pokud stále nepřišel

https://www.uschovna.cz/zasilka/JKWCGIKMY4HDS7FB-4U9/￼
Zásilka služby Úschovna ke stažení
uschovna.cz

**Comment by kangarko** [comment]
Vidim to iba na uschovni. Avsak neposlal si ho podla instrukcii. Nevidim tam ani jeden zapis "region-keep": "vypiš mi log z konzole prave v tej chvili, kedy Boss prekroci hranicu regionu a mal by nastať teleport späť"

**Comment by PriestOfTerror** [comment]
Posílám tedy přes úschovnu nový log. (Šel jsem k bossovi a došel s ním až pryč z hranice jeho regionu, přičemž stále útočil) 
Přikládám ještě screen, kde mám napsané to „region-keep"￼

**Comment by kangarko** [comment]
Prepáč, ale stále sa mi to nezobrazuje, žiaľbohu GitHub asi robí problémy keď to posielaš cez email. Môžeš ma teda priamo kontaktovať na matej@mineacademy.org aj s logom v prílohe nech to máme rýchlejšie.

**Comment by PriestOfTerror** [comment]
Dobrá během pondělí nebo úterý ti to tak pošlu, teď dělám hudební akci, takže jsem mimo domov. 27. 4. 2023 v 20:23, Matej Pacan ***@***.***>:﻿
Prepáč, ale stále sa mi to nezobrazuje, žiaľbohu GitHub asi robí problémy keď to posielaš cez email. Môžeš ma teda priamo kontaktovať na ***@***.*** aj s logom v prílohe nech to máme rýchlejšie.
