### ISSUE TITLE
1.19.3: Bosses not despawning if Chunks are unloaded + Mobs like Wither & Warden not despawning at all.

### ISSUE THREAD

**Issue by 0x484** [kangarko/Boss#1153]
Issues with the "Despawn when far away" function:

1. My Bosses are not despawning when they're in unloaded Chunks. To be specific, sometimes they do despawn but most of the time they don't. I am not sure if this is a bug with the Boss plugin or my Server or if it's even possible to despawn since the Chunks are unloaded.

2. Boss Mobs like the Wither and the Warden + maybe others (I haven't testet them all) do not despawn at all which im pretty certain is a "bug" with Boss. Is it possible to make those despawn as well?

Boss Version - 4.7.4

**Comment by matipoirierg** [comment]
Have you checked if you have persistency enabled?

**Comment by matipoirierg** [comment]
![2023-04-24_22 32 57](https://user-images.githubusercontent.com/97362850/234160448-d7f50d22-3c05-46a9-bccb-9a6b52dbef98.png)
