### ISSUE TITLE
1.19.4: NPC Boss Speed and target change on update or leaving area. 

### ISSUE THREAD

**Issue by nasiridrishi** [kangarko/Boss#1156]
NPC boss speed changes the moment they are updated after being spawned or if you leave chunk and go back. They also start try to attack even when you are in creative. 

Citizens version 2.0.31-SNAPSHOT (build 3083)
Boss version 4.7.7

Here is a video which might be helpful reproducing this issue https://youtu.be/doKy0A0Bemo

**Comment by kangarko** [comment]
Thank you. Unfortunately this looks like another one of those attributes that we would need to store manually. Looks like Citizens resets a bunch, we had a problem with custom health being reset after what you describe [here](https://github.com/CitizensDev/CitizensAPI/issues/77). Unfortunately I dont have the capacity to store every minecraft value manually.
