### ISSUE TITLE
I want to know why the pigs are not attacking me.

### ISSUE THREAD

**Issue by zaxsqwcde** [kangarko/Boss#1159]
And there are other animals that are like this too.
I also want to know how to adjust the monster's attack power.
Anyone knows how to adjust?
-
And armor enchanted by mmoitem, why are they useless?
when equipped with ferocious monsters
Including when they hit it to damage 3, how do we adjust it to increase or decrease?
or it still doesn't support cmi

**Comment by kangarko** [comment]
That's a citizens error, make sure you use their latest dev version, if yes then report it to them.

**Comment by zaxsqwcde** [comment]
ok

**Comment by zaxsqwcde** [comment]
Can I ask you one more thing?

**Comment by kangarko** [comment]
Can you send a screenshot of what message you mean?
