### ISSUE TITLE
1.19.4:FoException Report: Cannot instantiate SerializedMap(YAML) from String: []

### ISSUE THREAD

**Issue by Swede37** [kangarko/Boss#1160]
HI, I'm trying to update BOSS from version 3.7.1 to 4.7.7, and have been having issues.  During conversion, it keeps coming up with exceptions about a particular Boss.  I disable the boss from the backup folder, and reupload to the server to re-convert, but then it just picks another boss and assigns the same errors, so I'm assuming it's something to do with the actual conversion and not that particular boss.  This is what shows in the error log:[https://pastebin.com/VRDYGyq4](url)
I'm not sure if you want the entire folder uploaded or not?
Thanks in advance, and appreciate any help as we would really hate to have to recreate these Bosses all over again.

**Comment by Swede37** [comment]
Sorry, I'll try linking that again.
https://pastebin.com/VRDYGyq4

**Comment by kangarko** [comment]
Thanks, going to follow up via email.
