### ISSUE TITLE
Alphabetical Listing of Bosses

### ISSUE THREAD

**Issue by cobrex1** [kangarko/Boss#1163]
Hi Matej,

Have been using Boss for years. I now have over 200 bosses in the file.

Couple of suggestions:
1) Would it be possible in the Boss Menu -> Bosses GUI, that they appear in alphabetical order so it is easier for me to find the one I am looking for rather than searching all six pages?

2) It would also be really helpful to have a **/boss edit [name]** command to get into the bosses' editor even quicker, or make the /boss list list clickable and in alphabetical order,

I feel that either or both of these would improve the customer experience even further,

Thanks
Cobrex

**Comment by kangarko** [comment]
Excellent suggestion! I implemented this asap :)
