### ISSUE TITLE
1.19.4: Boss Rides despawn when underwater

### ISSUE THREAD

**Issue by 0x484** [kangarko/Boss#1169]
I have certain Bosses that ride on others. Those Ridables dissapear when they're underwater. Mobs that can not swim do not have this issue, eg. Skeleton Horses, Phantoms. Mobs like Zombie Horses, Ravagers dissapear. (This can be tested when spawning a boss underwater)

**Comment by kangarko** [comment]
I apology, this seems like a behavior from Bukkit/NMS, at this point I am unable to fix this.
