### ISSUE TITLE
Bosses execute commands

### ISSUE THREAD

**Issue by Curtis73** [kangarko/Boss#117]
Perhaps make it possible for bosses to execute certain commands when targeting another player, as it could add indirect support to custom command and numerous other plugins.

**Comment by kangarko** [comment]
Great suggestion, thank you!

For now, if you are a developer, you can simply listen to the EntityTargetEvent and use BossAPI to verify if the targetter entity is a boss.

**Comment by kangarko** [comment]
Had to close due to works on other priorities.
