### ISSUE TITLE
/boss butcher world not working properly

### ISSUE THREAD

**Issue by matipoirierg** [kangarko/Boss#1170]
Hi so I'm using the ptrodactyl crom system to spawn bosses, before spawning a boss I run the command /boss butcher Hub, Hub is the world where bosses are spawn, this way if the previous boss wasn't killed it won't stack on a new boss spawn. The problem it's that if the chunk where the boss is unloaded the butcher command won't kill them, I'm on purpur 1.20.1, Boss version 4.8.1.

**Comment by kangarko** [comment]
Correct, the butcher subcommand doesn't remove Bosses from unloaded chunks. This is a heavy operation and we have a dedicated command for this called /boss scan

**Comment by matipoirierg** [comment]
> Correct, the butcher subcommand doesn't remove Bosses from unloaded chunks. This is a heavy operation and we have a dedicated command for this called /boss scan

I can't use the command, Only MC 1.7.10 - 1.17 and up are supported. Please notify the developer to update. (I'm on 1.20)

**Comment by kangarko** [comment]
Thanks, will be fixed in 1h
