### ISSUE TITLE
Add range for skills (steal life, TNT, freeze...)

### ISSUE THREAD

**Issue by Lecer69** [kangarko/Boss#1171]
There are some skills that don't have a specified range. As a result, even when you are not near the boss, the boss's skill can still affect you. I have a suggestion to add a custom range or radius to skills.

For example, if the "Steal Life" skill currently doesn't have a range, it means it can damage players from a distance of 30+ blocks away. This causes confusion among players as they wonder where the damage is coming from.

**Comment by kangarko** [comment]
No problem, I have added it to settings.yml!

![a](https://i.imgur.com/49FoenQ.png)
