### ISSUE TITLE
1.16.5: Problem with Citizens

### ISSUE THREAD

**Issue by KoopinSmall** [kangarko/Boss#1177]
Hello!

I ran into a problem when I migrated my bosses to the Citizens system. For some reason, I can now kill my bosses with one hit, and the console is spamming errors. 
All plugins of the latest version (Citizens, Boss)

https://pastebin.com/qDPbNAQS

**Comment by kangarko** [comment]
It says "Health must be between 0 and 20.0, but was 2048.0". 

In root server folder, in your spigot.yml, change the max health to 2500 or any high value:

![a](https://i.imgur.com/qAoI8d7.png)
