### ISSUE TITLE
Minecraft Version: 1.18.2: Bosses lose AI

### ISSUE THREAD

**Issue by iZeaoGamer** [kangarko/Boss#1180]
So I have an issue with Bosses. The issue is, AI's abilities still work, but eventually has no functioning AI. It just doesn't move, but when you go close to it, it'll use its abilities on you. When the boss first spawns, it appears to work just fine, but after a while it just loses AI.
I've got RoseStacker which is a stacking plugin. I don't think this may be an issue since Mobs from spawners lose AI. Natural mobs that spawn, don't lose AI. It's just bosses that do, and they aren't from spawners.

I use Citizens plugin for Bosses too.
Here is the Boss folder in case it's a miss configuration issue.
[Boss.zip](https://github.com/kangarko/Boss/files/12282451/Boss.zip)

**Comment by iZeaoGamer** [comment]
Apologies for creating 2 issues. I've fixed that up, so this is the up to date issue.

**Comment by kangarko** [comment]
Thanks, I will add hook to RoseStacker tonight.
