### ISSUE TITLE
Version 1.20.1: Bosses disappear!

### ISSUE THREAD

**Issue by SirCorrosion** [kangarko/Boss#1182]
After a recent update (I believe it was after updating to the version supporting 1.20) MOST of my bosses have disappeared from my Boss Menu. All the files containing my different bosses are still in my server files but the plugin is not recognizing them. Only about 6 out of my 20+ bosses are still actually loaded into my server.

I cannot find a difference between files of bosses that still load onto the server and those that do not. I have noticed increased errors in the console regarding the Boss plugin. I have included a screenshot of the errors as well as my entire Boss plugin folder.

Thank you for the support!

[BossesFolder.zip](https://github.com/kangarko/Boss/files/12317044/BossesFolder.zip)

//

![Screenshot 2023-08-09 193602](https://github.com/kangarko/Boss/assets/141962917/d7c6d74f-17ee-48a3-a6bf-604879caee27)

**Comment by kangarko** [comment]
It says camel.yml boss is an empty file, it has 0kb size. Looks corrupted, are you able to send me the backed up folder before upgrading? If not try deleting that file and see if the other bosses load fine.

**Comment by SirCorrosion** [comment]
That fixed the issue! Thank you for the support I greatly appreciate it!!!

**Comment by kangarko** [comment]
@SirCorrosion you're welcome :) Mind dropping me a quick review at builtbybit to help me get going? Thx
