### ISSUE TITLE
Buggy Pets (Boss 4.8.9) (MC 1.19.4)

### ISSUE THREAD

**Issue by Lecer69** [kangarko/Boss#1183]
There is a bug in Pets. When there is a limit for pets and their passengers, it gets bugged. For example, as you can see in this screenshot, the Shrek Boss is spawn-limited to 1, just like its pet. When the pet is already spawned, the passenger cannot spawn the pet, and it prints an error or warning in the console.

Here is the error:
https://pastebin.com/zXWGafVH

The Screenshot:
![2023-08-12_19 32 37](https://github.com/kangarko/Boss/assets/83245235/cf035559-0c2f-47f1-a889-974fcf794b8f)

**Comment by kangarko** [comment]
I will fix that, thank you!
