### ISSUE TITLE
1.20.1 API PROBLEM

### ISSUE THREAD

**Issue by Gryglo** [kangarko/Boss#1185]
1.20.1 API PROBLEM

I am using Boss API in my plugin and I tried to check if the entity is Boss using "BossAPI.isBoss(entity)" and it returned false even if the entity actually was the boss. I am using it in ProjectileHitEvent and getting the event.getHitEntity() btw.

Please take a look at it

**Comment by kangarko** [comment]
Check if the entity has Boss_V4 metadata using Bukkit's API. If that wont work then unfortunately some other plugin you have is removing it, i.e. mob stacking plugins
