### ISSUE TITLE
1.19.4 - Adjusting mob spawn in a dungeon

### ISSUE THREAD

**Issue by Spygain** [kangarko/Boss#1189]
Hello, I'd like to create a dungeon with mobs that spawn near the player. It's a dungeon with high corridors and large rooms, spread over several levels. I've built it in void. However, the mobs spawn above the dungeon, even in the void. The light value makes no difference to the spawn, so the mobs appear anywhere. As for the radius, I've set it to the minimum (5) and the mobs always appear several dozen blocks above (above the dungeon). I'd like to know if it's possible to set the appearance zone more precisely, around the player.

Exemple :

https://imgur.com/a/lenZ2fS

Code :

https://pastebin.com/jqUEfwBA

Thanks in advance

**Comment by kangarko** [comment]
Hey!

No problem and thanks for using Boss. For your case I recommend using precise spawn points. First, create spawn locations with /boss tools and then simply create a spawning rule that will spawn at these location points in the desired time intervals, either it'll be the rule of entering a region, or at a block.
