### ISSUE TITLE
BossRegion spawn 

### ISSUE THREAD

**Issue by Victor75007** [kangarko/Boss#119]
Hello, 
my bosses doesn't spawn in BossRegion.
Region is online. 
Config good.

And, how i can create more BossRegions?
Because i click other block, then it delete older region.
The bosses will be dungeons bosses.
If it succeed.

[https://prnt.sc/jpy93u](url)

[https://prnt.sc/jpy99g](url)

[https://prnt.sc/jpy9du](url)

[https://prnt.sc/jpy9hx](url)

[https://prnt.sc/jpybtv](url)

[https://prnt.sc/jpybzu](url)  - Test zone

Thanks for help. :)
Have a nice day!

Kind Regards,

Victor

**Comment by kangarko** [comment]
Hello,

to see why they are not spawning, set Debug to "[spawning]" in settings.yml and post me the output. You must be within a region. Also read https://github.com/kangarko/Boss/wiki/Common-Issues#my-bosses-are-not-spawning-in-regions

To create more regions, simply use Region Tool in /boss tool to select two points, and then use /boss region add {name} (replace {name} with a unique name)

**Comment by kangarko** [comment]
Closing, message below if still having issues.
