### ISSUE TITLE
Multi-language translation of the plugin

### ISSUE THREAD

**Issue by Spygain** [kangarko/Boss#1194]
So I don't know if this has already been proposed, but translating the plugin's messages via a platform like : https://crowdin.com/

I know the universal language is English, but why not adapt the plugin for other languages, to make it easier for everyone to understand.
Having already translated some plugins via crowdin, I think it's a very good site for doing this kind of thing.

And if other people know of other plugins, why not suggest them below ?

**Comment by kangarko** [comment]
Thanks. I mean, you can just translate the messages_en.yml file to any language. Just send it to my email when done and I'll ship it with the plugin and credit you.
