### ISSUE TITLE
1.20.1: Nearest follow distance in citizens goals needs to be decreased 

### ISSUE THREAD

**Issue by nasiridrishi** [kangarko/Boss#1195]
There is a max hit distance where in boss is more than that then it won't hit you but if its less that that it will hit you and there is minimum follow distance after which it will stop following you i think its around 4 and the max hit distance is i think 2 so if you manage to stand still and not move in between that and not move then boss will also stand still and not follow you. I think minimum follow distance needs to be decreased to avoid this case since it can easily be abused by players. 
https://i.imgur.com/58LPKx5.png

**Comment by nasiridrishi** [comment]
Here is a short video showing what I mean 

https://github.com/kangarko/Boss/assets/27479208/ec39d28a-7dbb-462c-b1ae-ad73d57a4e7d

**Comment by kangarko** [comment]
Thanks, I'll ask the developer, I was not able to find the appropriate metadata to set.

**Comment by nasiridrishi** [comment]
may be look into https://github.com/mcmonkeyprojects/Sentinel and see how they handling it? I don't face issue with sentinel plugin

**Comment by kangarko** [comment]
Thanks, please test the next version going up tonight.

**Comment by nasiridrishi** [comment]
@kangarko nop, this is not fully fixed:  Boss version 4.8.13

https://github.com/kangarko/Boss/assets/27479208/334e6cef-79d7-49d1-8f65-5ba526af1c16

**Comment by kangarko** [comment]
Please send me /boss debug, I need to test your exact Boss. Mine appears to be working alright.

**Comment by nasiridrishi** [comment]
When fighting with boss, don't move or hit your self, stay still and let the boss hit you.
[debug.zip](https://github.com/kangarko/Boss/files/12472293/debug.zip)

**Comment by nasiridrishi** [comment]
@kangarko maybe reopen this issue so you don't forget?

**Comment by kangarko** [comment]
Thanks, going to review in 24h

**Comment by kangarko** [comment]
Thanks, the next version.

**Comment by nasiridrishi** [comment]
@kangarko  Seems like it still persists 

https://github.com/kangarko/Boss/assets/27479208/662ab69a-ea62-4cb3-95d1-9d6c7004ec28

[debug.zip](https://github.com/kangarko/Boss/files/12596699/debug.zip)

**Comment by kangarko** [comment]
I am sorry, going to investigate in 48h

**Comment by kangarko** [comment]
I unfortunately tried what their devs suggested and I am sorry to see it did not help, let's follow up here: https://github.com/CitizensDev/Citizens2/issues/3054
