### ISSUE TITLE
Compatibility with ItemsAdder

### ISSUE THREAD

**Issue by Spygain** [kangarko/Boss#1196]
I wonder if it would be possible to add compatibility with ItemsAdder, [spigot](https://www.spigotmc.org/resources/%E2%9C%A8itemsadder%E2%AD%90emotes-mobs-items-armors-hud-gui-emojis-blocks-wings-hats-liquids.73355/), [builtbybit](https://builtbybit.com/resources/itemsadder.10839/?ref=discover), for Boss loots, so that they can also drop custom items?

I don't have any other information to provide.

If you have any questions, I'm available

**Comment by kangarko** [comment]
I believe it should work as-is, just put the item into the GUI.

**Comment by Spygain** [comment]
I admit I haven't tested it before, but I wanted to know if it was planned or already included.

As soon as possible I'll do the test on my side.

**Comment by kangarko** [comment]
No worries, if it is not then we will just refund you or try to add this feature.
