### ISSUE TITLE
Can't set native conditions

### ISSUE THREAD

**Issue by Kimskell** [kangarko/Boss#12]
I can't set the native conditions for spawning bosses, like height. At first it looks like it goes right.  It is strange that the menu shows defaults and not showing the changes. But in the Boss yml height is changed. unfortunately after making some other changes like lightlevel the boss height is set back to default 0 - 256. Do I something wrong?
Tested it some more. If I first change Light condition and then Height, The pluginn only changes height condition. All other conditions are set to default (the number the menu shows).

**Comment by kangarko** [comment]
Hey,

good notice, I have fixed that.

PS: I am sorry for a late response, thank you for your patience.
