### ISSUE TITLE
Idea: Frendly mob will be aggressive 

### ISSUE THREAD

**Issue by Victor75007** [kangarko/Boss#120]
Hello, 

I have one idea.
The friendly mobs will be aggressive 
, if possible 
Wolf as Hostile Wolf
Villager as Bandit, or thief, or, rogue, or rebellious man, or other
Ocelot as jaguar, or tiger.. etc. 
Settings for friendly or aggressive animals. 
put in aggressive wolf to wilderness. 
It's very cool mobs on RPG server.
I think many people glad to it.

**Comment by kangarko** [comment]
https://github.com/kangarko/Boss/wiki/Common-Issues#can-you-make-animals-aggressive--add-better-ai
