### ISSUE TITLE
1.20.1 - Playerhead - HeadDataBase

### ISSUE THREAD

**Issue by cobrex1** [kangarko/Boss#1201]
I have added a HeadDatabase head to the Boss, so when viewed it displays that head.

However, on Death, the Boss drops the head but not the armor etc. I have vanilla drops disabled and the heads are not set in the player drop section either, but cannot see if there is any other option to disable the head also being dropped.

Have I missed something, or is this an improvement that could be added?

Thanks
Cob

**Comment by kangarko** [comment]
Hey! Just to make sure I understand 100% - you placed HeadDatabase item inside Boss' equipment slot as helmet, set the drop chance to 0% but it still drops?

**Comment by cobrex1** [comment]
Oooo, ok I need to check that. I am sure they are set to 0% and come back to you.

**Comment by cobrex1** [comment]
Yup the issue is resolved, a couple of bosses had 100% as the drop chance - thank you, didn't think to check that. :(
