### ISSUE TITLE
1.20.1 Boss Drop chance menu

### ISSUE THREAD

**Issue by cobrex1** [kangarko/Boss#1202]
When editing the drop chance menu of general drops, once I have completed editing the drop chances I come out the menu, however, now the items have been written with the drop chance edit menu. When the boss is killed the item dropped, looks like this.

![boss drop](https://github.com/kangarko/Boss/assets/44735826/f4f27e9a-5aa2-4281-81e6-a5d871f58446)

If I exit the drop edit menu with the chance editor on it does not re-write the lore but it is still there. If I click the edit icon back to a chest, the item's lore updates with the new drop chance.

Boss version 4.8.13

If I exit the drop edit menu with the chance editor on it does not re-write the lore but it is still there 
I have also just tested this with 4.8.12 same issue,
I am going to try a new paper version to check that this is not the issue. Current version 167, new version 169 and the issue persists.

**Comment by cobrex1** [comment]
I have added two boss flies for you to look at.
Karakota_1 (start line 220) is where I just added the paper item to the general drop chance. 
Krakota_2 (start line 230) is where I edited the drop chance of the paper drop. The lore has been added to.
I had to change the .yml to .txt

[Krakatoa_1.txt](https://github.com/kangarko/Boss/files/12503441/Krakatoa_1.txt)

[Krakatoa_2.txt](https://github.com/kangarko/Boss/files/12503442/Krakatoa_2.txt)

**Comment by kangarko** [comment]
Apologizes for the delay, I found a solution. It will be fixed tonight!
