### ISSUE TITLE
Bosses spawning on superior skyblock island, how do i stop players from being able to spawn bosses there?

### ISSUE THREAD

**Issue by FireKiller258** [kangarko/Boss#1203]

**Comment by FireKiller258** [comment]
also how do I stop bosses from clearing from clear lag?

**Comment by kangarko** [comment]
Hey! You would need to create a custom spawn rule and exclude the world where islands are:

![a](https://i.imgur.com/V3pLdBU.png)

For the other question, you would need to ask ClearLagg developer to ignore entities having Boss_V4 scoreboard tag

**Comment by FireKiller258** [comment]
Hey like how do you make it so bosses cannot spawn on superiorskyblock island worlds via spawn egg

**Comment by kangarko** [comment]
You'd have to reach out to that plugin developer and ask him kindly to cancel our BossEggEvent when on the island. You can send him Boss jar for this.
