### ISSUE TITLE
1.19.4 : Objects dropped by mobs retain the drop percentage display. 

### ISSUE THREAD

**Issue by Spygain** [kangarko/Boss#1204]
Server version paper 1.19.4
Boss version : 4.8.11

Hello, 

I've been using your plugin for a few weeks now and I've noticed that items dropped by mobs keep the drop percentage display. 
I suppose this is because when you quit the chance drop window, the game remembers the display, which is problematic for the player's immersion and costs a considerable amount of time to rectify.
I have tried to reload the plugin, without success. The only way I know of at the moment is to be very careful to leave the menu where you drop items, and not the one where you set drop rates.

Here are the screenshots with and without the bug : https://imgur.com/a/WaF4mtI
I think the concern is the same as this request : https://github.com/kangarko/Boss/issues/1202

Is there any way of getting around the problem or solving it?

Thanks in advance

**Comment by kangarko** [comment]
Thanks, apologizes for this and will be fixed asap!
