### ISSUE TITLE
Add New WorldGuard Flag for stop targetting players

### ISSUE THREAD

**Issue by Lecer69** [kangarko/Boss#1205]
a new worldguard flag to prevent boss from targetting players.
it's not the same as 'boss-target' flag, because the boss-target flag doesn't stop targetting player.

*by the way I'm still waiting for "apply looting for mob drops"*

**Comment by Lecer69** [comment]
> The boss-target stops targeting inside regions, how do you want the new flag to be different?

But boss-target doesn't stop targeting players when the players move to a new region with "boss-target" flag.

**Comment by kangarko** [comment]
I am sorry, I don't understand you exactly. So you want to un-target players automatically when they cross a region's border? I am afraid that would cause a lot of performance issues since we'd have to check for movement, but I can add it as a toggle able option if this is what you asked for.

**Comment by Lecer69** [comment]
> I am sorry, I don't understand you exactly. So you want to un-target players automatically when they cross a region's border? I am afraid that would cause a lot of performance issues since we'd have to check for movement, but I can add it as a toggle able option if this is what you asked for.

Yes, but you can use a runnable instead of checking for movements.

Here's the video for more details:
https://youtu.be/y_B7ZwJODTU

**Comment by kangarko** [comment]
Thanks, done!
