### ISSUE TITLE
Config to replace mob eggs with mob heads

### ISSUE THREAD

**Issue by jonathan-lr** [kangarko/Boss#1208]
1) How it would benefit others? (Not just you, but 1,000s of other people using the same plugin.)
Using the UI to select the mob for creation can be a pain, not everyone has the mob eggs memorized setting it to the mob skull would make it easier to find.

2) What would happen if we don't implement this feature? How's your server being affected?
The bottom line is it won't. It's just annoying creating a bunch of bosses. When you're looking for something like an elder guardian or a goat scanning through the names.

3) If suggesting something new - Can the old system be modified/improved instead?
Yes, setting in the config to change it to skulls instead, UI item stack can just use the mob skull instead of the egg. Even use the HeadDatabase API - https://github.com/Arcaniax-Development/HeadDatabase-API

**Comment by kangarko** [comment]
Eggs have been here since 2011, we have more important things on our list then swapping with heads
