### ISSUE TITLE
Boss ==> New Ideas

### ISSUE THREAD

**Issue by BlackGamer000** [kangarko/Boss#121]
Updates for Boss

Hello! Today I want to make some very nice proposals for the Boss Plugin. To be exact I want to make 5 proposals.

1° Idea: - Particles

Yes, right. I want to propose the addition of the particles available from many plugins or insertable within the plugin itself.

Basically from the command /boss menu ==> <name> ==> Settings ==> "Particles"

From this menu it will be possible to activate 2 or more particles at the time. Obviously it is not to be excluded the fact that this is aesthetically to do more design, the effects can also be used to cause damage depending on the radius of distance between a player and a Boss.

Sample of Particles:

Blood Aura: The approaching player receives a variable damage between 20-30 seconds with Blood explosions, the effect spreads to the players who approach the person who has been "influenced" by the Boss. Of course, it can also be mixed with the Minecraft potions. So as to make the battles much more beautiful and complex.

Lightning Aura: Through the Lightning Aura the player approaching the boss receives lightning strikes that propagate around the circle of the area.

Note: Damage can also be deactivated via the GUI.

2° Feature: New Skills:

Clone: ​​Through this skill the Mob performs a Freeze to the player and then the boss will make many copies around him. If within a Seconds Timing it does not Guess the true will be caused a fairly critical damage + an explosion.

Flight of the Condor: Through this skill the Boss puts all the players around him under control, making them launched randomly in the air to confuse their ideas.

Other skills will be designed in the future.

3° Idea:

Hook with CrackShot

Through crackShot it will always be possible for bosses to create new weapons to be inserted exclusively inside the Boss. In fact, the procedure must be to create a boss and then insert specific events in the form of "Strings".

To set CrackShot it will be necessary to work with some arguments. But as a Boss script.

Basically you can use the crack shot on a Mob doing /boss shotcreate <name> once created you can configure via /boss shotedit <name> (always with Arguments)
Then from /boss menu ==> <bosses> ==> <name> ==> Settings ==> CrackShot Abilities, from there you can put the weapon for the boss.

4th Idea: Boss as a VideoGame. 

This feature is a copy of an idea that has been published by another user on this repository. in Substance I want to propose a function that will introduce different boss battles for everyone, I intend to propose the addition of pressure plates for the boss. Basically the boss when spawn is invincible so any attack on the boss is useless. In this case you could set special pressure plates that will give a shock to the boss (or a different effect) that will remove the invulnerability to the Boss. From there, players will have a total of time (like 40 seconds) to inflict as much damage as possible before the boss resumes his invincibility. Obviously the idea is not so simple. Once the pressure plate have been pressed to weaken the boss, they will change position to make the game more lively.

5° Idea: Good Booster and Bad for the Players and same for the Boss. 

5th Idea: Boosters Advantageous and Disadvantageous for the players and the same for the Bosses.

With this feature you can create boosters that spawn randomly only and exclusively when the boss has been spawned. From the config (Boosters.yml) There will be a category that can be divided into

GoodBoosters: and BadBoosters:
Booster Category: Boss - Player

Booster1:
Name: &bText
Hologram_Block: Diamond_block
Commands_To_Execute_When_The_Booster_Has_Been_Obtained: -
   - /command1
   - /command2
   - /command3
   Message_When_You_Go_On_the_Booster: &bYou have obtained a booster!

Obviously this message is Changeable for each Booster.

Instead for the bosses you can use the same configuration with the holograms but if an user try to pass over the boss Booster can not use it and will receive a big kick that pushes him back.

I hope this idea is useful and also acceptable c:

GoodBye c:

Update of the 16:21

The hologram of the Booster idea is: 

                 &a&oBooster
                 For: &4Boss
              Ability: &cRandom
  <here there is a random block that roll>

**Comment by kangarko** [comment]
Hello,

to summarize, you're proposing:

1. Particles to Bosses (a) Decorational and b) Damageable)
2. Skill Flight of the Condor (the first is not possible with the current API, sorry)
3. CrackShot Integration
4. Timed Invicibility
5. Boosters

To the 3rd point, wouldn't CrackShot work if you just copy and place the weapon as the Boss' hand item in its equipment?

Honestly, while these all seem like a very good suggestions, right now I am more then occupied with a videocourse and I already got much of the summer time cut down, so I don't know if I can get to it any soon, but hey! I am leaving this open as always to add it partially or part-by-part in the future.

Thanks!

**Comment by BlackGamer000** [comment]
Hello kangarko! Sorry for the late Response.

1: Correct
2: Ok sorry :c 
3: So the CrackShot weapon works like a default weapon on the boss? 
4: Yes but with the Pressure Plate
5: Yes

**Comment by kangarko** [comment]
3. Yes, it would work as a weapon :)

**Comment by BlackGamer000** [comment]
Cool thanks a lot for that! :D

**Comment by kangarko** [comment]
Tied to roadmap.
