### ISSUE TITLE
1.20.1: NPC Boss head pitch needs to be fixed

### ISSUE THREAD

**Issue by nasiridrishi** [kangarko/Boss#1210]
Boss version: 4.8.16
mc version: 1.20.1

The bosses head pitch needs to be fixed, they seem to be look up or down and its really weird. It happens when they are targeting or wandering around

https://github.com/kangarko/Boss/assets/27479208/029417ff-81b4-494e-8e2d-160fbd35fa61

**Comment by nasiridrishi** [comment]
https://i.imgur.com/zM5L3F7.png

**Comment by kangarko** [comment]
I'll ask the developer, thanks: https://github.com/CitizensDev/Citizens2/issues/3054
