### ISSUE TITLE
Is there any way to have like a top 3 rewards a top 10 & participation rewards?

### ISSUE THREAD

**Issue by FireKiller258** [kangarko/Boss#1211]
So I want to do a Boss Event on my 1.12.2 server. But I want there to be a top 3 damager rewards & a top 10 rewards but with worse rewards for the top 10. How would I be able to do that & add it in like this. Have it like it has a top damage dealt with players 1-10, 1-3 top damagers being the same reward & 4-10 top damagers having a worse reward? Any way I can do this along with the boss death in chat with the players % of what damage they did. Kinda like cosmic pvp. 
![image](https://github.com/kangarko/Boss/assets/143948229/5ba225f1-7aa0-4d83-94aa-56786d0a0797)

**Comment by FireKiller258** [comment]
Also how do you make bosses not despawn to clear lag

**Comment by kangarko** [comment]
For the rewards issue, you need to manually configure which rewards are given for each damage in a row under Boss Settings > Death > Drops > Player Rewards, it will look something like this:

![a](https://i.imgur.com/vZhXelQ.png)

For the ClearLagg, unfortunately their developers must ignore our entities having Boss_V4 metadata. Bukkit provides a simple check for this using entity#hasMetadata("Boss_V4") so they can integrate without purchasing Boss, you need to ask them.

Thanks,
Matej
