### ISSUE TITLE
Minecraft Version: Issue Title

### ISSUE THREAD

**Issue by SuperIsSuper** [kangarko/Boss#1212]
<!---
To report a problem or a bug with this plugin, please follow the three steps below:

**IMPORTANT** If you Bosses are NOT spawning / having issues with them, please upload your folder as a ZIP (see step 3)!

1) Put your Minecraft version in the title.
Example: 1.16.1: Getting NullPointerException error

**1.19.4 Paper**

2) Be clear: What is your current situation, the desired situation, and your problem?
Example: I want my chat to be formatted in vanilla but not the creative world. My current situation is it is being formatted everywhere. I made sure not to use reload and haven't found any console errors. What I am doing wrong?

**I have created an NPC boss and it does not die in the void when I spawn it with egg and it drops down. It stops at the void level and does not die unless I butcher. I asked mod in discord and he said its probably a bug so I am here to report it.** 

3) If needed - upload your plugin's folder here and any errors using pastebin.com.
How to upload your folder?
**No errors or anything.** 

[archive-2023-09-25T144827+0100.tar.gz](https://github.com/kangarko/Boss/files/12715883/archive-2023-09-25T144827%2B0100.tar.gz)

**Comment by SuperIsSuper** [comment]
@kangarko idk why it closed issue I wrote everything down? and it did not post it. 

My NPC I created as boss do not die in the VOID when they fall. All other mobs die only not NPC type bosses on latest version.

**Comment by kangarko** [comment]
I closed it because this is what I saw: 
<img width="939" alt="Screenshot 2023-09-29 at 10 34 14" src="https://github.com/kangarko/Boss/assets/1918426/4e07cb52-1e69-47c8-b9b2-00d99afdedee">

Perhaps there is a setting for that in Citizens for NPCs not to die in void? You can ask on their support channel because Boss plugin only hooks into Citizens.
