### ISSUE TITLE
1.8.8: Warn Flood in console

### ISSUE THREAD

**Issue by IceGames23** [kangarko/Boss#1213]
I don't know why this is happening, I'm using version 4.9.0 of Boss Plugin, can u help me?

![image](https://github.com/kangarko/Boss/assets/71414690/b94b23ed-f90b-437f-97ac-566dff9187a7)

**Comment by kangarko** [comment]
Looks like you did not finish a region creation, find that region in regions/ with empty location data and remove it. I will silence this error in the next version.
