### ISSUE TITLE
1.20.1: Command spamming on boss spawn

### ISSUE THREAD

**Issue by willc5** [kangarko/Boss#1215]
When a boss spawns, for some reason the spawn command will spam a few times. There are no errors or anything

**Comment by kangarko** [comment]
What do you mean "spam a few times"?

**Comment by willc5** [comment]
> What do you mean "spam a few times"?

![Screenshot 2023-10-13 032358](https://github.com/kangarko/Boss/assets/52590664/52fdb00d-cf36-4c76-88e3-d0b34f69a23e)
When the boss spawns, whatever command I have for spawning will run more than once

**Comment by kangarko** [comment]
Send me /boss debug here please, let me know which Boss.

**Comment by willc5** [comment]
[debug.zip](https://github.com/kangarko/Boss/files/12892014/debug.zip)
When spawning at a certain location (arena) the issue does not occur. Not sure if I'm doing something wrong with the random spawning

**Comment by kangarko** [comment]
When it does occur? So I can try reproducing. Thanks.

**Comment by willc5** [comment]
Only occurs when using the "Randomly Around Players" spawn rule. Have tried changing Run Chance and Delay in that rule, but it still happens regardless

**Comment by kangarko** [comment]
Sorry, wasnt able to find the problem. So I have added a debug key to test it.

On the next version please set Debug key in settings.yml to [spawning-command], let me know what it says when the commands are duped in the console.

Also can you test whether or not it happens when you use "broadcast" instead of "essentials:broadcast"?

Sorry for taking time, hope we can resolve this asap.

**Comment by kangarko** [comment]
The code says that the Boss is spawning 5-6 times as you can see. But the commands are only run when the Boss is spawned successfully, i.e. appears as entity in the world.

I would need more data, I am sorry. In the next version, please set Debug key to [spawning-command, spawning2] in settings.yml and report the big logs when the spawning is duplicated. It should also say the location of the spawned boss

**Comment by willc5** [comment]
![Screenshot 2023-10-20 124123](https://github.com/kangarko/Boss/assets/52590664/51e84b7f-d9c7-4c22-8ea4-5d2a567cff67)

**Comment by kangarko** [comment]
As you can see, the locations are completely different. So that means the Boss is spawned 4x at totally different locations. Do you want me to cap the spawning to 1 boss maximum, per spawn rule tick?

**Comment by willc5** [comment]
Ah ok, yeah if you could add some kind of limit that would be a great addition to the plugin, thank you for the help btw

**Comment by kangarko** [comment]
Sure, let me look into this in a few days.

**Comment by kangarko** [comment]
I am sorry, I completely forgot about this. Anyways, I don't think adding more limits will make the purpose. You can configure a global limit in settings.yml > Spawning > Limits under World_Limit as well as in the game inside Spawning menu in the Boss GUI:

![Screenshot 2023-12-30 at 14 12 57](https://github.com/kangarko/Boss/assets/1918426/ff1935bf-e172-4ead-a9e1-c4cb5403b987)
