### ISSUE TITLE
1.12.2: Cave spider & spiders don't attack

### ISSUE THREAD

**Issue by SladeHazard** [kangarko/Boss#1216]
Is it possible to make it so cave spider & spider bosses attack players during the day as well?

**Comment by SladeHazard** [comment]
also how can I code this properly?

![image](https://github.com/kangarko/Boss/assets/45261094/a4689c29-49e1-4a6b-a4df-34c315d3975c)


    @EventHandler(priority = EventPriority.HIGHEST, ignoreCancelled = true)
    public void onDispenserPlace(BossSpawnEvent e) {
        Player player = e.getPlayer();

        // Check if the player is NOT in the "darkzone" region
        if (!isInsideDarkzoneRegion(player.getLocation())) {
            player.sendMessage(Main.colourise("&c&l[!]&c You cannot spawn a boss here! &a&l/warp darkzone"));
            e.setCancelled(true);
        }
    }

**Comment by kangarko** [comment]
Hey and thanks for using Boss!

> Is it possible to make it so cave spider & spider bosses attack players during the day as well?
Yes absolutely, just install Citizens and enable Custom pathfinders, set it to aggressive and set the target to player.

> Your other question
Correct, BossEggEvent is triggered on Egg use. This was an asked feature to trigger it in these cases.

You can disable the warning if you cancel BossEggEvent. Do you wish to remove the warning from BossSpawnEvent too?

**Comment by SladeHazard** [comment]
> Hey and thanks for using Boss!
> 
> > Is it possible to make it so cave spider & spider bosses attack players during the day as well?
> > Yes absolutely, just install Citizens and enable Custom pathfinders, set it to aggressive and set the target to player.
> 
> > Your other question
> > Correct, BossEggEvent is triggered on Egg use. This was an asked feature to trigger it in these cases.
> 
> You can disable the warning if you cancel BossEggEvent. Do you wish to remove the warning from BossSpawnEvent too?

I'm using BossSpawnEvent, how can I disable the warning here?

**Comment by SladeHazard** [comment]
> Hey and thanks for using Boss!
> 
> > Is it possible to make it so cave spider & spider bosses attack players during the day as well?
> > Yes absolutely, just install Citizens and enable Custom pathfinders, set it to aggressive and set the target to player.
> 
This did not work btw.

```
Citizens:
  Enabled: true
  Goal_Target_Enabled: true
  Goal_Target_Aggressive: true
  Goal_Target_Radius: 15
  Goal_Target_Entities: []
  Goal_Wander_Enabled: false
  Goal_Wander_Radius: 18
```
I also tried restarting the server,

![image](https://github.com/kangarko/Boss/assets/45261094/d60a4ba8-fcf9-444f-a36a-c0d653a47c97)
![image](https://github.com/kangarko/Boss/assets/45261094/fcbb050c-a1fc-4557-9319-f597b8e1264a)
![image](https://github.com/kangarko/Boss/assets/45261094/056405a5-0915-492e-b813-44537ea47cde)
![image](https://github.com/kangarko/Boss/assets/45261094/e8b07de1-9ded-48a8-a7a8-de1e2f2b5acb)

and clicking the "target list egg" seems to do nothing, no console errors or anything

**Comment by SladeHazard** [comment]
another question, is this wiki outdated or are there just no placeholders for getting top damagers, boss's killer name and player who spawned the boss's name?

The wiki shows {killer here}
![image](https://github.com/kangarko/Boss/assets/45261094/1cbb7158-6a0a-4d19-af22-e7dabe326f58)

but it's not shown on the actual placeholder wiki list:
![image](https://github.com/kangarko/Boss/assets/45261094/18c2ee30-2ab8-4cf2-9700-f927008eb7d0)

https://github.com/kangarko/Boss/wiki/Variables

**Comment by kangarko** [comment]
> > Hey and thanks for using Boss!
> > > Is it possible to make it so cave spider & spider bosses attack players during the day as well?
> > > Yes absolutely, just install Citizens and enable Custom pathfinders, set it to aggressive and set the target to player.
> > 
> > 
> > > Your other question
> > > Correct, BossEggEvent is triggered on Egg use. This was an asked feature to trigger it in these cases.
> > 
> > 
> > You can disable the warning if you cancel BossEggEvent. Do you wish to remove the warning from BossSpawnEvent too?
> 
> I'm using BossSpawnEvent, how can I disable the warning here? I can't seem to find anything related to it in settings.yml

No problem, I will add a new boolean to Egg.Spawn.Send_Fail_Message in your messages_x.yml file, set it to false to hide this warning.



> another question, is this wiki outdated or are there just no placeholders for getting top damagers, boss's killer name and player who spawned the boss's name?
> 
> The wiki shows {killer here} ![image](https://user-images.githubusercontent.com/45261094/275354274-1cbb7158-6a0a-4d19-af22-e7dabe326f58.png)
> 
> but it's not shown on the actual placeholder wiki list: ![image](https://user-images.githubusercontent.com/45261094/275354278-18c2ee30-2ab8-4cf2-9700-f927008eb7d0.png)
> 
> https://github.com/kangarko/Boss/wiki/Variables

We support more variables if you have PlaceholderAPI installed. You can use these extra variables from your second image on any place where PlaceholderAPI supports them.

**Comment by kangarko** [comment]
Let me know if you have more questions below!

**Comment by SladeHazard** [comment]
> Let me know if you have more questions below!

The default localization files don't have the option added and when I tried to add it manually, it did nothing. I'm not sure if I did it correctly:

![image](https://github.com/kangarko/Boss/assets/45261094/8091b804-a51d-44cf-b297-db89cd1e7cd1)
