### ISSUE TITLE
1.20.2: Slime Freeze skill doesn't work

### ISSUE THREAD

**Issue by Navalke** [kangarko/Boss#1217]
Hi,

When I add the freeze skill to my Slime Boss, it doesn't work. Also, there is no error on cmd. Here is the video: https://medal.tv/games/minecraft/clips/1zIrPXNRqB8fFf/XcZ98lRmQMmi?invite=cr-MSx4eTEsMTkwNDYxNjgwLA

Minecraft version: 1.20.2
Boss plugin version: 4.9.6

**Comment by kangarko** [comment]
Thanks, can you post me /boss debug and let me know which Boss name is it?

**Comment by Navalke** [comment]
Okey I will send it tomorrow.

**Comment by Navalke** [comment]
Sorry for the delay I have some hosting issues so I can't send it for now. I will send it in few days :(

**Comment by Navalke** [comment]
[debug.zip](https://github.com/kangarko/Boss/files/13181757/debug.zip)
Slime boss name is SlimeExample

**Comment by kangarko** [comment]
Thanks, will be fixed.
