### ISSUE TITLE
1.20.2:BossSpawn

### ISSUE THREAD

**Issue by Navalke** [kangarko/Boss#1218]
Hi!

I created a boss (Name is; ow_mummy) and set it to spawn only in a desert at night but even when I set the chance to 100, it didn't spawn. I will attach the debug file (In spawn rules, file name is "MumyaSpawn").

Thx 
[debug (1).zip](https://github.com/kangarko/Boss/files/13312445/debug.1.zip)

**Comment by kangarko** [comment]
Hi!

I recommend you [follow this guide](https://github.com/kangarko/Boss/wiki/Common-Issues#bosses-are-not-spawning) and then post me the console log when you try the final bullet point there.

**Comment by Navalke** [comment]
Thanks! I solved the problem
