### ISSUE TITLE
1.20.2: Can't Delete Boss

### ISSUE THREAD

**Issue by Navalke** [kangarko/Boss#1219]
Hi

I was designing my bosses and  spawned all of them next to next like in the picture 
![boss](https://github.com/kangarko/Boss/assets/109472441/4abe233c-f54e-4b1e-9309-b73f18c5b34d)
After a few days (During these days I restarted my server and also sometimes updated the boss plugin) When I joined my server and I right clicked to these bosses but I didn't receive any information message on the chat (message=Found .... Boss. Click here to copy its UUID.). Also, they don't attack so they stand like newly created citizens npc. Normally I fix this issue by killing the bosses and respawning them again but when I kill these ones they respawn back after the server restarts. I hope it was clear If you don't understand it I can record a video.

Thanks

**Comment by Navalke** [comment]
I also noticed that when I summon a boss and go away from it like 10 - 15 chunks , that kill button doesn't work.
![kb](https://github.com/kangarko/Boss/assets/109472441/62748833-615e-4349-a7eb-0ce04e42bf32)
 doesn't kill bosses

**Comment by kangarko** [comment]
Unfortunately with Citizens it's a different story, you would have to use their command [/npc remove](https://wiki.citizensnpcs.co/Commands) to get rid of it.
