### ISSUE TITLE
Sorry I was inactive, Can you add custom commands to the boss mob?

### ISSUE THREAD

**Issue by FriedCream** [kangarko/Boss#122]
Can you add custom commands to the boss mob?

**Comment by FriedCream** [comment]
Can you give me your discord? It would be a lot easier saying I'm traveling a lot.

**Comment by kangarko** [comment]
Hello, currently, support is given here.

See this link for all the commands for Bosses: https://github.com/kangarko/Boss/wiki/Common-Issues#how-can-i-send-custom-messages-or-commands-when-a-boss-diesspawns
