### ISSUE TITLE
Skills boss

### ISSUE THREAD

**Issue by Elkin04** [kangarko/Boss#1222]
Is there a place where people can upload or where they can see the skills that are personalized for bosses? Since there are very few and I don't know much about programming.

**Comment by kangarko** [comment]
No not right now, you don't need to know a lot of coding to get a new skill in. See my youtube tutorial video 1 and 2. at youtube.com/kangarko, then watch the libraries video and you should be able to import this: https://github.com/kangarko/Boss/wiki/Developer-API#creating-a-new-skill
