### ISSUE TITLE
timezone changing randomly

### ISSUE THREAD

**Issue by sennby** [kangarko/Boss#1223]
im on 1.20.2 latest paper.
boss up to date as well

It's happened over few months but now im sure of it since it just happened again.
My bosses have been spawning 7 pm est every day. I use hour 21 and any minute to spawn them.
All of a sudden, my wednesday boss isnt spawning when it should today. I set it to -1 for any time, and its on a whole different day i find out. So i go to my thursday boss and set it to spawn on any hour and it spawns.

So it changed my timezone up completely for some reason some how and my day as well. So now i have to guess which hour it put itself on, and then reset up all my spawn tables once again

**Comment by kangarko** [comment]
Please ask your host about it, we get the timezone from the server so it's out of our control.

I can add a hardcoded option that will let you specify the timezone in the settings.yml if that wont work, just let me know below.

**Comment by sennby** [comment]
Please add that that would be HUGE for me.

**Comment by kangarko** [comment]
Added. You know what would be huge to me? A trustpilot review :)
