### ISSUE TITLE
Support for multiple lines of text (Boss Alias.)

### ISSUE THREAD

**Issue by SrZenon** [kangarko/Boss#1224]
Hello, I'm sending this suggestion because I was searching the Boss wiki and couldn't find anything related to what I mentioned.

The operation is simple, by adding \n in the boss's alias you generate a new line, resulting in the mob having several alias lines.

**Example:** Alias: 'Skeletal Fighter \n Lv.2'
![image](https://github.com/kangarko/Boss/assets/153800614/2d02e21c-7c96-4723-a525-b0469797b282)

**_That's all, happy holidays!_**

**Comment by kangarko** [comment]
I am sorry, I tried a few ways but Minecraft was not nativelly designed for this and it's technically complex to make work on all MC versions. I am closing this down due to lack of time but I might return to it later.
