### ISSUE TITLE
1.20.2: Can't see Boss skins

### ISSUE THREAD

**Issue by Navalke** [kangarko/Boss#1227]
Hi! 

My server is 1.20.2 and I'm using BossTM 4.9.9 ( I can't use the latest BossTM plugin it gives error). I dont know since when but I can't see my player npc bosses skins now. 
![image](https://github.com/kangarko/Boss/assets/109472441/bb674a9a-e84d-4b18-9b6b-a31b2a2d2453)

**Comment by kangarko** [comment]
Please use latest citizens from https://ci.citizensnpcs.co/job/citizens2/.
If there is an error, please post me the error log below.

**Comment by Navalke** [comment]
I can't use the latest build it doesn't support 1.20.2
![image](https://github.com/kangarko/Boss/assets/109472441/af18edca-8c7f-4c2b-924e-0e72e6c28a6b)

**Comment by kangarko** [comment]
Then unfortunately it wont work because Citizens updated and I dont have the feasibility to support its multiple versions.
