### ISSUE TITLE
Minecraft Version: 1.20.2, I bought your old boss plugin, Any chance I could get the 1.20 version? Or Do I have to buy seperate? 

### ISSUE THREAD

**Issue by FireKiller258** [kangarko/Boss#1228]
I bought your old boss plugin on spigot, Any chance I could get the 1.20 version? Or Do I have to buy separately? I just thought they were the same and realised that the one on build by bit was updated to 1.20.2. I did buy it like 2 years ago before paypal banned you but I was just wondering if I could get the updated jar or verify me as a holder? & Do you have discord? 

![image](https://github.com/kangarko/Boss/assets/143948229/268bfdf6-5fc2-4dc0-b1eb-78d2dd3289b0)

**Comment by kangarko** [comment]
Hello,

I understand, however we offered free migration until Dec 31, 2023 and since it was a slow and manual process we have since shut. You can buy it for $9 [here](https://mineacademy.org/boss)
