### ISSUE TITLE
Minecraft Version: 1.20.4

### ISSUE THREAD

**Issue by JerichoTorrent** [kangarko/Boss#1229]
Hi Kangarko and team,

I wanted to inquire about the possibility of using custom model data in a resource pack I am creating, then apply that custom model data to bosses. I am creating a server that is an MMORPG with lore about an alien invasion, so I want to create bosses that are similar to the entities from Half Life or other games with alien mobs. 

I watched Kangarko’s videos on creating resource packs, and I’m wondering how the custom model data can be applied to a boss, if possible. Any tips would be greatly appreciated.

**Comment by kangarko** [comment]
Hello,

Right now Boss does not support custom model data. But you can place custom model items onto the Boss equipment. 

You can connect Boss with Citizens and use custom skins on entities there, or if Citizens support custom model data then you can connect that and Boss will support it.
