### ISSUE TITLE
Skills rework?

### ISSUE THREAD

**Issue by SoraShiunin** [kangarko/Boss#123]
Hello, I was wondering if skills are ever gonna be reworked so we can use the same skill but differently for each boss and edit basic values ingame, like potion type/strenght/duration , maybe multiple potion effects with "add potion effect when
attacking" ?

 My suggestion is also having default skills and when it is changed, the changes are saved within the appropriate bosses yml.

**Comment by kangarko** [comment]
Yes, we plan to rework skills to be uniquely customizable for each Boss, see roadmap.
