### ISSUE TITLE
Trouble setting boss region & fire resistanception not working

### ISSUE THREAD

**Issue by Veyjinn** [kangarko/Boss#1230]
Hello there! I've bought this resource recently and got 2 issues when setting up a boss.

**Minecraft version 1.20.1**

**Issue 1:**
I've been trying to use the spawn rule of players entering a region, but when I enter a region, nothing happens. I've set the region points ,added it to the boss spawn rules and also set the spawn location of the boss inside the region. Will appreciate any guidance in that matter.

**Issue 2:**
The fire resistance potion effect on bosses doesn't work. I made a player boss with the fire res 1 effect and it still takes damage from fire. Any ideas how to fix it?

**Comment by kangarko** [comment]
Hey!

Thanks for enrolling in Boss.

For the issue one, can you try setting the Debug key to [spawning] in settings.yml? It will tell you in the console more information about what is going on when you enter the region.

For the second issue, can you please send me /boss debug file and let me know which Boss has the potion? There is a 0.1% chance that this might be a bug in 1.20.1, I will be testing this on the latest subversion of 1.20 and I recommend you update too.

**Comment by kangarko** [comment]
Sorry for the delay, investigating in 24h

**Comment by kangarko** [comment]
Issue 2:

Unfortunately, after extensive testing, I was able to reproduce but not to fix it. Bukkit does report that our effect was added. The issue must lay somewhere in Citizens then afaik.

![a](https://i.imgur.com/MtlXnWm.png)

**Comment by Veyjinn** [comment]
I see. I've done some testing myself and found a workaround. Applying the Splash Potion of Fire Resistance does the job. But will do some more testing and eventually contact citizens devs about this issue

**Comment by kangarko** [comment]
Thanks for sharing!
