### ISSUE TITLE
3 Ideas [DespawnTimer, AggroWhenHit, FollowPlayer]

### ISSUE THREAD

**Issue by Veyjinn** [kangarko/Boss#1231]
Hello! I've got three suggestions for You, hope You might take them into consideration to achieve an even more sophisticated boss plugin. Note: the suggested ideas aren't urgent at all and maybe they might just give you a new flow of ideas.

**1) How it would benefit others? (Not just you, but 1,000s of others people using the same plugin.)**

A more diversified range of newly implemented customization possibilities offers a more attractive resource overall. Also makes the plugin stand more out in the face of competition. 

**2) What would happen if we won't implement this feature? How's your server being affected?**

The plugin will remain in its current status quo and will not evolve in therms of functionality, which can be totally fine! But there's no need for setting borders, when there are countless possibilities waiting to become real!

**3) If suggesting something new - Can the old system be modified/improved instead?**

I'm not sure about that one. I'm pretty new to this resource so there isn't much I can say

Idea 1: **Despawn Timer** - How about a function in which the boss despawns after a specified amount of time. So that the player has to defeat the boss before the timer ends. It gives a thrill of urgency and can be a nice addition to the challenge of beating the boss.

Idea 2: **Aggro when hit** - (behavior similar to iron golems) - Adding a behavior function, in which when the player hits the entity, it will attack back. The boss will remain passive if the player chooses not to interact. 

Idea 3: **Follow player** - (just like dogs) - pretty simple - boss follows other players (good for neutral bosses which can assist you in the fight with other mobs) Combined with the Despawn Timer you can create a temporary companion which will clear your spider infested cave

Thanks for hearing me out, cheers!

**Comment by kangarko** [comment]
Thank you! I love your ideas, however I am quite busy with other projects at the moment. We do have an extensive developer API and I recommend you or someone else develops these three new modes of behavior as a custom skill. There is a startup information set on the Wiki on how to get going.
