### ISSUE TITLE
1.8.8: Knockback Resistence not working correctly

### ISSUE THREAD

**Issue by IceGames23** [kangarko/Boss#1234]
Video demonstration: https://youtu.be/9_v9vyJhLn4

I want my boss to get 0 knockback of all types, but when I use the knockback or punch enchantment, it "bypasses" my boss's 1000 knockback resistance.

I'm using 1.8.8 and 4.10.3 boss version.

**Comment by kangarko** [comment]
There are some 1.8.8 forks with enchanted knockback settings, you can try them instead.
