### ISSUE TITLE
1.20.4: Confussion/bug with ItemAdder

### ISSUE THREAD

**Issue by Spygain** [kangarko/Boss#1235]
Hello, 

I have a display problem on my game, I use ItemsAdder, with this plugin I have the possibility to add a bar on the game except that when the entities are hit/targeted the bar disappears to show the combat info of the entity hit and once the life bar of the mob disappeared, the bar added by ItemsAdder returns.

Capture before hitting an entity :
![javaw_MD6lUCDx6L](https://github.com/kangarko/Boss/assets/50708110/304b607d-4f07-4706-bbbc-a0bdf64ecd6e)

Capture made after striking an entity :
![dyWnG54y2R](https://github.com/kangarko/Boss/assets/50708110/fd756b07-888e-477c-ab0f-c7cfd5e78546)

I don't see what could cause this disappearance, so I'm attaching some screenshots to this ticket, if you need logs or anything else, I can supply them.

**Comment by kangarko** [comment]
Probably an NBT incompatibility, I am unfortunately not having enough time to look into this so this edge feature will remain incompatible for the time being.
