### ISSUE TITLE
Minecraft Version: Boss's nameplate isn't shown as expected.

### ISSUE THREAD

**Issue by ThisisZeth** [kangarko/Boss#1236]
1) Put your Minecraft version in the title.
Server version: 1.20.4
My client version: 1.20.1

2) The problem I'm facing is:
The boss's name on their head isn't showing properly. I give him a "&e[Lv.240] &fToddy"
But it only shown as "[Lv.240] Tod" with colors applied

This issue happened on any other bosses too.
I think it's like a name limitation or something. As I'm looking at it, it seems to be limited for 16 characters for each boss' name (including the color codes)

I'm not sure if I can change these or not in the config files, I'm really need help with this. Thank you

**Comment by kangarko** [comment]
I believe you are reaching the maximum length for entity names, which unfortunately can't be changed in Minecraft

**Comment by ThisisZeth** [comment]
I'm not sure if it's using the same system or not. But this seems to be fine when I change the entity name with other plugins and name tag. Is there anyway you could try taking a look at it? Thanks

![image](https://github.com/kangarko/Boss/assets/68198919/176ad6cf-2566-45d1-ac37-68156694e946)

**Comment by kangarko** [comment]
What's the name of the plugin?

**Comment by ThisisZeth** [comment]
Sorry that I forgot to mention. The plugin is called ItemEdit, it's for changing item's name, lore and such. What I did is changed the mob's egg name into the picture above and spawned it there. I also tried to change it with name tag then applied to the mob, it's working fine as well.

**Comment by kangarko** [comment]
Apologizes very much for delay, I accidentally hit "Mark as read". Going thru this asap

**Comment by kangarko** [comment]
Upon closer review, I decided to put it to our long term roadmap. No ETA yet.
