### ISSUE TITLE
1.20.2 paper: BOSS PLUGIN ISSUE

### ISSUE THREAD

**Issue by josedabela** [kangarko/Boss#1238]
Hello i recently bought Boss Plugin saw some tutorials to see how it works all my plugins in my server are working just fine.
When i create a NPC Boss and go to the attributes tab it only appears damage multiplier but at thevanilla mobs it shows everything only on npc´s doesnt show and also the npc boss spawn whit and absurde movement speed.
Waiting for your response thank you
[debug.zip](https://github.com/kangarko/Boss/files/14750980/debug.zip)

**Comment by kangarko** [comment]
I have added a new option to Boss to customize the speed of your NPC, it will be available in the next version:

![a](https://i.imgur.com/jXvHUUJ.png).

Also, please note that NPCs do not have all attributes available due to missing APIs in Bukkit for player type entities.
