### ISSUE TITLE
Paper 1.20.4: How to remove a boss level

### ISSUE THREAD

**Issue by SAVANAONE** [kangarko/Boss#1241]
Hello! Have a nice day!

I'm using LeveledMobs on the server and from what I understand it adds a level to bosses. And this would not hurt, but due to leveledMobs the HP of the bosses I set changes, since the boss constantly spawns with a different level. At the same time, one boss (zombie villager) created through your plugin has no level and always spawns with the same amount of HP. That is, LeveledMobs does not affect some mobs, or I somehow set it up and don’t understand how to repeat it.

The most important question is how to remove levels from Bosses using LeveledMobs and your plugin?
![Uploading Screenshot 2024-04-16 at 11.00.33 AM.png…]()

**Comment by kangarko** [comment]
You need to consult that leveledmobs plugin to add an exception for Boss plugin. Its simple they just need to check if our Boss has persistent metadata or a scorebaord tag Boss_V4 without having to import our plugin at all since both methods are in Bukkit.
