### ISSUE TITLE
Minecraft Version: 1.20.2 paper

### ISSUE THREAD

**Issue by josedabela** [kangarko/Boss#1242]
My spawn rule is set for a specific time like 15 minutes and the boss world limit is 1 but for an example the rule is set for 15 minutes right? but if the bosses spawn and no one kill him and passes like 30 minutes that is 15"minutes"+15 "minutes" when a player kill that boss it respawn again whitout waiting the 15 minutes again i wanted to know how to fix this. i wanted that the countdown only started when the boss died not when he spawns please look at this kangarko.

**Comment by kangarko** [comment]
As you said, if the spawn rule fires every 15 minutes and you kill the boss in the middle of the timer, the new boss will spawn the next time the timer is out.

So you can just decrease the timer threshold to 30 seconds for example.

**Comment by josedabela** [comment]
If the respawn time is set to 15 minutes if passes 30 minutes when the boss
get killed it spawn another right away

A quarta, 24/04/2024, 8:23 AM, Matej ***@***.***> escreveu:

**Comment by kangarko** [comment]
Oh I am sorry I misunderstood. The logic in Boss is hardcoded this way. We at present have no plans to change this but I can put it to the roadmap for a bigger future release to allow spawning timer to wait until the next spawn.
