### ISSUE TITLE
Timed Bosses and giving all players that hit the boss rewards

### ISSUE THREAD

**Issue by PengBread** [kangarko/Boss#125]
How do i configure a Timed boss in a boss region like every 3 hours a boss spawn in that region? I only found "Native Conditions > Time" which isn't the timed feature I want.  From what i saw "Timed Spawning" in the plugin description page.

Other than that, is it possible to give all the players rewards for hitting that certain boss instead of vanilla drop and players loot?

**Comment by kangarko** [comment]
This is not possible and was discussed many times before. Timed Spawning is awaiting a major update for Boss.

Yes, also the loot system will be improved - see the roadmap.
