### ISSUE TITLE
1.20.4: PlaceholderAPI Throwing exception

### ISSUE THREAD

**Issue by HorusApl** [kangarko/Boss#1250]
Using TAB to make the bosses health appear in a bossbar as I saw no built-in way to do it. https://mclo.gs/Ny9Unee

Both relevant bosses included in the zip folder, haven't changed anything elsewhere in settings. Using latest version of both PlaceholderAPI and Boss

![image](https://github.com/kangarko/Boss/assets/64336395/0a79ad16-6247-4421-8a45-442ee50085df)
[Minion.zip](https://github.com/kangarko/Boss/files/15449228/Minion.zip)

**Comment by kangarko** [comment]
Unfortunately the placeholder needs to get the entities in chunk, which needs to be dealt with on the main thread. Due to how placeholderAPI is coded we don't control whether the call is sync or not. Tab seems to call this async. Ask them to add a toggle for sync processing.
