### ISSUE TITLE
1.20.4: Remaining Time placeholder

### ISSUE THREAD

**Issue by Kuveru** [kangarko/Boss#1251]
Hello I have a question before buy the Boss plugin is it a timer who shows when a Boss will spawn?
Imagine if I put the boss Every 2 Days... it have  a placeholder to say It will spawn "X" day "X" hour....

**Comment by kangarko** [comment]
No but we are working on a new timed spawning feature and I can incorporate a placeholder into it.

**Comment by Kuveru** [comment]
Yes but when? Its a estimated day?

**Comment by kangarko** [comment]
No ETA

**Comment by kangarko** [comment]
1-4 days
