### ISSUE TITLE
1.8.8: Default mob items issue

### ISSUE THREAD

**Issue by IceGames23** [kangarko/Boss#1254]
I tought this was fixed, but back when I spawn a large amount of bosses at the same time. 

![image](https://github.com/kangarko/Boss/assets/71414690/0a093f75-96be-4ec5-8ca4-07942e32cf23)

A large number of mobs spawns with they "default" items when I spawn a large amount of bosses. It's not always, but sometimes a this happens, and when happens, happens with a lot of mobs.

**Comment by kangarko** [comment]
1.8.8 is failing me. Bukkit tells that the equipment is AIR even though it is a spade: https://i.imgur.com/pVZrHyy.png

So what I had to do is wait for 2 ticks and take off the equipment/hand item later: https://i.imgur.com/kNUy6z5.png

I will try decreasing this delay a bit, but if it does not help then unfortunately its a hard server bug.
