### ISSUE TITLE
1.20.4 : boss region not creating properly

### ISSUE THREAD

**Issue by alm7airbi** [kangarko/Boss#1255]
hey hows it going, 

so i really like this plugin, easy to use and very friendly, but i have one issue with it, which is when im creating 2 different regions in the dungeon, left and right, it seems that one of the merges into the other

my concept is splitting 2 different regions, left and right, if player goes to either side, the mobs (bosses) will spawn in that side, and if the move to the reciprocal, the will trigger a spawn on that side too.

when i created the 2 regions and tried to spawn the right side, they dont spawn, and when i examined the regions it seems like i created only one region, or the region got combined into one

when selecting the different regions that are created from the /boss menu, it shows i have 2 different regions, but if i select one of them they both show in the same place.

video of the problem:
https://youtu.be/gI8B_P8-dC4

**Comment by kangarko** [comment]
Try making the two regions further away from each other, and make sure they do not overlap.

**Comment by kangarko** [comment]
Thanks - gonna have a look on Sunday or Monday, I am leaving the country today.

**Comment by kangarko** [comment]
Sorry I am not catching up, will be looking into this tomorrow asap.

**Comment by kangarko** [comment]
Solved by cloning the diskregion each time on creation. Fixed in the next version, I apology for delays.
