### ISSUE TITLE
1.20.6: Menu Command Error

### ISSUE THREAD

**Issue by Jmichaelz** [kangarko/Boss#1256]
1. Followed the steps and here is the debug file https://ufile.io/1vkd48yk

2. When running the "/boss:b menu <name>" command, I get a lot of errors which can be shown here https://pastebin.com/UpTrYMTR

Of course, I made sure that I am running Paper and tried to debug the error myself, but there does not seem much to be going off here (unless it isn't compatible with Geyser or something.)

**Comment by kangarko** [comment]
I apology, will fix asap tonight.
