### ISSUE TITLE
LAG 1.16.5

### ISSUE THREAD

**Issue by enderylmz** [kangarko/Boss#1257]
Boss plugin creates lag on my server and I cannot solve it in any way, please help me, I am using the latest version of the plugin.

https://timings.aikar.co/dev/?id=b4aa89c4f47c4693a87b18e52fe1382f

**Comment by kangarko** [comment]
Unfortunately Paper's /timings report is inconclusive because I cannot expand the section with the most lag. In some cases it even reports false data. Please install spark and provide us a link to a full spark report. Thank you!

**Comment by enderylmz** [comment]
https://spark.lucko.me/fscwGWXyDM

**Comment by enderylmz** [comment]
I've never seen a developer give bad support from you before, you haven't even responded for a few days and you closed it saying the problem was solved.

**Comment by kangarko** [comment]
We close tickets not because they are done but merely for organizational purposes. Yes this is a hobby project and while I try to respond as quickly as possible sometimes it might take a few days.

**Comment by kangarko** [comment]
![Screenshot 2024-07-24 at 11 57 13](https://github.com/user-attachments/assets/5f91869b-11a2-48a7-aaa2-fa76b7c3ff61)
I had a look at the report. The lag comes down to two sources, first one is persistent metadata api, the second is getting live entities. Both reside in Bukkit and I already try to resolve the issue with paper years ago to no avail (apart from "make your own implementation garbage advice): https://github.com/PaperMC/Paper/issues/2125

For the metadata api, I have added a cache so we avoid creating a new namespaced tag each time. You should see a performance increase in the next version.
