### ISSUE TITLE
I have a question about this variable: %boss_{bossName}respawn{spawnRule}% 

### ISSUE THREAD

**Issue by Kuveru** [kangarko/Boss#1258]
I have a question about this variable: %boss_{bossName}respawn{spawnRule}% 

What it means {spawnRule} in the variable, like where I can find it?

**Comment by kangarko** [comment]
The spawn rule name is the name of the spawn rule you create in the /boss menu > spawning > create new, the name you type in the chat. Avoid spaces to make it work in this variable.
