### ISSUE TITLE
1 Boss preventing plugin from loading?

### ISSUE THREAD

**Issue by SoraShiunin** [kangarko/Boss#126]
Because I have a custom terrain generator, it seems to cause issues for Boss spawn system, it completly prevented boss from being loaded correctly on the server.
Any boss command din't work.

Error log in boss folder:
https://hastebin.com/ilasilelor.php

The boss worked fine for a couple of hours...
I had to remove it to fix it.

**Comment by kangarko** [comment]
Thanks, should be fixed!
