### ISSUE TITLE
1.21 - cannot change Custom Settings in Boss menu

### ISSUE THREAD

**Issue by StormShaddy** [kangarko/Boss#1260]
When we try to change parameters in "Custom Settings" for any Boss (glowing, AI, persistant, etc), nothing happens. If you click on the icon of, lets say, "Silent", the text above will tell the opposite of what that setting is right now, like it actually toggled the setting (If "Silent" is glowing - then it says Silent Off, and opposite), but the setting itself does not change at all, nor in menu, nor on bosses.

Also, sometimes, when it actually lets you change something, at one moment, settings just break.

**Comment by kangarko** [comment]
Just for clarity sake are you on Paper? Are there any error in the console?

**Comment by StormShaddy** [comment]
Server is running on Purpur. no errors in a console

**Comment by StormShaddy** [comment]
Also, here is the list of plugins on a server:

[09:31:51 INFO]: Bukkit Plugins: (52):
[09:31:51 INFO]:  - AntiPopup, AuctionHouse, AuthMe, AxiomPaper, Boss, BreweryX, ChatBubbles, Chunky, Citizens, CMI
[09:31:51 INFO]:  CMIEInjector, CMILib, CoreProtect, DailyRewardsPlus, DecentHolograms, DiscordSRV, EasyPayments, EnchantsSquared, EvenMoreFish, ExcellentJobs
[09:31:51 INFO]:  GSit, Guilds, HeadDatabase, ImageFrame, InventoryRollbackPlus, ItemEditor, Lootin, LuckPerms, Multiverse-Core, nightcore
[09:31:51 INFO]:  PlaceholderAPI, PlasmoVoice, ProtocolLib, pv-addon-discs, pv-addon-lavaplayer-lib, PvPManager, squaremap, squaremarker, TAB, UltimateAutoRestart
[09:31:51 INFO]:  ValhallaMMO, ValhallaRaces, ValhallaTrinkets, Vault, ViaBackwards, ViaVersion, Votifier, VotingPlugin, WorldEdit, WorldEditSelectionVisualizer
[09:31:51 INFO]:  WorldGuard, WorldGuardExtraFlags

**Comment by StormShaddy** [comment]
[latest.log](https://github.com/user-attachments/files/16468378/latest.log)
Im also attaching a log, in which we tried to change custom setting on a freshly created Boss.

**Comment by kangarko** [comment]
Due to time limits we're unable to debug on forks. Please try on Paper first to see if the problem goes away, also try with just Boss plugin to isolate the problem.

**Comment by StormShaddy** [comment]
We've tried running same plugins and configs on Paper, same stuff happens. It seems like one of the plugins is conflicting with Boss, but we have no idea which one cloud it be.

**Comment by StormShaddy** [comment]
If you have no idea, then im closing this issue and going to shuffle plugins, in hopes of finding one, that causes the problem.

**Comment by StormShaddy** [comment]
Ok, so, if you REINSTALL Boss, then it works fine, both on Paper and Purpur.

**Comment by StormShaddy** [comment]
I've found a source of the problem.
Turns out, if you have a bunch spawnrules, that will randomly spawn mobs anywhere in the world around players (think custom mobs, like a zombie variant), and those spawnrules will run the default rule check, which is every 1 seconds, it will actually make Boss plugin so incredibly busy, that it will refuse to change custom setting for any Boss.

**Comment by kangarko** [comment]
Oh thank you so much for the discovery. I am going to investigate asap. We're rewriting some other unrelated stuff so there's NO eta but I will have a look.

**Comment by StormShaddy** [comment]
No problem) Closing the ticket then.

**Comment by kangarko** [comment]
I'm gonna leave it open since I need to fix it :) Thanks!

**Comment by kangarko** [comment]
Apologizes for the big delay. I'm still working through Foundation 7 update as well as Boss 5. ETA is 1-3 weeks depending on unexpected circumstances. Will be addressed by then. I will push an emergency release of Boss 4 tonight.

**Comment by kangarko** [comment]
Will be addressed at https://github.com/kangarko/Boss/issues/1265
