### ISSUE TITLE
Line feed does not work in the broadcast command

### ISSUE THREAD

**Issue by tokarvitaliy** [kangarko/Boss#1261]
Minecraft purpur version 1.16.5
Plugin version 4.13.6

I'm trying to create a boss spawn notification by executing a command at the moment of the boss spawn via broadcast.

The documentation says to use the | character to move to another line, but it doesn't work.
Command:
broadcast line1 | line2 | line3
gives me the following result

![image](https://github.com/user-attachments/assets/376f6b20-f8f8-4b1b-8efb-33525b45e6e9)

**Comment by kangarko** [comment]
We had to redact it for technical reasons. It should come back in the next few versions, no ETA, sorry and thanks for understanding.
