### ISSUE TITLE
1.21 - After rejoining the server while fighting Boss with Stun ability, player's movement speed attribute is set to 0

### ISSUE THREAD

**Issue by StormShaddy** [kangarko/Boss#1263]
After rejoining the server while fighting Boss with Stun ability, player's movement speed attribute is set to 0.
Strangely, if that player's attribute is manually set to something, other than 0, on joining the server it yet again changes to 0.
File with that Boss in the attachments.
[Bosses.zip](https://github.com/user-attachments/files/16609666/Bosses.zip)

**Comment by Codixer** [comment]
Something might have gone wrong with that zip file
![image](https://github.com/user-attachments/assets/0315bd27-6229-4018-af66-54daa42586f6)

**Comment by StormShaddy** [comment]
Try opening it with WINRAR, if you have it

**Comment by kangarko** [comment]
Sorry for the big delay, what is the Stun ability? There is no such skill name.

**Comment by kangarko** [comment]
Apologizes for the big delay. I'm still working through Foundation 7 update as well as Boss 5. ETA is 1-3 weeks depending on unexpected circumstances. 

Assuming you meant the Freeze Skill, it will be addressed in Boss 5. 

I will push an emergency release of Boss 4 tonight.
