### ISSUE TITLE
1.8.9. Buttons in custom settings don't update (sometimes)

### ISSUE THREAD

**Issue by Henriiig** [kangarko/Boss#1265]
As the title says and here is a picture

![image](https://github.com/user-attachments/assets/edb91c81-a5bf-4099-bc96-1cb3a2dc1250)

**Comment by Henriiig** [comment]
For me this menu is really buggy and doesn't really update/change the settings and sometimes it doesn't save my settings

**Comment by kangarko** [comment]
It all depends on your implementation, with the right use of the API it should not happen. If you're a student of MIneAcademy I recommend you join our Q&A calls and I can debug right on the call, if not you can ask our community at mineacademy.org/discord.

**Comment by Henriiig** [comment]
My implementation? Im just simply using the Boss.jar plugin and no other thing? @kangarko

**Comment by kangarko** [comment]
Oooh I am so sorry, I misread the url I thought this ticket was related to Foundation. My bad. Going to be testing tonight.

**Comment by Henriiig** [comment]
No problem otherwise the plugin is really great! I think this issue is the same as this https://github.com/kangarko/Boss/issues/1260

**Comment by Henriiig** [comment]
Maybe it has something to do with the live updating of the mobs which also does not work in 1.8.9 :/

**Comment by kangarko** [comment]
Looks def like the same issue, anyways we're totally rewriting the stuff that powers Boss so I can't even launch the plugin today, will be making sure this is fixed in the next update, thanks! (ETA 5-10 days)
