### ISSUE TITLE
1.8.9: Region Keeping doesn't work with worldguard

### ISSUE THREAD

**Issue by Henriiig** [kangarko/Boss#1267]
I don't know if this is actually intended but right now I have to set up a worldguard region for spawning and also a boss region for keeping since it doesn't track if the boss leaves the worldguard region and then despawn it.

**Comment by kangarko** [comment]
Due to performance reasons this feature is currently limited to Boss native region system

**Comment by kangarko** [comment]
WorldGuard APIs provided methods which were inefficient for this kind of lookup
