### ISSUE TITLE
1.8.9 Mobs don't drop loot (sometimes)

### ISSUE THREAD

**Issue by Henriiig** [kangarko/Boss#1268]
I sometimes experience that mobs don't drop loot at all and I have to restart the server to make this work again. It feels like sometimes that not with loot but just as if different bosses of same mob type is conflicting somehow. Maybe this also has something to do with https://github.com/kangarko/Boss/issues/1260 but thought you guys just wanted to know anyways.

Other than that really great plugin!

**Comment by kangarko** [comment]
I dont think that it is related. 

In the next update, please set the Debug key in settings.yml to [drops] and observe the console for whats happening.
