### ISSUE TITLE
Boss lives forever ...

### ISSUE THREAD

**Issue by Victor75007** [kangarko/Boss#127]
Hello

I have one big problem.
I remove this plugin, the Boss folder from Plugins folder ( I deleted Boss folder and the .jar file also )
I Restarted server.
And again restarted..
Because my created bosses stay alive, and spawn in the world, random, as i edited it.
I put again the .jar file on the plugins folder, and create again the bosses, with the same name , and i kill all bosses, and deleted these, and remove Boss folder, and .jar file, and restart the server, and the bosses lives forever my server and terrorizing my players. 
Bosses never die!

How can i remove forever these bosses ?
I tried other Boss plugin.  The plugin had the same command the same. / boss
So one of Plugin could not be used, if both plugin installed on my server.
So removed your boss plugin, how i tried the other boss plugin. 

Have a nice day. :)
Kind Regards,
Victor

**Comment by kangarko** [comment]
If you remove Boss, all spawned Bosses will remain on your world(s). You can use /killall named to remove Bosses from loaded chunks.

If that doesn't help, I recommend installing Boss again, creating Bosses with the exact same names as you had previously and then using the "/boss butcher" command.
