### ISSUE TITLE
Silent Tag to Mobs

### ISSUE THREAD

**Issue by Henriiig** [kangarko/Boss#1270]
Add "Silent" to the custom settings of mobs where giving them the nbt tag {Silent:1} will make them silent

**Comment by Henriiig** [comment]
Maybe you could then also add custom damage/death sounds to play for the boss without us needing to use citizens for this to work. Would be so cool!

**Comment by kangarko** [comment]
There is a silent custom setting already. It requires a new minecraft version due to missing apis however
