### ISSUE TITLE
Slime Max Health

### ISSUE THREAD

**Issue by Henriiig** [kangarko/Boss#1272]
Slimes max health are pretty much defined by their size. I read somewhere that it was possible to manipulate this by giving the slime a custom item with a maxHealth attribute. The problem is that equipment is turned off for slimes in the plugin. Maybe this could be used somehow as a improvement for the plugin (if it actually works of course).

**Comment by kangarko** [comment]
You can adjust the max slime health using their boss' setting in the boss menu and we will call API to override their max health
