### ISSUE TITLE
Animal Customization

### ISSUE THREAD

**Issue by Henriiig** [kangarko/Boss#1273]
Add the posibility to customize nbt tags for mobs such as type of ocelot (= cat in 1.8.9), wolf angry state, horse types and much more for the specific values for some entities.

**Comment by kangarko** [comment]
Easy in theory, harder in praxis plus all the incompatibilites this would cause would produce more problems than good. You can request a specific attribute and I add it as a custom setting if I have time. Also developers can add new custom settings thru our API easily
