### ISSUE TITLE
1.21: Key 'Arrow' is already in the map --> 'class org.mineacademy.boss.skill.SkillArrow'

### ISSUE THREAD

**Issue by knepyt** [kangarko/Boss#1275]
Not sure what is wrong with this plugin, it worked for the longest time and now its not working. I have included the error log text.
[error.txt](https://github.com/user-attachments/files/16720659/error.txt)

**Comment by kangarko** [comment]
Please do not use PluginManager, we can't provide support for plugin reloaders.
