### ISSUE TITLE
1.20.6 : compatibility with mmoitems abilities?

### ISSUE THREAD

**Issue by nizzaz** [kangarko/Boss#1277]
is there a way to get the bosses to use the abilities with mmoitems, they hold the weapon they just have to right click it usually, can i do this or is it impossible

**Comment by kangarko** [comment]
Unfortunately not unless their developer adds that compatibility.

**Comment by nizzaz** [comment]
![image](https://github.com/user-attachments/assets/962283f2-b8f4-4315-9a2a-4d8c94e7ed5e)
the developer dosent seem like there going to, is there a way to get  a mob to right click

**Comment by nizzaz** [comment]
in the same vein, is there a way to get mobs to throw tridents n stuff

**Comment by kangarko** [comment]
Unfortunately his attitude is not our problem. I am happy to collaborate and our API is very simple. If you experience poor support, I recommend you get a refund and switch plugins.

To get mobs to throw tridents, this is done through a vanilla behavior. So they should throw them if you place a trident into their hand slot for the mob type who throws one.
