### ISSUE TITLE
Spawn rule 

### ISSUE THREAD

**Issue by elhadesgamer97** [kangarko/Boss#1281]
I have a question, what is the spawn rule, where is it, what is it, I have tried everything but I still get an error in its variable:
%boss_{bossName}_respawn_{spawnRule}%
worse I don't know where or how to put the spawnrule,
![Captura de pantalla 2024-08-27 125005](https://github.com/user-attachments/assets/58be4351-2e5b-4bc9-a470-2200f5c026e7)

**Comment by kangarko** [comment]
I answered on the other ticket
