### ISSUE TITLE
1.16.5: Boss not attacking with custom weapon correctly

### ISSUE THREAD

**Issue by sa1f22** [kangarko/Boss#1285]
When I give my boss a weapon in their hand, for example a sharp 100 sword, it kills me in one hit with some weaker armour sets, for example, full non enchanted diamond, but when I have a full set of enchanted diamond armour on, it does no damage. It just hits me but applies 0 damage. It seems the mob is not recognising the enchant value when i have enchanted diamond armour.

[Boss.zip](https://github.com/user-attachments/files/16937962/Boss.zip)

**Comment by kangarko** [comment]
Hello! Which Boss is this? I can see you got multiple installed in your debug file.

**Comment by sa1f22** [comment]
Well so far I have tried it with Sentinel and my custom Citizens boss.

**Comment by kangarko** [comment]
Unfortunately looks like an issue with vanilla, we do not deal with this behavior as I explained in the other ticket.
