### ISSUE TITLE
1.18.2 : The boss NPC goes outside the region

### ISSUE THREAD

**Issue by TheD1AMOND** [kangarko/Boss#1287]
Even if a feature is enabled to prevent the Boss NPC from leaving the region, it will still do so

**Comment by TheD1AMOND** [comment]
Non-NPC bosses do not leave regions.

I created regions but still the boss NPC leaves the region even though it is set to not leave

**Comment by kangarko** [comment]
I'm out of office until Sunday, will be testing on Monday hope it's okay

**Comment by kangarko** [comment]
Sorry for the wait. I will fix that, however the fix requires you to re-create your bosses due to a Citizens bug. I apology for the issue.
