### ISSUE TITLE
New placeholders

### ISSUE THREAD

**Issue by Godinhooo** [kangarko/Boss#1289]
**Add placeholders to inform the players who stood out the most in Number of Bosses killed and Damage dealt to Bosses.**

_**Examples:**_

_%boss_top_kills%
%boss_top_kills_1%
%boss_top_kills_2%
%boss_top_kills_3%
%boss_top_kills_4%
%boss_top_kills_5%
%boss_top_kills_6%
%boss_top_kills_7%
%boss_top_kills_8%
%boss_top_kills_9%
%boss_top_kills_10%_

_%boss_top_damages%
%boss_top_damages_1%
%boss_top_damages_2%
%boss_top_damages_3%
%boss_top_damages_4%
%boss_top_damages_5%
%boss_top_damages_6%
%boss_top_damages_7%
%boss_top_damages_8%
%boss_top_damages_9%
%boss_top_damages_10%_

`This suggestion is important to me because I intend to reward the best players on my server as an incentive, and with this addition I will be able to reward the best players in the boss system, making the system more usable by players.
In my opinion, making the system usable by players brings many benefits even to the developer, who will end up selling it to more server owners.`

**Comment by kangarko** [comment]
I will add them to the next version! I already updated the Wiki here: https://github.com/kangarko/Boss/wiki/Variables

Thank you!! If you enjoyed this addition please give us a review <3
