### ISSUE TITLE
Meesage top damages

### ISSUE THREAD

**Issue by lukrr** [kangarko/Boss#1291]
Could you add that when a boss dies a message appears to all the players who dealt damage to that boss, informing them of the damage top? For example:

BossName has been murdered, top damage:
#1 Player1 - 706dmg
#2 Player2 - 524dmg
#3 Player3 - 214dmg
etc

And depending on which position you are in, I will give you one reward or another, thank you.

**Comment by kangarko** [comment]
Yes, in the next Boss release you can just use the new variables we added: https://github.com/kangarko/Boss/wiki/Variables and manually create a death broadcast command for the given Boss.

**Comment by lukrr** [comment]
And how can I make sure that message/broadcast is sent only to the players who hit the boss? so that it does not appear to everyone
