### ISSUE TITLE
Message only to players who dealt damage to the boss

### ISSUE THREAD

**Issue by lukrr** [kangarko/Boss#1294]
![imagen](https://github.com/user-attachments/assets/c014c517-a597-4af9-8f44-f3bbba85ff57)

It says there that you can use 'tell' for nearby players and 'broadcast' for all players. Is there a way to send a message only to the players who dealt damage to the boss? For example, if a player dealt at least 1 damage, even if that player dies or is far away, they would still receive the message that the boss died, thanks

**Comment by kangarko** [comment]
Cool, added!
