### ISSUE TITLE
Multiple Bug Reports - Copy/paste from Discussion Board @Spigot

### ISSUE THREAD

**Issue by reneg1990** [kangarko/Boss#13]
Heyo Kangarko!
- I've been messing about with setting up a boss.

I can't seem to get the drop tables to work. I've set a bunch of items up at a 100% drop chance, but without any luck. No items seem to drop when I kill the monster.

I checked the Config for my monster, theres no drops specified in there either, not sure if that could have something to do with it?

Heres the config: https://pastebin.com/B1Qbhevm
Heres a picture ingame of drop tables: https://gyazo.com/20b21b96e4360064fa076cb3d162658d
Heres a gif of me quickly killing the mob: https://gyazo.com/5a4b772828efb56f907f4ee7eaac0045

Version of Boss is the one released today.
We're running on the latest spigot 1.12.1 version aswell.

Hope to get a solution for this asap! :)

EDIT:

Spawn Conditions do not seem to work correctly either. I set a monster to spawn during nights, but its spawning all day/night long.

**Comment by kangarko** [comment]
Hey,

from my testing, drop tables work however, when the lightning bolt is spawned, items are fried and removed. I have replaced it with a fake lightning bolt.

PS: I have also fixed the spawn conditions :)
