### ISSUE TITLE
Minecraft Version: 1.19.4 : Boss World Limit Not applying

### ISSUE THREAD

**Issue by GanglyMoose** [kangarko/Boss#1301]
I have a boss spawn rule spawning a boss every 15 minutes on a certain block, at a certain time. Currently I have boss world limit set to only 1. However the boss still keeps spawning multiple over and over again.

**Comment by GanglyMoose** [comment]
I also am running into the issue of bosses not keeping to the region they're spawning in. They roam outside, and sometimes teleport back to their location, But do not stay thre.

**Comment by GanglyMoose** [comment]
![image](https://github.com/user-attachments/assets/493a3b13-2e80-4f64-8978-320cd5caf731)

**Comment by GanglyMoose** [comment]
There is only supposed to be 1 boss here... but as you can see here 9 have now spawned over the past two hours

**Comment by GanglyMoose** [comment]
![image](https://github.com/user-attachments/assets/ae6f66ce-a75b-437d-9083-0ab13a27ddc0)

**Comment by GanglyMoose** [comment]
![image](https://github.com/user-attachments/assets/4a5aecba-f18e-400b-9ed0-250e2c4fd2dd)


World spawning limits are 1

**Comment by kangarko** [comment]
Thanks for posting!

Are these chunks being unloaded? Did you try setting Count_Unloaded_Bosses option to true in Boss?

**Comment by GanglyMoose** [comment]
I believe these chunks are being unloaded when players leave the area, Yes. I do have That option set to true.

**Comment by GanglyMoose** [comment]
OH. Untrue. I did not have that option selected to true... This makes complete sense now.

**Comment by GanglyMoose** [comment]
Unfortunately, I set this, and it's still causing major issues. Too many bosses are spawning in the area.

**Comment by kangarko** [comment]
In the next version I will save unloaded bosses permanently. You will need to run /boss scan and remove all unloaded non marked bosses to see the changes 100%.
