### ISSUE TITLE
Plugin won't load on 1.8

### ISSUE THREAD

**Issue by Henriiig** [kangarko/Boss#1303]
https://pastebin.com/EiJhu5qp

**Comment by kangarko** [comment]
Can you try PandaSpigot 1.8.8? I will try making it work on Paper too

**Comment by Henriiig** [comment]
I am using PandaSpigot @kangarko

**Comment by Henriiig** [comment]
Maybe it had something to do with the config, becauae when I downgraded again it also did not work because of the config changes.
