### ISSUE TITLE
Minecraft Version: 1.20.4

### ISSUE THREAD

**Issue by Asssss2oh** [kangarko/Boss#1305]
![image](https://github.com/user-attachments/assets/f2a61c31-49be-482a-a5a3-2a485de7369f)

![image](https://github.com/user-attachments/assets/97e16488-e178-450f-a2db-c44ffec09ee7)

![image](https://github.com/user-attachments/assets/236d5a9a-edcc-420e-b149-0944853c2175)

![image](https://github.com/user-attachments/assets/921c3242-68f0-4665-a350-54c3eab832b1)

I want to display the time before the boss respawn in the hologram. How can I fix this error? Sorry for my English :3

Holographic Displays v3.0.4
Boss 4.13.7

**Comment by kangarko** [comment]
I apology, this only works with Respawn After Death rules given the Boss was killed by an entity and not removed by /butcher or clearlag

**Comment by Asssss2oh** [comment]
Ok, if the player is considered an entity, then what rule do I need to write

**Comment by kangarko** [comment]
This rule: ![https://i.imgur.com/KqxoJrg.png](https://i.imgur.com/KqxoJrg.png)
