### ISSUE TITLE
Sort Location Menu

### ISSUE THREAD

**Issue by IceGames23** [kangarko/Boss#1308]
We already have A-Z sort in spawning menu, but for some reason we don't have in regions and in locations menu what difficult a lot for create new locations and spawn rules. In my case, I have 615 locations and for found what I want in locations menu it's a nightmare.

![image](https://github.com/user-attachments/assets/3cc11230-cde4-4dae-af5e-abc0781ce6e5)
![image](https://github.com/user-attachments/assets/a7e09008-6c33-4d61-92df-8e80507bb61d)
![image](https://github.com/user-attachments/assets/78604d4c-6215-4f83-9d2c-85e46e5dbf8c)
![image](https://github.com/user-attachments/assets/a77d0178-0322-48ea-a1b6-4bbd5ebbb74c)

So the suggestion it's or make a "filter" or make a default A-Z sort, both cases will solve my problem and I belive the problem of other users.

**Comment by kangarko** [comment]
Whoa i overlooked that completely, let me fix that tonight thanks!
