### ISSUE TITLE
1.20.4: Replace Vanilla Mobs not working

### ISSUE THREAD

**Issue by jan-osicka** [kangarko/Boss#1310]
Hello, 

I am natively running Purpur-2176 (1.20.4), but for testing I also tried Paper-497 (1.20.4). Running Java 21. No special flags. 
I am attaching zipped folder of my settings. When I create boss and try to replace vanilla mobs, it does not work at all. I changed chance to 100% but there is no mobs being replaced. When I changed to 15% then I was getting ("[spawning] [SpawnRule=AngrySheepReplaced] Not running due to chance did not pass: 15.0%)
The debugging was of course turned on the whole time, but when it was set to 100% there was no information. The bosses were just not spawning. 
What I am trying to achieve is that each vanilla passive mob will have a chance to spawn Angry version, which will be attacking players.
I went trough wiki and old errors here, unfortunately it did not solved it for me. 
I am getting no errors in the console. 

Interestingly after many restarts/tries and errors. Once right after restart, all mobs were replaced with the bosses. However new spawning mobs were not. I have not managed to replicate this and that time there was also nothing special in the console. 

When I tried to change spawning rule to any other, everything was working perfectly (Bosses were spawning).
When I spawn them from a normal egg, it spawns bosses. Only the natural spawning is not working.

I tried to debug this as much as I could, tried removing several plugins, which could theoretically caused issues, but nothing helped.  

Thank you for any help or aiming be where to look for mistakes. :) 

[Boss.zip](https://github.com/user-attachments/files/17355098/Boss.zip)

**Comment by kangarko** [comment]
Turns out chunk gen when a new entity spawns is no longer called (https://i.imgur.com/l0p79Wo.png). I have worked this around in the next Boss release!
