### ISSUE TITLE
1.20.4: Bossess attacking each other

### ISSUE THREAD

**Issue by jan-osicka** [kangarko/Boss#1311]
Hello,

this is straight forward question. When I use Citizens for bosses and set them up so they attack players, they are also attacking each other as they are considered players as well. How do I turn off this behaviour? For example I have 3 types of players bosses (citizens) and each type is attacking each other. I did not find any option to turn this off. Like "Ignore other bosses, ignore citizens NPC etc". Is there this option? 

More explanation if it would be needed: 
3 types of player boss. 
Type A
Type B
Type C
When I set them all to attack and target players. 
Type A is not attacking other Type A bosses. However is attacking Type B and Type C bosses when close by. 
I do not want to limit spawning, so they never meet. I want to spawn close to each other, just not attacking each other and wait for the real players. It seems like basic function especially in dungeons, when there is many bosses close to each other. However I went trough the menus several times also the wiki, but cannot find it at all. 

Thank you also for help in previous issue! Amazing support :)

**Comment by kangarko** [comment]
Unfortunately the targeting is a bit broken with citizens on 1.21. I recommend you detach the Boss from Citizens and use Sentinel with Citizens NPC to setup the targeting instead.
