### ISSUE TITLE
1.20.4: Plugin Boss v5.0.5 generated an exception while executing task

### ISSUE THREAD

**Issue by jan-osicka** [kangarko/Boss#1312]
Hello,

I am natively running Purpur-2176 (1.20.4), but for testing I also tried Paper-497 (1.20.4). Running Java 21. No special flags.

Boss plugin failed to fetch skin for one of the bosses. After that the server completely froze with spamming the same warning repeatedly. From 1 AM to 8 AM the boss plugin alone generated 330MB file (log). Started on line 280 ended on line number 2718201. Server was unreachable for the whole time. It already happened second time. Also I have no idea what was the plugin trying to do, but filled completely ram memory. Which never happened before as we have a lots of free memory.  I cannot attach the whole file as it is huge, but I will place the start of the error and a few times the message which it was generating. 

[CrashError.log](https://github.com/user-attachments/files/17390519/CrashError.log)

With this happening, the plugin is unusable for my server.

**Comment by kangarko** [comment]
Let me get back to you in 24 hours

**Comment by kangarko** [comment]
Sorry unfortunately I had to delay it, but I should be finally sitting down this weekend.

**Comment by kangarko** [comment]
Thanks, fixed! A new release will be out tonight.
