### ISSUE TITLE
1.20.4: Hex Codes don't work in Actionbar

### ISSUE THREAD

**Issue by 0x484** [kangarko/Boss#1315]
Hex Codes (Now need to be set in Format "#ad5f00Name" instead of "&#ad5f00" (Dont know if thats intentional)
Theres a bug with this whereby Boss Names are correct, but they don't format in the actionbar display.
![image](https://github.com/user-attachments/assets/e533e02e-67c0-45fc-8e27-c1d0715212ba)

**Comment by kangarko** [comment]
Hello!

Thanks for reaching out. Please use this syntax instead in the next version of Boss:

`<#ad5f00>`

I will also adjust the help message to inform of this.
