### ISSUE TITLE
All Versions - Citizen Boss Registering as Player

### ISSUE THREAD

**Issue by ProjectGuinness** [kangarko/Boss#1316]
The citizen based bosses are registered as players. When a boss is killer it is announcing it in chat for example my boss names Vampire which I want as a natural spawning boss for players to hunt is spamming chat "Vampire was killed by drowning" or "Vampire was slain by [Player]" which is annoying in chat. 

Also we use a PVP management system to automatically moderate our pvp rules. Such as a tp protection which protects players up to 30 seconds after teleporting from engaging in PVP which seems to be counting the bosses. 

Also we have a pvp log protection so when someone logs out they are killed which also goes into effect with the bosses.

**Comment by kangarko** [comment]
Please see: https://github.com/kangarko/Boss/wiki/Common-Issues#console-spams-with-named-entity-x-was-slain-by-y-messages

Thank you.

As for the PvP protection you need to ask that plugin author to add an exception if the entity is a Citizens NPC (he needs to hook into Citizens not Boss)
