### ISSUE TITLE
Bugg - Target nearest player

### ISSUE THREAD

**Issue by lukrr** [kangarko/Boss#1317]
I installed the latest version of the plugin, but it doesn't work for me to make the boss attack the nearest player. Just in case, I'll let you know that I don't have Citizens, I'm using the base plugin

https://github.com/user-attachments/assets/bedee331-71ec-4b2f-be8b-7461f435bdb0

**Comment by kangarko** [comment]
Hello!

Please try setting Fighting.Retarget_Chance to 100%, it should then always make the boss retarget to you or whoever hit it last.
