### ISSUE TITLE
Message Leaderboard

### ISSUE THREAD

**Issue by lukrr** [kangarko/Boss#1319]
Hi, I'll send you the image of what I wrote on Discord. I would like to make it so that when the boss dies, a message is sent only to the players who hit the boss, listing the players who dealt damage. For example: '#1 PlayerName - DamageValue,' '#2 PlayerName - DamageValue,' and so on.
![Screenshot_1](https://github.com/user-attachments/assets/2b174716-b368-4a6f-92da-dc17567492f8)

**Comment by kangarko** [comment]
Added to the next version <3

https://github.com/kangarko/Boss/wiki/Boss-Commands#special-commands
