### ISSUE TITLE
Custom enchantment disappear after Server restart

### ISSUE THREAD

**Issue by AconTM** [kangarko/Boss#132]
Hey,

i have made my own "enchantment" to let items "glow" like normal enchanted items.. But when i restart my Server the glow effect is gone (item drops from boss)..

I hope you understand what i mean :D here 2 screens to help :D

https://i.imgur.com/PoGMZyf.png
https://i.imgur.com/RYPau81.png

**Comment by AconTM** [comment]
And also Players wont attack with Skills.. here screens:

37 Bosses vs 1 Player & they used 0 Skills:
http://i.epvpimg.com/5cSqeab.jpg

21 Bosses vs 1 Player & they used a spam of Skills (right chat):
http://i.epvpimg.com/rbRCfab.jpg

**Comment by kangarko** [comment]
Hello,

how do you make the item glow? Boss does not alter items when they are dropped. I am sorry but I don't provide support for code outside for Boss.

I don't understand the second post; so the skills are not working even when you get the message that they are dispensed?

PS: Please post me your settings.yml and Hades' .yml file.

**Comment by kangarko** [comment]
Closing, if you still need help, please comment below and I will re-open.
