### ISSUE TITLE
Bugg - Target nearest player - Ticket 2

### ISSUE THREAD

**Issue by lukrr** [kangarko/Boss#1320]
Hello, I put "Retarget_Chance: 100%" in the plugin, and when I hit it it starts attacking me, even if I have a nearby player, isn't there a way to make it always attack the closest player? regardless of whether other players are hitting him from further away?

https://github.com/user-attachments/assets/e888a9f9-7314-4657-90d0-a93bcaad0ea2

https://github.com/user-attachments/assets/e09dc578-e1f4-4904-a560-10fa292302de

**Comment by kangarko** [comment]
Unfortunately not, it's a feature that the majority of Boss users requested - to target the player who damaged the Boss.

I could add an option for what you request but that I do not have the time right now, plus it would add a performance penalty to iterate through nearby entities and calculate the nearest one.
