### ISSUE TITLE
Top Damage

### ISSUE THREAD

**Issue by lukrr** [kangarko/Boss#1324]
Hi, there's a bug with the damage dealt to the boss. If a player goes several seconds without hitting the boss, they disappear from the top. I tested it with two accounts, and for example, if Player2 hits the boss once, and after 20-30 seconds Player1 kills the boss, Player2 won't receive their reward because 20-30 seconds have passed. I know they disappear from the damage top because if the boss has 5000 health, Player2 deals 4900 damage, and after 20-30 seconds Player1 goes and deals the remaining 100 damage, Player1 gets the top 1 reward despite only doing 100 damage, as the other player dealt 4900 several seconds earlier and was removed from the top.

**Comment by kangarko** [comment]
Fixed!
