### ISSUE TITLE
Bugg Rewards

### ISSUE THREAD

**Issue by lukrr** [kangarko/Boss#1325]
Hello, I mentioned before that there was a bug where if the boss died, players who had dealt damage to it more than 15-20 seconds earlier would not get their damage counted. Well, in this new version you released, I see it still hasn’t been resolved. I investigated a bit more and found that if you kill the boss quickly (meaning within 15-20 seconds from when the last player hit the boss), both players receive the reward without any issues. But if the boss dies, players who hit it more than 15-20 seconds ago don’t receive the reward. I’ll show you two pictures: the first one shows how both players receive the reward (3 of the red item for one player, and 2 of the red item for the other) since I killed the boss before 15-20 seconds had passed. However, in the second picture, Player2 hit the boss, then I waited more than 15-20 seconds, and killed the boss with Player1, and Player2 didn’t receive their reward of 2 of the red item because too much time had passed, even though they still appear on the damage dealt list, but don’t receive the drop.

![Foto1](https://github.com/user-attachments/assets/d5e46d33-20e1-488b-bd99-f6337d1287ef)

![Foto2](https://github.com/user-attachments/assets/7becb4b9-e81d-43d2-a48a-2d327f5e7c11)

**Comment by kangarko** [comment]
I am leaving office for the weekend and will take this after. Thank you.

**Comment by kangarko** [comment]
I am so sorry completely overlooked this!!

Did you try increasing this option in Boss Menu > Boss > Drops > Player Drops?

![a](https://i.imgur.com/Gedri2f.png)

**Comment by lukrr** [comment]
I didn't know that option existed. I wanted to set it to 60 minutes, but it won't let me; it only allows a 10 minute limit. Is there any way to set it for a longer time or even infinite time? This way, all players would receive the reward even if they hit the boss hours ago

**Comment by kangarko** [comment]
I will remove that artificial block. Keep in mind the damager cache is reset upon reloading or server restart.
