### ISSUE TITLE
Boss Damage Bugg

### ISSUE THREAD

**Issue by lukrr** [kangarko/Boss#1328]
Hello, I found a bug with the boss's damage. I set 'Strength 4' in the PotionEffect section, but the boss's damage is much lower than it should be with that potion. For example, in my previous server, I used another boss plugin, and with Strength 4, the boss would deal 8 hearts of damage, and if I had Resistance 3, it would deal 3 hearts. However, in this plugin, the boss only deals 1 heart of damage, and if I have Resistance 3, it doesn’t damage me at all. I tried increasing the strength, but I had to set it to 'Strength 20' for it to deal those 3 hearts of damage. But if I removed Resistance 3, it would kill me in one hit instead of taking 8 hearts. I thought it might be a change in Minecraft, since I used to play on 1.16.5 and now on 1.21.1. However, I logged in with a secondary account, gave that player Strength 4, and when they hit me, it correctly dealt 3 hearts of damage (8 hearts if I didn’t have Resistance), just like it was with the other boss plugin

**Comment by kangarko** [comment]
Investigating in 24 hours

**Comment by kangarko** [comment]
Unfortunately I was unable to find the exact cause. Your other Boss plugin might have been modifying some behavior that we do not. We aim to be as close to vanilla as possible.

In the next Boss update, please try adjusting the Boss attribute in the Boss Settings > Attributes menu namely the attack damage one. That should multiply the damage dealt by the bow.

What you can do in the next version is setting the Debug key to [damage] and seeing the original vs modified damage in the console log when the Boss hurst you, that way you can better calibrate the attribute and enchant to your needs.
