### ISSUE TITLE
HEX Colors

### ISSUE THREAD

**Issue by lukrr** [kangarko/Boss#1329]
Hello, I assigned a HEX color to the boss, but it doesn’t work. In the editor, the color shows up fine, but when I spawn the boss, it doesn’t appear with that color. Also, when the boss dies in the "tell-damager-list" with {bos_alias}, that color doesn’t show up either. I tried removing the "&", but it still doesn’t work, thanks.

![Screenshot_1](https://github.com/user-attachments/assets/95e66853-a559-4249-a647-5c56d4083cb8)

![Screenshot_2](https://github.com/user-attachments/assets/6056e083-3d70-4e80-9556-1e30b9745557)

![Screenshot_3](https://github.com/user-attachments/assets/720f54db-be74-41b5-8243-296960836bd8)

**Comment by kangarko** [comment]
You need to use the minimessage format which is `<#123456>`
