### ISSUE TITLE
Boss Suggestions :)

### ISSUE THREAD

**Issue by nickswizle** [kangarko/Boss#133]
Hi, I just purchased this plugin and I thought i'd give some suggestions to help improve it.
1 - Ability to change the size of the mob.
2 - Particle effects option. 
3 - Boss bar option
4 - Custom armor stand mob
5 - More skills

This is a great plugin, I really enjoy it! Keep up the great work.

**Comment by kangarko** [comment]
Hello and thank you for your purchase!

1. This is possible with Slimes. Ageable Bosses can be made into Babies, but Minecraft does not allow to set size for majority of mobs.
2. Thank you, I believe I already got this noted!
3. What effect should the bar have?
4. Sorry we are not planning this at the moment.
5. If you have concrete ideas, you are more than welcome to post them ;)
