### ISSUE TITLE
HEX color in tell-damager-list

### ISSUE THREAD

**Issue by lukrr** [kangarko/Boss#1330]
Hello, I modified the boss's name with MiniMessage, setting it to <#5c330a><bold>Duvil. It works fine, but in the command I have in tell-damager-list, the boss’s name shows up in green if I use {boss_alias} (it’s taking the last letter of the MiniMessage, the letter "a," and applying the green color to it. If I change that letter to "b," it shows up in aqua). I tried removing {boss_alias} and using the same as the name, like <#5c330a><bold>Duvil, but the result is the same. Thanks.

![Sin título](https://github.com/user-attachments/assets/fdc8420a-7cb3-4ff4-989e-898ebd354c21)

**Comment by kangarko** [comment]
What MC version are you on? I'm on Spigot 1.21.3, used `tell-damagers-list <#5c330a><bold>Duvil|&r&c{order} &7- &f{damager} &7- &c{damage}`

The only thing not working is the alignment when the name is bold, because that is unsupported.

![a](https://i.imgur.com/cqCRoNH.png)

**Comment by lukrr** [comment]
I'm on purple 1.21.1
From what I see in your image, the name of the boss is seen in red, I think it would not be working correctly for you, since the hex color is brown

**Comment by kangarko** [comment]
Thanks, will be fixed. I also got rid of the ----- line so now you can customize the header completely

I recommend you use {boss_alias} instead of hardcoding the boss name.
