### ISSUE TITLE
Enchantment Power Bugg

### ISSUE THREAD

**Issue by lukrr** [kangarko/Boss#1331]
Hello, sorry for so many tickets, but I found another bug. I gave a Stray a bow enchanted with Power 60, but it doesn’t deal the damage it should (it does about 25% of the damage it should). To make it deal the damage I want, I had to increase the Power level to around 180. This seems to be an issue because, in my previous boss plugin, I had it set to Power 60. Additionally, I spawned a Stray with Power 60 using a command (just a normal mob, not a boss), and it did the correct damage with the same bow.

**Comment by kangarko** [comment]
Hey! No problem, I am happy to help you make sure it works at least as good as the previous plugin!

Now, I can't reproduce this. Tested on Spigot 1.21.3 (what's yours?), the stray kills me in one hit even with netherite armor.

![a](https://i.imgur.com/DHZUVzn.png)

I tested summoning Stray with

`/summon stray ~ ~1 ~ {PersistenceRequired:1,HandItems:[{count:1,id:bow,components:{enchantments:{levels:{'power':60}}}},{}]}`

And got the same 205 score upon one-shot kill.

Can you please test only with the Boss plugin to make sure no other plugins conflict?

**Comment by lukrr** [comment]
Hi, here I'm showing you a video with just the Boss plugin, using power 60.

(Just in case, I'm wearing leather armor with 5 armor points on each piece, extra hearts for each armor piece, and I've also applied the resistance 3 effect)


https://github.com/user-attachments/assets/930642a0-668a-4174-a89f-91bebbf45048

**Comment by kangarko** [comment]
Can you please send me /boss debug?

**Comment by kangarko** [comment]
Copying over the other ticket since I think the solution will apply here too:

>In the next Boss update, please try adjusting the Boss attribute in the Boss Settings > Attributes menu namely the attack damage one. That should multiply the damage dealt by the bow.

>What you can do in the next version is setting the Debug key to [damage] and seeing the original vs modified damage in the console log when the Boss hurst you, that way you can better calibrate the attribute and enchant to your needs.
