### ISSUE TITLE
Bugg /boss menu

### ISSUE THREAD

**Issue by lukrr** [kangarko/Boss#1335]
![Screenshot_1](https://github.com/user-attachments/assets/39bcf60b-aa2a-4ff3-8948-daa5cd2fb6ad)

Hello, with the latest version of the plugin it doesn't let me open the different bosses I had in /boss menu

**Comment by kangarko** [comment]
Do you have Citizens installed?

**Comment by lukrr** [comment]
I don't have it installed

**Comment by kangarko** [comment]
I dont normally work Sundays but since this is a critical issue, you will get it fixed by tomorrow :)

**Comment by lukrr** [comment]
Thanks :)

**Comment by kangarko** [comment]
Is more complicated due to some breaking changes in spigot than I thought, try deleting any super-new bosses like Creaking for now. I need 1-2 days to fix it, thank you.

**Comment by lukrr** [comment]
Actually I am using 1.21.1 and the same configuration as the previous version of the plugin, I did not put any cracking or anything similar

**Comment by kangarko** [comment]
Okay test the next version, if it happens again please post me your full /boss debug. The new release will be out tonight.
