### ISSUE TITLE
1.20.4 Is it possible to avoid exceeding the spawning limit?

### ISSUE THREAD

**Issue by Saspen111** [kangarko/Boss#1337]
1) 1.20.4 We are faced with the problem of exceeding the spawning limit with the respawn after death rule, when players switch on and leave the world with the arena.

2) I found the /boss scan command in the documentation, but I didn’t fully understand what its essence was and whether it would help solve this problem once and for all, or whether it requires running after each server restart. I hope that you will tell me what its essence is, or how we can solve our problem in an alternative way. thank you and sorry for my english.

**Comment by kangarko** [comment]
Did you set Spawning.Count_Unloaded_Bosses_In_Limits to true in settings.yml ?

**Comment by Saspen111** [comment]
Yes

**Comment by kangarko** [comment]
1 Can you please send me your /boss debug output? You can drop the ZIP here.

2 Regarding your second question, the /boss scan removes Bosses in unloaded chunks. 

3 Normally, when you have the Count_Unloaded_Bosses_In_Limits option set, we keep a track of unloaded Bosses in unloaded-bosses.yml file - can you check it for me to see if they are indeed being stored?

4 You can set the Debug key to [spawning] in settings.yml and inspect why the Bosses are spawned when they exceed the limit, let me know the console logs.

Thanks!

**Comment by Saspen111** [comment]
[debug.zip](https://github.com/user-attachments/files/17759176/debug.zip)
[Logs.txt](https://github.com/user-attachments/files/17759177/Logs.txt)


Regarding your third question - I could not find such a file in my storage.

**Comment by kangarko** [comment]
I see you're on v4.13.7, please update to the latest Boss version because we specifically made improvements in that part there. Thank you!
