### ISSUE TITLE
Health Bar

### ISSUE THREAD

**Issue by IceGames23** [kangarko/Boss#1339]
I think a big improvement of Boss it's another options of healthbar and not only actionbar healthbar

Like, I have a combatlog plugin that the players are tagged by mobs too. And the combatlog uses actionbar, so when the player it's fighting with the boss the healthbar it's useless.

My suggest it's to have another options of healthbar, like that for example:
![image](https://github.com/user-attachments/assets/2ff4e548-3c55-45bf-9039-c1d9a61a2199)

A simple, but clean example of healthbar.

Other thing that will be better in this case, it's that the healthbar will only apper if the boss takes damage. Same for the name, like, to have a option for only show the name of the boss if he takes damage.

**Comment by kangarko** [comment]
Thanks, I will keep this in mind however I have been very busy these last months, so for now I suggest you use an alternative plugin like https://modrinth.com/plugin/holomobhealth for this one feature :)

**Comment by kangarko** [comment]
Unfortunately I am unaware of any 1.8.8 compatible plugins for this feature
