### ISSUE TITLE
Spawning

### ISSUE THREAD

**Issue by Buzzzzy** [kangarko/Boss#134]
I'm having A LOT of trouble trying to sort out this spawning nonsense. Basically, I want the players to be able to obtain a boss egg through various means, and then go to a specific place in a world called the Boss Altar, and place the egg on the Altar to spawn the boss. I have created a region with both world guard, and the boss tools, and I'm running into a lot of problems such as: when the region 'Altar' is selected the boss can spawn anywhere, in any world, when I'm trying to restrict it to only be able to be spawned on the Altar, and when I play with the spawning settings it completely disables the boss from being spawned anywhere in the entire world.

**Comment by kangarko** [comment]
Hello,

I am sorry you have issues with Boss. To make the boss only spawn in the region Altar, make sure you do not have the Blacklist option enabled
![a](https://i.imgur.com/hoy0Vqj.png)

and that you only selected region Altar in which you want the Boss to appear:

![b](https://i.imgur.com/ReYpnJq.png)

You can also debug spawning by setting Debug to [spawning] in settings.yml and seeing what is the cause of the problem.

If you need more help, please attach the Boss/ folder as a ZIP to your answer here so I can test using your exact conditions.
