### ISSUE TITLE
1.21.1: World limits and butcher commands

### ISSUE THREAD

**Issue by LucidAPs** [kangarko/Boss#1340]
So from my testing it, it seems like the world limits each boss has are working great even if bosses are in unloaded chunks, however the command that butchers that boss in every possible world "boss butcher * Black_Knight" only checks loaded chunks, that means if you have a world limit for that boss to 1 and it goes into an unloaded chunk or is just lost somewhere, then you are essentially screwed because that boss cannot be removed with commands. The only solution I found for this was turning that setting to false

  # Save unloaded bosses to a unloaded-bosses.xml to include in spawning limits?
  Count_Unloaded_Bosses_In_Limits: false

So how do we actually remove these bosses in unloaded chunks? This whole thing is a bit of a questionable design in my opinion.

Boss-5.1.2

**Comment by kangarko** [comment]
Correct, because removing Bosses in offloaded chunks is a resource-extensive operation, and questionable design would be to hang the server each time /boss butcher is run.

Therefore we have /boss scan command which will do the job and remove all bosses from all chunks.
