### ISSUE TITLE
Skills execute Commands

### ISSUE THREAD

**Issue by IceGames23** [kangarko/Boss#1341]
It's a simple addition but it will greatly improve my experience with the Boss, it's basically adding support for the bosses skills to execute commands when they are used. With that I can, for example, use custom sounds for each skills in different bosses.

Other great idea it's add a skill that only executes commands, that it's a similar thing to custom skills, but without code.

**Comment by kangarko** [comment]
Awesome tip, on it, will release in 1-3 days :)

**Comment by kangarko** [comment]
I added three command-only skills and added commands (console + per-player) into each skill, enjoy and give review if you like! New release will be out in a few days.
