### ISSUE TITLE
New Variables&Placeholders

### ISSUE THREAD

**Issue by SentorCraft** [kangarko/Boss#1342]
The plugin currently provides placeholders like %boss_{bossName}_top_damage_{leadingPosition}_{player/value}% and %boss_{bossName}_top_kills_{leadingPosition}_{player/value}%, which are useful for tracking player contributions. However, there are no placeholders to capture data specific to the last killed boss. Adding a placeholder such as %boss_{bossName}_lastkilled_top_damage_{leadingPosition}_{player/value}% would be a game-changer. This addition would enable the creation of announcements—whether in chat or via holograms—highlighting the players who made the biggest contributions to defeating the boss and the amount of damage they dealt.

Although there is an alternative tell-damagers-list <format> or <title>|<format>, It does not enable me to make customization and lacks some features like multi-server support.

Additionally, placeholders similar to %boss_top_damager% could enhance compatibility. For example, %boss_top_damager_1% and %boss_top_damage_1% would provide detailed and accessible data, making the plugin seamlessly compatible with other plugins that process commands and variables. These features would significantly improve usability and customization options. Thanks for your attention.

![image](https://github.com/user-attachments/assets/be8dc41d-fffb-4f17-8cf4-33d5a4455d3a)

**Comment by kangarko** [comment]
Thanks. While these are great suggestions, I am really tight on time due to some personal matters and I have already spent two days implementing the new custom skill system. I will reconsider this next month when I get more time, hope you understand.
