### ISSUE TITLE
1.21.1: Bosses don't Spawn when above Lush_cave Biome

### ISSUE THREAD

**Issue by 0x484** [kangarko/Boss#1344]
I have Bosses set to Randomly Spawn around the player using the Spawnrule.
I just Updated to the latest Version (I was on 5.0.10 before)

When I have a Boss set to spawn in a certain Biome, for example a Warden in a Dark_forest and 
there is a Lush Cave below it, the Boss can't spawn. Once I remove the Lush cave via Worldedit, it works.

Easily testable by
1. Selecting a boss to spawn in a certain Biome with 10s intervall
2. Using Worldedit to create a huge Lush Cave Biome below it
3. See no bosses spawning
4. Remove the Biome below -> see bosses spawn again

I think this most likely happens with every Biome, its just an issue with lush/dripstone caves since they generate below other biomes.

**Comment by kangarko** [comment]
Investigating
