### ISSUE TITLE
Add Lands Support to the plugin for spawn rules

### ISSUE THREAD

**Issue by ChiefWarPig** [kangarko/Boss#1345]
1) Lands is on 7890 downloads on Spigot alone and seem to be gaining popularity as an anti grief/land claim plugin due to it's ease and simplicity in use. Adding support to lands to recognise if the mob spawn flag is set or not will enhance the user experience as currently because it is not supported mobs spawn even in lands with the no mob spawn flag enabled. In addition to the reason mentioned adding support would give better consistency across your plugin range as you already support Lands in ChatControl Red. 

2) If you don't add the feature then players who do not want mobs spawning are going to be subject to them wethey they want them or not, the only way to negate this would be for server owners to make special regions but this will frustrate gameplay where a server wide approach is desired. 

3) I am certainly no expert but as you have used the Lands API in other plugins and already have functionality to support and respect other plugins I suspect it would be a relative minor addition to code in comparison to if it was to be a completely new implementation.

**Comment by kangarko** [comment]
Added! A new release will ship tonight. Rate the plugin if you enjoyed the fast support :)
