### ISSUE TITLE
Minecraft Version: Paper 1.21.1-132 

### ISSUE THREAD

**Issue by ChiefWarPig** [kangarko/Boss#1346]
Blocks that are not full blocks (Slabs, Farmland etc) are being deleted when the cobweb placed by the freeze skill is removed from the map. Obviously the desired effect here would be not to have blocks being deleted, if this isn't technically possible then maybe either making the cobweb spawn a block higher or add a check to only place it if the player is on a full block that won't be deleted? 1 other idea is if there can be a check to see what is deleted when the cobweb is removed and then replace any blocks that are not cobwebs if that is another possible option? 
[BossFile.zip](https://github.com/user-attachments/files/18004408/BossFile.zip)

**Comment by kangarko** [comment]
I will make it so cobweb is only placed if the replaced block is air: ![a](https://i.imgur.com/qY1QoVw.png)

Also note that for certain scenarios this might be tricky so best way is to disable cobweb feature if it is occluding blocks.
