### ISSUE TITLE
Giving rewards using variables console commands?

### ISSUE THREAD

**Issue by Xpomodz** [kangarko/Boss#1347]
Id live to give the last player whom killed the boss a reward how do i do this

**Comment by Xpomodz** [comment]
[22:23:31 INFO]: Can't find player with this name! ([name]) (money -> %boss_top_damager%)

**Comment by kangarko** [comment]
You can setup player rewards in Boss > Death > Drops and enable Inventory Drops, then add commands for each drop by order, 1 being the drop for the player who dealt the most damage to the boss before the boss died.

I do not understand your other message.
