### ISSUE TITLE
Extra mob drop customisability.

### ISSUE THREAD

**Issue by LogGits** [kangarko/Boss#135]
Setting for modifying drops (with chance) for any type of mob (regular mobs). Even commands to run when a mob is killed or giving economy money to the player for killing a mob (random between a min and max value). This would be a really addition and would be very convenient for me. P.s. I apologies if someone has already requested this, I couldn't find anything about it.

**Comment by kangarko** [comment]
Hello,

I am sorry but Boss only affects the behaviour of custom monsters created within it. Mobs outside are not monitored nor managed. This would be a nice idea for a separate plugin, though.

Matej

**Comment by kangarko** [comment]
After a quick search this may be of interest to you: https://www.spigotmc.org/resources/1-6-1-12-customdrops.36777/
