### ISSUE TITLE
Minecraft Version: 1.8.8: boss won't spawn anymore

### ISSUE THREAD

**Issue by maxbakker1** [kangarko/Boss#1352]
Version 1.8.8

Current situation: My boss worked well yesterday. Made a second boss, did a restart and both bosses don't show up in de GUI anymore. After used a backup of a few hours ago and the boss I set up yesterday still doens't spawn. In the console it says it does spawn. Debug also [spawning].

Question is; why doesn't the boss spawn anymore ?

Latest log and boss file + settings.yml in attachmentment
[lastest.txt](https://github.com/user-attachments/files/18135920/lastest.txt)
[Undead.txt](https://github.com/user-attachments/files/18135921/Undead.txt)
[settings.txt](https://github.com/user-attachments/files/18135924/settings.txt)

**Comment by kangarko** [comment]
Boss does not support worlds with dots in their name, please change the . to _ in world 1.8/ork_kitpvp and also rename this key to 1_8/ork_kitpvp in your Undead.yml file.
