### ISSUE TITLE
Minecraft v1.21.1: Alive boss speed reduced to a slow crawl after killing other nearby boss

### ISSUE THREAD

**Issue by PeakPartyGames** [kangarko/Boss#1353]
I am having an issue where boss movement speed is reduced to nearly nothing. When a group of bosses spawn in a region, a player kills one of those bosses, then the remainder will be slow. If additional bosses spawn they will be at regular speed. When one of them are killed, all other bosses they spawned with will be slow. 

For any boss with this condition, their speed is reset if their target is changed. Once they retarget the same player that killed them, their speed is reduced.

While writing the bug report, I found the culprit. If the boss is targeting "player" boss types, it will cause the issue. Disabling this will give them standard behavior. 

I am using Citizens for pathfinding and behavior. Submitting this bug for transparency. Thank you!

![image](https://github.com/user-attachments/assets/4958f991-43ef-456d-9c6f-9d67886e79c3)

**Comment by PeakPartyGames** [comment]
My discord handle is `ewwwadesigner`. Feel free to reach out there for a quicker response if you need more details.

**Comment by kangarko** [comment]
Can you please disable Citizens integration in Boss Settings menu to see if it gets resolved? Citizens have been causing some issues recently and we're trying to isolate the problem, unfortunately that is outside of our API scope since they take over these properties quite aggressively

**Comment by PeakPartyGames** [comment]
That doesn't seem to fix it.

**Comment by kangarko** [comment]
Great! For now I am closing this. I am sorry that the Citizens integration is faulty. We could take over but I do not have the time to reimplement all Citizens features, so for now that will remain a wontfix.
