### ISSUE TITLE
Minecraft Version: 1.21.4 - Return Location On Escape

### ISSUE THREAD

**Issue by jonathan-lr** [kangarko/Boss#1355]
Hi,

Boss Type: PLAYER not returning to the location on escape or walking back to the location using citizens.
Other mob types I have tested teleport back fine but never walk back when using citizens.

Boss file:
https://pastebin.com/aL3LLR0m

Also is there any way to un-target the player when no one else is around as the target range is 10 but it will still chase at 50 blocks separation?

Thanks

**Comment by kangarko** [comment]
Citizens seems to be cracking up a bit in the recent releases, unfortunately I wont be really having time to deal with their APIs until I come back home Jan 3. If regular Bosses work then it's out of our scope and we'd have to implement a workaround that will take more time. Sorry about that!
