### ISSUE TITLE
Question about "Boss".

### ISSUE THREAD

**Issue by TheIntelloBox** [kangarko/Boss#136]
Hey ! :D 

Is it possible to send a message in the tchat to all players when a boss is spawning in a region ?
For example: "The boss "Squid" spawned in the region "Spawn". Go kill him to have money !".

Thanks for your answer,
TheIntelloBox.

**Comment by TopCZE** [comment]
I think this Boss plugin does not have this feature. But maybe I'm wrong.

**Comment by kangarko** [comment]
Hey,

you can add custom commands such as a "broadcast" or a "say" command to your Boss editing their yml file: https://github.com/kangarko/Boss/wiki/Common-Issues#how-can-i-send-custom-messages-or-commands-when-a-boss-diesspawns
