### ISSUE TITLE
Boss does not spawn..

### ISSUE THREAD

**Issue by Kit-Pan** [kangarko/Boss#138]
I have noticed a slightly annoying issue with the plugin... The only ways that a boss spawns is via converting an existing mob to a boss. I have tried to make Wither Skeletons spawn in the overworld and I can- if I use a mob egg- but they do not naturally spawn in the world. The same can be said for endermites.

Could you please assist, as I think I am just misunderstanding a piece of the config file.

I am using the latest version of Boss 1.7.0

**Comment by kangarko** [comment]
Hello,

please see https://github.com/kangarko/Boss/wiki/Common-Issues#my-bosses-are-not-spawning-naturally

If you will still have issues, please post me your Boss/ folder zipped directly to the answer window and I will reopen this and get back to you.
