### ISSUE TITLE
Equipped items do not drop

### ISSUE THREAD

**Issue by Leomelonseeds** [kangarko/Boss#140]
The title explains it all. When the custom mob is killed the custom items it is equipped with do not drop, even though I set it to 100%. There are no errors in console.

**Comment by kangarko** [comment]
Please ZIP me your Boss/ folder directly to this answer window.

**Comment by Leomelonseeds** [comment]
Sorry for the late reply, Github forgot to send me an email :P
MC version: 1.12
[Boss.zip](https://github.com/kangarko/Boss/files/2233213/Boss.zip)

**Comment by kangarko** [comment]
Confirmed, fixed. Thanks.
