### ISSUE TITLE
Boss Minions Configuration

### ISSUE THREAD

**Issue by KGKhan1** [kangarko/Boss#142]
Hi,

I have a question. How can I set what the boss will summon as a minion and how many to summon them?

Thanks.

**Comment by kangarko** [comment]
Hello,

Open /boss menu, select your Boss, click Death, then Reinforcements and use the sections there.

**Comment by KGKhan1** [comment]
I'm not talking about death events... I'm talking about the skills...

**Comment by kangarko** [comment]
You can set the amount of them to spawn in the skills/ folder to that skill.

I will include an option to select what to spawn in the next update.
