### ISSUE TITLE
Pageable Drops Menu

### ISSUE THREAD

**Issue by drewgleaves1028** [kangarko/Boss#143]
I recently purchased your plugin and it is great and I thought of a good and useful idea that would be good to implement. 
Allowing the user to make a new loot inventory when you fill one up to keep adding items without going into the config. In my opinion, this would be a great feature put in because I'm making a faction server and would like to see this being implemented in the future.
I really enjoy using your plugin very easy to navigate. Keep up the good work hope to see this put in.

**Comment by kangarko** [comment]
@drewgleaves1028 thank you for your purchase & I apology for a late reply!

Do you mean that, after filling up the default drop menu, you could easily go to the next page there to add even more items?

**Comment by drewgleaves1028** [comment]
Yes, that what I mean I know it might have been a bit descriptive I think it would a good installment.

**Comment by kangarko** [comment]
Had to close due to works on other priorities and it turned out that it is not possible without a major rewrite of that menu rendering, sorry.
