### ISSUE TITLE
Improvement: Mob Stack Support

### ISSUE THREAD

**Issue by JTGgamer** [kangarko/Boss#144]
My server has spawners and i really need to add a mob stacker plugin but it contrasts with the boss plugin as they combine and they only have to fight one at a time( i want them to remain seperate).As well as this, the second boss is turned into a normal zombie. 
Could u add support plz?

Plugin:
https://www.spigotmc.org/resources/mobstacker-merge-mobs-together-opensource.52459/

**Comment by kangarko** [comment]
I am sorry but due to the nature of that other plugin it is incompatible with Boss.
