### ISSUE TITLE
Boss + Mobhunting

### ISSUE THREAD

**Issue by alexanderevain** [kangarko/Boss#145]
Hey i loved Boss very very much!!! i have only an issue which isn't a real issue...it justs messes the economy plans of my new server im planning...I want mobhunting to work with Boss....i already asked the dev of mobhunting and told me that its a paid plugin so he cant do anything...and im wondering is there any way you can cooperate so you can bring this awesome feature in your very very awesome plugin?? :) thank youu

**Comment by kangarko** [comment]
Thank you for your feedback!

What specifically you need with MobHunting and what does not work? Boss has an API (I attached it here, however, this won't work as a plugin since it only contains API classes) so they can take a look and let me know if there is anything I can add.

**Comment by kangarko** [comment]
.

**Comment by alexanderevain** [comment]
heyyy sorry, i answered this late :)
in the mob hunting config, i can add mobs and tell how many gold they will
give you etc
but i want to add the specific names of the custom-made mobs from the boss
plugin....cause if i, for example, have a custom zombie mob and kill it it
will drop what zombies drops according to the config setting about the
zombies says .sorry for my bad English i hope you understand :)

**Comment by kangarko** [comment]
We are not planning to include this feature at the moment due to other priorities.

**Comment by alexanderevain** [comment]
alright
