### ISSUE TITLE
Major Additions needed for the plugin to succeed.

### ISSUE THREAD

**Issue by Kariizma** [kangarko/Boss#148]
1. Adding Skills settings (damage, duration, radius) for each individual boss. 
Example: Zombie Pigmen: Fireball Power = 1.8 but Magma Cube Fireball Power - 2.8

2. being able to edit the damage/power of all SKILLS such as (Throw Player, Strike Lightning, Ignite Player.)

3.  being able to do 1 and 2 in the GUI (right click the skill to change its power for a certain boss)

4.  being able to determine what the babies are. (Cave spider mom, spawns Regular spider babies)

1 and 2 are major, 3 and 4 are minor

**Comment by kangarko** [comment]
Thank you for the suggestions. Number 4 is not possible due to the nature of Minecraft. We are planning a skill update in the future in that each skill will be customizable to each Boss.
