### ISSUE TITLE
Edit quantity?

### ISSUE THREAD

**Issue by SoraShiunin** [kangarko/Boss#156]
Hello the edit quantity editing "1 2 5 10 20" was removed (For drops)? 
Could it be reintroduced please?

**Comment by kangarko** [comment]
I still have them, what's your MC version and where you don't see them?

![a](https://i.imgur.com/l3ohXta.png)

**Comment by SoraShiunin** [comment]
In drops. The vanilla mob drops is on top of it.

**Comment by kangarko** [comment]
Awesome spot, fixed right away! Sorry the for the delay.
