### ISSUE TITLE
Boss region missing in newest version

### ISSUE THREAD

**Issue by SoraShiunin** [kangarko/Boss#157]
In 1.7.5 Boss region is not in the spawning options ?
![screenshot_776](https://user-images.githubusercontent.com/23641964/44294708-fc389f80-a29b-11e8-85c1-4269d9e0fa13.png)

**Comment by kangarko** [comment]
Sorry for delays, works fine for me. What's your MC version? Any console errors when opening that menu?

In any case ZIP me your Boss folder so I try to reproduce using same conditions.

**Comment by SoraShiunin** [comment]
No errors. Mc 1.12.2 .
[Boss Config.zip](https://github.com/kangarko/Boss/files/2319852/Boss.Config.zip)

**Comment by kangarko** [comment]
@SoraShiunin is the issue resolved now?

**Comment by kangarko** [comment]
Closing. Cannot reproduce. If you need help, post below please.
