### ISSUE TITLE
Suggestion - Rewards

### ISSUE THREAD

**Issue by harry0198** [kangarko/Boss#159]
I am unsure really where to put this so I thought I'd put it here and it might get considered properly than if it was put in the discord or somewhere.

To give rewards to players for killing a boss is REALLY hard and now I think impossible in 1.13. In 1.12 I had to make a command using &a[r=250 x=236 y=80 z=80] or something ridiculous so I think there should be placeholders for general players in an area or attacking the boss or the top 3 players that do the most damage to the boss. Or in general something along those lines! Placeholders would be nice as it would allow for easy reward giving for commands ( such as /eco give %top_3_players% 10000 )

The main thing I'm asking is the ability to give rewards to people who are fighting the boss... rather than the whole server. (if I used @a to represent the players) 

Thanks for reading! Hope you really take this into thought or respond saying it's already in the game! Thank you

**Comment by kangarko** [comment]
Hey, we are planning to include a better reward system soon! Thank you for your suggestion, I think you will benefit from it.
