### ISSUE TITLE
[Question] Can i teleport a player after kill a Boss?

### ISSUE THREAD

**Issue by AconTM** [kangarko/Boss#16]
Hi! I will buy this Plugin if it can do what i want ^^ Is it possible after 
killing a Boss to teleport the Player away? Because i have a special Map
only for the Boss & after the Boss dies i woud like to teleport players to
the Spawn.. I have special items for fighting the Boss, so it´s not the point
to kill the Boss more than 1 times or waiting for Spawning :/

Hope you understand my bad English^^ 

- AconTM

**Comment by kangarko** [comment]
Hello!

Yes it is! Once you create your boss, open its configuration file, for example plugins/Boss/bosses/Warrior.yml (in case your boss' name is Warrior).

Then, find the Death.Commands section and set there the command you wish to execute - in your case - the /spawn command like this:

```
Death:
  Commands:
    - spawn {killer}
```
