### ISSUE TITLE
Drop Ietms

### ISSUE THREAD

**Issue by BenRulez** [kangarko/Boss#164]
Not sure if this is already a thing or not, if it is i cant find it.
You should make it so your able to set it so each boss can only drop 1 of the specified items it drops on death.

**Comment by kangarko** [comment]
Hey, do you mean 1 piece of each item in the Drops menu or only 1 item from that menu?

**Comment by BenRulez** [comment]
Only 1 of the items from the menu, so if you put a diamond with 50% and an iron with 50% the player will only get 1 or the others not both

**Comment by kangarko** [comment]
Should we respect the chances in percent and not drop anything if they fail, or make sure to always drop 1 item?

**Comment by BenRulez** [comment]
Probably respect the percent, so if 1 item has 20% and another 10% it will drop either nothing, the first item OR the 2nd item

**Comment by kangarko** [comment]
Got you. Currently we are not taking suggestions but I am leaving this open to add in

**Comment by kangarko** [comment]
Will be implemented
