### ISSUE TITLE
Interested in buying, have a question

### ISSUE THREAD

**Issue by Devillion** [kangarko/Boss#169]
I want to use eggs to spawn boss mobs in certain world guard regions. Can I do this with your boss plugin? Can I set it to block the egg from being used unless in a specific region?

**Comment by kangarko** [comment]
Hey,

I believe yes. You can give players the permission to use spawn eggs once they enter the region and remove it once the leave it, see https://github.com/kangarko/Boss/wiki/Common-Issues#is-it-possible-to-let-bosses-spawn-if-you-enter-a-region
