### ISSUE TITLE
Problems with Boss plugin

### ISSUE THREAD

**Issue by sirben99** [kangarko/Boss#17]
Hey. I reasently bought your pluging Boss becose it looked very promesing for me. It had a very good rewies and i was amazed with the customation abilities that this plugin had to offer to its other "create your own bosses plugins". But when i test it it ingame, i have to say that im very dissapointed to what this plugin has to offer. Heres the things i am dissapointed with

- In the equipment menu i can only add or remove drop chanches ny 5%. It isnt possible to set the drop rate you realy want/need (e.g 1%)

- In the skills menu it isnt possible to edit skill settings ingame (e.g right clicking a skill would pring up the skill settings)

- I cant edit the skills for a surtean boss. I have to edit them globally witch is a very big letdown.

- The boss config file doesent show what the boss drops or its equirment meaning if i wanted to edit the drop rates manualy from config i cant.

- In the drops section there is a same problem as noted above. You can only change the prosent by 5. If i wanted to add a very rare drop that drops at 1 prosent, i cant do that.

- In the reinforsments after death i cant add any vanilla mobs. it would be nice to be able to add vanilla mobs along also (I know there is a skill for that but after death would be nice)

- In the natural spawning section i can only add/remove the spawning in worlds by 2%. it is possible to do in the comfig but this should be difrent

- There is no option for a biome spesifict spawning. If i wanted to spawn my boss naturaly in only the plains biome, i cant do that.

Conclusion: Boss was indreducts as a boss making plugin that would beat it alternative plugins but with the lack of options and confurgation ingame and in the config files isnt worth the price.

Im sorry for my poor english. I would like to request a refound for this product. I hope these reasons are good enought. If they arent, i would love to see these features added/fixet so more players like (possibly) woudnt get dissapointed.

Ben

**Comment by kangarko** [comment]
PM'd.
