### ISSUE TITLE
worldguard 1.13, worldedit 1.13 and boss issues with them

### ISSUE THREAD

**Issue by eclipcen** [kangarko/Boss#171]
the current stable release of worldedit https://dev.bukkit.org/projects/worldedit , does not work with 1.13
the latest worldedit release works with 1.13 but doesnt work with the latest stable release of worldguard
https://dev.bukkit.org/projects/worldguard , and only the latest dev build (7.0.0) of both worldedit and worldguard work with 1.13 and with eachother, but boss does not work with the latest dev builds of worldguard which makes timed spawnings/region not work : https://pastebin.com/nj1pqBAj

**Comment by kangarko** [comment]
Try with these dev WorldEdit and WorldGuard builds:

http://builds.enginehub.org/job/worldedit/10408/download/worldedit-bukkit-7.0.0-SNAPSHOT-dist.jar
http://builds.enginehub.org/job/worldguard/10409/download/worldguard-legacy-7.0.0-SNAPSHOT-dist.jar
