### ISSUE TITLE
Plugin wont load 

### ISSUE THREAD

**Issue by LegendCObra** [kangarko/Boss#176]
I am using spigot 1.8.8 and when i try typing command /boss help or any commands nothing is working what do i do

**Comment by kangarko** [comment]
Hello,

Please post me your startup log uploaded to pastebin.com

Also, is the plugin displayed green in the /plugins list?

**Comment by LegendCObra** [comment]
It worked but not fully like menu is broken to edit the features are of
bosses

**Comment by kangarko** [comment]
Any console errors? What do you mean by "broken". Please provide more information on how to reproduce.

**Comment by LegendCObra** [comment]
Yes there is console errors and what I mean is I try click to boss menu and
says plz contact administrator for console for error  but I looked and
there was nothing it could help me but I tried plugin on seperate server do
you have discord

**Comment by kangarko** [comment]
Post me the console errors. If unsure, start server, open the menu, and post me the full console log.

**Comment by kangarko** [comment]
Use PaperSpigot 1.8.8 from https://papermc.io/ci/job/Paper/443/ instead of your distribution, that is lacking proper APIs. All plugins are compatible.

**Comment by LegendCObra** [comment]
So what do I do with do I change it isntead of my spigot or do I just add
it in I never used before

**Comment by LegendCObra** [comment]
Your idea worked
