### ISSUE TITLE
Heroes.

### ISSUE THREAD

**Issue by JTGgamer** [kangarko/Boss#177]
Think this is based of your plugin, the bosses give a stupid amount of hero xp and i need to change it as well as this it is running an error in console: https://pastebin.com/xH81EGs0

**Comment by kangarko** [comment]
It says an entity was assigned HP 586,657 when the limit is 2048. ZIP me your Boss/ folder please.

**Comment by JTGgamer** [comment]
It have only checked the Haunted soul, but after more testing it only seems to give the insane amount of hero exp when in a boss zone (naturally spawned).

**Comment by JTGgamer** [comment]
Hello?

**Comment by jascotty2** [comment]
Just a question - that error that you have in the pastebin is from a plugin named "Heroes" - are you certain that that plugin is not conflicting in some way?
(If you disable the Heroes plugin, does the problem still happen?)

**Comment by JTGgamer** [comment]
the problem isn't the plugin itself, its the amount of heroes exp the bosses give when they die, i was hoping for support

**Comment by kangarko** [comment]
I could not reproduce the problem.

Please remove Heroes to see if the problem persist and comment below. I strongly err on the side that this is unrelated to Boss and caused by either server's configuration or most likely that plugin.
