### ISSUE TITLE
Healthbar

### ISSUE THREAD

**Issue by Nakronym** [kangarko/Boss#178]
**Dear Support,**

I was looking for a way to set a healh bar above the boss but I couldn't find anything. I think that might be very usefull in case you got a whole bunch of bosses in your world and each of them has a different health so let's say you got the "Weak Bosses" "Normal Bosses" "Hard Bosses" and so on. Based on the health the player can decide if he is willing to attack the boss nor not.

That's my little suggestion for you.

Yours Sincerely, 

**Nakronym**

**Comment by kangarko** [comment]
Hey,

thank you for your suggestion. At present we have the action bar displaying a Boss health, and we are not planning to make the health above his head because that would hide his name. You can give the boss a name "Weak Boss" ... "Hard Boss" anyways.
