### ISSUE TITLE
Bossess spawning conditions are wrong

### ISSUE THREAD

**Issue by SoraShiunin** [kangarko/Boss#179]
Since the new update *1.7.1.1* and MC 1.12.2, bosses have been acting weird. Some nether only world bossess spawn in the overworld and thunder and rain only monsters are always spawning in.
magmoo, nether only boss spawning in the overworld anywhere.
thunderghast thunder only monster spawning in always.
![screenshot_1011](https://user-images.githubusercontent.com/23641964/46904702-df5dc880-cee8-11e8-89e7-7e05de88aba6.png)

Spawn chances don't seem right. Nothing changes from 1% chance and 50% chance, the number of spawns is roughly the same.

https://github.com/kangarko/Boss/issues/158 . Also this issue is now worst. Now some aggressive mobs spawn in areas they shouldn't like the spawn area, not just the mounts and they start using their powers agaisn't players.
![screenshot_1012](https://user-images.githubusercontent.com/23641964/46904700-d7058d80-cee8-11e8-9b47-72557dc3a70a.png)

**Comment by SoraShiunin** [comment]
Im on normal spigot 1.12.2.
[Boss.zip](https://github.com/kangarko/Boss/files/2475410/Boss.zip)

**Comment by SoraShiunin** [comment]
Looks like the new boss i made for halloween Pumpko doesn't spawn in the overworld. Neither does an old boss named Savage Blaze.

**Comment by jascotty2** [comment]
I'm having some trouble getting the issue to reproduce.
Can I jump on your server to have a look at how you're using it and where the errors are happening?

**Comment by SoraShiunin** [comment]
Yes.

**Comment by kangarko** [comment]
@jascotty2 have you been able to reproduce?

**Comment by kangarko** [comment]
Set Debug to [spawning] in settings.yml and post the console spammy messages. There should be a lot of them so you can only select the ones related to the Boss you are having issues. Also please re-attach your Boss ZIP file with the new bosses.

Closing until your response.
