### ISSUE TITLE
[Question] Bossrooms possible?

### ISSUE THREAD

**Issue by AconTM** [kangarko/Boss#18]
Hey,

i have buy this Plugin yesterday and it works fine! But i have now a big Problem!
How can i make Bossrooms like:

Room1 = Boss1 | every 40 seconds spawn | Max 1 boss from this type
Room2 = Boss2 | every 40 seconds spawn | Max 1 boss from this type
Room3 = Boss3 | every 40 seconds spawn | Max 1 boss from this type
Room4 = Boss4 | every 40 seconds spawn | Max 1 boss from this type
Room5 = Boss5 | every 40 seconds spawn | Max 1 boss from this type

Is it possible? pls help me :/

**Comment by AconTM** [comment]
Here is the old plugin wich i used for Bosses:
https://www.spigotmc.org/resources/custommobs.7339/

with this i can place "Spawners" with Spawnintervall.. Is it possible with Boss?

**Comment by kangarko** [comment]
Hey and thank you for your purchase!

You can make 5 different Boss regions with /boss region, and then assign each boss spawning to 100% in Boss>Spawning>Region>Boss menu for each region.

Also set Limits.Individual.Enabled to true and Limits.Individual.Chunk to 1.

**Comment by AconTM** [comment]
but how can i make a spawning intervall?

**Comment by kangarko** [comment]
See the section Timed_Spawning in settings.yml, here you can control the interval in the Delay option.

**Comment by AconTM** [comment]
I have make a Region, create a boss, have spawnsettings to this region changed & worlds Chance to 100%.. But nothing is spawning :/ I also changed the Config to 2 Seconds :/
