### ISSUE TITLE
Boss plugin causing massive lag spikes sometimes

### ISSUE THREAD

**Issue by SoraShiunin** [kangarko/Boss#180]
https://timings.spigotmc.org/?url=ketimodimu

Unsure if these timed spawns in console are related to boss.
![screenshot_1017](https://user-images.githubusercontent.com/23641964/46909075-f8886880-cf2c-11e8-932b-412164e24b45.png)

**Comment by kangarko** [comment]
Update Boss and turn on Async_Conditions (search your settings.yml)

**Comment by kangarko** [comment]
I also recommend using PaperSpigot instead of Spigot.

**Comment by kangarko** [comment]
Alright. Please also see this: https://github.com/kangarko/Boss/wiki/Common-Issues#boss-is-lagging-my-server

If that does not help, ZIP me your Boss/ folder.

**Comment by kangarko** [comment]
I assume the suggestions above should do, if not post the zip folder below.
