### ISSUE TITLE
Illegal reflective access operation

### ISSUE THREAD

**Issue by derkoboldi** [kangarko/Boss#182]
[16:16:38 INFO]: WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by me.kangarko.boss.final. .com3 (file:/Server/Spigot/run%201.12/plugins/Boss-1.7.14.jar) to field java.net.URL.factory
WARNING: Please consider reporting this to the maintainers of me.kangarko.boss.final. .com3
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

Maybe you have an idea about this error

**Comment by kangarko** [comment]
Try re-downloading the plugin. Also, Boss is compatible with Java 8, what is your Java?

**Comment by kangarko** [comment]
It seems your plugin still loaded, this is just a warning. Closing. If in doubt, use Java 8.
