### ISSUE TITLE
Can I spawn 1 boss and only one boss?

### ISSUE THREAD

**Issue by Yeetlord64** [kangarko/Boss#185]
I use command regions so when a player enters that region the boss will spawn, but when two players enter the region than two bosses spawn, how can I make it so even with two players entering the region it will still only spawn 1 boss?

**Comment by kangarko** [comment]
You can use Region Limits. Open the menu -> Bosses -> Your Boss -> Spawning -> Regions -> Boss Regions -> Select the region -> Open the region -> Set the limit

**Comment by Yeetlord64** [comment]
if I put the name of the boss region in CommandRegions (CR) I assume you're saying it will work?

I thought it had to be only Worldedit regions for the CR plugin to work.

**Comment by kangarko** [comment]
CommandRegions are not supported by Boss, but you can use them to execute a Boss command.

Please ZIP me your Boss/ folder.
