### ISSUE TITLE
Problem with Spawning

### ISSUE THREAD

**Issue by AconTM** [kangarko/Boss#19]
I have make a Region, create a boss, have spawnsettings to this region changed & worlds Chance to 100%.. But nothing is spawning :/ I also changed the Config to 2 Seconds :/

(This is the Post from here: https://github.com/kangarko/Boss/issues/18)

**Comment by kangarko** [comment]
Hey!

I am sorry you have issues, I believe it is caused by that you don't have any biome conditions. I will fix that.
