### ISSUE TITLE
How do players spawn Bossess with egg

### ISSUE THREAD

**Issue by LegendCObra** [kangarko/Boss#192]
Whenever I try or another person  tries to  spawn an egg it says unable to spawn the HulkGkit( which is the name of the boss) in this locations

**Comment by kangarko** [comment]
If you have enabled spawning limits in your settings.yml, probably they are exceeded, or there is another plugin blocking the spawn, such as Residence or WorldGuard.

**Comment by LegendCObra** [comment]
Also some of the abilities don’t work what do I do to fix it

**Comment by kangarko** [comment]
Can you be more specific?

**Comment by LegendCObra** [comment]
For instance mob stacker is messing up with reinforcements ability is there
way to change so it’s not the same as the boss so it doesn’t

**Comment by kangarko** [comment]
Is mob stacker another plugin? If this case, no. If not, please elaborate on what does "messing up" means.

**Comment by LegendCObra** [comment]
Yes mob stacker makes it so nerby mobs will come as one mob

**Comment by kangarko** [comment]
Sorry, we cannot control that plugin, Boss is not responsible for handling it.
