### ISSUE TITLE
Boss items won't go into inventory on death, they drop on ground [Boss v - 1.8.0]

### ISSUE THREAD

**Issue by Devee1111** [kangarko/Boss#195]
Error (stack traces): None are outputted to console. 
How to reproduce: When you kill the boss, no matter the setting on drops it won't drop into inventory, always on the ground.
Server version: 1.12.2-R0.1-Snapshot (http://puu.sh/C4K1E/c362b14ceb.jpg)
Plugins: http://puu.sh/C4K9X/0311a56e2d.png (Some are custom: KPF, Servers, InfoCommands, StaffPowers, and NickMe but none of them deal with inventories or items.)  
Boss version: 1.8.0 (http://puu.sh/C4K8q/8eb59927c9.png)
Files: [Boss.zip](https://github.com/kangarko/Boss/files/2598327/Boss.zip)
I've tried turning it off and seeing if maybe it was reversed it would go into inventory, but still no matter what it drops on the ground. When I updated boss I deleted the old .jar but I didn't change the boss folder and I'm not sure what could be wrong with the folder so I just uploaded the entire file.

**Comment by kangarko** [comment]
We will continue on PM.
