### ISSUE TITLE
Skill removale

### ISSUE THREAD

**Issue by DiamondDagger590** [kangarko/Boss#198]
Hello, there is an issue where if two of the same boss spawn, then the first boss will loose all skills and turn into a normal mob (still will drop the custom loot). Temp fix is limiting one boss spawn but if a boss is lost and never found then this fix kinda crumples.

**Comment by kangarko** [comment]
How to reproduce? Please ZIP me your Boss file

**Comment by DiamondDagger590** [comment]
I’ll grab it in a bit. And it’s as simple as one boss spawning and then another boss of the same type spawning. We only have one boss rn if that contributes

**Comment by kangarko** [comment]
I'm sorry but I can't reproduce:

![a](https://i.imgur.com/1CXdkzU.gif)

Any console errors? What is your MC version?

**Comment by jascotty2** [comment]
Issue due to how the skill timings were stored per-type, not per-entity - fixed for build 1.8.10 :)

**Comment by DiamondDagger590** [comment]
Thank you <3 Figured it was something similar. Fix is greatly appreciated
