### ISSUE TITLE
Boss region crashing server

### ISSUE THREAD

**Issue by DiamondDagger590** [kangarko/Boss#199]
Attempting to make a large region causes this

02.12 15:31:36 [Server] WARN java.lang.OutOfMemoryError: Java heap space
02.12 15:31:36 [Server] WARN at java.util.Arrays.copyOf(Unknown Source)
02.12 15:31:36 [Server] WARN at java.util.ArrayList.grow(Unknown Source)
02.12 15:31:36 [Server] WARN at java.util.ArrayList.ensureExplicitCapacity(Unknown Source)
02.12 15:31:36 [Server] WARN at java.util.ArrayList.ensureCapacityInternal(Unknown Source)
02.12 15:31:36 [Server] WARN at java.util.ArrayList.add(Unknown Source)
02.12 15:31:36 [Server] WARN at me.kangarko.boss.final. .CON.protected(SourceFile:92)
02.12 15:31:36 [Server] WARN at me.kangarko.boss.final. .A.super(SourceFile:48)
02.12 15:31:36 [Server] WARN at me.kangarko.boss.command.RegionCommand.handleSubCommand(SourceFile:90)
02.12 15:31:36 [Server] WARN at me.kangarko.boss.final. .CoM4.handleCommand(SourceFile:172)
02.12 15:31:36 [Server] WARN at me.kangarko.boss.final. .cOm4.onCommand(SourceFile:61)
02.12 15:31:36 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
02.12 15:31:36 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
02.12 15:31:36 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648)
02.12 15:31:36 [Server] WARN at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397)
02.12 15:31:36 [Server] WARN at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232)
02.12 15:31:36 [Server] WARN at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
02.12 15:31:36 [Server] WARN at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
02.12 15:31:36 [Server] WARN at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
02.12 15:31:36 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
02.12 15:31:36 [Server] WARN at java.util.concurrent.FutureTask.run(Unknown Source)
02.12 15:31:36 [Server] WARN at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
02.12 15:31:36 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
02.12 15:31:36 [Server] WARN at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
02.12 15:31:36 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
02.12 15:31:36 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
02.12 15:31:36 [Server] WARN at java.lang.Thread.run(Unknown Source)

**Comment by kangarko** [comment]
Cannot be fixed, create a smaller region. These are software limitations. Or upgrade your memory.
