### ISSUE TITLE
Throw player and other suggestions

### ISSUE THREAD

**Issue by LogGits** [kangarko/Boss#2]
Awesome plugin i have just been testing it out and i noticed that, the throw player feature throws players that are in creative and spectator. 

Also in the Spawn Conditions tab will we see a Biomes tab? I am trying to get a boss to only spawn in a specific biome. 

This may be ambitious but could you make mobs that avoid water or lava and mobs that dont care about water and lava? Even mobs that are immune to lava damage or drowning? 

Maybe even a skill called "Enderman" where the mob will randomly teleport around the player with a configurable distance e.g. 5-20 blocks.

Also could you add a chance system to the reinforcements section aswell. So it has a configurable chance of spawning reinforcements.

Is there a way to have Localization? (Similar to how it is used in ChatControl Pro and CoreArena)

**Comment by kangarko** [comment]
Hello,

**Throw Skill feature**
Will be fixed.

**Biome condition**
Great suggestion, marked!

**Avoiding water/lava**
This involves editing NMS (internal server) pathfinding. I don't have experience in that to be honest. I know in MythicMobs you can edit pathfinding, but I don't want to copy from it without fully understanding how it works.

**New Endermen skill**
Will add.

**Chance reinforcement system**
Great suggestion, marked!

**Localization**
What messages are you looking forward to translate?

**Comment by kangarko** [comment]
Closing. Regarding the localization, if there is any message regular players are viewing (not you as a developer) and you want it to be translated please let me know below.
