### ISSUE TITLE
Bugs (And a question)

### ISSUE THREAD

**Issue by sirben99** [kangarko/Boss#20]
Hey. I wanted to inform you some bugs/things that dont work right.

- Im having problems with the natural spawning in the sense that when i go to settings.yml and change the converting to false (wich i assume means that indsead of converting vanilla mobs of same type it spawns the boss on it own), the boss doesent spawn anymore. I wanted to turn this off becose i made a zombie miner that spawns 3 zombie when it dies, but if the change of the boss spawning is too high (its at 100% in the world im in and in the biome im in) one or more of the reinforsments turns in to the boss.

- This is more of a question than a bug (I assume its not a bug) but is it possible that when you only put the world change (e.g 50%) it will spawn in all of the biomes in 50% without you touching to the biomes and set every one indevitsualy

- In the drops menu after the boss dies you cant go pass 52% in the GUI when you have quantity of 1% selected

**Comment by kangarko** [comment]
Hello!

Sorry for a late reply, I have answered it below:

* Would you like to disable "Converting" vanilla mobs into Bosses, while having Timed_Spawning enabled? From my testing, this is not the case and Timed_Spawning still works. How are the Bosses not spawned anymore?
* If you have all biomes enabled = no biomes selected in the Biomes menu, then world chance will apply just as you asked.
* I have fixed that!

**Comment by sirben99** [comment]
Hey. Sorry for the late response. I had timed spawning false in the config file because i thought the custom mobs would start spawning with a percent that i set in the world spawning (I dint want to set them spawning in sertain time periot e.g every 90 sec). I dont know did i undrestand your anser nor the problem im having (If it is a problem im kinda confused). But thank you for your answering my questions and fixing things!

**Comment by kangarko** [comment]
Cheers! Timed_Spawning is a task that Boss runs manually, and Converting happens naturally when your server spawns mobs as per the game rules.
