### ISSUE TITLE
Spawn minions not spawning anything

### ISSUE THREAD

**Issue by Vehzx** [kangarko/Boss#204]
Hi, everything with the new updated has fixed timed spawning and everything is setup correctly and working for me.

One issue, the spawn minions ability doesn't do anything, when fighting the boss the messages appear in chat "Say hello to your new friends {name}" but nothing is spawned. I made sure my worldguard region allows mob spawning and I even tried this outside of a claimed area with worldguard (the wild, no claims) yet still nothing.

Any ideas on how to fix this would be great.

Also, I had an issue with the boss region plugin selector. I can create regions with the boss region tools and apply them, but it seems nothing is spawned with the timed spawn? I ended up fixing this by just using a worldguard region instead but using the boss region tool would be way easier. I also think when a worldguard region is made, and a boss region claim is made inside that worldguard reigon, the boss will not spawn unless both regions are set to allow spawning. (This becomes an issue for people wanting to make a circle arena for example where they want the boss to spawn) as it is easy to just make a cube claim around the arena with worldguard to stop players breaking the area, but if you enable boss spawning there the boss just spawns outside of the arena since the claim goes outside slightly in the corners.

Anyways thats not a huge issue just a Quality Of Life fix i guess, but the spawning minions just doesn't work as far as i'm aware.

**Comment by kangarko** [comment]
Hey,

the next version will bring the region fixes, please test it out and report if you still experience the issue. If still, than post your entire Boss folder in a ZIP so we can reproduce the problem ;)

Thanks,
Matej

**Comment by Vehzx** [comment]
Not sure if by the next version you meant 1.8.9. But I just updated and tried fighting the boss, but still the same issue, the chat says "Dreevus has spawned reinforcements" yet still nothing is spawned. If this was the update that was supposed to fix this then below is my entire boss folder.

https://drive.google.com/open?id=1Yr_tw5GXbQgFZV_QXir2dROxMTmbDzAk

**Comment by jascotty2** [comment]
Issue due to how the minion skill was checking for space to spawn - fixed for 1.8.10 :)
