### ISSUE TITLE
Suggestion: Placeholders?

### ISSUE THREAD

**Issue by Vehzx** [kangarko/Boss#205]
Potential addition of placeholders? I couldn't find online any currently, I know {boss} displays the boss name in bossname.yml files, but maybe one for player names? This could allow for broadcasts on a boss death with something like "{player} has slain {boss}" or something along the lines of that.

**Comment by kangarko** [comment]
Hey,

currently, you can use the {killer} placeholder to display the name of the killer, if any. Many placeholders about the player are scheduled as a future update in the roadmap. 

Best,
Matej
