### ISSUE TITLE
Spawning issue with worldguard?

### ISSUE THREAD

**Issue by Vehzx** [kangarko/Boss#206]
I'm not too sure what's causing this honestly, I already have a boss setup and running fine, I made a second worldguard region in the sky where I pasted my cube box to put the boss inside of. I made an enderman boss, but after realising it wouldn't spawn tried many other types of mobs, I even copy and pasted the current boss I had and just changed the name so it had the exact same conditions and yet it will not spawn inside the region. I made sure the worldguard region had the exact same settings and the other region that is working and yet still no spawning. I am really at a dead end here and have no idea what to do, I tried changing stuff around for hours and trying everything I could think of and have managed nothing :/

**Comment by jascotty2** [comment]
Please provide a copy of your Boss and WorldGuard config folders, and I can see what I can do to help you troubleshoot.

You may also message me on Spigotmc: https://www.spigotmc.org/members/jascotty2.3571/ )

**Comment by jascotty2** [comment]
Resolved with build 1.8.8 :)
