### ISSUE TITLE
Boss spawning issue

### ISSUE THREAD

**Issue by ultrapunisher97** [kangarko/Boss#207]
I have created 7 different bosses that I want to spawn in a specific location once a week. Basically each day at this location there will be a new boss battle with a new boss. So each boss should spawn here once a week. I know the command to force it to happen. However since I don't use multicraft making a scheduled task such as this is a very complicated thing to do. No plugin really offers what I want. I've been spawning them manually and it's awful. The spawning features you guys offer does not offer the one thing I want. If you could add that. 10/10 plugin. Thx.

**Comment by kangarko** [comment]
We can look into adding special "spawners" that you can place on the ground as a block and they would spawn bosses at a certain interval, would that help?

In the meanwhile, you can try using https://www.spigotmc.org/resources/mc-cron-schedule-anything-event-jobs.37632/ plugin to see if it helps your needs.

**Comment by kangarko** [comment]
Added
