### ISSUE TITLE
Boss spawning with Towny

### ISSUE THREAD

**Issue by Vehzx** [kangarko/Boss#209]
I have created a towny region over a boss arena I built to stop others from claiming it with their own town. The claim is an outpost claim (which I don't think should have an affect on how the boss spawns) but when enabling the towny region aswell as the worldguard region in the boss settings. It attempts to spawn and the lightning strikes as if the boss is going to spawn but then nothing happens. When I try to spawn the boss with a boss spawn egg it says "Unable to spawn Skeletal in this location".

**Comment by kangarko** [comment]
Hey,

Boss listens to the "creature spawn event" that may be cancelled by any other plugin. This is to respect third party compatibility. You need to check if you have monster spawning disabled in each of these plugins in the region, and disable that restriction.

You can enforce Boss to spawn by setting Egg_Spawning.Check_Regions to false and testing whether it works now by manual Egg Spawn.

**Comment by Vehzx** [comment]
Hey, I have fixed this and bosses are now spawning inside of the first claim.
