### ISSUE TITLE
🎈 Official Roadmap: Suggestions & Ideas

### ISSUE THREAD

**Issue by kangarko** [kangarko/Boss#21]
This roadmap has been closed, refer to the new one please.

**Comment by kangarko** [comment]
Sorry I don't understand what you mean, each Boss has its own configuration file, and you can use Region Spawning to limit the spawn of each Boss to only 1 at a time.

**Comment by mibby** [comment]
> you can use Region Spawning to limit the spawn of each Boss to only 1 at a time.

Interesting. I never knew this was possible. How would I go about doing this?

**Comment by kangarko** [comment]
You make a region via /boss region, then open /boss menu, navigate to Spawning, Regions, Boss Regions, and simply left click the created region to open its settings. This was not possible before actually and was added some time ago.

**Comment by mibby** [comment]
Would it be possible to implement an option to auto-retarget (aggro) a player if a boss is hit by an entity (arrow/fireball/etc), regardless of distance set in the config?
