### ISSUE TITLE
Console Spam with EpicWorldGen

### ISSUE THREAD

**Issue by DiamondDagger590** [kangarko/Boss#210]
When using EpicWorldGen (none of the custom biomes are added in the spawn biomes) with the latest build, I get this spam

10.12 20:07:19 [Server] WARN Received invalid biome id 110
10.12 20:07:19 [Server] WARN Received invalid biome id 110
10.12 20:07:19 [Server] WARN Received invalid biome id 110
10.12 20:07:19 [Server] WARN Received invalid biome id 110
10.12 20:07:21 [Server] WARN Received invalid biome id 110
10.12 20:07:21 [Server] WARN Received invalid biome id 110
10.12 20:07:21 [Server] WARN Received invalid biome id 110
10.12 20:07:22 [Server] WARN Received invalid biome id 110
10.12 20:07:22 [Server] WARN Received invalid biome id 110
10.12 20:07:22 [Server] WARN Received invalid biome id 110
10.12 20:07:22 [Server] WARN Received invalid biome id 110
10.12 20:07:22 [Server] WARN Received invalid biome id 110
10.12 20:07:23 [Server] WARN Received invalid biome id 110
10.12 20:07:23 [Server] WARN Received invalid biome id 110
10.12 20:07:23 [Server] WARN Received invalid biome id 110
10.12 20:07:23 [Server] WARN Received invalid biome id 110

There are various ids but its the same occurrence and only happened post update from version .6 to .10

  Biomes:
    EXTREME_HILLS_WITH_TREES: 2%
    REDWOOD_TAIGA_HILLS: 2%
    TAIGA_COLD: 2%
    FROZEN_OCEAN: 5%
    MUTATED_EXTREME_HILLS: 2%
    FROZEN_RIVER: 5%
    ICE_MOUNTAINS: 5%
    TAIGA_COLD_HILLS: 2%
    MUTATED_ICE_FLATS: 4%
    SMALLER_EXTREME_HILLS: 2%
    REDWOOD_TAIGA: 2%
    ICE_FLATS: 5%
    EXTREME_HILLS: 2%

Biomes Allowed

**Comment by DiamondDagger590** [comment]
Appears to happen infrequently with version .6 as well but it happened all the time with .10

**Comment by kangarko** [comment]
There is no such biome with id 110, see https://minecraft.gamepedia.com/Biome

I don't see how Boss can create this warning in EWG, please contact its author for further explanation and possible hiding of this message.

We do not use IDs in Boss as they were removed in 1.13

**Comment by DiamondDagger590** [comment]
Apparently I had the wrong plugin xD We use OpenTerrainGenerator

**Comment by kangarko** [comment]
Alright I consider this issue solved.
