### ISSUE TITLE
Clearlagg with Boss Mobs

### ISSUE THREAD

**Issue by tjelano** [kangarko/Boss#211]
Hello,

I would like to know if it was possible to remove Boss mobs with the plugin Clearlagg. I didn't know if it was appropriate to ask help on the Boss page since I'm technically asking help for the Clearlagg plugin.

Anyways... is this actually possible or should I start using another clearlagg plugin? If so would you be so kind as to suggest one that supports Boss or would make it possible to do what I want it to do.

Kind Regards,

Tjelano

**Comment by kangarko** [comment]
Hey,

most likely it is not if ClearLagg ignores entities that are named. I highly recommend using the /boss butcher command or limiting the max. amount of Bosses instead. When you remove named entities by another plugin, you may also loose your named pets etc.
