### ISSUE TITLE
Not an issue but..

### ISSUE THREAD

**Issue by EricColland** [kangarko/Boss#212]
Is there any way that we can customize certain messages (such as skill messages)? I want to customize some of the messages that are sent out when the skills (e.g. throwing a fireball) is done.

**Comment by BlackGamer000** [comment]
In the Folder of Boss it should be a Folder called Skills (or something). In that Folder there are all the Skills in .yml files.

**Comment by EricColland** [comment]
Ah, thanks! Didn't notice it.
