### ISSUE TITLE
Linking Bosses to DungeonsXL

### ISSUE THREAD

**Issue by Dave5080** [kangarko/Boss#213]
DungeonsXL is a great open source plugin I started use for my server a few weeks ago. It offers a set of incredible tools in order to quickly implement instaanciable worlds called DUNGEONS. In my dungeons I should set a few Bosses of course. Now, since this plugin offers great compatibilities to most of the Boss deployment's plugin, I was wondering if it were possible to make this two plugins combatible with each others. I'm going to open the same issue  on both plugins pages cause I don't know which one has to move the first step. Greetings.

**Comment by kangarko** [comment]
Hey,

as much as I love developing new, amazing features, I cannot take any more features at this time.

PS: You can somewhat integrate Boss into anything following this question and the one below that: https://github.com/kangarko/Boss/wiki/Common-Issues#can-i-spawn-bosses-individually-at-a-certain-time
