### ISSUE TITLE
Currently getting this error in my error.log

### ISSUE THREAD

**Issue by Vehzx** [kangarko/Boss#214]
------------------------------------[ 20.12.2018 23:41:48 ]-----------------------------------
Boss 1.8.11 encountered a NullPointerException
Running CraftBukkit 1.13.2-R0.1-SNAPSHOT and Java 1.8.0_191
Plugins: dynmap v3.0-beta-2-138, WorldEdit v7.0.0-beta-03;b192466, PluginConstructorAPI v1.0.49, CrazyCrates v1.8.4, redclockdetector v23, Essentials vTeamCity, LogBlock v1.13.2-SNAPSHOT (build #384), BlockLocker v1.5, ClearLag v2.9.7, Boss v1.8.11, WorldBorder v1.9.0, MessageAnnouncer v1.9.1, Votifier v1.9, KillStreaks v1.4.0, SilkSpawners v1.6, ProtocolLib v4.4.0, ActionPoints v1.6.0, WorldGuard v7.0.0-beta01;01dfebe, AdvancedPortals v0.0.49, SignEdit v1.9.3, ReportSystemReloaded v2.0, EssentialsChat vTeamCity, PermissionsEx v1.23.4, mcMMO v1.6.0-SNAPSHOT, PHPUltraV4 v4, Vault v1.7.1-b91, EssentialsSpawn vTeamCity, ID-Library v[2.1.0.0], ChatManager v3.3.0, TitleManager v2.1.3, MiniaturePets v2.1.2, PlayerMention v3.7, GChestShop v[3.1.1.0], Rankup v1.3, Towny v0.93.0.0, HolographicDisplays v2.3.1, BuycraftX v11.0.0, CommandSigns v1.6.8, Envoys v4.6.0, TownyChat v0.53, DiscordSRV v1.16.4, TownyNameUpdater v2.0, SuperbVote v0.5.3, CombatLogX v9.2.1.0, FlightControl v2.1
----------------------------------------------------------------------------------------------

More Information: 
Error making a Boss!
Entity: CraftSkeleton
Boss: AssassinSkeleton
%error
NullPointerException (Unknown cause)
	 at me.kangarko.boss.final. .a.protected(SourceFile:863)
	 at me.kangarko.boss.final. .AUx.transient(SourceFile:176)
	 at me.kangarko.boss.final. .AUx.spawn(SourceFile:130)
	 at me.kangarko.boss.final. .bD.transient(SourceFile:164)
	 at me.kangarko.boss.final. .bD.protected(SourceFile:46)
	 at me.kangarko.boss.final. .bA.run(SourceFile:51)
	 at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81)
	 at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:391)
----------------------------------------------------------------------------------------------

------------------------------------[ 20.12.2018 23:41:48 ]-----------------------------------
Boss 1.8.11 encountered a NullPointerException
Running CraftBukkit 1.13.2-R0.1-SNAPSHOT and Java 1.8.0_191
Plugins: dynmap v3.0-beta-2-138, WorldEdit v7.0.0-beta-03;b192466, PluginConstructorAPI v1.0.49, CrazyCrates v1.8.4, redclockdetector v23, Essentials vTeamCity, LogBlock v1.13.2-SNAPSHOT (build #384), BlockLocker v1.5, ClearLag v2.9.7, Boss v1.8.11, WorldBorder v1.9.0, MessageAnnouncer v1.9.1, Votifier v1.9, KillStreaks v1.4.0, SilkSpawners v1.6, ProtocolLib v4.4.0, ActionPoints v1.6.0, WorldGuard v7.0.0-beta01;01dfebe, AdvancedPortals v0.0.49, SignEdit v1.9.3, ReportSystemReloaded v2.0, EssentialsChat vTeamCity, PermissionsEx v1.23.4, mcMMO v1.6.0-SNAPSHOT, PHPUltraV4 v4, Vault v1.7.1-b91, EssentialsSpawn vTeamCity, ID-Library v[2.1.0.0], ChatManager v3.3.0, TitleManager v2.1.3, MiniaturePets v2.1.2, PlayerMention v3.7, GChestShop v[3.1.1.0], Rankup v1.3, Towny v0.93.0.0, HolographicDisplays v2.3.1, BuycraftX v11.0.0, CommandSigns v1.6.8, Envoys v4.6.0, TownyChat v0.53, DiscordSRV v1.16.4, TownyNameUpdater v2.0, SuperbVote v0.5.3, CombatLogX v9.2.1.0, FlightControl v2.1
----------------------------------------------------------------------------------------------

More Information: 
Error making a Boss!
Entity: CraftSkeleton
Boss: MageSkeleton
%error
NullPointerException (Unknown cause)
	 at me.kangarko.boss.final. .a.protected(SourceFile:863)
	 at me.kangarko.boss.final. .AUx.transient(SourceFile:176)
	 at me.kangarko.boss.final. .AUx.spawn(SourceFile:130)
	 at me.kangarko.boss.final. .bD.transient(SourceFile:164)
	 at me.kangarko.boss.final. .bD.protected(SourceFile:46)
	 at me.kangarko.boss.final. .bA.run(SourceFile:51)
	 at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81)
	 at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:391)
----------------------------------------------------------------------------------------------

**Comment by kangarko** [comment]
Thanks, please use the next version coming up tonight.
