### ISSUE TITLE
Suggestion: Use of worldguard __global__ region

### ISSUE THREAD

**Issue by Vehzx** [kangarko/Boss#215]
Hi, I was wondering if it is possible to add functionality to __global__ region for worldguard. This is the default global region for changing a worldguard setting for the entire minecraft world.

If boss could use this it would be helpful because for some of the bosses I could limit how many spawn in the world. As far as i'm aware I couldn't find any way of doing it with the current version.

Maybe once creating a boss and having worldguard installed, the __global__ region is automatically in the boss spawning menu for the boss you create.

**Comment by kangarko** [comment]
Hey,

I am sorry to disappoint you but due to plugin limitations it is actually not possible to search for regions starting with "__", that includes your mentioned regions.

Thanks you for your understanding.
