### ISSUE TITLE
Console Spam w/ invalid biome

### ISSUE THREAD

**Issue by DiamondDagger590** [kangarko/Boss#216]
When using OpenTerrainGenerator (none of the custom biomes are added in the spawn biomes) with the latest build, I get this spam

10.12 20:07:19 [Server] WARN Received invalid biome id 110
10.12 20:07:19 [Server] WARN Received invalid biome id 110
10.12 20:07:19 [Server] WARN Received invalid biome id 110
10.12 20:07:19 [Server] WARN Received invalid biome id 110
10.12 20:07:21 [Server] WARN Received invalid biome id 110
10.12 20:07:21 [Server] WARN Received invalid biome id 110
10.12 20:07:21 [Server] WARN Received invalid biome id 110
10.12 20:07:22 [Server] WARN Received invalid biome id 110
10.12 20:07:22 [Server] WARN Received invalid biome id 110
10.12 20:07:22 [Server] WARN Received invalid biome id 110
10.12 20:07:22 [Server] WARN Received invalid biome id 110
10.12 20:07:22 [Server] WARN Received invalid biome id 110
10.12 20:07:23 [Server] WARN Received invalid biome id 110
10.12 20:07:23 [Server] WARN Received invalid biome id 110
10.12 20:07:23 [Server] WARN Received invalid biome id 110
10.12 20:07:23 [Server] WARN Received invalid biome id 110

There are various ids but its the same occurrence and only happened post update from version .6 to .10

Biomes:
EXTREME_HILLS_WITH_TREES: 2%
REDWOOD_TAIGA_HILLS: 2%
TAIGA_COLD: 2%
FROZEN_OCEAN: 5%
MUTATED_EXTREME_HILLS: 2%
FROZEN_RIVER: 5%
ICE_MOUNTAINS: 5%
TAIGA_COLD_HILLS: 2%
MUTATED_ICE_FLATS: 4%
SMALLER_EXTREME_HILLS: 2%
REDWOOD_TAIGA: 2%
ICE_FLATS: 5%
EXTREME_HILLS: 2%

**Comment by kangarko** [comment]
Hey,

what makes you suspect Boss from causing this message? We are not injecting any custom biome, only iterating through existing ones using the official API in Bukkit.

Still, I recommend you contact the author of that plugin.
