### ISSUE TITLE
change drop quantity and skill not work

### ISSUE THREAD

**Issue by SeanWalk** [kangarko/Boss#219]
the latest version doesn't have button to change drop chance by 20% 、 10% 、5%.
if i want set the chance to 10% , i need click 40 times to reduce the chance. it's really inconvenient. 

And i have no idea why boss skill usually Invalid.
no any error in console. just doesn't work.
Some version is good. some version is broken.

i'm using paper 488 and latest boss now

**Comment by kangarko** [comment]
Hey,

sorry for the delay, I added back the "edit quantity" button.

What do you mean by "Invalid" ? You can answer below

**Comment by SeanWalk** [comment]
umm I set the skill true and boss never use it . Anytime any boss.

**Comment by kangarko** [comment]
Set Delay of each of the skill file to a smaller number like 5-15 seconds.

Use latest Boss and set Debug to "[skills]" in settings.yml and restart. Observe your console output for any weird messages.

If problem still persists, comment below.
