### ISSUE TITLE
Feature Request: Spawn a custom mob without saving it (one-time-spawns)

### ISSUE THREAD

**Issue by MatheweB** [kangarko/Boss#22]
I was wondering if you could add a feature to simply create a mob and spawn it without saving it as a boss? Like a "make your creature" gui that then gives you an egg to spawn it without saving it to the boss database.

Thanks!

**Comment by kangarko** [comment]
Hey!

Thank you for your suggestion! Unfortunately there are two things blocking me from doing this: the way Boss works deeply inside, and my exams very soon :) I am closing this. Thank you for your understanding.
