### ISSUE TITLE
Suggestion: aSkyblock Support

### ISSUE THREAD

**Issue by EricColland** [kangarko/Boss#221]
I prefer these bosses to be spawned on player's islands, because, why not? They can build their own arenas and fight from there.
However, the boss doesn't reappear once it falls into the void - so I suggest a feature where there is an option where if the boss falls into the void, it reappears back on land.
Thanks!

**Comment by EricColland** [comment]
in my particular scenario, by "falling into the void" - falling off the island.

**Comment by kangarko** [comment]
Hey, I understand that would be a great suggestion, but currently I do not have the resources nor time to add it, sorry about that
