### ISSUE TITLE
Don't let bosses target NPCs

### ISSUE THREAD

**Issue by SoraShiunin** [kangarko/Boss#222]
Title.
Could it be made so Bosses AND Skills don't target Citizens ?(https://www.spigotmc.org/resources/citizens.13811/)

They keep kidnapping NPCs with the teleport skill lol and trapping them with web.

**Comment by kangarko** [comment]
Hey, I am not planning to include this right now, but I can leave this open for the future

**Comment by kangarko** [comment]
This was added some time ago actually
