### ISSUE TITLE
No Global Lightning Sound & Rideable Horses From Mobs

### ISSUE THREAD

**Issue by farisjaclyn** [kangarko/Boss#223]
Hello, I am loving the BOSS plugin. I have a small suggestion for the lightning sound feature.

I'm noticing that if you have the lightning enabled (monster attack, death, skill, spawn, etc) all players online hear a thunder sound. The thunder sound can become annoying because it is heard by everyone online on the server. I'm wondering if this can be fixed within the settings or if the thunder could be enabled to a range mode?

Thank you

**Comment by farisjaclyn** [comment]
Additionally,

My players love rideable horses espeicaly zombie horses and skeleton horses. We are enjoying the fact that we can get rideable zombie horses from the mobs. However, the only way I can get the zombie horses to be rideable is to give the mob levitation and then take it away. The mob jumps off of the rideable zombie horse (or skeleton horse) and makes it rideable for a player. That's amazing! I understand that's not it's intended use but, I'm wondering if there can be an option to allow the player to keep the rideable animal after the mob is killed? Love the plugin!


![zombie horse](https://user-images.githubusercontent.com/46360512/50719182-1a8e1480-105e-11e9-8429-eddde2de1250.png)

**Comment by kangarko** [comment]
Thank, leaving as open suggestion.

For your other question, you can toggle that in Settings -> Riding menu for your Boss, see below:

![a](https://i.imgur.com/djLpsXH.png)

**Comment by kangarko** [comment]
Thank you for suggesting that as well, however that's not possible within the vanilla game, I can check if we can implement it but that would come later as it requires some hacky coding outside of the regular api.

**Comment by farisjaclyn** [comment]
Thank you Kangarko I appreciate the response and effort.

**Comment by kangarko** [comment]
Will be partially implemented for horses if the API allows it.
