### ISSUE TITLE
Sounds with ProtocolLib not working

### ISSUE THREAD

**Issue by Zerzav** [kangarko/Boss#224]
Hello! When I try to add a mob sound to a specified mob using the following CC sound List: https://www.spigotmc.org/wiki/cc-sounds-list/
I will get an error message saying that I must use a sound from the link.
I am unsure if this is a bug or something but I have yet to really be able to use this feature and get it working.
I am currently hosting a server that is on version 1.13.2 if that may be the cause to anything.

Any help is much appreciated!

**Comment by Zerzav** [comment]
Edit: Some sounds work from the list but don't seem to actually do anything/change the mob noises.

**Comment by kangarko** [comment]
The lists is not yet updated to 1.13, you find the latest names at https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html

Also, it only works on the sounds the Boss already emits, and these are the only sounds you can change.
