### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by Nedjii** [kangarko/Boss#228]
Hello, i'm not able to make any permission working, i'm using luckperms, i give the perm written in the chat but it does nothing.

**Comment by kangarko** [comment]
Hey, what permission are you talking about? For commands, also try giving the generic "boss.command" permission alongside with the command-specific one.

**Comment by Nedjii** [comment]
No matter what i do any permission is working, i also tried giving myself (op) negative permission but i'm still able to use the command. i need to be op to use any of the plugins's command, i also tried giving every command noticed is the wiki to my alt player account but it does nothing !
