### ISSUE TITLE
[Suggestion] Advanced sound feature for bosses

### ISSUE THREAD

**Issue by LogGits** [kangarko/Boss#23]
This would add the ability to play sounds for bosses. The type of sounds, pitch, volume would be configurable. Not only this, we can take it a step further. Sounds caused by events/conditions. e.g. Boss health == 20%, Play sound. Boss attacks player, Play sound. Boss takes damage, play sound, etc. This would need to be really configurable. Multiple sounds for the same events/conditions. Implemented through a gui would be the best way to implement this, however, you can easily set it up to be config based feature that eventually comes to GUI.

**Comment by kangarko** [comment]
Great idea!

I am having exams right now, so all I could do is to make it hook into ProtocolLib and remap existing sounds, but I believe the possibilities are pretty big.

![amg](https://i.imgur.com/OlSJMiW.png)
