### ISSUE TITLE
How do i get this to work with corearena?

### ISSUE THREAD

**Issue by bowdyyy** [kangarko/Boss#230]
no commands are shown when I type /boss

**Comment by sirben99** [comment]
Hey! Did you try to do /boss ? or /boss menu? Are they working?

**Comment by bowdyyy** [comment]
I tried /boss and /b but I didn’t yet try /boss menu


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by sirben99** [comment]
Ah alright. You can get the commands when you tybe /boss ?
and to show the menu (where you edit and create bosses) you tube /boss menu
If you type /boss it will only show what version your running and who made the plugin.
Hope this helps!

**Comment by kangarko** [comment]
Please check your console at startup and upload me your full startup log to pastebin.com. Also check the console under executing of that command and post any errors.

Finally, zip me your entire Boss/ folder and upload to uploadfiles.io so I can reproduce under exactly the same conditions.

**Comment by bowdyyy** [comment]
Like the new title says how does it work with corearena? when I try to spawn 2 boss's enitity blazes in my arena they spawn as skeletons

**Comment by kangarko** [comment]
You had issues with 3 plugins as I remember from a direct message on Spigot, make sure to get that solved first.

Than, still check the console for any other errors related to Boss.

**Comment by kangarko** [comment]
Closing, discussion continues in the PM. So far turned out that you were using outdated WorldEdit version.

**For everyone having similar issues on Minecraft 1.13+, always make sure to use the very latest WorldEdit 7 from http://builds.enginehub.org/job/worldedit/last-successful?branch=master (download the Bukkit version).**
