### ISSUE TITLE
Reinforcement on Boss Death Bug

### ISSUE THREAD

**Issue by StoopidMeap** [kangarko/Boss#237]
*All new plugin, reinstalled it and it happens without changing anything*

I created a drowned boss named "test", and whenever i go to vanilla reinforcements on death and click an "Iron Golem" (is a sheep egg), it doesnt change anything and when i x out of it and go back into the page it added +1 to the "Sheep" mob on death.

I cannot spawn anything that doesnt directly have its own spawn egg, the other mobs work.

On a brand new install of the plugin, deleted the folder and tried again and still doesnt work.

No console error when i add/remove an iron golem to the death reinforcements.

**Comment by StoopidMeap** [comment]
1.13.2, latest Spigot BuildTools.

**Comment by kangarko** [comment]
Thanks, fixed
