### ISSUE TITLE
Suggestion: Chicken that lays different things.

### ISSUE THREAD

**Issue by StoopidMeap** [kangarko/Boss#239]
*oops, didnt mean to click enter*

Suggestion: Add the ability to control how chickens lay things (if its possible). Like lay time, and what the chicken lays.

i.e.:

Every 3000-5000 Ticks - 50% chance of laying 1 emerald.

**Comment by kangarko** [comment]
Hey, sorry this is not possible with the current Spigot API and we are not planning to code in own system for monitoring this. Thank you for your understanding.
