### ISSUE TITLE
Added monsters & more.

### ISSUE THREAD

**Issue by reneg1990** [kangarko/Boss#24]
Heyo!
- Just wanted to say good job on all the previous updates, I see a lot of the suggestions and what not has been added in.

I have a few more "urgent" updates that i'd love to see before the first December, as we could really use that for our server.

Suggestions:
1: Make us possible to set zombies/husks as Babies (i.e we could make "evil elves" for christmas then)
2: Add snowman + more neutral animal types. We wanted to do turkeys for thanksgiving, but also noticed theres no chickens etc :D

Hope to see these monsters/features added soon!

**Comment by kangarko** [comment]
Hello!

Thank you 👍 

1. Baby Zombies are possible:

![img](https://i.imgur.com/nUuWBy5.gif)

2. Snowmen and passive mobs are planned very very soon!
