### ISSUE TITLE
Potion bug

### ISSUE THREAD

**Issue by mrcoffee1026** [kangarko/Boss#240]
Potions are set as 2 different things we have a potion "skill" which allows a selection of whichever potion... and then a separate place to say "throw potion at player" ... and no way to differentiate which potion is tossed at the player or which the mob will use on itself.  They appear to automatically do both... tossing both positive and negative potions at the player while simultaneously ingesting both positive and negative potions.  Also, potion count / effect is incredibly overblown.  I have a mob regen +1 which makes it virtually unkillable without the most OP of weaponry.  Giving a mob a poison potion causes it to poison itself... nearly to death.  Would be nice to have 2 potion configuration panels one for the potions they should be using on themselves and a different one for the ones they should be throwing.

**Comment by kangarko** [comment]
Hey,

I am not sure which two systems you are referring to. Currently there are:

**1) Boss Potion Effects (found in Boss->Settings).**
This gives the Boss a permanent non-throwing potion effect.

**2) Boss Potion Skill (found in Boss->Skills)**
Gives the Boss the ability to apply a temporary potion to the player he is chasing (without throwing).

If you Boss naturally throws potions (i.e. witch) we cannot do anything about it. I believe you can just adjust Boss according to your needs differently.

**Comment by mrcoffee1026** [comment]
example would be a boss spider which does not naturally do anything with potions.  If I set potion skill to enabled (your #2)... there is no way of configuring what potion the spider will be using except for under #1: Boss Potion Effects.  I select an individual potion bottle from regen which seems to make this boss regenerate 10-20 hearts every second, which seems unreasonably OP for the quantity on hand.  Also there's no way of telling it what potions to throw and which to use on itself so it seems to do either, almost randomly.  I'm saying there should be a different menu for determining what he throws with the potion skill versus what he gets to use on himself... right now there's only the boss->settings to adjust which and the strength of the potions and even that isn't reliable right now.

**Comment by kangarko** [comment]
I see. You can configure the Potion Skill (2) in its respective file. At present this is applied globally so every Boss will have the same potion skill (we have this in our roadmap):

![a](https://i.imgur.com/1ckioME.png)
