### ISSUE TITLE
Minions vs Reinforcements

### ISSUE THREAD

**Issue by mrcoffee1026** [kangarko/Boss#241]
would love to see this more similar to the Mythic Mob behavior where "reinforcements" are summoned rather at random or when the boss has taken some damage or some random time has passed with the player having made attempts anyway... quantity and mob being a setting completely independent of "minions" which this plugin summons upon death of the boss.  Flip the names if it makes more sense the other way but it would still be nice to independently configure the two... maybe having the ones that appear on death be a slightly harder or easier mob to kill than the ones the boss first summoned earlier... varying settings here until it seemed more or less reasonable for a player to accomplish.

**Comment by kangarko** [comment]
Thank you for your suggestion. We are not planning to include this right now until our roadmap is cleaned up.

**Comment by mrcoffee1026** [comment]
cool, thank you much!
