### ISSUE TITLE
+ winter madness

### ISSUE THREAD

**Issue by mrcoffee1026** [kangarko/Boss#242]
If we also have your Winter plugin installed can we have a Psycho snowman boss?

**Comment by kangarko** [comment]
Hey, if you create an independent Boss mob named Psycho, yes, both Phycho Boss and Psycho from Winter will function.

**Comment by mrcoffee1026** [comment]
I meant more along the lines of if the actual "Psycho" mob mentioned in Winter could be utilized as a boss.  I haven't tinkered with it much but in 1.12.2 the only option for a boss is just the regular snowman.. which is not a good boss and won't even toss snowballs.

**Comment by kangarko** [comment]
This is currently not possible, because the Psycho utilizes NMS. We disregarded from using it to ensure stability and easy-to-update system in Boss, see more at https://github.com/kangarko/Boss/wiki/Frequent-Questions-and-Tips#can-you-make-animals-aggressive--add-better-ai
