### ISSUE TITLE
Toggle to disable lightning on boss spawn?

### ISSUE THREAD

**Issue by Zethrus** [kangarko/Boss#243]
Hey there,

I have a request as I have players complaining about too much random lightning that happens.
I am wondering if it would be possible for you to add a toggle to turn on/off lightning when a boss spawns? 

I do admit that it is a bit annoying to have lightning every 30 seconds with more frequent custom mobs spawning, as I use the plugin for common mobs as well.

**Comment by kangarko** [comment]
You can disable that in settings.yml
![a](https://i.imgur.com/yhluadz.png)
