### ISSUE TITLE
Console Spam after updating server to 1.13.2

### ISSUE THREAD

**Issue by SoraShiunin** [kangarko/Boss#244]
I'm uploading all plugins I got to 1.13, When I got to Boss, this error spams the console as soon as the server starts.

https://pastebin.com/0735i1gd

**Comment by kangarko** [comment]
Update your WorldEdit http://builds.enginehub.org/job/worldedit/last-successful?branch=master

**Comment by SoraShiunin** [comment]
I'm using FAWE. Not world edit.
https://www.spigotmc.org/resources/fast-async-worldedit-voxelsniper.13932/

**Comment by kangarko** [comment]
Update your FAWE, https://ci.athion.net/job/FAWE-1.13/

It seems they are shipping with an outdated WorldEdit for the time being, there is nothing I can do about it sadly: https://github.com/boy0001/FastAsyncWorldedit/issues/1265
