### ISSUE TITLE
Error from Boss in console (Spamming)

### ISSUE THREAD

**Issue by 0liverG** [kangarko/Boss#245]
This error has been spamming my console all week long really wanting to remove it to clear my console
https://hastebin.com/nizupaluju.php

**Comment by 0liverG** [comment]
Also running paperspigot 1.13.2 let me know what else you need

**Comment by SoraShiunin** [comment]
I have the same issue.

**Comment by kangarko** [comment]
Update your WorldEdit http://builds.enginehub.org/job/worldedit/last-successful?branch=master
