### ISSUE TITLE
Make breeding bosses' bred baby the same boss

### ISSUE THREAD

**Issue by StoopidMeap** [kangarko/Boss#246]
I'm not sure if this is possible, but it would be cool (and VERY useful) if it were possible to make it so if 2 passive bosses bred, the baby boss would be the same type of boss.

If this is not possible, is there any workaround in making it so if they breed it isnt a normal mob, but something else?

**Comment by kangarko** [comment]
Thank you for your suggestion, however this is currently impossible.

**Comment by kangarko** [comment]
Leaving open for implementation, should be possible

**Comment by kangarko** [comment]
Closing, due to resource and time constrains we'll not be including this feature
