### ISSUE TITLE
Suggestion: Cooldown for abilities?

### ISSUE THREAD

**Issue by Zethrus** [kangarko/Boss#248]
Hey there.

I am wondering if it would be possible to add some sort of cooldown settings to the Boss abilities? 
That way, players aren't spammed with confusion every 2 seconds (it's really annoying) and server owners can set exactly how long between abilities usages for a Boss.

Thank you for your consideration.

**Comment by kangarko** [comment]
Hey,

you can set the skill delay in the skills/ folder for each skill individually.
