### ISSUE TITLE
Natural Spawning

### ISSUE THREAD

**Issue by iAzk** [kangarko/Boss#25]
Hi, I have a problem with your plugin :/
The condition : Biome, Region, World is not empty and in debug mode, I see that in my console.

[15.11.2017 15:11:52] [spawning]: Failed to pass conditions to spawn Boss{MaÃ®tre_Des_Abysses - ZOMBIE}' at Survie [-382, 63, 2257]
[15.11.2017 15:11:52] [spawning]: World Ressources has null% of spawning boss. Should spawn? false

**Comment by kangarko** [comment]
Hello!

Please upload me the .yml file of that boss.

**Comment by iAzk** [comment]
#  ------------------------------------------------------------------------
#  Welcome to the individual Boss settings file.
#  ------------------------------------------------------------------------
#  Here you can configure the same settings as in
#  '/boss menu' for this Boss
# 
#  It is recommended to use the GUI above to edit this file.
#  We have documentation to each setting in the game.
#  ------------------------------------------------------------------------

Type: ZOMBIE
Custom_Name: Maitre_Des_Abysses
Health: 2048
Dropped_Exp: '20'
Potions:
- SPEED 4
- FIRE_RESISTANCE 10
- REGENERATION 1
Specific_Settings:
  Glowing: true
  Invulnerable: false
  No_AI: false
  Gravity: true
  Can_Pickup_Items: false
  Silent: false
  Auto Target: false
  Burns_Under_Sunlight: false
  Baby: false
  Powered: false
  Spawn Babies: true
  Size: 4
Attributes:
  Armor Toughness: 30.0
  Knockback Resistance: 10.0
  Follow Range: 48.0
  Armor: 2.0
  Movement Speed: 0.25
  Max Health: 200.0
  Zombie Spawn Reinforcements: 100.0
  Attack Damage: 3.5
Skills:
- Throw Player
- Shoot Fireball
- Shoot Arrow
- Ignite Player
- Steal Life
- Spawn Minions
- Enderman
- Strike Lightning
- Confuse Player
- Bomb
Death:
  Commands:
  - bc {killer} Vient de térasser le Maître Des Abysses !
  Reinforcements:
    Vanilla:
    - ZOMBIE_VILLAGER, 0
    Boss:
    - Esclave_Des_Abysses, 3
  Lightning: true
Spawning:
  Worlds:
    Ressources: 0%
    Nether: 0%
    Event: 0%
    Survie: 0%
    end: 0%
    Spawn: 100%
  Biomes:
    PLAINS: 100%
  Regions:
    Boss:
    - Donjon1
    Towny: []
    Factions: []
    Residence: []
    WorldGuard:
    - donjon1
  Conditions:
    Rain: false
    Thunder: false
    Light: 0 - 15
    Time: 0 - 24000
    Height: 0 - 256
Sounds:
  Debug: false
  Remapped: {}
Equipment:
  LEGGINGS:
    item:
      ==: org.bukkit.inventory.ItemStack
      type: DIAMOND_LEGGINGS
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        enchants:
          PROTECTION_ENVIRONMENTAL: 6
    dropChance: 0.0
  HELMET:
    item:
      ==: org.bukkit.inventory.ItemStack
      type: DIAMOND_HELMET
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        enchants:
          PROTECTION_ENVIRONMENTAL: 6
    dropChance: 0.0
  CHESTPLATE:
    item:
      ==: org.bukkit.inventory.ItemStack
      type: DIAMOND_CHESTPLATE
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        enchants:
          PROTECTION_ENVIRONMENTAL: 6
          DURABILITY: 10000
          THORNS: 5
    dropChance: 0.0
  BOOTS:
    dropChance: 0.0
Drops:
  0:
    item:
      ==: org.bukkit.inventory.ItemStack
      type: IRON_SWORD
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: §8§l❖ §9épée des Abysses §8§l❖
        lore:
        - §9§m-----------------------
        - §8➜ §7Outil rare & précieux
        - §8➜ §7Gagner au §9Donjon Abyssale
        - §8➜ §7Edition §9Elyria
        - §9§m-----------------------
        enchants:
          DAMAGE_ALL: 3
          DURABILITY: 10
          VANISHING_CURSE: 10
    dropChance: 100.0
  1:
    item:
      ==: org.bukkit.inventory.ItemStack
      type: SLIME_BALL
      amount: 10
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: §8[§a✭§8] §aCristal Doyen §8[§a✭§8]
        lore:
        - §8➜§r §7Cette monnaie te sert
        - §8➜§r §7à gagner des grades
        - §8➜ §7Parle aux §2PNJ §7dans §7la zone §6VIP
    dropChance: 100.0
  2:
    item:
      ==: org.bukkit.inventory.ItemStack
      type: EYE_OF_ENDER
      amount: 5
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: §8[§6✭§8] §6Cristal Féerique §8[§6✭§8]
        lore:
        - §8➜§r §7Cette monnaie te sert
        - §8➜§r §7à gagner des grades
        - §8➜ §7Parle aux §2PNJ §7dans §7la zone §6VIP
    dropChance: 0.5
  3:
    item:
      ==: org.bukkit.inventory.ItemStack
      type: DIAMOND
      amount: 4
    dropChance: 0.5
  4:
    item:
      ==: org.bukkit.inventory.ItemStack
      type: SKULL_ITEM
      damage: 2
    dropChance: 0.5
  5:
    item:
      ==: org.bukkit.inventory.ItemStack
      type: DIAMOND_CHESTPLATE
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: §8§l❖ §9Plastron Des Abysses §8§l❖
        lore:
        - §5§m-----------------------
        - §8➜ §7Armure rare & précieuse
        - §8➜ §7Gagner au §9Donjon Abyssale
        - §8➜ §7Edition §9Elyria
        - §5§m-----------------------
        enchants:
          PROTECTION_ENVIRONMENTAL: 6
          DURABILITY: 5
          BINDING_CURSE: 10
    dropChance: 0.5
  6:
    item:
      ==: org.bukkit.inventory.ItemStack
      type: SNOW_BALL
      amount: 16
    dropChance: 0.5

**Comment by iAzk** [comment]
https://hastebin.com/qisoyocozi.scala

**Comment by kangarko** [comment]
Hello,

according to your file, the world Ressources has 0% chance of spawning Boss. You can edit the file directly add add some percentage like you have under Spawn, or use the menu.

![img](https://i.imgur.com/vZ8Y52d.png)

**Comment by iAzk** [comment]
There is no results

**Comment by kangarko** [comment]
Have you restarted the server instead of just /b rl (sometimes that helps)?

Please also upload me your settings.yml

**Comment by iAzk** [comment]
https://hastebin.com/akohalejab.scala

**Comment by kangarko** [comment]
Hello,

I have reset Spawning conditions for you: https://pastebin.com/LAVLAeD9 (make sure you backup your file, just in case).

I have noticed the following:

1. The time was only from 0 to 100. In other cases the boss would not spawn. I have reset it.
2. The Boss would only spawn in PLAINS biome. That means in NO OTHER biomes that plains. I have reset it.
3. The Boss would only spawn in Donjon1 Boss region and donjon1 WorldGuard region, NOT anywhere else. I have reset it.

Please configure it again piece-by-piece, and notice after each step if it works as expected. Please also test the "Debugger: [spawning]" option in the next version because it will print much more meaningful messages. Thank you.

**Comment by iAzk** [comment]
I have set my config boss and the console spam that error:

[19:37:26 INFO]: World Survie has null% of spawning boss. Should spawn? false
[19:37:26 INFO]: Failed to pass conditions to spawn Boss{Maître_Des_Abysses - ZOMBIE}' at Survie [4965, 65, 5814]

**Comment by iAzk** [comment]
I think it comes from Worldguard who blocks the boss's spawn
Even in the global region he does not want spawn

**Comment by kangarko** [comment]
Please update Boss, those messages you posted are outdated and have changed..

You can so disable preventing monsters spawning in WorldGuard.

**Comment by kangarko** [comment]
Assuming fixed, closing.
