### ISSUE TITLE
High resource usage in Timings

### ISSUE THREAD

**Issue by ElFlyGod** [kangarko/Boss#250]
Boss seams to use a lot of resources as seen here http://prntscr.com/mma0sr

Full timings: https://timings.aikar.co/?id=83ce2b0178ee4be79cd14674f8bb4e21

Please fix this as soon as you can, thank you!

**Comment by ElFlyGod** [comment]
Using paper 1.12.2

**Comment by kangarko** [comment]
Post me your Boss ZIP folder

**Comment by ElFlyGod** [comment]
Heres the link: https://www.mediafire.com/file/al8c5bu18k8k862/BossFolder.zip/file

**Comment by kangarko** [comment]
Please set Timed_Spawning.Performance.Async_Conditions back to false and re-test.

**Comment by ElFlyGod** [comment]
I have a SSD, and no i dont use DynMap. I disabled the async, ill try it now.

**Comment by ElFlyGod** [comment]
http://prntscr.com/moayzc

**Comment by jascotty2** [comment]
Sorry, it seems we missed updating this ticket - a small change was made in v1.9.6 to help address this issue - whenever you get a chance to update, could you see if this benefits your timings?

**Comment by kangarko** [comment]
Closing, if you still perceive the issue please comment below - we get notified! :)
