### ISSUE TITLE
Allow coordinate decimal when spawning mobs

### ISSUE THREAD

**Issue by nickswizle** [kangarko/Boss#251]
[14:31:59 INFO]: BOSS // Location must be a whole number (or ~ for your location)! Got: 88.5

im using the dungeonsxl plugin and you use signs to spawn mobs and the sign sits in the middle of the block therefore its always going to have a decimal of .5 is there a way to fix this to make it a whole integer or bypass this ?

**Comment by kangarko** [comment]
Alright I will add that
