### ISSUE TITLE
Issue regarding boss messages

### ISSUE THREAD

**Issue by RebelDs** [kangarko/Boss#252]
![](https://cdn.discordapp.com/attachments/438022226202066950/546732634227736626/unknown.png)

![](https://cdn.discordapp.com/attachments/438022226202066950/546732426140057621/unknown.png)

![](https://cdn.discordapp.com/attachments/438022226202066950/546732395915640833/unknown.png)

We get this error even though we followed (I think) the steps provided in the spigot update announcement. Is there something we're doing wrong?

**Comment by kangarko** [comment]
Set Message to "" or to none.

![a](https://i.imgur.com/syQeDwF.png)
