### ISSUE TITLE
Custom spawning support

### ISSUE THREAD

**Issue by RebelDs** [kangarko/Boss#253]
Although Boss functions (if you overhaul vanilla) with minecraft spawners, it'd be a nice (AND VERY USEFUL) feature for it to support its own spawners, much like Mythicmobs. As for now, Mc-Cron is suggested to create timed, constant spawnings, but this 3rd party plugin is bugged (its config regenerates on server restart and it required modifying its core code in order to work). 

What I propose is a command to set certain blocks as boss spawners. 

For example, take the block pointed at by a player's target. The player could use the command ./boss setspawner <bossname> <duration in minutes for every spawn round> <number of bosses to spawn> 

It would greatly improve every MMORPG's server spawning rate, because right now we have to use regions which although they work, are still hard to schedule and ensure players a constant mob presence. 2/4 of our complaints are for the lack of mobs, which seriously alters the gameplay of a quest-based server.

**Comment by kangarko** [comment]
Great idea, suggested many times, I prioritized this to n1 and will be working on it soon.

**Comment by PengBread** [comment]
Also add /boss time [boss name] or something to check the timer.

**Comment by kangarko** [comment]
Hey, that was actually added in /boss tools, you can add set the time there
