### ISSUE TITLE
Performance issues (boss spawn event)

### ISSUE THREAD

**Issue by Kira07** [kangarko/Boss#254]
Could you please improve this ? 
https://i.imgur.com/lq2bNCJ.png
Thanks in advance!

**Comment by kangarko** [comment]
Hey, unfortunately nothing can be done as we are waiting for setting properties for your custom bosses. You can try setting Timed_Spawning.Performance.Async_Conditions to true in settings.yml

**Comment by Kira07** [comment]
Hey, thank you, will try!
