### ISSUE TITLE
Refund

### ISSUE THREAD

**Issue by nytlaaa** [kangarko/Boss#257]
Hey I recently purchased boss today and I realized that I did not need the plugin as another plugin I had already supported a boss feature. I read the terms of service and saw that in the first 5 days I could attain a refund. My paypal email is promazing212gmail.com and the transaction happened today 2/27/19. Thank you!

**Comment by kangarko** [comment]
Hey,

I understand, what's your PayPal transaction ID? Private message me the ID to Spigot please.

**Comment by nytlaaa** [comment]
I didn't really know how to PM, I hope I did it right I sent it in your
conversations

**Comment by kangarko** [comment]
Yes PM is private message on Spigot forums :)
