### ISSUE TITLE
Boss spawning region issue

### ISSUE THREAD

**Issue by titlezero1234** [kangarko/Boss#258]
In my server 1.13.2 
1: the boss not spawning in region but can spawning naturally.
2: and a monster spawns naturally not spawn any world.etc zombie skeleton zombie pigman enderman(not spawning in the end)

**Comment by titlezero1234** [comment]
> In my server 1.13.2
> 1: the boss not spawning in region but can spawning naturally.
> 2: and a monster spawns naturally not spawn any world.etc zombie skeleton zombie pigman enderman(not spawning in the end)

Now a monster can spawns naterally 
but boss not spawning region

**Comment by kangarko** [comment]
Duplicate
