### ISSUE TITLE
Boss is limilt 20 HP 

### ISSUE THREAD

**Issue by hallday0024** [kangarko/Boss#26]
Boss is limilt 20 HP and .i chane 1000 HP .but Boss  is 20 Hp
NOT ERROR

**Comment by kangarko** [comment]
Hello!

Please make sure that the attribute maxHealth (see below) is at 1001 or greater in Spigot.

![img](https://i.imgur.com/2zwf7sK.png)

How exactly it does not work? Can you see the right health in the menu after you change it, and in the .yml file?

**Comment by hallday0024** [comment]
I set attribute maxhealth 10000 in spigot.yml .and i chanc boss health is 1000 .and in game boss is health 20 Hp

**Comment by kangarko** [comment]
Update: You was right, under certain circumstances the HP was not set.

I have fixed that!
