### ISSUE TITLE
Plugin not working in newer updates

### ISSUE THREAD

**Issue by RebelDs** [kangarko/Boss#261]
Hi. I've been using this plugin for quite a while, but the last two or three updates do not work. Simply the plugin won't load. This is available for CoreArena too. Here's the error we get with Boss:
https://pastebin.com/UFaaK7yM

With CoreArena, we don't get any errors. Older versions work, but anything newer than the 4th last update is not working. Having these two plugins as core features of our servers means we have to stop access for players until the issue is solved..

**Comment by RebelDs** [comment]
For no apparent reason, it loaded successfully now.

**Comment by kangarko** [comment]
Do not use plugman for our plugins
