### ISSUE TITLE
Spawners not spawning

### ISSUE THREAD

**Issue by snimka** [kangarko/Boss#265]
After updating to 2.0.2 spawners do not spawn anything until I delete the plugin.

**Comment by snimka** [comment]
I'm talking about vanilla spawners. Boss spawners work fine.

**Comment by kangarko** [comment]
Set **Timed_Spawning.Prevent_Vanilla_Mobs.Enabled** to **false**

**Comment by snimka** [comment]
Where do I set Timed_Spawning.Prevent_Vanilla_Mobs.Enabled to false?

**Comment by kangarko** [comment]
Open settings.yml, find the **Timed_Spawning** section, inside of it find **Prevent_Vanilla_Mobs** key and set it to **false**. 

Or just use CTRL+F to find Prevent_Vanilla_Mobs key ;)
