### ISSUE TITLE
/reload command not working

### ISSUE THREAD

**Issue by FeroxDrood** [kangarko/Boss#267]
Error appears when I type /boss reload on a clean install of the plugin. Running latest version and paper spigot 1.12.2

12.03 20:56:29 [Server] INFO *-----------------------------------------------*
12.03 20:56:29 [Server] INFO Reloading plugin Boss v2.0.3
12.03 20:56:29 [Server] INFO *-----------------------------------------------*
12.03 20:56:29 [Server] INFO BOSS // Boss 2.0.3 encountered a NullPointerException! Please check your error.log and report this issue with the information in that file.
12.03 20:56:29 [Server] INFO java.lang.NullPointerException
12.03 20:56:29 [Server] INFO at me.kangarko.boss.final. .O.protected(SourceFile:23)
12.03 20:56:29 [Server] INFO at me.kangarko.boss.final. .bC.short(SourceFile:50)
12.03 20:56:29 [Server] INFO at me.kangarko.boss.final. .bC.transient(SourceFile:41)
12.03 20:56:29 [Server] INFO at me.kangarko.boss.BossPlugin.super(SourceFile:144)
12.03 20:56:29 [Server] INFO at me.kangarko.boss.final. .lPT5.coM8(SourceFile:544)
12.03 20:56:29 [Server] INFO at me.kangarko.boss.final. .lPT5.cOM3(SourceFile:504)
12.03 20:56:29 [Server] INFO at me.kangarko.boss.command.ReloadCommand.handleSubCommand(SourceFile:20)
12.03 20:56:29 [Server] INFO at me.kangarko.boss.final. .CoM4.handleCommand(SourceFile:172)
12.03 20:56:29 [Server] INFO at me.kangarko.boss.final. .cOm4.onCommand(SourceFile:61)
12.03 20:56:29 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
12.03 20:56:29 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151)
12.03 20:56:29 [Server] INFO BOSS // *-----------------------------------------------*
12.03 20:56:29 [Server] INFO BOSS //  Error reloading Boss 2.0.3
12.03 20:56:29 [Server] INFO BOSS // *-----------------------------------------------*
12.03 20:56:29 [Server] INFO BOSS // Oups, reloading failed! See the console for more information. Error: unknown

**Comment by kangarko** [comment]
Thanks, fixed in the last version
