### ISSUE TITLE
Villagers & Mob Targetting

### ISSUE THREAD

**Issue by Blobbyguy** [kangarko/Boss#268]
Here is the .yml for the boss - https://pastebin.com/p2EjUpvM

As you can see targetable is set to false "Targetable: false", however, other zombie bosses continue to run straight for my villagers and attack them.

I'm also attempting to make the villagers hostile (Idk if that's possible or not), but I've set the option "Auto Target: true" in the hopes that they'll just attack. Idk if it is intentional or not, but setting this option to true on passive mobs don't do anything (as far as I know/could test). It'd be cool if you could make them hostile with this option ^_^.

Atm, I'm just using zombies and disguising but it'd be much simpler I reckon.
 
Spigot Ver:
Paper 1.12.2-R0.1-SNAPSHOT
Boss: 2.0.3

**Comment by kangarko** [comment]
Hey, 

apology very much for forgetting about this ticket. Feel free to tag me next time but I will watch out for this.

The Targettable flag works the other way around, it makes your Boss not being targetted by other monsters. It can and will still attack them. You would have to create a Villager Bosses and set their Targettable flag to false to prevent Zombies attacking them.

As per villagers, no, they cannot be made aggressive, neither can be any other non-aggressive image. More info here: https://github.com/kangarko/Boss/wiki/Frequent-Questions-and-Tips#can-you-make-animals-aggressive--add-better-ai

Hope that helps,
have a wonderful day!
