### ISSUE TITLE
Error when I want to create a new boss in the GUI

### ISSUE THREAD

**Issue by Phoetrix** [kangarko/Boss#269]
Hi!

I get this error when I click on the "Create New" item in the boss menu:
https://pastebin.com/PQxDJJqe

I hope you could solve this error kangarko. :)

(I use last build of Spigot 1.13.2)

**Comment by SoraShiunin** [comment]
Just updated. Same. I use /boss new and then edit it.

**Comment by kangarko** [comment]
Thanks, that will be fixed
