### ISSUE TITLE
Suggestion - Custom Sounds

### ISSUE THREAD

**Issue by BenRulez** [kangarko/Boss#27]
I think it would be pretty cool if we could use custom sounds in our bosses, by this i mean using sounds added in to a resource pack that arent default minecraft sounds. This way in order to use a custom sounds we wouldnt have to replace sounds in our packs.

Another addition to this would be the ability to play a sound when the boss spawns.

**Comment by kangarko** [comment]
Hello!

I can add a sound effect when the Boss spawns.

Do you mean using the sounds just as they are right now, but they could be also replaced to custom sounds from resource packs?

**Comment by BenRulez** [comment]
So when you add a custom sound into a resource pack you can name it whatever IE- boss_sound
Then you can play it using the /playsound command not sure how you would add it in your plugin but its NOT a minecraft sound. its completely added in by the pack.

**Comment by kangarko** [comment]
I see. Currently the logic allows only for vanilla sounds but after exams I will be looking for this expansion.

**Comment by kangarko** [comment]
I am sorry, I am not planning to add this feature in the near future but I put it on hold to the roadmap.
