### ISSUE TITLE
Console issues

### ISSUE THREAD

**Issue by SolknightJuan** [kangarko/Boss#273]
https://pastebin.com/sLWVa5Mk
Here is the link to the console messages.I hope that this problem can be solved.Ignore the worldedit error.Thank you!

**Comment by SolknightJuan** [comment]
Update,I am not sure why this evening when I decided to shut down and start the server again,my console has been spamming with these [warn] messages non stop that I have to temporarily disable it because I have no clue what is going on.
https://pastebin.com/36vR2uaX

**Comment by kangarko** [comment]
Hey,

regarding the errors, please grab the latest WorldEdit from https://dev.bukkit.org/projects/worldedit
