### ISSUE TITLE
Boss name "none" doesn't hide the boss name

### ISSUE THREAD

**Issue by SoraShiunin** [kangarko/Boss#276]
Boss 2.2.0
Minecraft ver 1.13.2
Using boss name "none" doesn't hide the boss name

Mobs will instead have their boss name if they were spawned for a while(looks like its by refreshing the mob/chunks) and then it will turn the name into the mob type. eg: Spawn kingSlime, it will have the name kingSlime, after a while it will switch to slime.

**Comment by kangarko** [comment]
Thanks, that will be fixed.
