### ISSUE TITLE
A problem with equipment 

### ISSUE THREAD

**Issue by MrGeins** [kangarko/Boss#277]
Hello Kangarko!
I write this issue, because I've bought the plugin yesterday and it is amazing. But today I found a problem in the /boss menu, in particulary in the equipment menu. In fact if I put an helmet and a bow in the sheet, then they disappear with no reason (no console error).
I enclose the proof and the minecraft version.
![1](https://user-images.githubusercontent.com/46764878/55328806-7f0a1580-548d-11e9-98af-5fcbadc3df7e.PNG)
![2](https://user-images.githubusercontent.com/46764878/55328812-829d9c80-548d-11e9-8290-dd4b5c9219e9.PNG)
![3](https://user-images.githubusercontent.com/46764878/55328815-84fff680-548d-11e9-8130-17816dfbb26f.PNG)

**Comment by kangarko** [comment]
Hello and thanks for using our plugin!

Is there are any other plugin modifying inventories such as CMI? Try removing it for a testing round.

Also, what kind of monster is your Boss? Not all Bosses can wear armor.

Hope that helps,
Have a wonderful day!

**Comment by MrGeins** [comment]
Hi kangarko!
Thank you for everything. The plugin that modifying inventories was OpenInv.
In fact now it works.

Have a nice day too!
