### ISSUE TITLE
Boss Spawner (BUG)

### ISSUE THREAD

**Issue by johnsoncui02** [kangarko/Boss#279]
spigot version 1.13.2
boss version: 2.2.2

Issue: when spawner is placed down it cannot be removed.
possible outcome: conflict with songoda's EpicSpawner plugin (version 5.8.4)

**Comment by kangarko** [comment]
Does it still happen when you remove EpicSpawner plugin?

**Comment by kangarko** [comment]
Closing, comment below if still having issues
