### ISSUE TITLE
boss menu error: click on an item that activates some things (skills, settings ...)

### ISSUE THREAD

**Issue by Bobinho44** [kangarko/Boss#280]
when I click in the edit menu of a boss, (to activate something), the menu closes

error: https://pastebin.com/ikdw5GmW

message: https://www.cjoint.com/doc/19_04/IDfnZp8u5vN_2019-04-05-15.49.59.png

**Comment by kangarko** [comment]
Purchase Boss.

**Comment by Bobinho44** [comment]
We bought it. And everything was working well yesterday and nothing

**Comment by kangarko** [comment]
PM'd on Spigot.
