### ISSUE TITLE
Boss Despawning

### ISSUE THREAD

**Issue by CobraPlayz** [kangarko/Boss#283]
My Bossess are just despawning and I never put that as an option how do I fix it

**Comment by kangarko** [comment]
Hey, please disable despawning in /boss menu -> Bosses -> Your Boss -> Settings -> Specific Settings

![a](https://i.imgur.com/xbRMJDj.png)

Also, what is your MC version? I believe this option does not work on 1.8.9.

**Comment by CobraPlayz** [comment]
It’s on 1.8.9

**Comment by kangarko** [comment]
I am sorry, but it is not possible to use that option on your MC version.

**Comment by CobraPlayz** [comment]
Then is there way to fix it I have no clue why it’s happening

**Comment by kangarko** [comment]
Hey, sorry for giving you wrong info, I just tested and indeed that option is available on 1.8.x.

This is not coming from boss but from your server settings or a no-lag plugin, you'll have to adjust these.
