### ISSUE TITLE
Prevent Specific Vanilla Mobs?

### ISSUE THREAD

**Issue by farisjaclyn** [kangarko/Boss#284]
Hello! Just curious, if there is a way currently to disable a specific vanilla mob from spawning. My kiddos are constantly dying left and right from phantoms. I'd like to disable them if possible. :)

(I do understand that if a player lays in their bed the phantoms will leave them alone, but that message is difficult to get around to hundreds of players).

**Comment by kangarko** [comment]
Excellent question!

It was not possible so I just went ahead and added that for you, check out this option in the next release:

![a](https://i.imgur.com/eccKyvQ.png)

Best,
Matej

**Comment by farisjaclyn** [comment]
Yay thank you you are always the best!

**Comment by kangarko** [comment]
If you liked this update you can always post a quick review, that would be much appreciated :)
