### ISSUE TITLE
Remove Boss

### ISSUE THREAD

**Issue by titlezero1234** [kangarko/Boss#285]
Now cannot remove Boss from another world.

**Comment by kangarko** [comment]
What do you mean?

Provide me your current situation, your desired situation and what the problem specifically is and how to reproduce it.

**Comment by titlezero1234** [comment]
Like I'm in spawn world, I can't use the command / b butcher to kill boss in nether

**Comment by kangarko** [comment]
Use /boss butcher nether, however players must be there to load the chunks so we can remove Bosses. 

To remove Bosses from unloaded chunks use /boss scan command
