### ISSUE TITLE
Spawner and some stuff

### ISSUE THREAD

**Issue by PengBread** [kangarko/Boss#286]
spigot version 1.13.2
Boss 3.0.4

Spawner doesn't work properly, made the spawner to spawn 30minutes later after the boss has been killed yet it still spams spawning the bosses.

Region limit is not working, the spawners still spawn more than 1 boss.

NO errors

**Comment by PengBread** [comment]
Forgotten to mention this, when set to 30 or 35 minutes, the numbers just becomes automatically negative in the spawner menu after exiting the GUI and enter the GUI again.

**Comment by kangarko** [comment]
For the limits, do you have **Limits.Apply_For_Spawners** on **true** in settings.yml?

For the delay bug, sorry to say this is Spigot/PaperSpigot plugin, please report to them.

**Comment by PengBread** [comment]
I have a question, does the spawners spawn mobs even if there's no players inside that certain world?

**Comment by kangarko** [comment]
No, it behaves just like the vanilla spawner
