### ISSUE TITLE
How to allow Boss spawns in a WorldGuard region?

### ISSUE THREAD

**Issue by Chahuahua** [kangarko/Boss#287]
Is there a way to allow bosses to spawn in a WorldGuard region with mob-spawning denied? I would prefer to keep the spawn region free of other hostile mobs but allow bosses to spawn. Is that possible?

**Comment by kangarko** [comment]
Hey, unfortunately this is cancelled after us so we can't catch up. At present that cannot be fixed, sorry about this.
