### ISSUE TITLE
Give eggs

### ISSUE THREAD

**Issue by BenRulez** [kangarko/Boss#29]
Thanks for making the command to give people eggs, was wondering if you can make it accessible from the console. Im trying to add eggs to crates and also a gui shop but its not letting the command run from the console

**Comment by BenRulez** [comment]
Extension of this:

Players without any special permissions can use the eggs to edit bosses

**Comment by kangarko** [comment]
I will!

In the next version, only players with boss.command.menu will be able to open the Boss menu.
