### ISSUE TITLE
Some Improvements for Boss and Github

### ISSUE THREAD

**Issue by SushiBarIV** [kangarko/Boss#292]
**Minecraft**:
Some features I would love to see.
- An option for Hostile Mobs to attack Players.
- Spawn Amount in Spawners.
- Whether or not Spawners spawns monsters either in the night and/or at the day ( Configureable )
- Creating skills without any programming knowledge, just like MythicMobs did.
- Disable players damaging mobs from outside a boss region. ( Configureable )

**Github**:
Setting myself the lable "Improvement"

**Comment by kangarko** [comment]
Hi,

please see our Wiki for why some of the features are unavailable.

Thanks for the tips though.
