### ISSUE TITLE
[ Issue ] Bosses dont spawn on snow

### ISSUE THREAD

**Issue by SushiBarIV** [kangarko/Boss#293]
Hey,

Bosses won't spawn above the snow.
They Spawn in the snow block itself.

http://prntscr.com/nj5fbs

**Comment by kangarko** [comment]
Hi, the image is too dark I can't see anything, can you provide another one?

**Comment by SushiBarIV** [comment]
Sorry.

This should be better: http://prntscr.com/nlqum9

**Comment by kangarko** [comment]
Thanks, I fixed that now
