### ISSUE TITLE
Add time of boss despawn after player far away

### ISSUE THREAD

**Issue by SlimeLittle** [kangarko/Boss#295]
The new despawn setting too fast,Just teleport away and back in 1 sec the boss despawn already,hope can add setting make boss despawn in specific time after player far away

**Comment by kangarko** [comment]
Hi,

sorry, if you toggle "despawn" settings for Boss, we let the control to your MC server. If there are too many entities this process is speed up. If you are running an antilag plugin it may interfere as well. We do not have control over despawning.
