### ISSUE TITLE
Spawn chance to Reinforcements

### ISSUE THREAD

**Issue by TadiklCZE** [kangarko/Boss#296]
Hi I am doing some bosses and I want to add chances to Reinforcements. When the boss died, it will spawn skeleton with 5% chance. Thx, T.G.

**Comment by kangarko** [comment]
Ahoj, 

zatiaľ to nieje možné, musím prioritizovať aktualizáciu pre MC 1.14, potom sa na to môžem pozrieť, ďakujem.

Matej

**Comment by TadiklCZE** [comment]
Dobře, děkuji za informaci 😇

Dne st 8. 5. 2019 18:08 uživatel kangarko <notifications@github.com> napsal:

**Comment by TadiklCZE** [comment]
Dobrý den, chci se vás zeptat, jestli je možné se s vámi spojit na
discordu. Mám nějaké problémy, které bych potřeboval vyřešit. A to
konkrétně ChatControlPro. Děkuji, T.G.

Discord: L A R K Y Y#0001

**Comment by kangarko** [comment]
Prepáč ale typicky nepoužívam Discord, vytvor si ticket v ChatControl Pro.

**Comment by kangarko** [comment]
Will be implemented.
