### ISSUE TITLE
Terms of service Question

### ISSUE THREAD

**Issue by Lastphysics** [kangarko/Boss#299]
Hey, I was wondering about the 2nd term of service, wich says "One purchase is valid for 1 minecraft server".
1st : First, if i buy it and try to use it on a solo world (local computer) for testing, does it count as a server ?
2nd: If I have a minecraft server with Pebblehost (hosting), and I run it for like 2 month and just close my account for a short amount of time after. If i reopen with a personnal backup of the ancient game, IP probably changes, but does it count has a 2nd purchase if i want to re-use it ?

**Comment by kangarko** [comment]
Hi,

1) No, you can test it on your local PC just fine.

2) That's fine, if the plugin gets disabled for piracy just contact me and I'll fix that.

Matej
