### ISSUE TITLE
Big problem :/

### ISSUE THREAD

**Issue by PLAYGAME294** [kangarko/Boss#30]
Hey I bought your plugin 

But I have a problem (I already have a problem like that with the plugin mmoitems and the author solve it)
When I try to type a custom thing in the chat thats not work
for example: When I create a mob and i want to Put a custom sound ex:ENTITY_BAT_HURT Thats not working Why ?
Because the plugin Ultrapermissions change the text of the chat and I can't remove it 

So I ask you plz to make a command when I need to type ENTITY_BAT_HURT I type:
/b msg ENTITY_BAT_HURT

The autor of this plugins "MMOITEMS" Do it for me and its take 2 m so Plz can you add this command

**Comment by kangarko** [comment]
Hey,

I have replied to your PM on Spigot.
