### ISSUE TITLE
mythicmobs support

### ISSUE THREAD

**Issue by mexbotdude** [kangarko/Boss#300]
Hello, Im really interested into ur plugin, it really seems easier to understand than mythic mobs, despite having worked with the previous plugin for some years I wanted to know what kind of things does support Boss from mythic mobs, as you said it has compatibility. Is there any way to use the skills created in mythicmobs with the Boss mobs? can I configure the Mob AI as I please, or can I allow mobs to use custom sounds, particles, and special effects? I really like BOSS's GUI thing as It will be easier for my staff to create mobs bc Im really the only one who knows the mythicmobs plugin.

**Comment by kangarko** [comment]
Hi,

I don't thing you can use skills from Boss in the other plugin unless their developers use our API. In Boss you cannot configure mob AI however you can give them potion effects, custom sounds and more.

The gui system is the easiest thing we've ever created and I am sure everyone of you will be able to take full advantage of all Boss' features without even touching a single file.

Matej
