### ISSUE TITLE
Console Errors

### ISSUE THREAD

**Issue by xStarDustMcx** [kangarko/Boss#302]
I am getting lots of errors in console when opening up the boss menu for some reason. Also when updating the latest version from my current version 3.2.0 the plugin broke and would not even let me load the /boss menu command. On top of that currently I can't click on the boss egg to get an egg as it just errors in console. I have been using the same bosses I have had for the past few months and have not changed their settings.

Also, I am on Spigot v1.12.2

Edit: Here is a paste of just some of the errors from console: https://pastebin.com/mYYLUrC4

**Comment by kangarko** [comment]
Hi, apology for this, there is a problem preventing Boss 3.2.0 from loading on MC 1.12. New release should be available within an hour or so. Please load it up. That should also fix the other problem, if it won't, please post a new error log below.

Thanks
