### ISSUE TITLE
Boss Plugin Doesn't Work

### ISSUE THREAD

**Issue by Superperson15** [kangarko/Boss#31]
Hey, I bought your plugin and when I start the server, the plugin does not start, I have had this issue posted in your support on discord and have not gotten a fix for it yet. Could you help?

![uuo0hfk](https://user-images.githubusercontent.com/2702313/33026269-1092d5e2-cdde-11e7-8d4e-292dd18c7f0a.png)

**Comment by kangarko** [comment]
Hey,

please PM me on Spigot. If you already did, please disregard from this message.
