### ISSUE TITLE
GUI Mob disappeared

### ISSUE THREAD

**Issue by DarkXrabbit** [kangarko/Boss#310]
My first mob disappeared, but the configuration file was loaded, and the original swawn egg was also available. That yml file is stored in Chinese.

![6dLE3CW](https://user-images.githubusercontent.com/16366999/58675641-cf1b3080-8387-11e9-91c7-23b081ddb14c.png)

**Comment by kangarko** [comment]
Hi,

sorry but some systems dont support names other than english alphabet. Try creating Bosses named only in English and giving them Chinese custom name instead.
