### ISSUE TITLE
Show name when invisible.

### ISSUE THREAD

**Issue by nontagan** [kangarko/Boss#311]
![image](https://user-images.githubusercontent.com/51222204/58680564-6be2cb80-8392-11e9-9593-4747456c11da.png)

After I have used I am so happy but I see that mob invisible not show name
I need the option to show the name when invisible.
Thanks
Sorry for bad english

**Comment by nontagan** [comment]
I already give u reply 5 star ;P

**Comment by nontagan** [comment]
![image](https://user-images.githubusercontent.com/51222204/58680855-e829de80-8393-11e9-89aa-0891ceb77fc5.png)

other problem

**Comment by kangarko** [comment]
Sorry but showing names for invisible bosses is not possible in Bukkit.

Thanks, will take a look. When do this problem happened exactly?

**Comment by kangarko** [comment]
Closing, that problem should be fixed in the latest version
