### ISSUE TITLE
Bosses taking armour and weapons even though they're set to not

### ISSUE THREAD

**Issue by DXUltimate** [kangarko/Boss#312]
This isn't a crash or anything, but for whatever reason, all of the illager bosses I have made are picking up my members items and upon death, they do not drop them. We tried to enable a gamerule so mob grief is permanently disabled, but it is only making it worse (they still pick up the weapons), not sure what's going on and I have had to give them back their items via spawning.

Plugin list is as follows;
https://puu.sh/DzL1B/d62be04420.png

I'm using paper-53 1.14.2 atm but I am about to update to v58 after next restart.

**Comment by kangarko** [comment]
Have you tried disabling the following specific setting?

![a](https://i.imgur.com/XZmem9I.png)

**Comment by DXUltimate** [comment]
Yes, I have tried that on all of the illager mobs, as well as the undead mobs, and it has happened both times with and without that setting on. This rarely only happens once in a while and it has not happened since I have posted this issue, with settings unchanged. I made sure it was set up to not pick up items so I really don't know why that happens.

**Comment by kangarko** [comment]
Does it happens for zombies or other mobs? Seems this is a spigot/paper bug not respecting that flag.

**Comment by DXUltimate** [comment]
Specifically the Illager mobs, Vindicator and Illusioner's to be be exact.
I've been trying with most undead but they don't seem to give. I will keep
you updated.

**Comment by DXUltimate** [comment]
I actually just had an idea on where and why the items were not dropping,
it could be from this setting;
https://puu.sh/DB3BE/7d5096607d.png
We could have any "picked up items" as an exclusion for this rule/setting
for mobs.

**Comment by kangarko** [comment]
That setting is irrelevant as all it does it clears up the drops when they should be dropped on death. But I understand your suggestion and will note it down.

Can you reproduce on Zombies?

**Comment by DXUltimate** [comment]
No. I have been testing since you were on vaca and all tests have proven negative. I'll continue it, though.

**Comment by DXUltimate** [comment]
It happened again, but strangely enough, with a spider lol.

https://puu.sh/DFJzV/d1ef867993.png

https://puu.sh/DFJDq/391759df98.png

**Comment by DXUltimate** [comment]
It's never happened with a zombie or their variants. Only with the other
mobs. Might need to report to paper/spigot.,

**Comment by kangarko** [comment]
I have opened an issue for Paper, thank you for your testing.

**Comment by kangarko** [comment]
Ok, the next version of Boss listens for each time an entity picks up an item, and I added debug messages to clarify what is happening. I also added so that we check if the entity is allowed to pickup the items depending on Boss' specific flag "pickup" as shown above.

Set Debug to [boss-pickup] and report me messages when you see the issue occuring again, thanks.

**Comment by kangarko** [comment]
I assume adding that event had solved your problem, kindly return to me and comment below if this is not the case. Thanks.

**Comment by kangarko** [comment]
@DXUltimate 

Paper has finally fixed the problem server-side, for reference purposes this is the ticket I opened last year: https://github.com/PaperMC/Paper/issues/2205#issuecomment-503761899
