### ISSUE TITLE
Spawner Range

### ISSUE THREAD

**Issue by DampfWaffel** [kangarko/Boss#314]
Hey,
it is possible to set a range for the spawners, so when the entity is out of range it get killed?
And also, can it be disable that silverfish go in Stone Blocks?

lg

**Comment by kangarko** [comment]
Hi, 

you can configure Spawning Range in the spawner. When entities go out of their range they cannot be removed, sorry.

![a](https://i.imgur.com/S6eWMNC.png)

The silverfish behavior cannot be modified, see https://github.com/kangarko/Boss/wiki/Frequent-Questions-and-Tips#can-you-make-animals-aggressive--add-better-ai

**Comment by DampfWaffel** [comment]
Hey,
whats with the [EntityChangeBlockEvent](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/EntityChangeBlockEvent.html)?
can this not be canceled for the Boss Monster?

**Comment by kangarko** [comment]
I am sorry but currently we don't have the time/scope to change the current system. I can look into that, honestly I don't know, but that would be in some time in the future.
