### ISSUE TITLE
Question about compatibility with MMOItems

### ISSUE THREAD

**Issue by DogeTennant** [kangarko/Boss#315]
Ahoj, chtěl sem se jenom zeptat na takovou rychlou otázku, tenhle plugin asi nejde nějak udělat, aby byl kompatibilní s tímto pluginem, že? https://www.spigotmc.org/resources/mmoitems-90-item-options-65-abilities-item-edition-gui.39267/ - Zkouším to s tím tvým pluginem, ale drtivá většina věciček z toho pluginu se nedají využít na ty bosse. Jelikož mobové celkově neumějí right click, tak bossové nemůžou použít abilitky z těch itemů, a z nějakého důvodu ani ty další věci moc nefungujou z mob side. Třeba když přes ten plugin dám na item Fire Damage, a použiju ho já na bosse, tak ho zapálím, ale když ten stejný item dám bossovi tak mě s tím může hitovat jak dlouh ochce, ale nezapálí mě, a to přitom u tohohle zrovna není potřeba žádný right click, ale jen obyčejné hity. A prostě celkově spousta dalších attributů funguje jen z mojí strany (když útočím na moba) a ne z opačné strany (když mob útočí na mě) je to jen protože je to nekompatibilní, nebo prostě ti mobové celkově mají nějaké limity?

**Comment by kangarko** [comment]
Ahoj, je mi ľúto ale nejde to, máme vlastné nastavenia na Bossov, nejdú kombinovať z inými pluginmy.
