### ISSUE TITLE
Is possible to make donkey boss?

### ISSUE THREAD

**Issue by climeno** [kangarko/Boss#317]
I want to know if its possible make a boss with a donkey, it is not in the list

**Comment by kangarko** [comment]
Yes, you can do "/boss new yourbossname donkey":

![a](https://i.imgur.com/NRTqbm2.png)

**Comment by climeno** [comment]
is this possible to make in 1.8 versions?

**Comment by kangarko** [comment]
No sorry, entity types are lacking on that version.
