### ISSUE TITLE
Make timed bosses spawn when a chunk is loaded

### ISSUE THREAD

**Issue by kayc01** [kangarko/Boss#318]
I am using a plugin that loads and keeps chunks loaded: https://www.spigotmc.org/resources/keepchunks.23307/

I have gone to the spawn point of the chunk where a timed boss is meant to spawn (in a Boss Region). And saved that chunk via that plugin so it stays loaded. 

Is it possible to make it so that the timed boss will spawn based on the loaded chunk instead of if it's in the radius of a player? 

I saw that the /boss spawn command with co-ords forces the chunk to load which is good. But there is no way to know if the boss is dead, and no way to limit the boss (1 per region, and keeping it in the Boss Region) when using the /boss spawn command. 

So having an;

MinecraftChunk bossChunk = boss.getCo-ords().getChunk();
if (bossChunk.isLoaded || player is in radius) {    
            SpawnBoss();
}

^ Obviously none of the above code is actually the right terminology. But I assume it could work like that? 

Otherwise I may have to have a look at your API, if you have something onBossDeath, then I could trigger my plugin to do a /boss spawn command a certain time from that boss dying.

**Comment by kangarko** [comment]
Hi,

apologies, we are currently busy recoding Boss and recording an online training and are not planning to change the current system.

**Comment by kayc01** [comment]
Just a quick follow up, is there any other way you recommend me getting around this?

(A World Boss that can spawn without needing players near it)

Again, I can code my own scheduler if it actually can tell when the Boss Dies via the API to stop more than one spawning once with the /boss spawn command. Unless you think that won't even work? 

And are you saying this won't be an improvement you might do? Even after the re-code? 

Thanks

**Comment by kangarko** [comment]
Technically you can listen to BossSpawnEvent and cancel it, or listen to the BossDeathEvent. See our API on the wiki page please.
