### ISSUE TITLE
API missing declaration

### ISSUE THREAD

**Issue by QTimort** [kangarko/Boss#319]
There is some missing decleration in the API.
For example "AutoUpdateMap" or "AutoUpdateList" are not defined and cannot be cast into either a map or list making some part of the API unusable.

**Comment by QTimort** [comment]
Also when setting equipment (ignore the null values)
```boss.getEquipment().set(null, null);```

cannot access org.mineacademy.fo.helper.FoSerializable:  class file for org.mineacademy.fo.helper.FoSerializable not found

**Comment by kangarko** [comment]
Apology, the public API cannot contain these as they are coming from a private library only available in the full Boss version. If you are a developer contact me on SpigotMC and you can obtain a free licence for certain cases.

**Comment by QTimort** [comment]
@kangarko I contacted you on SpigotMC
