### ISSUE TITLE
Giant's Won't Move, also a few questions, and suggestions

### ISSUE THREAD

**Issue by mminnett** [kangarko/Boss#32]
I made a boss that is a giant, and it won't move. It will only use the skills I gave it, but without moving. I have just purchased this, and was wondering if it works like mythic mobs. With mythic mobs, you can make a mob a pumpkin, that when a player walks by, it will come alive and attack the player. I was wondering if this was possible for this, or if you were planning on adding it. Also, I had a suggestion if it isn't already there, could you add things like player type bosses? Maybe you could also add player skins to them. For example, I could make a boss that looks like a Mage, because it would have a mage skin. Or orc, or giant, etc. I think these things would make this plugin perfect.

**Comment by kangarko** [comment]
Hello & thank you for your purchase!

> I made a boss that is a giant, and it won't move. It will only use the skills I gave it, but without moving.
Hey, this may be the default server's behaviour. Please test whether giants spawned by /spawnmob giant also do not move. If this is the case, then there's little I can do about it, I am sorry.

> With mythic mobs, you can make a mob a pumpkin, that when a player walks by, it will come alive and attack the player
Sorry, currently this is not possible. I am having exam period so I also have to delay suggestions as such.

> Could you add things like player type bosses? Maybe you could also add player skins to them.
Same as above, but this is planned :)

Cheers!

**Comment by mminnett** [comment]
Thanks for responding so quickly. Good luck with exams. 😊
