### ISSUE TITLE
Boss Issues from Update + "Malformed Syntax" issue

### ISSUE THREAD

**Issue by DXUltimate** [kangarko/Boss#326]
Hi, so I updated Boss to 3.3.1 from 3.2.5, and paper from r58 to r62.

I keep getting a malformed syntax issue involving editing the bosses experience drops.

https://puu.sh/DBUNl/400895a8df.png

Second, Boss crashed several times loading up the configs from my pre-existing bosses made in 3.2.5, here are the pastebins;

https://pastebin.com/MgDDZ5pZ

I've had to completely remove the old boss configs, and remake the bosses from scratch, but I can't even do that because of the issue above with the experience. When you get back from leave, please have a look. =3

**Comment by DXUltimate** [comment]
Sorry for the immediate double post, but, when trying to click on "specific settings", this exception is thrown. I will have to revert back to the older version of boss until these are fixed. =3

https://pastebin.com/4kPwXYFx

**Comment by kangarko** [comment]
Thanks, the dropped exp problem will be fixed. I believe that will also solve the other issues in your error.log file.

This fix will also solve your second post as they are all related to the RangedValue class which had a program mistake crashing in certain cases.

Thanks for your patience.
