### ISSUE TITLE
Boss-3.3.1-BETA - server crash

### ISSUE THREAD

**Issue by ArtNRG** [kangarko/Boss#327]
Paper version git-Paper-571 (MC: 1.13.2)
Stacktrace: https://hastebin.com/raw/oliyogesep
Default boss config without adding any boss. Just dropped the plugin into the plugins folder.

From #paper-help:
> electroniccat: Your issue is the boss plugin is accessing the world async

**Comment by kangarko** [comment]
Sorry, the hastebin page seems to be down today, may you please reupload for example to pastebin.com? Thanks.

**Comment by ArtNRG** [comment]
@kangarko ok, here it is https://pastebin.com/raw/xqTTz9Xk

**Comment by kangarko** [comment]
Hi, apology for a late reply, can you please set Setup.Hook_ProtocolLib to false and re-test whether it will still crash? I can see that part of the problem lies in remapping sounds which is a packet-related feature.

**Comment by kangarko** [comment]
Unfortunately this was confirmed to be the packet feature on remapping sounds. This has temporarily been disabled until we find a better solution.

**Comment by kangarko** [comment]
You can follow up here: https://github.com/PaperMC/Paper/issues/2284
