### ISSUE TITLE
Spawning Suggestion

### ISSUE THREAD

**Issue by MsArtix** [kangarko/Boss#33]
Spawning suggestion is to add the ability for Bosses to spawn when players walks into a certain region/area (set with the plugin region commands) and also set a limit for how many times this boss can spawn in this area. (this is already in but not for the range feature I am suggesting)
When a player walks into the area **and** the boss does spawn the player gets a message of some sort "BOSS is nearby" but only on successful boss spawns this way they cant walk in and out of an area and get spammed with messages. 

This is useful for creating custom one time dungeons for players to find around the world.

**Comment by kangarko** [comment]
Thank you for your suggestion! I am leaving it open for future implementation, but at this time I cannot give you an ETA.

**Comment by LogGits** [comment]
Great idea @MsArtix. This would be a cool addition that would be very useful 🙂

**Comment by demon2749** [comment]
Looking for this same feature  👍

**Comment by kangarko** [comment]
@MsArtix  Would you like to have a timed task, for example every 5 seconds we would go through all Boss' regions you create by /boss rg, and if the player is inside one that has this option enabled, a selected Boss would spawn there, does it work? Also with configurable message like "Boss X has appeared nearby!"

**Comment by MsArtix** [comment]
@kangarko that sounds good to me I assume we would be able to set the timer for however many seconds it would check, and would this limit the amount of spawns in certain regions? so I could have 5 regions and of that 3 regions are only allowed to spawn the boss X amount of times. (perhaps make this mandatory for all regions and use a character or word for unlimited amount of spawns)

**Comment by kangarko** [comment]
Yes the delay would be configurable, but the higher, the more performance it would ate due to constant world scan.

There is no limit of Bosses per region yet, but I can include this as well.

Yes, you could select regions in which the Boss would spawn with Natural Spawning just like now.

**Comment by MsArtix** [comment]
@kangarko Do you mean a lower time? If its set to every 60 seconds it would run once a minute but if its set to 5 seconds it would run 12 times a minute. Thus 12 times would cause more lag (if I am wrong please correct me). Yah I think the boss limit per region would be useful for some and if people dont want it that way they can simply set it to false or unlimited or whatever the option is.

**Comment by kangarko** [comment]
Correct. Okay I will get to it after exams.

**Comment by MsArtix** [comment]
Awesome, cant wait for that update and I know this question is about ChatControl (id rather not create an entire ticket for a single question) but is there a rough estimate of when /nick will be added to CHC?

**Comment by kangarko** [comment]
Tied to roadmap.
