### ISSUE TITLE
Getting the spawn egg, and changing the spawner to spawn the boss doesn't work.

### ISSUE THREAD

**Issue by iMoshang** [kangarko/Boss#332]
Whenever I click on the spawn egg nothing happens. and when I got to a spawner and try it lets me click but no gui pops up.

**Comment by kangarko** [comment]
I was not able to reproduce, sorry, are you getting any console errors? Please also post me your full startup log.

**Comment by iMoshang** [comment]
[debug.log](https://github.com/kangarko/Boss/files/3322721/debug.log)
I have it set so it will spawn every 30 minutes and only in one region, just to try and get it to auto spawn without using a spawner, I don't get any console errors besides those things in the debug log. My main problem is when placing a spawner down, I go into the gui and I am unable to click the egg in the menu, it acts as if there's no further menu.

**Comment by kangarko** [comment]
Thanks, I investigated and it seems to be very weird so I opened a ticket at paper: 

https://github.com/PaperMC/Paper/issues/2256

**Comment by kangarko** [comment]
This has been since resolved
