### ISSUE TITLE
Some questions about Boss features

### ISSUE THREAD

**Issue by 121jwang** [kangarko/Boss#334]
Hello, before I decide to spring on purchasing Boss, I would like to confirm that it has some of the features that I want, or if not, would it be possible to implement it myself with the API.
- Are you able to spawn minions through the API as a skill?
- Can I alter the knockback that the boss mob takes?
- Can I give the boss mob as well as the minions custom pathfinding? Such as a basilisk boss running away from chickens but the minions that they spawn go and attack the chickens.
Thank you very much

**Comment by kangarko** [comment]
Hi,

yes, you are able to spawn reinforcements using our API (https://ibb.co/pnydyp3)

For the knockback, I am not sure what you are talking about but you can edit the Boss entity in the BossSpawnEvent.

For the path finding, if you know how to achieve that using NMS than potentially you could edit its pathfinding in the BossSpawnEvent as well, however we have no support for that for stability reasons.

Thanks and let me know if you got any more questions!
