### ISSUE TITLE
The bosses wont spawn with the spawner.

### ISSUE THREAD

**Issue by Puruuuu** [kangarko/Boss#337]
When I made my dungeon, I placed some spawners, but they do not seem to spawn. I do have timed-spawn enabled, I have it in the spawned region.

**Comment by Puruuuu** [comment]
Oh, it is because no one is near them, but is it possible to change it, that it spawns without people being near it.

**Comment by kangarko** [comment]
Hey,

at present Spawners only work when you have players nearby :) You can customize the spawning radius when you click on them.
