### ISSUE TITLE
Boss won't work (no powers, no death commands/drops) + error

### ISSUE THREAD

**Issue by Kira07** [kangarko/Boss#338]
Hi,

I have the following error on startup (I use the latest version):

[Boss] Plugin Boss v3.3.4 has failed to register events for class org.mineacademy.boss.int. .o because org/bukkit/event/entity/EntityPickupItemEvent does not exist.

**Comment by kangarko** [comment]
What is your MC version?

**Comment by Kira07** [comment]
1.8.8

**Comment by kangarko** [comment]
Thanks, will be solved.

**Comment by Kira07** [comment]
Perfect, you're welcome
