### ISSUE TITLE
Unable to change how much damage the monster does.

### ISSUE THREAD

**Issue by cryptoncore** [kangarko/Boss#342]
My issue:
We have created a custom boss of a iron golem, we want it to be a starter boss but we cannot lower the damage it does, so it kills people in iron armour in a single hit. All other attributes are available except Damage.
We are running spigot 1.14.3

My desired situation:
To be able to lower damage done by the iron golem in order to make it more accessible.

**Comment by jacob54261** [comment]
Boss -> settings -> attributes -> damage.

**Comment by cryptoncore** [comment]
Jacob, that attribute is the only one not in the list.

**Comment by kangarko** [comment]
Hello,

apology, I just tested the code, we are only showing attributes that are "applicable". Bukkit returns nothing for the attack attribute since it unfortunately cannot be applied to the golem.

![a](https://i.imgur.com/MR2bOMH.png)

Maybe you can give him weakness potion instead?

**Comment by kangarko** [comment]
You know what, the code was not good so I rewrote it and added our own system for multiplying damage. You will be able to use it starting tonight. Thanks.

**Comment by cryptoncore** [comment]
Wow! What a developer. Plugin was well worth the money, you're the man,
thanks!
