### ISSUE TITLE
Minion Spawns

### ISSUE THREAD

**Issue by jacob54261** [kangarko/Boss#343]
My desired situation is I want my Boss to be able to spawn minions other than his generic mob type. I would like minions to customizable as vanilla mobs or other bosses such as mounts or death reinforcements.

**Comment by Handyfon** [comment]
I agree, I wish that would be a feature

**Comment by kangarko** [comment]
Are you talking about the Minion Skill? We can definitely look into that although for now we don't have ETA on new features.

**Comment by jacob54261** [comment]
Yes, I meant the minion skill, basically when you click on minion skill if it could open the same options as death reinforcements and mount options.

**Comment by kangarko** [comment]
Alright that makes sense.

I recently published an announcement that I can't take new features in the close future because we use our remaining time to get the plugins to an enterprise stability level. Thanks for your understanding.

Leaving this open for future implementation.

**Comment by kangarko** [comment]
Will be implemented.
