### ISSUE TITLE
Boss Butcher not working

### ISSUE THREAD

**Issue by climeno** [kangarko/Boss#344]
Server version: 1.8.8 
Boss version: 3.3.5

Problem: The /boss butcher command is not sending a message that says that 40 or 48 bosses were removed, but i had any bosses spawned, this appears with all the bosses and using the kill bosses in the edit boss GUI
![image](https://user-images.githubusercontent.com/35473657/60391012-91a2e380-9aaa-11e9-9c2b-612254443384.png)

(I made a issue like this before but i wasnt able to answer at, so i made this better explained i think)

**Comment by kangarko** [comment]
Hey,

it works for me, please check your console for errors and post me the output after you type that command:

![a](https://i.imgur.com/pPHxsVX.png)

If it does not show up for you why are you having an image above then of that message?

**Comment by climeno** [comment]
I have no errors 
![image](https://user-images.githubusercontent.com/35473657/60688260-ad770280-9e79-11e9-9e55-74ceb07051bb.png)

![image](https://user-images.githubusercontent.com/35473657/60688269-c41d5980-9e79-11e9-81b8-7f66a8ed68c0.png)

**Comment by kangarko** [comment]
Hey,

I appeared to have solved this issue in the latest release, closing this. Let me know below in case it appears again.
