### ISSUE TITLE
Making New Mobs

### ISSUE THREAD

**Issue by Spencer7k** [kangarko/Boss#348]
Is there a way to make a boss that doesn't pull its spawn option from vanilla?  essentially i don't want to make a boss per-say, but just extra mobs that exists. Like an endermite that spawns in the overworld and is like a beetle or something.  Does it always have to pull from the vanilla spawns?

**Comment by kangarko** [comment]
Yes you cannot create new Bosses without client modification, only edit the entities already existing in the game.
