### ISSUE TITLE
Worldedit

### ISSUE THREAD

**Issue by RainDropped** [kangarko/Boss#349]
how do I make a boss run a command like /setblock, everytime I try this it doesn't work. even like running a worldedit command

**Comment by kangarko** [comment]
Hello,

when do you need that Boss to run that command? You can try editing your boss yml file manually as described here: https://github.com/kangarko/Boss/wiki/Frequent-Questions-and-Tips#how-can-i-send-custom-messages-or-commands-when-a-boss-diesspawns
