### ISSUE TITLE
Spawners Doesnt work

### ISSUE THREAD

**Issue by NikeSchuh** [kangarko/Boss#351]
I cant choose which boss should spawn!
If i click on the Egg Nothing happens …
MC Version : 1.12.2
Spigot Version : git-Spigot-dcd1643-e60fc34 (MC: 1.12.2) (Version 1.12.2-R.0.1-Snapshot)
No Errors occour in the Console

**Comment by kangarko** [comment]
Thank you this is confirmed and will be available in shortest possible time, few days max.

**Comment by kangarko** [comment]
Fixed since
