### ISSUE TITLE
1.14.3: 'Kill Bosses' Removing Extra Mobs

### ISSUE THREAD

**Issue by TakoidGit** [kangarko/Boss#353]
Hello. I am using Boss 3.3.6 on Paper 1.14.3 build 120. When I use the 'Kill Bosses' button for a Boss that has not spawned in the world (0% chances, no timed spawning), extra mobs are being removed.

I have discovered after further testing that it seems to be mobs with NBT info that are being removed such as villagers with jobs/trades, armor stands spawned from plugins, etc.

**Comment by kangarko** [comment]
Thank you, I solved that problem. Apology for the issue.
