### ISSUE TITLE
1.14.3: Can't edit drop chances, due to 'wither rose'?

### ISSUE THREAD

**Issue by JustKavis** [kangarko/Boss#354]
The title essentially says it all, I'm not able to edit the drop chance for a mob drop if it contains some flowers it seems. You can find my boss folder here: https://drive.google.com/open?id=1z3H_jKbu8K5qLSWIm9ucu8q0nnlKqkrp

**Comment by kangarko** [comment]
Hey,

please try using the next version, I am pretty sure we solved the issue:

![a](https://i.imgur.com/Et4bsAN.gifv)

**Comment by JustKavis** [comment]
Alright I will!
