### ISSUE TITLE
1.14.3: Error from Boss?

### ISSUE THREAD

**Issue by supertakeru** [kangarko/Boss#356]
1) Be clear. Tell me your current situation, desired situation and your problem.
Server is crashing, I asked Paper devs and they said to refer to you for this problem. Can you give some insight?

https://pastebin.com/5vPNniDU

They highlighted this line
org.mineacademy.boss.int. .lPT1.const(SourceFile:1436)

Thank you.

**Comment by kangarko** [comment]
Thanks, reported to PaperSpigot.

Matej

**Comment by kangarko** [comment]
Disable Setup.Hook_ProtocolLib for now until this is fixed.

**Comment by kangarko** [comment]
This is a known long standing issue, we are addressing this problem
