### ISSUE TITLE
Improvement API (CustomItems Plugin)

### ISSUE THREAD

**Issue by Lastphysics** [kangarko/Boss#358]
Im using a custom item plugin and I heard that other plugins need to get the API of it, so that they can work together.
Could you make it ? So I will be able to make customitems drops out of bosses

I asked the owner of the plugin for the API, thats what he gave me :
https://github.com/jojodmo/CustomItems/wiki/Developer-API

**Comment by kangarko** [comment]
Thank you for your request!

At present we don't have the capacity to add third party plugins such as this, however Boss also has an API so that the dev of CustomItems can simply listen to BossDeathEvent and add its drops there instead.

Matej
