### ISSUE TITLE
Boss Suggestions

### ISSUE THREAD

**Issue by MsArtix** [kangarko/Boss#36]
Sorry for the length. 

Custom Death messages for players and Bosses
Pretty self explanatory, just like ChatControl has custom death messages make some here as well with randomness. Then make it so one is displayed randomly on death (can toggle messages on/off as well as randomness) 
- 'BOSSNAME has beheaded PLAYER'
- 'PLAYER was slaughtered by BOSSNAME'
- 'PLAYER was skinned alive by BOSSNAME'
The messages below would be based off the person who dealt the final blow to the boss
- 'PLAYER has defeated BOSSNAME'
- 'BOSSNAME was stabbed in the heart by PLAYER'
- 'PLAYER killed BOSSNAME with a WEAPONNAME' (WEAPONNAME would be whatever item was used to kill the boss like Diamond Sword or Bow n Arrow)

NewSkills:
FireSplash:
Have the boss drop lava or fire around the area which damages the player if stepped in. The lava/fire doesnt go away until put out by player.

Invulnerable Regen:
Make the boss go invincible when it reaches XX% of health then it regenerates XX% amount of health and then when its done regenerating it becomes killable again. 

Action necessary kills:
This part might be more complicated but make it so the boss goes invincible UNTIL a certain criteria is met. For example, there are a number of (configurable by the person setting up the region) pressure plates around the boss area. There is a command that needs to be done and then hit the pressure plate or lever/button for it to be needed for the boss killpart. During the fight they all need to be active (stepped on or pushed/switched) at the same time for the boss to become killable again. (once all plates are stepped on the boss becomes killable) This would encourage teamwork for killing select bosses. Could also use levers, or buttons to be switched, This could go either way, they all need to be active at the same time, or they can be activated at any time (could even set it up so there can be a time limit for how long they have to push all the buttons/plates/levers) Could even make it so the buttons/plates have to be switched in a certain order (broadcast or send a message to the player to let them know they screwed up or its a successful press/switch) 

PriorityTarget:
The boss would target the player who is doing the most damage

Invulnerable Target:
Make the boss invincible for X amount of seconds every X seconds. So make the boss go invincible for 5 seconds every 30 seconds and while the boss is invincible it still targets/kills players. Mind you that if it goes invincible for 5 seconds every 30 seconds it will only be killable for 25 seconds out of every 30 seconds, or make it so the counter doesnt count the XX seconds it cant be killed. 

FakeBoss:
Have the boss spawn "copies" of himself but the copies only take 1-2 hits to kill and they dont drop anything. This would confuse players who are fighting the boss. 

NOTE: If I think of more things I will add them to this ticket so I dont keep creating more tickets. Thanks and I hope to see some or all of this implemented into the plugin if possible :D if some of this is not possible please let me know. Thank you.

**Comment by kangarko** [comment]
Great suggestions! Yes I believe most of them can be implemented and will be welcomed by you and the players. I will look forward to add them in the end of the next week or so.

**Comment by kangarko** [comment]
Some of them were implemented/are being/will be implemented. Thanks again!
