### ISSUE TITLE
Prevent boss spawning in grief prevention, claims

### ISSUE THREAD

**Issue by iTz-MrAnonymous** [kangarko/Boss#360]
I was wondering if it would be possible to prevent bosses spawning inside a claim made by grief prevention. As I want to create a mob that spawns in the overworld, pretty much whenever with little to no conditions but would prefer if there was an option to prevent bosses spawning inside of a claim. Thanks

**Comment by kangarko** [comment]
Apology for a late reply.

Is there a flag such as 'no-mob-spawn' in your claim or do you want to prevent it in any claim?

**Comment by iTz-MrAnonymous** [comment]
Hello,
that's okay. So I don't have any flags set in the claims, as we do not have GriefPrevention Flags installed. Should I install that plugin? I would like it disabled in all claims since we use worldguard for spawn and other server builds.

**Comment by kangarko** [comment]
Yes try installing that plugin. Also set Egg_Spawning.Spawn_If_Event_Cancelled to false in settings.yml

**Comment by kangarko** [comment]
Closing in good faith this has been resolved, if not comment below
