### ISSUE TITLE
Boss Spawns much Different in 1.14.3 than 1.13.2

### ISSUE THREAD

**Issue by Dynamite99** [kangarko/Boss#363]
Hello, I am using Paper 1.14.3 and using boss on my server. The mob spawns seem to be exponentially more in my boss regions and even the boss mobs I have spawning naturally. This also occurs with normal mobs, despite no settings changed in the spigot.yml. Any ideas?

**Comment by Foxxite** [comment]
The mob spawning has been changed in 1.14, you can lower it in the spigot.yml

**Comment by kangarko** [comment]
As Foxxite mentioned, the changes were in the server itself. I recommend you increase Timed_Spawning.Period and lower the spawn chances as low as to 1%.

I assume you may already have them on 1%, so I will work on a new system that allows you to set a decimal point such as 0.1% or even 0.001% to further decrease them.

**Comment by kangarko** [comment]
Closing in good faith this has been resolved, we have 0.0x1% changes in the roadmap
