### ISSUE TITLE
More variables for skills to customize for each boss.

### ISSUE THREAD

**Issue by MoonOfAutumn** [kangarko/Boss#365]
I really hope that the skills is for each certain boss. For instance, if i want to make a boss which could make players nearby become poisoned by giving potion effect and another boss which could make players nearby become bleed by giving potion effect too, I have to program for each boss with API.(I have to create a skill named potion-spider, potion-wither) and that's impossible for many server owners who can't program. 

Here's an example for good configurable skills.
`Skills:`
`- Confuse Player(radius=10)`
`- Potions(effect='poison 2, 10 seconds')`

I wish developer teams could make Boss  which is a great plugin better and better.

(My English is not very good, I'm sorry for that.)

**Comment by kangarko** [comment]
Thanks, that is unfortunately currently impossible but it's our top priority once we start taking suggestions again. You can just follow up on the Roadmap on the Issues Page.
