### ISSUE TITLE
Custom Biome integration? 

### ISSUE THREAD

**Issue by Spzatak** [kangarko/Boss#367]
I want to integrate boss to run wild spawns on an custom gen map specifically,
but I am not sure how i would go about getting boss to read the custom gen biomes seperately
from regular biomes???

For reference i eman this generator https://www.spigotmc.org/resources/realisticworldgenerator.15905/

**Comment by kangarko** [comment]
I am afraid this won't go, I -think- they are only using the existing biome map in Spigot however sending packets with custom values that we can't catch.

**Comment by Spzatak** [comment]
I see i see. I will test it personally and let you know :D However thank you very much, 10/10 response time. I If they do read as regaular biomes, perhaps I can easily just set up per world spawning 🗡
Perhaps you can have seperate biome based mob spawn lists per world? 
I regret to admit i haven't had Hands on testing with it yet, as I amcurrently still trying to get to 1.14.3 haha.
Again, thank you.

**Comment by kangarko** [comment]
Awesome appreciated that :)

You can just configure the Biomes or Worlds in which the bosses will spawn. Or ask a friend who knows coding to use our friendly API to prevent the spawn.

If you appreciated my reply consider shouting a quick review, would mean a lot <3 Sometimes takes longer to reply depending on my workload.
