### ISSUE TITLE
The Log_Lag_Over_Milis now outputs all messages when set to 0. Set to -1 to disable instead.

### ISSUE THREAD

**Issue by mrcoffee1026** [kangarko/Boss#369]
This is not a true statement.  When set to -1, the console floods messages about how long it took to perform the "keep region task".  I have to change the setting to Region_Keeping:
  Enabled: false
In order to stop it.

*Identical problem with chatControl... setting to -1 does NOT disable the messages, it effectively does what you said 0 would do (show all messages)
[21:18:26 INFO]: [ChatControl 8.2.13] Command Rules Check took 0 ms
[21:18:26 INFO]: [ChatControl 8.2.13] Command event took 0 ms

**Comment by kangarko** [comment]
Thanks, will take a look into it. Apology for the big inconvenience.
