### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by Dmitry1924** [kangarko/Boss#37]
1)The developer, I elaborate on my question. I can drop the sheet to add objects created by using the - https://www.spigotmc.org/wiki/custom-item-models-in-1-9-and-up/ ? They will not lose their texture when you add?
2)If I do that the boss appeared in the region, can I limit the number? Let's say that 1 boss spawn every 10 minutes?

**Comment by kangarko** [comment]
Hello,

1. You can try, I don't know, it should work but if it won't I cannot fix that.

2. This is planned and coming soon :)
