### ISSUE TITLE
how to translate the boss  gui

### ISSUE THREAD

**Issue by MusicTW** [kangarko/Boss#371]
I want to translate the boss gui in my server
And i wanna how to do

**Comment by kangarko** [comment]
Hello,

thank you for your inquiry. At present the Menu system is tied up with the rendering and thus it cannot be translated without it breaking your menus. You can translate other messages in your localization/ folder.

Thank you for your understanding and I apology that this is not possible within the scope of the plugin

Matej
Founder & lead dev of MineAcademy
