### ISSUE TITLE
Could not load 'plugins/Boss-3.4.2.jar' in folder 'plugins'

### ISSUE THREAD

**Issue by Ragnarak123** [kangarko/Boss#372]
I'm using 1.8.8 Spigot and Plugin's latest version. And there is errors.

https://pastebin.com/qwz2ndJg

and there is my plugins

![image](https://user-images.githubusercontent.com/40489713/61255096-e06da000-a76f-11e9-9136-e8b01d1fef6c.png)

**Comment by kangarko** [comment]
Thanks, will be solved.
