### ISSUE TITLE
Boss gives money on death or execute console commands

### ISSUE THREAD

**Issue by TurtLeLaaG** [kangarko/Boss#376]
Hello Sir,
This is actually a question.
Is there any way i can make the boss give player (the killer) money when it is killed.
I want to make the console give the amount
[using some format like - eco give {killer} amount ]

I dont know how to detect the killer or how to make the console put the command.

**Comment by kangarko** [comment]
Hey!

Yes sure, enable Inventory Drops in Death->Drops and then head back to Settings->Commands->Death By Player commands and set that eco command from there :)
