### ISSUE TITLE
CAnt run boss after creating a BOSS

### ISSUE THREAD

**Issue by chi27870** [kangarko/Boss#379]
IF I delete the BOSS folder, everything goes back to normal. I am giving the BOSS Armor from MMO Items Premium with variable stats. Not sure if that makes a difference. This is the error log.

------------------------------------[ 22.07.2019 13:38:40 ]-----------------------------------
Boss 3.4.4 encountered a LPt9
Running CraftBukkit 1.14.2-R0.1-SNAPSHOT and Java 1.8.0_201
Plugins: CoreProtect v2.17.5, WorldEdit v7.0.0;214af8a, GroupManager v0.2.0, JumpPads v1.22.2, PlaceholderAPI v2.10.3, DeluxeCommands v1.9.0, Boss v3.4.4, ChatControl v5.8.3, Holograms v2.8-SNAPSHOT, ProtocolLib v4.5.0-SNAPSHOT, WorldGuard v7.0.1-beta-01;14e7525, DeathMessagesPrime v1.14.5, LibsDisguises v9.8.2-SNAPSHOT, AdvancedPortals v0.2.0, ChatReaction v1.8.0, VotingPlugin v5.19.1, Images v1.0.6-SNAPSHOT, Confiscate v2.2.3, WolfyUtilities v1.2.1.1, DeluxeMenus v1.12.0, SaveRod v2.4.5, GSit v[2.6.3.0], LastHolo v46, Vault v1.7.2-b107, GriefPrevention v16.12.alpha.1, Essentials v2.17.0.0, GadgetsMenu v4.3.22, WarpSystem v3.1.13, MMOItems v4.7.3, RandomTP v1.0.7.2, Citizens v2.0.25-SNAPSHOT (build 1704), Quests v3.7.5, EssentialsProtect v2.17.0.0, EssentialsGeoIP v2.17.0.0, EssentialsAntiBuild v2.17.0.0, GriefPreventionFlags v5.4.0, EssentialsSpawn v2.17.0.0, WorldGuardExtraFlags v4.1.2, MyPet v3.4, dtlTraders v5.0.7
----------------------------------------------------------------------------------------------

More Information: 
Malformed configuration! Key 'Metadata.Entity.661a66c1-359e-4111-b708-c63e864fc974' in data.db must be List but got MemorySection: 'MemorySection[path='Metadata.Entity.661a66c1-359e-4111-b708-c63e864fc974', root='YamlConfiguration']'
LPt9 Report / Malformed configuration! Key 'Metadata.Entity.661a66c1-359e-4111-b708-c63e864fc974' in data.db must be List but got MemorySection: 'MemorySection[path='Metadata.Entity.661a66c1-359e-4111-b708-c63e864fc974', root='YamlConfiguration']'
	 at org.mineacademy.boss.double. .d.const(SourceFile:1329)
	 at org.mineacademy.boss.double. .d.do(SourceFile:475)
	 at org.mineacademy.boss.double. .d.goto(SourceFile:766)
	 at org.mineacademy.boss.double. .d.void(SourceFile:866)
	 at org.mineacademy.boss.double. .Aux$protected.protected(SourceFile:321)
	 at org.mineacademy.boss.double. .Aux$protected.const(SourceFile:310)
	 at org.mineacademy.boss.double. .d.const(SourceFile:283)
	 at org.mineacademy.boss.double. .Aux$protected.<init>(SourceFile:305)
	 at org.mineacademy.boss.double. .Aux$protected.<clinit>(SourceFile:297)
	 at org.mineacademy.boss.double. .lPT6.onEnable(SourceFile:270)
	 at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
	 at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352)
	 at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:416)
	 at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:458)
	 at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:372)
----------------------------------------------------------------------------------------------

Please help. Thanks for the support!!

**Comment by chi27870** [comment]
THis is the data.db file

# 
# This file stores various data you create via the plugin.
# 
#  ** THE FILE IS MACHINE GENERATED. PLEASE DO NOT EDIT **

Metadata:
  Entity:
    661a66c1-359e-4111-b708-c63e864fc974:
      661a66c1-359e-4111-b708-c63e864fc974:
      - Boss%-%KaBoss%-%Zombie_Knight
    372afbc7-bde5-4d17-80c1-70f430537356:
      661a66c1-359e-4111-b708-c63e864fc974:
      - Boss%-%KaBoss%-%Zombie_Knight
      372afbc7-bde5-4d17-80c1-70f430537356:
      - Boss%-%KaBoss%-%Zombie_Knight
    ce762a58-6eeb-4e8e-88bb-c2576e04f1f4:
      661a66c1-359e-4111-b708-c63e864fc974:
      - Boss%-%KaBoss%-%Zombie_Knight
      372afbc7-bde5-4d17-80c1-70f430537356:
      - Boss%-%KaBoss%-%Zombie_Knight
      ce762a58-6eeb-4e8e-88bb-c2576e04f1f4:
      - Boss%-%KaBoss%-%Zombie_Knight
    b8beae86-2d37-417c-923f-e9ec17fd6e1a:
      661a66c1-359e-4111-b708-c63e864fc974:
      - Boss%-%KaBoss%-%Zombie_Knight
      372afbc7-bde5-4d17-80c1-70f430537356:
      - Boss%-%KaBoss%-%Zombie_Knight
      b8beae86-2d37-417c-923f-e9ec17fd6e1a:
      - Boss%-%KaBoss%-%Zombie_Knight
      ce762a58-6eeb-4e8e-88bb-c2576e04f1f4:
      - Boss%-%KaBoss%-%Zombie_Knight
    f60b01ae-a422-43b8-b35c-8b3588cd906e:
      661a66c1-359e-4111-b708-c63e864fc974:
      - Boss%-%KaBoss%-%Zombie_Knight
      372afbc7-bde5-4d17-80c1-70f430537356:
      - Boss%-%KaBoss%-%Zombie_Knight
      b8beae86-2d37-417c-923f-e9ec17fd6e1a:
      - Boss%-%KaBoss%-%Zombie_Knight
      ce762a58-6eeb-4e8e-88bb-c2576e04f1f4:
      - Boss%-%KaBoss%-%Zombie_Knight
      f60b01ae-a422-43b8-b35c-8b3588cd906e:
      - Boss%-%KaBoss%-%Zombie_Knight
    3371d42a-578c-4100-897d-038d75980c8d:
      661a66c1-359e-4111-b708-c63e864fc974:
      - Boss%-%KaBoss%-%Zombie_Knight
      372afbc7-bde5-4d17-80c1-70f430537356:
      - Boss%-%KaBoss%-%Zombie_Knight
      b8beae86-2d37-417c-923f-e9ec17fd6e1a:
      - Boss%-%KaBoss%-%Zombie_Knight
      ce762a58-6eeb-4e8e-88bb-c2576e04f1f4:
      - Boss%-%KaBoss%-%Zombie_Knight
      f60b01ae-a422-43b8-b35c-8b3588cd906e:
      - Boss%-%KaBoss%-%Zombie_Knight
      3371d42a-578c-4100-897d-038d75980c8d:
      - Boss%-%KaBoss%-%Zombie_Knight
    9e6284cc-a5b9-4ff4-9531-e7759e61ffc3:
      661a66c1-359e-4111-b708-c63e864fc974:
      - Boss%-%KaBoss%-%Zombie_Knight
      372afbc7-bde5-4d17-80c1-70f430537356:
      - Boss%-%KaBoss%-%Zombie_Knight
      b8beae86-2d37-417c-923f-e9ec17fd6e1a:
      - Boss%-%KaBoss%-%Zombie_Knight
      9e6284cc-a5b9-4ff4-9531-e7759e61ffc3:
      - Boss%-%KaBoss%-%Zombie_Knight
      ce762a58-6eeb-4e8e-88bb-c2576e04f1f4:
      - Boss%-%KaBoss%-%Zombie_Knight
      f60b01ae-a422-43b8-b35c-8b3588cd906e:
      - Boss%-%KaBoss%-%Zombie_Knight
      3371d42a-578c-4100-897d-038d75980c8d:
      - Boss%-%KaBoss%-%Zombie_Knight
    c37a202f-cd11-4a0a-9582-a8d6c43ed8af:
      661a66c1-359e-4111-b708-c63e864fc974:
      - Boss%-%KaBoss%-%Zombie_Knight
      c37a202f-cd11-4a0a-9582-a8d6c43ed8af:
      - Boss%-%KaBoss%-%Zombie_Knight
      372afbc7-bde5-4d17-80c1-70f430537356:
      - Boss%-%KaBoss%-%Zombie_Knight
      b8beae86-2d37-417c-923f-e9ec17fd6e1a:
      - Boss%-%KaBoss%-%Zombie_Knight
      9e6284cc-a5b9-4ff4-9531-e7759e61ffc3:
      - Boss%-%KaBoss%-%Zombie_Knight
      ce762a58-6eeb-4e8e-88bb-c2576e04f1f4:
      - Boss%-%KaBoss%-%Zombie_Knight
      f60b01ae-a422-43b8-b35c-8b3588cd906e:
      - Boss%-%KaBoss%-%Zombie_Knight
      3371d42a-578c-4100-897d-038d75980c8d:
      - Boss%-%KaBoss%-%Zombie_Knight
    d729701d-d23c-4861-9ee6-c72672ea7072:
      661a66c1-359e-4111-b708-c63e864fc974:
      - Boss%-%KaBoss%-%Zombie_Knight
      c37a202f-cd11-4a0a-9582-a8d6c43ed8af:
      - Boss%-%KaBoss%-%Zombie_Knight
      372afbc7-bde5-4d17-80c1-70f430537356:
      - Boss%-%KaBoss%-%Zombie_Knight
      b8beae86-2d37-417c-923f-e9ec17fd6e1a:
      - Boss%-%KaBoss%-%Zombie_Knight
      9e6284cc-a5b9-4ff4-9531-e7759e61ffc3:
      - Boss%-%KaBoss%-%Zombie_Knight
      d729701d-d23c-4861-9ee6-c72672ea7072:
      - Boss%-%KaBoss%-%Zombie_Knight
      ce762a58-6eeb-4e8e-88bb-c2576e04f1f4:
      - Boss%-%KaBoss%-%Zombie_Knight
      f60b01ae-a422-43b8-b35c-8b3588cd906e:
      - Boss%-%KaBoss%-%Zombie_Knight
      3371d42a-578c-4100-897d-038d75980c8d:
      - Boss%-%KaBoss%-%Zombie_Knight
    94673008-1d67-4b7c-8cc9-d2bd2d64f53f:
      661a66c1-359e-4111-b708-c63e864fc974:
      - Boss%-%KaBoss%-%Zombie_Knight
      c37a202f-cd11-4a0a-9582-a8d6c43ed8af:
      - Boss%-%KaBoss%-%Zombie_Knight
      372afbc7-bde5-4d17-80c1-70f430537356:
      - Boss%-%KaBoss%-%Zombie_Knight
      b8beae86-2d37-417c-923f-e9ec17fd6e1a:
      - Boss%-%KaBoss%-%Zombie_Knight
      9e6284cc-a5b9-4ff4-9531-e7759e61ffc3:
      - Boss%-%KaBoss%-%Zombie_Knight
      d729701d-d23c-4861-9ee6-c72672ea7072:
      - Boss%-%KaBoss%-%Zombie_Knight
      ce762a58-6eeb-4e8e-88bb-c2576e04f1f4:
      - Boss%-%KaBoss%-%Zombie_Knight
      f60b01ae-a422-43b8-b35c-8b3588cd906e:
      - Boss%-%KaBoss%-%Zombie_Knight
      3371d42a-578c-4100-897d-038d75980c8d:
      - Boss%-%KaBoss%-%Zombie_Knight
      94673008-1d67-4b7c-8cc9-d2bd2d64f53f:
      - Boss%-%KaBoss%-%Zombie_Knight
    fea10fde-3249-43c2-a291-00a8d05737d7:
      661a66c1-359e-4111-b708-c63e864fc974:
      - Boss%-%KaBoss%-%Zombie_Knight
      fea10fde-3249-43c2-a291-00a8d05737d7:
      - Boss%-%KaBoss%-%Zombie_Knight
      c37a202f-cd11-4a0a-9582-a8d6c43ed8af:
      - Boss%-%KaBoss%-%Zombie_Knight
      372afbc7-bde5-4d17-80c1-70f430537356:
      - Boss%-%KaBoss%-%Zombie_Knight
      b8beae86-2d37-417c-923f-e9ec17fd6e1a:
      - Boss%-%KaBoss%-%Zombie_Knight
      9e6284cc-a5b9-4ff4-9531-e7759e61ffc3:
      - Boss%-%KaBoss%-%Zombie_Knight
      d729701d-d23c-4861-9ee6-c72672ea7072:
      - Boss%-%KaBoss%-%Zombie_Knight
      ce762a58-6eeb-4e8e-88bb-c2576e04f1f4:
      - Boss%-%KaBoss%-%Zombie_Knight
      f60b01ae-a422-43b8-b35c-8b3588cd906e:
      - Boss%-%KaBoss%-%Zombie_Knight
      3371d42a-578c-4100-897d-038d75980c8d:
      - Boss%-%KaBoss%-%Zombie_Knight
      94673008-1d67-4b7c-8cc9-d2bd2d64f53f:
      - Boss%-%KaBoss%-%Zombie_Knight
    b1e5377a-2363-4f11-994e-dc6877f33a20:
      661a66c1-359e-4111-b708-c63e864fc974:
      - Boss%-%KaBoss%-%Zombie_Knight
      b1e5377a-2363-4f11-994e-dc6877f33a20:
      - Boss%-%KaBoss%-%Zombie_Knight
      fea10fde-3249-43c2-a291-00a8d05737d7:
      - Boss%-%KaBoss%-%Zombie_Knight
      c37a202f-cd11-4a0a-9582-a8d6c43ed8af:
      - Boss%-%KaBoss%-%Zombie_Knight
      372afbc7-bde5-4d17-80c1-70f430537356:
      - Boss%-%KaBoss%-%Zombie_Knight
      b8beae86-2d37-417c-923f-e9ec17fd6e1a:
      - Boss%-%KaBoss%-%Zombie_Knight
      9e6284cc-a5b9-4ff4-9531-e7759e61ffc3:
      - Boss%-%KaBoss%-%Zombie_Knight
      d729701d-d23c-4861-9ee6-c72672ea7072:
      - Boss%-%KaBoss%-%Zombie_Knight
      ce762a58-6eeb-4e8e-88bb-c2576e04f1f4:
      - Boss%-%KaBoss%-%Zombie_Knight
      f60b01ae-a422-43b8-b35c-8b3588cd906e:
      - Boss%-%KaBoss%-%Zombie_Knight
      3371d42a-578c-4100-897d-038d75980c8d:
      - Boss%-%KaBoss%-%Zombie_Knight
      94673008-1d67-4b7c-8cc9-d2bd2d64f53f:
      - Boss%-%KaBoss%-%Zombie_Knight
    680e00cc-b3d6-4aa4-80e7-94aa9d438c72:
      661a66c1-359e-4111-b708-c63e864fc974:
      - Boss%-%KaBoss%-%Zombie_Knight
      b1e5377a-2363-4f11-994e-dc6877f33a20:
      - Boss%-%KaBoss%-%Zombie_Knight
      fea10fde-3249-43c2-a291-00a8d05737d7:
      - Boss%-%KaBoss%-%Zombie_Knight
      b8beae86-2d37-417c-923f-e9ec17fd6e1a:
      - Boss%-%KaBoss%-%Zombie_Knight
      9e6284cc-a5b9-4ff4-9531-e7759e61ffc3:
      - Boss%-%KaBoss%-%Zombie_Knight
      ce762a58-6eeb-4e8e-88bb-c2576e04f1f4:
      - Boss%-%KaBoss%-%Zombie_Knight
      94673008-1d67-4b7c-8cc9-d2bd2d64f53f:
      - Boss%-%KaBoss%-%Zombie_Knight
      680e00cc-b3d6-4aa4-80e7-94aa9d438c72:
      - Boss%-%KaBoss%-%Zombie_Knight
      c37a202f-cd11-4a0a-9582-a8d6c43ed8af:
      - Boss%-%KaBoss%-%Zombie_Knight
      372afbc7-bde5-4d17-80c1-70f430537356:
      - Boss%-%KaBoss%-%Zombie_Knight
      d729701d-d23c-4861-9ee6-c72672ea7072:
      - Boss%-%KaBoss%-%Zombie_Knight
      f60b01ae-a422-43b8-b35c-8b3588cd906e:
      - Boss%-%KaBoss%-%Zombie_Knight
      3371d42a-578c-4100-897d-038d75980c8d:
      - Boss%-%KaBoss%-%Zombie_Knight
    0f2c3bc6-779e-4b23-9d09-3f3fd13dfe0a:
      661a66c1-359e-4111-b708-c63e864fc974:
      - Boss%-%KaBoss%-%Zombie_Knight
      b1e5377a-2363-4f11-994e-dc6877f33a20:
      - Boss%-%KaBoss%-%Zombie_Knight
      fea10fde-3249-43c2-a291-00a8d05737d7:
      - Boss%-%KaBoss%-%Zombie_Knight
      b8beae86-2d37-417c-923f-e9ec17fd6e1a:
      - Boss%-%KaBoss%-%Zombie_Knight
      9e6284cc-a5b9-4ff4-9531-e7759e61ffc3:
      - Boss%-%KaBoss%-%Zombie_Knight
      ce762a58-6eeb-4e8e-88bb-c2576e04f1f4:
      - Boss%-%KaBoss%-%Zombie_Knight
      94673008-1d67-4b7c-8cc9-d2bd2d64f53f:
      - Boss%-%KaBoss%-%Zombie_Knight
      680e00cc-b3d6-4aa4-80e7-94aa9d438c72:
      - Boss%-%KaBoss%-%Zombie_Knight
      c37a202f-cd11-4a0a-9582-a8d6c43ed8af:
      - Boss%-%KaBoss%-%Zombie_Knight
      372afbc7-bde5-4d17-80c1-70f430537356:
      - Boss%-%KaBoss%-%Zombie_Knight
      d729701d-d23c-4861-9ee6-c72672ea7072:
      - Boss%-%KaBoss%-%Zombie_Knight
      0f2c3bc6-779e-4b23-9d09-3f3fd13dfe0a:
      - Boss%-%KaBoss%-%Zombie_Knight
      f60b01ae-a422-43b8-b35c-8b3588cd906e:
      - Boss%-%KaBoss%-%Zombie_Knight
      3371d42a-578c-4100-897d-038d75980c8d:
      - Boss%-%KaBoss%-%Zombie_Knight
  Block: {}
Spawners:
  Stored: {}
Boss:
  Zombie_Knight:
    Loaded: 1563765126010

**Comment by kangarko** [comment]
Please remove your data.db and update Boss to the latest version.
