### ISSUE TITLE
Add please

### ISSUE THREAD

**Issue by Dmitry1924** [kangarko/Boss#38]
Please add ItemStack serialization
https://www.spigotmc.org/wiki/itemstack-serialization/

So I could add items with my texture in the drop of the boss
- https://www.spigotmc.org/wiki/custom-item-models-in-1-9-and-up/

**Comment by kangarko** [comment]
We already have it:

![a](https://i.imgur.com/TyBt8zq.png)

Just use Boss#getDrops().add and create a new BossDrop class with your itemstack. 

The next version will have a BossDrop class that can be easily instatiated.
