### ISSUE TITLE
[Issue] Boss creating doesnt work propely

### ISSUE THREAD

**Issue by NikeSchuh** [kangarko/Boss#380]
By Nike_Schuh
1.13.2 Spigot

//Plugin Folder

[Boss.zip](https://github.com/kangarko/Boss/files/3418787/Boss.zip)

I cant create Bosses when i try it just sais Boss Creation has been abandoned 
But it creates a Boss and if i Reload the Server/Plugin it sais
Ouups, reloading failes!

Raw Error Output
https://pastebin.com/BjVDeyzt

**Comment by kangarko** [comment]
Hello,

you can only use ASCII letters, i.e. no German äö letters etc. in your Boss names. Simply remove the ?? letters from your Boss .yml file name and it will load.

**Comment by NikeSchuh** [comment]
Ah ok
