### ISSUE TITLE
Spawn Buildings [Feature Request]

### ISSUE THREAD

**Issue by JustKavis** [kangarko/Boss#381]
It would be nice that there would be an option that for example, if a specific mob dies or spawns, they would also spawn a specified structure.

I would imagine how it would work is that you would you a "wand" to specify what structure you want it to spawn.

**Comment by kangarko** [comment]
Thank you for your suggestion, however as per our announcement we cannot take suggestions right now:

https://www.spigotmc.org/resources/%E2%98%9B-boss%E2%84%A2-custom-monsters-and-animals-on-your-server-1-8-9-1-14-4.46497/update?update=286813

Thanks
