### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by PengBread** [kangarko/Boss#382]
I'm getting this error spamming in my console after updating Boss plugin to the latest version.

23.07 07:56:11 [Server] ERROR Could not pass event EntityDamageByEntityEvent to Boss v3.4.1
23.07 07:56:11 [Server] INFO java.lang.NullPointerException: null

**Comment by kangarko** [comment]
Your error is incomplete, please post the entire stack trace.

**Comment by PengBread** [comment]
My bad, i only looked it in console instead my log file.
https://pastebin.com/KM34HcWb

**Comment by kangarko** [comment]
Just update your Boss please

**Comment by PengBread** [comment]
i just realize im using versions that are lower by 5 versions. Sorry for the false info.
