### ISSUE TITLE
Adding decimal numbers to drop chances

### ISSUE THREAD

**Issue by DogeTennant** [kangarko/Boss#383]
Ahoj, chtěl sem se zeptat, jestli by bylo možný přidat, abych mohl nastavit drop nějakého itemu u bosse pod 1%, protože plánuju udělat dropy, kde i 1% je moc velká šance, takže bych potřeboval, aby šlo udělat třeba 0.1% nebo i třeba nižší, třeba 0.025% všimnul sem si že někdo  už to tu psal ,ale to bylo před více jak rokem, tak jsem ten nápad chtěl tak nějak oživit, a doufat že se to brzy přidá. :D 

Díky.

**Comment by kangarko** [comment]
Ahoj,

áno plánujeme to v roadmap:

https://github.com/kangarko/Boss/issues/21

Ale momentálne nám do toho vošli iné veci a zatiaľ vznikli nejaké problémy zo stabilitou takže našou prioritiou je aby plugin bežal naprosto bezchybne predtým než začneme znovu prepisovať a doplňovať kód: https://www.spigotmc.org/resources/%E2%98%9B-boss%E2%84%A2-custom-monsters-and-animals-on-your-server-1-8-9-1-14-4.46497/update?update=286813

Ďakujem za porozumenie.
