### ISSUE TITLE
[Question] Commands

### ISSUE THREAD

**Issue by NikeSchuh** [kangarko/Boss#384]
Hey!
I have following Problem if i let the Boss run the Death By Player Command
upc addPlayerPermission {Player} boss1 
It gets executed from the Player but i want it to get executed by the console
Is there a way to let the console execute this command?

**Comment by kangarko** [comment]
Hello,

the player commands are run with the specific player permissions.

Matej

**Comment by kangarko** [comment]
To the next version, I added Death.Run_Player_Commands_As_Player option to settings.yml. Set it to false to run cmds as the console :)

**Comment by NikeSchuh** [comment]
Ok ty :) 5 stars
