### ISSUE TITLE
[Issue] Boss HP

### ISSUE THREAD

**Issue by NikeSchuh** [kangarko/Boss#385]
Version 1.13.2 Spigot

In the Spigot.yml i set the maximum to 200000000000000000048.0
And then i could set the Maximum hp over 2048
But there is still a Limit 2000000000000
And if i go above that number the Plugin sends me an Error

https://pastebin.com/gAyBBuGc

**Comment by kangarko** [comment]
The number overflows mathematical precision and the amount of memory it can allocate for the 'int' type (Spigot uses double). There's nothing we can do, don't use such ridiculous amounts just stick to low numbers and solve your problem in a better way than a hacky workaround like this.
