### ISSUE TITLE
Database Error

### ISSUE THREAD

**Issue by RobZenTL** [kangarko/Boss#386]
Hey, what happened: We start the server, everything is fine. When we restart the server the next time (after ~20 hrs) there occurs a database error and the plugin is disabled at the start.

This is the log:
https://pastebin.com/Wx1KfSg1

MC 1.8.8
Boss 3.3.5 - 3.4.5 (in every version)

If you need more information, let me know!

**Comment by kangarko** [comment]
If possible, use /boss butcher to remove all alive Bosses, if not just remove your data.db and start fresh.

**Comment by RobZenTL** [comment]
Yeah, we did that 10 times. And after the next restart this error occurs again.

**Comment by kangarko** [comment]
Please use 3.4.6 version of Boss.
