### ISSUE TITLE
Questions regarding spawning

### ISSUE THREAD

**Issue by JustKavis** [kangarko/Boss#388]
Hey!

So question, when configuring the spawn transformation, I am a bit confused. So when selecting the % value, for the menu for over world, nether, and end, how does it work? Would it be for example every (x) ticks there is a % value of a normal mob being transformed into a "Boss" mob? 

And is there a difference for the % value for the menu where one can tweak all of the biomes? Like is it separate from the first one I mentioned above? Do they interact in some sort of way? Do they transform mobs or just spawn them in?

And lastly what would be the recommended % value for both menus for the spawn rate of a, for example a zombie? Or is it recommended to tweak only one or the other? (I don't know since again, I'm not sure if they interact or not.

And is there a way to cap the amount of certain bosses allowed to be in the world?

Thanks and sorry if it was a bit long!

**Comment by kangarko** [comment]
Hey,

There are two concepts in Boss, converting and timed spawning, which one are you talking about?

For Timed Spawning, we spawn Boss in the time interval you set in Timed_Spawning.Delay and there is a percentage chance of spawning a Boss each time the interval hits. This can be anywhere from 5 second to 3 hours and more depending on your settings.

The Biomes settings is a whitelist for the main percentage conversion. That means that the percentage chance must hit as well as the mob or a random location we find must be in the correct biome from that list.

As for recommended value I suggest a very small number like 1% chance and timed spawning set on 5 hours. If you are constantly running boss these monsters will increases over time so you don't annoy players in 1-2 weeks. 

You can cap the max amount of Bosses in settings.yml per world and per chunk, see Limits.

Matej
