### ISSUE TITLE
Setting health and attribvutes of bosses when using BungeeChat

### ISSUE THREAD

**Issue by Tirco** [kangarko/Boss#389]
Hey! 

On my server, chat is handled by BungeeChat, and that makes it so that when Boss is awaiting input for health and other things, it doesn't work. 
Other than editing the bossfiles directly, is there an alternative way to set the health of a boss?

**Comment by kangarko** [comment]
No sorry, if another plugin is taking over the "event priority" pipeline of how Spigot fires events, Boss can't do anything about it, you'll have to manually edit your yml files.
