### ISSUE TITLE
Boss not spawning and Bug with Boss regions

### ISSUE THREAD

**Issue by JavituRec** [kangarko/Boss#39]
The Boss no spawning (no way) in regions (worldguard-Bossregions).

Boss: https://hastebin.com/copateluna.scala

Server version: 1.8.8
Boss plugin version: last

** _And When you select a zone with the emerald of "/ boss tools" emerald blocks fall and when you create the region they do not disappear._

All the best.

**Comment by kangarko** [comment]
Thanks, will be fixed asap.

**Comment by JavituRec** [comment]
Not work yet.

**Comment by kangarko** [comment]
I have accidentally not fixed the region visualization correctly, this is now patched.

As per the region spawning, it all works for me, see below. Make sure you have Timed_Spawning.Enabled on true. Post me your settings.yml as well please. Also make sure that monsters are allowed to spawn in that region.

![a](https://i.imgur.com/4e6BbaZ.png)

**Comment by JavituRec** [comment]
Hello,

My files:
Boss: https://hastebin.com/qobadebadi.go
Setting: https://hastebin.com/wexaxeviqo.http

Region not block spawning of mobs:
https://image.ibb.co/evjk2G/minonsrg.png

**Comment by kangarko** [comment]
Hey, I just wrote a quick article regarding two questions, you can read it at https://github.com/kangarko/Boss/wiki/Common-Issues

also, set Debug to [spawning] and post me the output. Try to notice where the problem may lie yourself if possible.

**Comment by JavituRec** [comment]
This spam in console but if you see my boss file the boss have a region.
https://hastebin.com/axogicepuc.md

**Comment by kangarko** [comment]
Are you actually inside of the region when the messages appear? Bosses spawn near players, not all around the world.

**Comment by JavituRec** [comment]
I am two blocks away from the region. The region is inside the building with a roof. Is it possible that he is trying to spawn the boss on the roof?

**Comment by kangarko** [comment]
Yes definitely. Try another region with an open area where bosses can spawn more naturally, walk in the middle of it, and test if the spawning works.

**Comment by JavituRec** [comment]
Yes, Its correct but can not spawn naturally two bosses in the same region

**Comment by kangarko** [comment]
Hey, please test out the next 1.5.3 available shortly, set Debug to [spawning] and tell me what the messages are.

**Comment by kangarko** [comment]
Closing in faith that it has been resolved.
