### ISSUE TITLE
 Name cannot be null!

### ISSUE THREAD

**Issue by Hushine** [kangarko/Boss#391]
Hello I want to ask, is this a serious problem?
![image](https://user-images.githubusercontent.com/53359553/61988952-ee1a0400-b052-11e9-89cb-6e11f5c3f063.png)

**Comment by kangarko** [comment]
Please post me your data.db

**Comment by Hushine** [comment]
this?
![image](https://user-images.githubusercontent.com/53359553/61995567-6ebd1c80-b0b4-11e9-9bd4-287733f372cd.png)

And also this plugin makes my server tps go down.
![67156119_443829043135211_7282971486866898944_n](https://user-images.githubusercontent.com/53359553/61995582-a6c45f80-b0b4-11e9-8c5b-5d0b73d03f55.png)

**Comment by kangarko** [comment]
Alright thanks, seems like the timed task is draining the server, please ZIP me your entire Boss folder, I need to take a look at settings.yml and individual Boss files.

**Comment by kangarko** [comment]
The 'Name cannot be null' issue was solved. Closing for now, return back to me with the ZIP folder of Boss so I can take a look at the lag issue
