### ISSUE TITLE
boss are not spawning in the region

### ISSUE THREAD

**Issue by healingparm** [kangarko/Boss#392]
help...
Version: 1.12.2
Mob are not spawning..

**Comment by healingparm** [comment]
[Boss.zip](https://github.com/kangarko/Boss/files/3441704/Boss.zip)
my settings

**Comment by LeePC** [comment]
보스 생성할 이름을 [M]좀비 파일을 영어로 전환시켜보세요
대부분 외국 플러그인들은 한글로 전환할시 에러를 발생시킵니다
그러니 대부분의 파일들을 영어로 전환시키면 될꺼라봅니다

**Comment by healingparm** [comment]
그렇군요....

**Comment by healingparm** [comment]
Not work...

**Comment by kangarko** [comment]
Hey,

can you please try changing the Boss name to English? 

Also it says "World world has no chance of spawning boss. No spawn.". To fix this you need to increase world spawn chances, see our Wiki:

![a](https://i.imgur.com/NjVJ0Sh.png) (https://github.com/kangarko/Boss/wiki/Common-Issues)

**Comment by healingparm** [comment]
Yes i try english..

**Comment by kangarko** [comment]
Closing, let me know if you will need any more help (just comment below)
