### ISSUE TITLE
Area of effect after death

### ISSUE THREAD

**Issue by ItsHoney** [kangarko/Boss#396]
Hi,

I'd like to request a feature that I think will be very cool for this plugin to have and is fairly easy to implement.

I want a feature, on Boss death, that a configurable region at the point of death is given a specific effect, which is also shown using the effect of particles.

The kind of effect I am looking for is kindof similar to how when a lingering potion is thrown onto an area.

**Comment by kangarko** [comment]
Hello,

I am sorry we are currently not taking new suggestions. However - do you mean just spawning the lingering potion at the given location - would that be sufficient?

**Comment by ItsHoney** [comment]
> 
> 
> Hello,
> 
> I am sorry we are currently not taking new suggestions. However - do you mean just spawning the lingering potion at the given location - would that be sufficient?

Yup that should be sufficient, the potion of lingering when spawned gives the effect in the region, which is what I am looking for as well!

**Comment by kangarko** [comment]
Great, I just leave this open, should be fairly easy to add

**Comment by kangarko** [comment]
Will be implemented.
