### ISSUE TITLE
I got a great idea

### ISSUE THREAD

**Issue by Flynndamsko** [kangarko/Boss#397]
What if I could configure specific bosses to not attack certain groups like vip or maybe noob.
I had this idea for a server where you achieve different ranks you will fight different bosses
maybe this is alrady a feature and if it is could you maybe show me how? i have a license <B luv your plugin alot!!

**Comment by Flynndamsko** [comment]
i also have an issue where i cant set the spawn layers 64 and obove. It doesnt change even though it gives a confirmation in chat. I mean i cant configure the mobs to spawn above the ground

**Comment by Flynndamsko** [comment]
im running on paper and minecraft version 1.14.4

**Comment by Flynndamsko** [comment]
nvm i just read you wont add new features i understand for stability. But maybe its not too hard because the groups already exists through vault/permissionsplugin.

**Comment by kangarko** [comment]
What do you mean by spawn layers?

**Comment by Flynndamsko** [comment]
Thanks!! I see you fixed it

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
