### ISSUE TITLE
Spawners are not loaded after restart / reload

### ISSUE THREAD

**Issue by PomborDaerri** [kangarko/Boss#399]
Hi,

I have a problem with Boss version 3.4.6 !

I make a spawner for my boss and after each restart or reload, spawners are not recognized. Therefore, spawners are spawning the vanilla mob and not the boss, I can't change the spawner again, I have to make another one.

I add you my config with logs.

[Boss.zip](https://github.com/kangarko/Boss/files/3451927/Boss.zip)

Thank you

**Comment by healingparm** [comment]
me to..

**Comment by kangarko** [comment]
Thank you, that will be fixed.
