### ISSUE TITLE
Boss Sugestion Region/Message

### ISSUE THREAD

**Issue by JavituRec** [kangarko/Boss#40]
Region- It would be great if the boss only left if the players attacked him and if the players die the boss teleported automatically to the region of spawnned that has configured.

 Message- A message when Boss spawned.

Time -  Boss spawned each X time. This it is include but it for all Bosses.

All the best.

**Comment by kangarko** [comment]
Hello,

Region: Thanks for pointing that out, but this is not possible with the current bukkit API, sorry.

Message: Thanks, I have noted that down.

Time: You can achieve this using Timed Spawning.
