### ISSUE TITLE
Dolphin boss aggressive - paper 1.13.2

### ISSUE THREAD

**Issue by BobbyMere** [kangarko/Boss#405]
How do I get mobs like dolphins, chickens, rabbits, and all other passive or non aggressive mobs, aggressive towards players?

**Comment by BobbyMere** [comment]
Also, is there a way to get the mobs to spawn under the water? Currently if you spawn a drowned under water, the actual mob spawns on top of the water

**Comment by kangarko** [comment]
Hey,

currently that's not possible, sorry, here's why: https://github.com/kangarko/Boss/wiki/Frequent-Questions-and-Tips#can-you-make-animals-aggressive--add-better-ai

Yeah the mobs always spawn on the uppermost surface block. I can add an option for that however.

Not sure what you mean by height mob spawn?

The placeholder is {killer}.

**Comment by BobbyMere** [comment]
oooh, ok. thank you

**Comment by kangarko** [comment]
Closing, let me know if you got more questions
