### ISSUE TITLE
1.13.2: how to remove 'tell' in the messages

### ISSUE THREAD

**Issue by BobbyMere** [kangarko/Boss#406]
When you click on death command, it says to simply do tell {message}, but 'tell' shows up in the message. 

Doing 'tell mmm' will show up as message saying 'tell mmm.' How do I remove the word tell from the message thats being displayed?

Or is there a way to disable the built in tell command since it's bugged? So I can run the actual tell raw command without the plugin interfering with it

**Comment by BobbyMere** [comment]
[Boss 2.zip](https://github.com/kangarko/Boss/files/3471290/Boss.2.zip)

**Comment by kangarko** [comment]
Hello,

the tell command is dynamic and is sent to the killer player(s).

What you can do is to create a command alias in commands.yml in your root server folder and give it a unique name that you call, such as b_tell as a workaround for your particular case.

Guide: https://bukkit.gamepedia.com/Commands.yml
