### ISSUE TITLE
1.13.2: Magma Cube splits 

### ISSUE THREAD

**Issue by BobbyMere** [kangarko/Boss#408]
Even with the magma cube splitting into babies as being off, it still splits. 

Turns out that slimes also split if they're in a slime chunk. Even with the split option off
[Boss 2.zip](https://github.com/kangarko/Boss/files/3474582/Boss.2.zip)

**Comment by kangarko** [comment]
Hey, apology for a late reply, we've been extraordinarily busy with mineacademy.org and I will get back to you within 24 hours.

**Comment by kangarko** [comment]
Houps totally forgot about you man, sorry! Just refreshed the ticket.

**Comment by kangarko** [comment]
Will be fixed in a future rewrite.
