### ISSUE TITLE
Variables

### ISSUE THREAD

**Issue by climeno** [kangarko/Boss#409]
Hi, is there some way to make in the broadcast commands say the last X players that killed the boss or the top X players that made most damage to the boss with any variable?

**Comment by kangarko** [comment]
Hello,

you can use the tell {killer} message that will send it to the last X players who killed the Boss (given that the Inventory Drops feature is enabled).

Matej

**Comment by climeno** [comment]
But i want to broadcast the message not only tell the X last players i want to make this:

--------------------------------------------------
BOSS X HAS BEEN DEFEATED!

MOST DAMAGE PLAYERS
1: {mostdamagebyplayer1}
2: {mostdamagebyplayer2}
3: {mostdamagebyplayer3}
-------------------------------------------------

Or

-----------------------------------------------
BOSS X HAS BEEN DEFEATED!

Lastest killers:

1- {killer1}
2- {killer2}
3- {killer3}
-------------------------------------------------------

**Comment by kangarko** [comment]
Sure, that is currently not possible but it's something I love to add, so I am leaving this open

**Comment by kangarko** [comment]
Will be implemented
