### ISSUE TITLE
1.13.2: Mobs of the same type

### ISSUE THREAD

**Issue by BobbyMere** [kangarko/Boss#413]
So it turns out that when using spawners, the mob limit is of that mob type and not the boss name. Say you have two different named zombies in the same area. One will take priority while not spawning the other. Is there to have two different named bosses of the same type spawn in the same area when using spawners?

**Comment by kangarko** [comment]
Hey,

this seems to be related to that we leave the spawner up to vanilla's rules, I am closing this but I left your other ticket opened here https://github.com/kangarko/Boss/issues/411
