### ISSUE TITLE
Spawn regions not working for me

### ISSUE THREAD

**Issue by GreenBaii** [kangarko/Boss#416]
Now i use spawn regions for a lot of things i have world guard for protection and i use b region for the monsters however the monsters do not spawn in the regions i haven't changed anything in the settings or anything? Any ideas?

**Comment by kangarko** [comment]
Hello,

please take a look at this https://github.com/kangarko/Boss/wiki/Common-Issues#bosses-are-not-spawning-in-regions. If nothing helps follow the last step and post me the output.

**Comment by kangarko** [comment]
Closing, post below if still having issues
