### ISSUE TITLE
1.14.4: Boss wont start after editing Skill Messages, Error in Throw Player.yml, skill not loaded

### ISSUE THREAD

**Issue by mcpantheon** [kangarko/Boss#417]
So I gogled how to disable the cat messages from the skills and went ahead and did it, replace the messages with  ""

I copied the messages to the top in all the skills and put "" as indicated.

Problem is now Boss wont load. In console it says the following:

14.08 15:42:18 [Server] Server thread/INFO Error loading configuration in Throw Player.yml!
14.08 15:42:18 [Server] Server thread/INFO Problematic section: ''
14.08 15:42:18 [Server] Server thread/INFO Problem: java.lang.ClassCastException: java.lang.String cannot be cast to java.util.List (see below for more)
14.08 15:42:18 [Server] Server thread/INFO Plugin is now disabled.
14.08 15:42:18 [Server] Server thread/INFO !-----------------------

Here's the complete error: https://pastebin.com/rtjsUEHb

Here are the contents of Throw Player.yml:
https://pastebin.com/gtN6qcaL

it's basically the same as how the other skill files are.

Can you help me out and see why it says this file is the reason Boss will no longer load on my server?

Thank you,
Oscar
[Boss.zip](https://github.com/kangarko/Boss/files/3503395/Boss.zip)

**Comment by mcpantheon** [comment]
And here's the contents of error.log in /plugins/Boss/error.log

https://pastebin.com/Vb2bNDfX

**Comment by kangarko** [comment]
Thanks, will fix.
