### ISSUE TITLE
Boss are not respawning

### ISSUE THREAD

**Issue by YanisDark20041** [kangarko/Boss#42]
Hi. I have a problem, boss aren't respawning.
I created a Boss Region with the Emerald tools, i named it and i enabled boss region respawn on my boss.
I set the limit to 1.
Is that possible to do something that when the boss is killed, another respawns 30 mins after, but with a maximum of only 1 boss per region?

**Comment by kangarko** [comment]
Hey, please try the new version. If it won't help please post me your Boss yml file of that specific boss.
