### ISSUE TITLE
I have two generation problems.

### ISSUE THREAD

**Issue by hologame** [kangarko/Boss#423]
1st - It is impossible for me to generate a boss with the characteristics of a Giant, I have reviewed the configuration and the pluging and I can't find any way to make it be generated.

2nd - I can't make any boss be generated by using any type of region, not even the pluging region or the world ward region, he doesn't tell me anything, they just don't generate, we have been looking for a while how to fix it and not We found the answer.

We would be very grateful if you could help us solve these problems, for the rest everything is fine.

[settings.txt](https://github.com/kangarko/Boss/files/3525771/settings.txt)

**Comment by kangarko** [comment]
Hello,

1 - yes, just type /boss new bossname Giant and you will create a Giant Boss. Just know that their AI has not been properly implemented by Minecraft so they may not behave as expected.

2 - Please post me your entire Boss folder in a ZIP

Matej

**Comment by kangarko** [comment]
Closing, let me know if you have more questions
