### ISSUE TITLE
MobHunting - Boss Support

### ISSUE THREAD

**Issue by Rocologo** [kangarko/Boss#424]
I am the dev of MobHunting and one of my users has asked if I could add support for Boss (https://github.com/Rocologo/MobHunting/issues/556) 

I have checked you API and it looks like you have the needed methods in the API, but I cant test anything without having a copy of Boss. And since MobHunting is free I am not ready to pay for Boss to add support?

**Comment by kangarko** [comment]
You can contact me on Spigot for a developer licence, or you can use the API provided in our Wikipedia.
