### ISSUE TITLE
Custom Items arent saved into boss drops

### ISSUE THREAD

**Issue by Lastphysics** [kangarko/Boss#428]
Hey, im running a 1.14.2 server for the moment, and im using a custom Item plugin which can set nbt and custom textures on an item.

When I try to put the item into the mob drop, it just wont save the item.
I asked once to introduce the plugin API. But thats not my request today. Cause I suppose that a Plugin API only works for 1 plugin and not the others.

Could you add a way to save items with custom nbt's and textures ?
This way, your plugin would be even more amazing, and give better rewards for chasing bosses around the world.

Hope I convinced you about how usefull it could be.

Best regards

Ps : sorry couldnt make a request for some reason, thats why its saved in issue

**Comment by kangarko** [comment]
Hello,

can you post me your data.db with the custom NBT item saved? Let me know which Boss is it and which slot.

**Comment by Lastphysics** [comment]
Sorry, Im dont know many things about programming and all that.
How do I get the data.db file ?
I have a plugin that shows me the NBT of an Item, would a simple picture of it work ?

Its with all bosses that it doesnt seem to work, and what do you mean by wich slot ? If I remember, i puted it in the 1st slot.

Im gonna look

**Comment by Lastphysics** [comment]
Well, just tried out with your new build, and everything works fine.
Custom drops are now enabled and everything is saved normally.

Thanks for the fast support.
(Sorry for the interruption)

**Comment by kangarko** [comment]
Awesome!
