### ISSUE TITLE
Question about boss spawning

### ISSUE THREAD

**Issue by Dinoseto** [kangarko/Boss#429]
Hello,
Is possible to have a different limit per world? I have a world where the only mobs I want are custom mobs made with this plugin and then I have the normal world where I have other bosses that I want to be rare, but if I change the world limit they are too much for the normal world or too low for the other world

**Comment by kangarko** [comment]
Yes, you can customize world chances from 0% to 100% in /b menu -> Your boss -> Spawning -> Worlds menu.

**Comment by Dinoseto** [comment]
Hello, what I wanted to say was not that, I wanted to ask if I can set different world boss limits in the config or different timed spawn settings, for example:

world1: timed spawn 30 minutes and limits 2 per chunk and 100 in world

world2: timed spawn 1 minute and limits 5 per chunk and 500 in world

If it is not implemented would be a nice improvement for multiple world servers

**Comment by kangarko** [comment]
Not for now, you only have a flat timed spawning period but in the major next version we will rewrite the system.
