### ISSUE TITLE
Boss bar

### ISSUE THREAD

**Issue by Nedjii** [kangarko/Boss#430]
Hello, i suggest another way to show boss health because some people like me are already using the action bar for something else,I thought about the boss bar (enderdragon/wither),
regards.

**Comment by kangarko** [comment]
Boss bar is harder to clear and can have remains, it's generally less recommended for showing text. We'll continue using action bar.

**Comment by Nedjii** [comment]
I understand, I also suggested this because the action bar showing the boss health doesn't appear anymore for some reason, it's enabled by default in the config and I didn't remove it, even when I put a default boss (just created one), the bar isn't here so I got no way to see the boss health,
have you got any idea how to fix this ?

**Comment by kangarko** [comment]
We can just continue here, seems like there's other plugin blocking it .You can try disabling plugins one by one to find it. If you use CoreArena it may not appear during arena fight since we handle it differently though

**Comment by Nedjii** [comment]
I'm not using CoreArena, that's weird because the boss action bar used to work when I installed the plugin, thought I missed something in the config but there is only one thing related to health bar, I'll try to disable all plugins to see.
