### ISSUE TITLE
🎈 Official Roadmap: Suggestions & Ideas

### ISSUE THREAD

**Issue by kangarko** [kangarko/Boss#431]
![pic](https://i.imgur.com/ntDTWbp.png)

## Having a new idea or a suggestion?
Due to time and resource constraints we cannot take new suggestions at this time. Thank you for your understanding.

## Official Roadmap
We're currently rewriting Boss and have pulled the vast majority of suggested features. There's no ETA however we'll post our progress below so you can follow it up.

**Comment by Lastphysics** [comment]
Is it possible to make the boss region compatible with the 'Epic World Generator' Plugin ?

**Comment by kangarko** [comment]
If you have a question please open a new ticket, this page for for informative purposes only.

**Comment by kangarko** [comment]
The development of Boss4 got stalled due to personal circumstances, we have plans to resume it shortly this year.
