### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Nedjii** [kangarko/Boss#435]
Hello, i didn't find any place for suggestions so i'll right it here.
So, I suggest a permission that  would multiply the damages dealt to bosses, that'd be a great donor perk.
I also suggest a placeholderapi integration to have placeholders such has boss killed by boss etc,
regards.

**Comment by kangarko** [comment]
Hello,

thank you for your suggestions, you can now change the damage multiplier of the damage dealt by a Boss in his attributes menu.

Some sort of variables integration is planned though.
