### ISSUE TITLE
Problem kill boss

### ISSUE THREAD

**Issue by TwerkRekt** [kangarko/Boss#437]
Hi i have a problem with boss :)

https://image.noelshack.com/fichiers/2019/35/6/1567279771-2019-08-31-15-27-53.png
"was slain by ....."

To make it simple sometimes when the boss is killed, he does not give the reward (that indicates player not found)

https://code.alwyn974.re/fumudiweko.md

**Comment by TwerkRekt** [comment]
version: paper 1.12.2
boss zip:
https://www.mediafire.com/file/kp4igi30qtkm8i4/bosszip.rar/file

**Comment by kangarko** [comment]
Hey,
 you are using the {killer} variable which sometimes is but sometimes is not translated into the player who dealt the last damage. We unfortunately have no control over this as we only call a Bukkit call getKiller which, turns out, may behave like this in certain cases. I apology for this.
