### ISSUE TITLE
question about the plugin

### ISSUE THREAD

**Issue by dronex73** [kangarko/Boss#438]
hello i would like to ask you some details about your plugin.
1. are you able to set a respawn delay for different bosses?
(for example: to set that boss X will spawn on block Y every 24 hours)
2. can you give a custom item to the boss? that will drop from him?
(i mean custom like custom lore, name, enchants, atributes)
3. can you also set the drops from the minions that the master boss spawns?
4. can you spawn boss X using command blocks? or by any ingame direct command?

thats everything for now
best regards
-dronex

**Comment by kangarko** [comment]
Hello,

1. Not in Boss3 but in Boss4 you will have that ability.
2. Yes totally! Give him any items you create from any other plugin, just drag and drop into his inventory.
3. The minions have the same settings as Boss so yes.
4. Yes you can use /boss spawn and run this command from a command block as well.

Thanks
Matej
