### ISSUE TITLE
Still database-problems in 1.8

### ISSUE THREAD

**Issue by RobZenTL** [kangarko/Boss#441]
Hey, I opened 2 issues and tried every new release. But we still encounter many problems with boss.

What happens?
We start the server and Boss is running. After a server-restart or -crash the plugin creates an exception and doesn't load anymore. We still don't know why this happens.
Sometimes some errors occur, like this: https://pastebin.com/r3yiZQ5F

The exception at the server-start: https://pastebin.com/YUqAG6dK

Minecraft 1.8.8
Boss-Version: any (last ones tested were 3.4.8 + 3.4.17)
We have 8 bosses configured, 3 of them can spawn in our worlds

When we delete the data.db-file boss works again after the next server start. Until we restart again...

**Comment by kangarko** [comment]
Please provide me your data.db file when it breaks.

**Comment by RobZenTL** [comment]
https://www.dropbox.com/s/gn5h2zqmgntnw9q/data.db?dl=0

**Comment by kangarko** [comment]
Oh seems like the section with the Boss name has been split!

![a](https://i.imgur.com/XRbmtEn.png)

Please ZIP me your entire Boss folder. I need to take a look at the Bosses. Remember to send me the folder when the plugin is broken.

**Comment by RobZenTL** [comment]
Sure: https://www.dropbox.com/s/j7scwtqnm7cm3fd/Boss-broken.zip?dl=0

(I am on vacation until sunday, sorry if I don't answer until then)

**Comment by kangarko** [comment]
[data.zip](https://github.com/kangarko/Boss/files/3612851/data.zip)
You cannot use "._" in your Boss name, sorry.

Replace your data.db with the data I uploaded here, remove Mr._Bones and create a Mr_Bones boss instead. You can give him a custom name with dots and spaces afterwards.

Thanks.

**Comment by RobZenTL** [comment]
After a few days I can tell you: Problem solved. Thanks for the help!
