### ISSUE TITLE
Boss Spawner tick issue

### ISSUE THREAD

**Issue by Ratthew** [kangarko/Boss#443]
Hi, Id like to report what seems to be a bug on 1.14.4 correct me if its not. When editing boss spawners in game using the gui by right clicking and then adjusting the time between spawning it appears that if I use anything over 6464 ticks it will shoot down to 6464 or somehow into the negatives

Example: Say I set the tick speed to 1 hour/60 minutes, when I reenter the mob spawner it changes the tick speed to 6464 which translates roughly to 5.4 minutes which wont work for my current dungeon that is all timed on an hourly spawning basis.

Example 2: Setting the spawners tick speed to 30m and then reentering the mob spawner to check if it worked it will display -29536 ticks instead of 36000 which glitches some spawners making them useless or make them spawn in mobs instantly.

Another Question: Say I put 6 mob spawners in an area and selected a boss, then I set all the spawners to spawn 2 mobs each. Im wondering if that will have a total amount of that selected bosses will be 2 or 12 for max spawn rates. Basically what im trying to say is will each spawner add to the total number spawned.

Please get back to me asap since my servers goin to the gutter atm waiting for the dungeon update with your boss plugin that ive been constantly delaying :)

Thanks ~Ratthew
~PS: I will most likely have a delayed response of 2 days due to work/school

**Comment by kangarko** [comment]
Hello,

I have some good news and some bad news. Spawners use short number type for saving their spawn delay. Short type overflows (google "integer overflow") at the value you just discovered. There is nothing we can do about this in the moment.

Good news is that PaperSpigot saves the value as "long" allowing for much longer values. Even better news is that Boss4 will completely take over this system so we don't have to rely on an external API and you will be able to set spawning even periodically, such as every friday, every 4pm etc.

You can consider using PaperSpigot for now. Boss4 is on its way but it'll take a few months.

Best,
Matej
