### ISSUE TITLE
Zombie AI for Giants

### ISSUE THREAD

**Issue by DumbatorCZ** [kangarko/Boss#444]
Is it possible to have Giant as a boss with AI? Or are they useless?

And second q: Is there any comunity on Discord, or is it just an ad for trainee program? As I can see only one channel and on spigot page, it says "use our Discord to chat with our support team".

Thanks

**Comment by kangarko** [comment]
Best way to get help is here or send me a PM.

Giants have poor AI and Boss cannot modify it at the moment, sorry. See https://github.com/kangarko/Boss/wiki/Frequent-Questions-and-Tips#can-you-make-animals-aggressive--add-better-ai
