### ISSUE TITLE
Boss 1.9.4 data issues

### ISSUE THREAD

**Issue by UnfamousThomas** [kangarko/Boss#447]
This happens often after a restart or crash.

https://pastebin.com/9Ls2Tc2y

**Comment by kangarko** [comment]
Are you running the latest available 1.9.4 build?

**Comment by UnfamousThomas** [comment]
Hey.

It should be, if not **the latest** then at least one of the latest builds - using Pterodactyl latest keyword for it.

**Comment by kangarko** [comment]
Seems like the Paper version you are using contains different NMS internals than we support for some reason. If you can't test using different jars I can refund you, let me know below.
