### ISSUE TITLE
1.8.3 Minecraft doesn't work with boss?

### ISSUE THREAD

**Issue by jlund7** [kangarko/Boss#449]
Hey, what version of Boss do I need to work with spigot 1.8.3? I have tried many versions and the menus on them seem not to work. I paid $10 for this plugin, why is it not compatible with 1.8.3??? Also will post log of when I try to create boss via the command.

**Comment by jlund7** [comment]
20.09 13:44:25 [Server] INFO BOSS // Created default file: Spider.yml
20.09 13:44:25 [Server] INFO BOSS // A new Boss was successfully installed: Spider
20.09 13:44:25 [Server] INFO BOSS // Boss 1.6.11 encountered a NoSuchMethodException! Please check your error.log and report this issue with the information in that file.
20.09 13:44:25 [Server] WARN java.lang.ExceptionInInitializerError
20.09 13:44:25 [Server] WARN at me.kangarko.boss.final. .c.<init>(SourceFile:25)
20.09 13:44:25 [Server] WARN at me.kangarko.boss.final. .aUx.protected(SourceFile:85)
20.09 13:44:25 [Server] WARN at me.kangarko.boss.final. .Con.CoM8(SourceFile:312)
20.09 13:44:25 [Server] WARN at me.kangarko.boss.final. .Con.getHealth(SourceFile:308)
20.09 13:44:25 [Server] WARN at me.kangarko.boss.final. .Con.short(SourceFile:158)
20.09 13:44:25 [Server] WARN at me.kangarko.boss.final. .Con.protected(SourceFile:96)
20.09 13:44:25 [Server] WARN at me.kangarko.boss.final. .aUx.<init>(SourceFile:62)
20.09 13:44:25 [Server] WARN at me.kangarko.boss.final. .aUx.protected(SourceFile:70)
20.09 13:44:25 [Server] WARN at me.kangarko.boss.final. .aO.protected(SourceFile:81)
20.09 13:44:25 [Server] WARN at me.kangarko.boss.command.NewCommand.handleSubCommand(SourceFile:46)
20.09 13:44:25 [Server] WARN at me.kangarko.boss.final. .cOm4.handleCommand(SourceFile:172)
20.09 13:44:25 [Server] WARN at me.kangarko.boss.final. .COM3.onCommand(SourceFile:57)
20.09 13:44:25 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
20.09 13:44:25 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
20.09 13:44:25 [Server] WARN at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchCommand(CraftServer.java:646)
20.09 13:44:25 [Server] WARN at net.minecraft.server.v1_8_R2.PlayerConnection.handleCommand(PlayerConnection.java:1133)
20.09 13:44:25 [Server] WARN at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:968)
20.09 13:44:25 [Server] WARN at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
20.09 13:44:25 [Server] WARN at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:1)
20.09 13:44:25 [Server] WARN at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13)
20.09 13:44:25 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
20.09 13:44:25 [Server] WARN at java.util.concurrent.FutureTask.run(FutureTask.java:266)
20.09 13:44:25 [Server] WARN at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60)
20.09 13:44:25 [Server] WARN at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:710)
20.09 13:44:25 [Server] WARN at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368)
20.09 13:44:42 [Multicraft] Skipped 46 lines due to rate limit (30/s)

**Comment by kangarko** [comment]
Use Boss 3.4.18.
