### ISSUE TITLE
Feature: Hostile Passive Mobs

### ISSUE THREAD

**Issue by mrcoffee1026** [kangarko/Boss#45]
Because I made an "Angry Chicken" Boss... and it just sits there.  When you attack it, it tries to evade you as a passive mob normally would.  The "Throw Player" I gave it does function, but you have to basically jump on the guy for several minutes to get him to use it.  While it's not normal for a chicken to have/hold an axe, I equipped him with one expecting him to "peck" with it... but that doesn't happen.  In any case, a specified mob should - I believe - be automatically hostile if it is a "boss", I feel this is probably a toggle somewhere that should be fairly easy to implement (I hope).  We kind of wanted them to spawn/attack on the condition of a player killing chickens nearby, but I'm not sure how feasible that is or if it's something a bit more convoluted that could be scripted using the eventually added javascript feature.  Also I THOUGHT there was an option to lighting on spawn?  Shows in the config file but not on the bosses themselves.
First attempt using this seemed to spawn an incredibly large amount of Bosses

**Comment by kangarko** [comment]
Hello,

for the hostile passive mobs, please read the following question https://github.com/kangarko/Boss/wiki/Common-Issues#can-you-make-animals-aggressive--add-better-ai

for the lightning - there is an option for that in Timed_Spawning, that will make the lightning appear when a Boss is spawned naturally. There is no lightning when you spawn it manually using a command or an egg.
