### ISSUE TITLE
Percentage Rewards?

### ISSUE THREAD

**Issue by julian-lundquist** [kangarko/Boss#451]
Is there an option to set top 3 players that did the most damage for that boss and give them a certain item thru the gui? Also I want to disable to spawing of random mobs in a region, but make it where I can still spawn the boss there

**Comment by kangarko** [comment]
Yes there is, please see https://github.com/kangarko/Boss/wiki/Drops#inventory-drops-and-pvp-spreads

You can use the Spawning menu inside of your individual Boss menu to configure how they spawn. You can make them spawn randomly inside of regions, or outside (see the black-list option)

Matej
