### ISSUE TITLE
Make Bosses Bigger?

### ISSUE THREAD

**Issue by jlund7** [kangarko/Boss#452]
Sorry for asking so many questions, but how do you make a boss bigger? For example, make a spider 4x bigger than its normal size. Is that even a feature that Boss plugin has? And for the first question, I was asking if there was something that kept track of how much damage a player did to the boss, and after it dies, then the top 3 players get a 1st, 2nd, and 3rd place prize.

**Comment by jlund7** [comment]
Those are the main 2 reasons I purchased this plugin. to have larger spider boss, and give people who did most damage certain prizes.

**Comment by kangarko** [comment]
Sorry this is not possible without client mods, you can only enlarge the ones that are supported by the client such as the Slime or the Phantom.
