### ISSUE TITLE
Boss spawn worldguard

### ISSUE THREAD

**Issue by TwerkRekt** [kangarko/Boss#453]
Hello, since the last update, bosses no longer spawn in the worldguard region with the flag "mob-spawning: deny" yet before it worked it's annoying because I use a scheduler that spawns at 18:00 every day and he can not message is "unable to spawn boss in this location"

Version: paper 1.12.2 (1618)

**Comment by kangarko** [comment]
Hey,

ensure you have Egg_Spawning.Check_Regions on **false** and Egg_Spawning.Spawn_If_Event_Cancelled on **true** in your settings.yml file

You can create a sub-region that has the spawning enabled or force the spawning using the /boss spawn command

**Comment by TwerkRekt** [comment]
Already on that :/

**Comment by kangarko** [comment]
Can you create a sub-region that has the spawning enabled or force the spawning using the /boss spawn command ?

**Comment by TwerkRekt** [comment]
boss spawn SpawnV2 -12 87 -51 OrthyonMC2

https://image.noelshack.com/fichiers/2019/40/1/1569800954-2019-09-29-19-48-34.png

**Comment by kangarko** [comment]
Set Limits.Apply_For_Commands to false and it should work :)

**Comment by TwerkRekt** [comment]
dont  work

**Comment by TwerkRekt** [comment]
https://code.alwyn974.re/bebawigofu.shell

**Comment by kangarko** [comment]
Try setting Limits.Global.Enabled to false to disable limits.

Also are you using Boss eggs to spawn that boss or how are you spawning it?

**Comment by J3fftw1** [comment]
i got the same issue i tried all the above i tried with boss spawn dungeon ~ ~ ~ Diana got same error
i tried with spawn egg also didnt work
my config
https://hasteb.in/uxelihav.yaml
