### ISSUE TITLE
Boss Spawns Every Hour?

### ISSUE THREAD

**Issue by julian-lundquist** [kangarko/Boss#454]
Hey, I tried to set the native conditions for the boss, but it never spawns in the boss region that i set for it. I saw on another server that the boss would spawn every hour and warns you 1 minute before the boss is going to spawn again in chat. Is that possible with your boss plugin?

**Comment by TwerkRekt** [comment]
use a scheduler plugin

**Comment by kangarko** [comment]
Thanks, this is already planned for Boss 4 and works have begun!

Right now you can use a scheduler plugin to run /boss spawn command at the specified times.

**Comment by julian-lundquist** [comment]
please make sure that it works with spigot 1.8.8!

**Comment by kangarko** [comment]
Of course, every major feature will work and we're not planning to drop any old release.

Only cosmetics such as particles or some damage modifiers won't work under 1.8 as they lack the necessary API's.
