### ISSUE TITLE
Noob Question....

### ISSUE THREAD

**Issue by B0iledEGG** [kangarko/Boss#455]
This may seem like a dumb question but, how do I create a region. Every time I select the are with the tool and do the command "/b region add (name)" nothing happens?

**Comment by kangarko** [comment]
Hey,

1. First use /boss tool to get the region tool and select two points by right, and left clicking a cuboid selection
2. Then use /b region add {name}

If "nothing" happens post me the message you get as well as check the console for errors. Just post it below and I will see it.

Cheers ! :)
