### ISSUE TITLE
Dispenser Issue

### ISSUE THREAD

**Issue by RAVA1234** [kangarko/Boss#456]
Hi There,

Sorry if it's already been brought up but bosses are currently able to be spawned in regardless of the region/area you're in by putting them in dispensers then activating them. This is an issue as players can spawn them on their islands etc which I don't want possible.

Please can you help find a solution! 

Thanks

**Comment by kangarko** [comment]
Thanks, will look into it

**Comment by kangarko** [comment]
Confirmed, a fix is on the way!

**Comment by kangarko** [comment]
Fixed. Will be available in the next release.
