### ISSUE TITLE
Spawners

### ISSUE THREAD

**Issue by HoodedDuk** [kangarko/Boss#457]
The spawners work for about 5 minutes and then soon after completely stop working and I don't know why... 

The spawner settings are:

1 Mob

10 seconds

45 blocks

**Comment by kangarko** [comment]
Hello,

the spawners use vanilla Minecraft rules. If there are enough monsters of the Boss kind, spawner will stop functioning. It also needs to be night/dark lightning for hostile mobs. We'll be rebuilding this to use our custom coded system in Boss4.
