### ISSUE TITLE
Feature (or information on): Spawning Minions [Skill]

### ISSUE THREAD

**Issue by mrcoffee1026** [kangarko/Boss#46]
How do you configure what minions are spawned/how many?  There's a different setting for spawning "reinforcements" on death, I feel like it should take the information from that setting... or have some similar way of configuring if possible?  Thanks.

**Comment by kangarko** [comment]
Hey,

I have added "Amount" option to the Spawn Minions skill's yml file. For the time being this is a flat option for all bosses having this skill. In the future I plan to rewrite Skill system for individual per-boss settings.
