### ISSUE TITLE
Spawner Error Fix Please [Debug log add]

### ISSUE THREAD

**Issue by LeePC** [kangarko/Boss#460]
1. Tested Version 1.12.2

2. Plugins Version Latest

3. Error Video 
https://www.youtube.com/watch?v=aNghU1fJERA&feature=youtu.be

**Comment by kangarko** [comment]
I apology for the delay, do you use Paper or Spigot?

**Comment by LeePC** [comment]
> I apology for the delay, do you use Paper or Spigot?
> 
> I see the issue in that you've set the delay to 40 ticks but the plugin thinks it's on 0. Spigot saves the spawner's delay in a way potentially causing it, that's why I asked.



spigot use
No Paper

**Comment by kangarko** [comment]
I am sorry, for this feature to work properly, Paper is required.
