### ISSUE TITLE
BossDamageEvent

### ISSUE THREAD

**Issue by CJCrafter** [kangarko/Boss#462]
Making a little plugin for a client and noticed that your plugin's entities don't seem to throw entity damage events, oddly. 

I am not seeing a BossDamageEvent in your api. Mind adding one?

**Comment by kangarko** [comment]
Hello,

we don't cancel the EntityDamageByEntityEvent. Try listening to that one and use @EventPriority(priority=EventPriority.LOWEST) to see if it hits. If not, change the priority to HIGHEST.
