### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by J3fftw1** [kangarko/Boss#463]
is there a way to register everyone who hit a certain boss and give all of the players the reward or the top 3 damage 
and is there a discord or something else to talk about the plugin

**Comment by kangarko** [comment]
Yes we have a feature for pvp spreads and inventory drops for top killers: https://github.com/kangarko/Boss/wiki/Drops#inventory-drops-and-pvp-spreads

There is no discord, send a PM if you need to talk in private otherwise use GitHub.
