### ISSUE TITLE
Spawner Limit Error??

### ISSUE THREAD

**Issue by LeePC** [kangarko/Boss#466]
1. Log use No Error
2. Tested Version : 1.12.2
3. Tested Bukkit : Paper
4 Error Video
https://youtu.be/oGGkWOEHco4

**Comment by kangarko** [comment]
Please ZIP me your Boss folder in its entirety, I need to check your file where spawners are saved.

**Comment by LeePC** [comment]
> Please ZIP me your Boss folder in its entirety, I need to check your file where spawners are saved.

[Boss.zip](https://github.com/kangarko/Boss/files/3753543/Boss.zip)

**Comment by kangarko** [comment]
Can you please run /version to give me your server's version?

**Comment by LeePC** [comment]
paper-1618 1.12.2 version
fix please

**Comment by kangarko** [comment]
I am on it, I am so sorry for the delay!

**Comment by kangarko** [comment]
I again apology for the delay, this was much harder to fix than expected. A new release is on the way!
