### ISSUE TITLE
Suggestion - Integration with ClueScrolls

### ISSUE THREAD

**Issue by MrHumblePie** [kangarko/Boss#47]
I've spoken to the developer of ClueScrolls ( https://www.spigotmc.org/resources/★-cluescrolls-★-║-1-7-to-1-12-2-20-off-new-year-sale.30276/ ), I was asking if he could add support for Boss and he said:

_From the looks of it, you'll need to ask the developer to add a BossDeathEvent. There's only a BossSpawnEvent so I can't do much with it._

Is this something that could be added? It would be helpful for the likes of RPG or quest type plugins to be able to make quests that center around killing particular bosses.

**Comment by kangarko** [comment]
Thank you, I have added the BossDeathEvent.
