### ISSUE TITLE
Issue with mob egg changing

### ISSUE THREAD

**Issue by Blankscar** [kangarko/Boss#470]
Most items have a bugged texture and it wont let me change the id on any item.
https://youtu.be/3wD_wRMd9g8

**Comment by Blankscar** [comment]
No clue why the video is distorted like that but the issue is clearly visible

**Comment by LeePC** [comment]
Did you use spigot ??

**Comment by Blankscar** [comment]
BeerSpigot

**Comment by LeePC** [comment]
boss plugin only supports paper

**Comment by kangarko** [comment]
Hi,

Boss plugin works fine on Spigot and Paper. I am not sure what MC version you are using but please try using Paper or Spigot and comment below if the issue persists.

I have fixed the error stack from the video you've posted, thank you.
