### ISSUE TITLE
Spigot compatibility 

### ISSUE THREAD

**Issue by longbow122** [kangarko/Boss#471]
Hello, I am unsure as to whether this plugin is compatible with Spigot 1.12.2 build #131. If it is, I am pleased to say I will be planning on purchasing both Bosses and CoreArena. Are you able to answer this question for me? Thank you. I may not see this for a while. If you wish me to respond quicker. You can contact me on discord at longbow122 #9252

**Comment by kangarko** [comment]
Hello, if the build 131 is the latest build released for 1.12.2, then it should be compatible.

Otherwise I highly recommend using Paper 1.12.2 instead of Spigot.
