### ISSUE TITLE
Spawning Within Boss Region Not Working

### ISSUE THREAD

**Issue by Erikpie** [kangarko/Boss#472]
Hi, I'm having difficulty attempting to get bosses to spawn in a set region. 
The mob I'm trying to spawn are phantoms.

Here are the steps I've taken:
/b region add Mine1to2Area
/b menu --> Bosses --> Selected boss (Mine2_Boss) --> Spawning --> Enabled region spawning --> Boss regions --> Selected region

I also increased the chances of spawning to 100% per world and also in the respective WorldGuard region. I also increased the biome spawning to 100% just in case.

Despite these steps, I still cannot get mobs to spawn. Could I get some help with this issue? :)
![2019-10-28_16 29 34](https://user-images.githubusercontent.com/13648906/67720608-666dc980-f9a2-11e9-9ddf-65a5baa5e461.png)

**Comment by kangarko** [comment]
Hi! I apology for a late reply, please follow the steps here and provide me the info from the last sentence: https://github.com/kangarko/Boss/wiki/Common-Issues#bosses-are-not-spawning-in-regions

**Comment by Erikpie** [comment]
Hi, I wasn't sure what you meant by "set Debug to [spawning]". Could I get the exact command to execute?
Sorry about that!

**Comment by kangarko** [comment]
Hi, I meant you simple open the settings.yml file, navigate to the "Debug" key and set its value to "[spawning]".

![a](https://i.imgur.com/O2SosSy.png)

**Comment by Erikpie** [comment]
The mobs that are spawning from random spawning in world ("SpawnWorld") spawn fine but regions don't work for some reason. Also, how do I spawn in regions exclusively?

> [23:29:29 INFO]: [spawning] Attemt to spawn Skeleton at SpawnWorld [190, 38, 149] for CONVERTED
> [23:29:29 INFO]: [spawning] Not spawning. World SpawnWorld has 10% of spawning boss. Should spawn? false
> [23:29:29 INFO]: [spawning] Attemt to spawn Skeleton at SpawnWorld [190, 39, 175] for CONVERTED
> [23:29:29 INFO]: [spawning] [OK] Spawned.
> [23:29:30 INFO]: [spawning] Attemt to spawn Skeleton at SpawnWorld [253, 38, 152] for CONVERTED
> [23:29:30 INFO]: [spawning] Not spawning. World SpawnWorld has 10% of spawning boss. Should spawn? false
> [23:29:30 INFO]: [spawning] Attemt to spawn Skeleton at SpawnWorld [252, 38, 154] for CONVERTED
> [23:29:30 INFO]: [spawning] Not spawning. World SpawnWorld has 10% of spawning boss. Should spawn? false
> [23:29:30 INFO]: [spawning] Attemt to spawn Skeleton at SpawnWorld [283, 38, 217] for CONVERTED
> [23:29:30 INFO]: [spawning] Not spawning. World SpawnWorld has 10% of spawning boss. Should spawn? false
> [23:29:31 INFO]: [spawning] Attemt to spawn Skeleton at SpawnWorld [200, 41, 167] for CONVERTED
> [23:29:31 INFO]: [spawning] [OK] Spawned.
> [23:29:36 INFO]: [spawning] Attemt to spawn Skeleton at SpawnWorld [268, 38, 208] for CONVERTED
> [23:29:36 INFO]: [spawning] Not spawning. World SpawnWorld has 10% of spawning boss. Should spawn? false
> [23:29:36 INFO]: [spawning] Attemt to spawn Skeleton at SpawnWorld [253, 38, 207] for CONVERTED
> [23:29:36 INFO]: [spawning] Not spawning. World SpawnWorld has 10% of spawning boss. Should spawn? false
> [23:29:37 INFO]: [spawning] Attemt to spawn Skeleton at SpawnWorld [242, 38, 171] for CONVERTED
> [23:29:37 INFO]: [spawning] Not spawning. World SpawnWorld has 10% of spawning boss. Should spawn? false
> [23:29:37 INFO]: [spawning] Attemt to spawn Skeleton at SpawnWorld [265, 38, 232] for CONVERTED
> [23:29:37 INFO]: [spawning] Not spawning. World SpawnWorld has 10% of spawning boss. Should spawn? false
> [23:29:39 INFO]: [spawning] Attemt to spawn Skeleton at SpawnWorld [222, 38, 199] for CONVERTED
> [23:29:39 INFO]: [spawning] Not spawning. World SpawnWorld has 10% of spawning boss. Should spawn? false
> [23:29:39 INFO]: [spawning] Attemt to spawn Skeleton at SpawnWorld [220, 38, 201] for CONVERTED
> [23:29:39 INFO]: [spawning] Not spawning. World SpawnWorld has 10% of spawning boss. Should spawn? false

**Comment by kangarko** [comment]
Do you still need help? If so send me your latest ZIP folder. What do you mean that regions don't work? You spawn in regions only if you select them in the Spawning menu. Boss will not spawn elsewhere.
