### ISSUE TITLE
Boss mobs ignoring worldguard regions again

### ISSUE THREAD

**Issue by mrcoffee1026** [kangarko/Boss#476]
Current config settings for me are to use selected regions as blacklist.  This dis work but now no longer does... so now bosses are spawning in my protected spawn regions which is exactly where they shouldn't ever be. (as of ver 3.5.3)  (Paper build 225)

**Comment by mrcoffee1026** [comment]
Also this version appears to not be putting name tags onto the bosses anymore either.

**Comment by kangarko** [comment]
Can you please ZIP me your whole config?

**Comment by mrcoffee1026** [comment]
I would do all of that but after having debug on and waiting for a very long time, it did not happen again (also this last release seems to have fixed the missing name tags).  What it might be is that the region was new and I needed a restart with the setting in place before it accepted the change.  In any case disregard this as either it was restricted to the last build or needed another restart to "kick in".  Thanks!
