### ISSUE TITLE
Loot drop suggestion

### ISSUE THREAD

**Issue by GalaxyBabe** [kangarko/Boss#477]
Hi Matej,

The loot drops per boss is currently either a single item, or everything in the drop menu.  Would it be possible to add a function where you can specify more than one drop based on the amount of damage the player did.  For example.  The player who did the most damage gets 5 items, 2nd player gets 4 items etc.  

Or just a number of drops to give a player.  For example all players gets 3 drops.

I hope this makes sense lol.

Kind Regards,
Galaxy

**Comment by kangarko** [comment]
Hi Galaxy,

thank you for your suggestion. We are already planning a complete rewrite of the Boss plugin, I make sure to include all of the new suggestions once it is ready.
