### ISSUE TITLE
Bosses attacking each other

### ISSUE THREAD

**Issue by BobbyMere** [kangarko/Boss#481]
Bosses still attack each other if two of them have a range weapon and hits the other. This still happens with Targettable turned off. 

Updates notes: "Rewritten Boss Spawner mechanism. Instead of relying on vanilla behavior, we now check how many Bosses are nearby spawners manually, solving problems with older MC versions and enabling precise limits."

This doesn't work either. If two bosses of the same vanilla mob types are in the same area with limit set to spawn 1 each, only 1 boss will spawn.

**Comment by kangarko** [comment]
Thanks, I am out of office, will take a look in about 3 days.

**Comment by kangarko** [comment]
What kind of mobs have you tested the targetable flag on?

**Comment by BobbyMere** [comment]
Husk, zombie, skeleton, drowned

**Comment by kangarko** [comment]
Thanks, I will fix that
