### ISSUE TITLE
DiscordSRV with Boss v3.5.5 Failed loading - paper 1.13.2

### ISSUE THREAD

**Issue by BobbyMere** [kangarko/Boss#484]
Removing DiscordSRV v1.8.1 will allow for boss v3.5.5 to function perfectly
Is there a way to completely disconnect this plugin for discordSRV?  I am curious though about what kind of features there are for this boss plugin to hook into discord. Please tell me? I don't see them listed on the home page

15.11 15:05:35 [Server] INFO Disabling Boss v3.5.5
15.11 15:05:35 [Server] INFO !-----------------------------------------------------!
15.11 15:05:35 [Server] INFO Error: Unable to get the error message, search above.
15.11 15:05:35 [Server] INFO !-----------------------------------------------------!
15.11 15:05:35 [Server] INFO Running on 1.13.2-R0.1-SNAPSHOT (v1_13_R2) & Java 1.8.0_181
15.11 15:05:35 [Server] INFO Error loading Boss v3.5.5, plugin is disabled!
15.11 15:05:35 [Server] INFO !-----------------------------------------------------!
15.11 15:05:35 [Server] INFO |_|
15.11 15:05:35 [Server] INFO |_| |_|\___/ \___/| .__/|___(_)
15.11 15:05:35 [Server] INFO |  _  | (_) | (_) | |_) \__ \_|
15.11 15:05:35 [Server] INFO | |_| |/ _ \ / _ \| '_ \/ __| |
15.11 15:05:35 [Server] INFO | | | | ___   ___  _ __  ___| |
15.11 15:05:35 [Server] INFO _   _                       _
15.11 15:05:35 [Server] INFO at java.lang.Thread.run(Unknown Source)
15.11 15:05:35 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412)
15.11 15:05:35 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:334)
15.11 15:05:35 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)
15.11 15:05:35 [Server] INFO at org.mineacademy.boss.double. .lPT6.onEnable(SourceFile:313)
15.11 15:05:35 [Server] INFO at org.mineacademy.boss.lib.fo.model.LpT7$protected.<init>(SourceFile:213)
15.11 15:05:35 [Server] INFO at github.scarsz.discordsrv.api.ApiManager.subscribe(ApiManager.java:63)
15.11 15:05:35 [Server] INFO at github.scarsz.discordsrv.util.LangUtil$InternalMessage.toString(LangUtil.java:816)
15.11 15:05:35 [Server] INFO java.lang.NullPointerException
15.11 15:05:35 [Server] INFO ______________________________________________________________
15.11 15:05:35 [Server] INFO https://github.com/kangarko/Boss/issues
15.11 15:05:35 [Server] INFO Get help:
15.11 15:05:35 [Server] INFO https://github.com/kangarko/Boss/wiki
15.11 15:05:35 [Server] INFO Tutorial:
15.11 15:05:35 [Server] INFO Loading bosses (0) ..
15.11 15:05:35 [Server] INFO Update settings.yml at 'Prevent_Vanilla_Mobs.Worlds' -> '[*]'
15.11 15:05:35 [Server] INFO |______/ \___/(___/(___/
15.11 15:05:35 [Server] INFO | |__)  ) |_| |___ |___ |
15.11 15:05:35 [Server] INFO |  __  ( / _ \ /___)/___)
15.11 15:05:35 [Server] INFO ____)  ) ___   ___  ___
15.11 15:05:34 [Server] INFO (____  \
15.11 15:05:34 [Server] INFO ______
15.11 15:05:34 [Server] INFO Enabling Boss v3.5.5

**Comment by kangarko** [comment]
Thanks, I added a comment: https://github.com/DiscordSRV/DiscordSRV/issues/572

**Comment by kangarko** [comment]
Boss does not use DiscordSRV directly, however the library we use, scans a whole bunch of supported plugins such as DiscordSRV to make their functions available in case we want to use it. This is used in ChatControl Pro, it is scanned but not loaded in Boss. However we have a developer API so we make it available in case a developer wants to connect through Boss.

**Comment by BobbyMere** [comment]
Ah! Ok. So it's dev accessibility is the reason. Thanks for replying so quickly

**Comment by kangarko** [comment]
They have fixed it, just update to the latest bleeding edge: https://github.com/DiscordSRV/DiscordSRV/issues/572
