### ISSUE TITLE
Suggestion: Libs Disguise?

### ISSUE THREAD

**Issue by FeroxDrood** [kangarko/Boss#485]
Would be awesome if we could disguise our bosses as player skins or other mobs really wanna make a Santa boss for Christmas aha.

**Comment by kangarko** [comment]
Thanks, currently this is planned using the Citizens plugin.

**Comment by skerit** [comment]
Any idea when we could expect this to land?
I'm currently using Citizens + Sentinel when I really want a player skin boss, but those are quite limited in how they fight.

**Comment by kangarko** [comment]
@skerit sorry I completely missed your ticket, we're in the process of releasing a brand new plugin, then we'll rewrite Boss, so it should come in 1-2 months

**Comment by Baktus79** [comment]
#523
