### ISSUE TITLE
How does a mob's damage work?

### ISSUE THREAD

**Issue by Dynamite99** [kangarko/Boss#486]
I have been trying to give custom MMOItems to mobs to use, but it seems that boss does not recognize the values of the weapon damage. Is there a tutorial or an explanation on how damage values work or how to equip a sword to do a certain amount of damage on a mob?

**Comment by kangarko** [comment]
Seems like the MMOItems plugin is using a way of checking damage that's not through the vanilla Bukkit API and thus we cannot catch it.

What you can do is either giving your Boss a weapon with the Sharpness enchantment, or setting the damage multiplier in the Attributes menu:

![a](https://i.imgur.com/GK0dDbp.png)

**Comment by Dynamite99** [comment]
so i would assume giving a mob with a custom item that has a custom data value is impossible?

**Comment by lackoSK** [comment]
Hello,

Just tested it out for you, and I can say, it works with MMOItems Premium, Server: 1.14.4

You can simply give him a sword created by MMOItems, and he will normally drop that sword.

![image](https://user-images.githubusercontent.com/53174757/69279322-65683a80-0be4-11ea-9e65-115dc43d2e47.png)

Regards, 
lackoSK

**Comment by Dynamite99** [comment]
ohhh must it be on the right hand side? i have been putting it on the left. that may explain that

**Comment by Dynamite99** [comment]
![2019-11-20_21 14 52](https://user-images.githubusercontent.com/52388333/69298079-d6a2f000-0bda-11ea-85b9-33cc24e8eb98.png)
i tried with this item in either hand on a skeleton and can tell you, it did not work

**Comment by kangarko** [comment]
Have you tried the damage multiplier option ?

**Comment by Dynamite99** [comment]
yes its still the same problem. i set it to all different values

**Comment by lackoSK** [comment]
Hello,

I think it shall be because there are required levels to each before you can use that weapon, try settings them to 0 and see if it works.

Regards,
lackoSK

**Comment by Dynamite99** [comment]
The required level is at 0 already and I changed it as well and made no difference.

**Comment by lackoSK** [comment]
Hello,

I think it will be a problem with MMOItems Premium; please contact the developer.

The problem is he doesn't store those item meta values correctly in MC API, so we can not register those weapons enchantments.

Regards,
lackoSK
