### ISSUE TITLE
Spawning 

### ISSUE THREAD

**Issue by CotedeBoeuff** [kangarko/Boss#487]
Hello, 

I’m french,

I can not spawn more than 1 boss per region and why spawners are not available with spigot ?

**Comment by lackoSK** [comment]
Hello,

Of course, they are!

Here is a wiki tutorial for 'spigot spawning' - mean Natural Spawning ;-)
https://github.com/kangarko/Boss/wiki/Natural-Spawning

You can spawn bosses in regions how much you want.

Take a look at here:
https://github.com/kangarko/Boss/wiki/Spawning-Limits

Hope, it will help ;)

Regards,
lackoSK ;-)

**Comment by kangarko** [comment]
What server version are you having?

Please ZIP me your Boss/ folder so I will take a look on why you can only spawn 1 Boss per region.

**Comment by CotedeBoeuff** [comment]
Hello

My version is the following 1.14 spigot





Le mer. 20 nov. 2019 à 21:19, Matej Pacan <notifications@github.com> a
écrit :

**Comment by CotedeBoeuff** [comment]
So ?

Le mer. 20 nov. 2019 à 21:42, Clément ONFROY <clement91.onfroy@gmail.com> a
écrit :

**Comment by lackoSK** [comment]
Hello, 

You haven't done that, what we requested yet. 

![image](https://user-images.githubusercontent.com/53174757/69343948-d5230780-0c6e-11ea-8179-6c2bd03d0f38.png)

Please send us the file so we can take a look at it ;-)

Regards,
lackoSK

**Comment by CotedeBoeuff** [comment]
I do not understand what you ask me, do you want my boss file? or a file?

Sincery

**Comment by lackoSK** [comment]
Hello,

Just a folder named 'Boss'.

Here's a guide:
https://github.com/kangarko/Boss/issues/432

Regards,
lackoSK

**Comment by CotedeBoeuff** [comment]
And message error and spawner



Le jeu. 21 nov. 2019 à 19:52, Clément ONFROY <clement91.onfroy@gmail.com> a
écrit :

>
>

**Comment by CotedeBoeuff** [comment]
Le jeu. 21 nov. 2019 à 19:53, Clément ONFROY <clement91.onfroy@gmail.com> a
écrit :

**Comment by CotedeBoeuff** [comment]
So ?


Le jeu. 21 nov. 2019 à 19:09, Clément ONFROY <clement91.onfroy@gmail.com> a
écrit :

**Comment by kangarko** [comment]
Please upload to us your Boss folder. The one that is in the server/plugins folder. Use uploadfiles.io for that. Thank you.

**Comment by lackoSK** [comment]
Closing the issue - User not responding
