### ISSUE TITLE
Spawner

### ISSUE THREAD

**Issue by CotedeBoeuff** [kangarko/Boss#489]
Hello,

How to ask a spawner with this message of error

"Boss spawners require Paper server software, as Spigot does not saves spawner data correctly. Upgrade for free at www.papermc.io."

**Comment by lackoSK** [comment]
Hello, 

It says if you want to use boss spawner you have to use paperspigot server, not a spigot.

Download it and replace spigot.jar to paperspigot.jar and it should work.
https://papermc.io/downloads

Regards,
lackoSK
