### ISSUE TITLE
Maven repository

### ISSUE THREAD

**Issue by SkytAsul** [kangarko/Boss#490]
Hello,
I'm the developer of a quests plugin and I'd like to add a custom objective with your plugin Boss.
While downloading the API file, I was wondering if there will be a Maven repository for this plugin (or only the API) in the future? It would be very useful for devs ^^
Thanks,
SkytAsul

PS: I'm a part of a team which provides free maven repo, in case you don't own one 😉

**Comment by lackoSK** [comment]
Hello,

You can hook it using the 'systemPath' dependency scope in Maven.

I think that is planned. 

Regards,
lackoSK

**Comment by SkytAsul** [comment]
That's what I planned to do, but this is not easy to do on a CI.
