### ISSUE TITLE
Pull Request for Another Plugin?

### ISSUE THREAD

**Issue by BobbyMere** [kangarko/Boss#494]
I was curious if you could do a pull request with [Jobs](https://github.com/Zrips/Jobs/pulls) and add support for this plugin. It would not only give you more publicity within a popular plugin, it would also widen your potential market.

**Comment by lackoSK** [comment]
Hello,

Thanks for this idea. We have already sent a message to the author of Jobs Reborn.

Regards,
lackoSK
