### ISSUE TITLE
Deny Mob-Spawning except Boss Mobs

### ISSUE THREAD

**Issue by Ghmmy** [kangarko/Boss#496]
I have been figuring out how to deny natural mob spwaning without disabling the spawns of the bosses. 
I have been making changes in-game and in the config on how bosses should sapwn, but it wont work:

`Prevent_Vanilla_Mobs:  
   Enabled: false/true
   Prevent_From: [NATURAL, CHUNK_GEN, SPAWNER, VILLAGE_DEFENSE, VILLAGE_INVASION, REINFORCEMENTS, INFECTION, CURED, DROWNED]
   Prevent_Mobs: [SKELETON]
      `

I have tried everything: "Enabled: false to true (and vice versa) | Prevent_From: [removed NATURAL] | Prevent_Mobs: [SKELETON, SPIDER, CREEPER, WITCH] and instead of Prevent_Mobs it was Entities which I removed because the little help msg said Prevent_Mobs instead of Entities" 

Summary: I want to deny skeletons, creepers, spiders, witches and enderman from spawning, making it only available for my custom zombie to spawn, but I cant make it to work, no matter what I do.

**Comment by BobbyMere** [comment]
you could do /gamerule doMobSpawning false
This would block all natural spawning but allow spawners, but this would effect the entire world. 
I know worldguard has the ability to block specific mobs from spawning so you might be able to hook into worldguard and allow specific boss to spawn

**Comment by lackoSK** [comment]
Hello,

I think you can use the "Converting" flag in setting.yml.

Regards,
lackoSK
