### ISSUE TITLE
Boss not deleting

### ISSUE THREAD

**Issue by 7SINS7** [kangarko/Boss#497]
Boss's are still in my world after delete and restart, how do I get rid of them?
Spigot
1.14

**Comment by lackoSK** [comment]
Hello,

Just do /boss butcher before you remove the bosses.

Regards,
lackoSK

**Comment by 7SINS7** [comment]
And what if you already deleted them? Cause that's not working.

**Comment by kangarko** [comment]
You can try creating a Boss with the same name then running the command again. If that does not work then unfortunately you have to use a third party command such as "/butcher named" or "/butcher all named". I believe these are available in EssentialsX or WorldEdit. But beware, these will remove ALL bosses and other custom named entities that are currently loaded.

**Comment by 7SINS7** [comment]
That’s fine, I appreciate very much you getting back to me with a solution!
