### ISSUE TITLE
Needing a refund

### ISSUE THREAD

**Issue by DeadEyeDonny101** [kangarko/Boss#499]
To whom it may concern,

Around 2 -4 days ago I bought this plugin because I saw that it was what I wanted on my server but I did not realize how restricted I was from doing things, like I did not have particle effect and sound effects. although it is very easy to use and it has a great selection of customization's, but I felt that I was restricted and there is too many things to think about, plus there was a couple bugs like some of the bosses did not  attack  the players near by and another was that they did not disappear after it was slain. other then those things there was nothing much. I am seeking a refund because its something i do not need right now but for the time being it was fun seeing what you have created.

**Comment by kangarko** [comment]
Hello,

the behavior of mobs is controlled by Minecraft not Boss, we cannot alter whom they attack. In the following next Boss milestone, version Boss 4.x.x, we'll be able to adjust that.

You may miss some of the features if you're running on an old server version, what's your version?

**Comment by DeadEyeDonny101** [comment]
I simply do not have time for the up coming updates and I feel restricted
by this, I also use version 1.13 which should work with the plugin just
fine but I still have some issues with the bosses not targeting the players
even though I checked through the config to see whether or not the
playe/entity targetting features are disabled, enabled and I applied these
changes. I just want to refund this plugin please, I am not satisfied with
the contents of this plugin, that's final.

**Comment by DeadEyeDonny101** [comment]
I simply do not have time for the up coming updates and I feel restricted
by this, I also use version 1.13 which should work with the plugin just
fine but I still have some issues with the bosses not targeting the players
even though I checked through the config to see whether or not the
playe/entity targetting features are disabled, enabled and I applied these
changes. I just want to refund this plugin please, I am not satisfied with
the contents of this plugin, that's final.

**Comment by kangarko** [comment]
What's your PayPal address?

**Comment by DeadEyeDonny101** [comment]
levkay@gmail.com

**Comment by DeadEyeDonny101** [comment]
Whoops wrong one, sorry, send it to this one
Correct one:
halilyusuf0920@gmail.com

**Comment by kangarko** [comment]
Refund sent
