### ISSUE TITLE
1.14.4 - Bosses not limited to 1 spawn per egg.

### ISSUE THREAD

**Issue by Elijeh** [kangarko/Boss#500]
Boss: 3.5.9
Paper: 237 (for 1.14.4)

I created a region from the plugin and set the limit to 1 spawn. I also set 'limits.apply_for_eggs' to true in configuration, but it seems like it's ignoring the option and you are able to spawn multiple bosses in the same region.

[Boss.zip](https://github.com/kangarko/Boss/files/4006219/Boss.zip)

**Comment by lackoSK** [comment]
Hey!

Apologies for the delay. I am not quite sure what you mean? When you set a limit for the egg to enable, you also have to set the actual limit (number)

**Comment by Elijeh** [comment]
Yes, that's what I did.

I set the limit to 1 in the region, but, you can spawn more than 1 boss in that region.

**Comment by lackoSK** [comment]
Hello, 

Apologies for the delay was on vacation.

Have you set the limit for the region or egg? 
Also, there's a perm:
>Perm: boss.bypass.eggregions
Info: Allow you to spawn bosses from eggs even outside of allowed regions.

**Comment by Elijeh** [comment]
I did set the limit for the region & egg. Setting the permission to false still allows me to spawn more than one boss in the region.

**Comment by kangarko** [comment]
@JavaFactoryDev may you also have a look at this? Thanks!

**Comment by JavaFactoryDev** [comment]
Hi Elijeh,

Thanks for reporting this issue.
I will have look at this.
If we can confirm this issue, we will fix it asap.

Regards,
Leonhard from MineAcademy.

**Comment by lackoSK** [comment]
> I did set the limit for the region & egg. Setting the permission to false still allows me to spawn more than one boss in the region.

You have to set the permission to false to deny access to them to place more than allowed.

**Comment by Elijeh** [comment]
> > I did set the limit for the region & egg. Setting the permission to false still allows me to spawn more than one boss in the region.
> 
> You have to set the permission to false to deny access to them to place more than allowed.

Like I said, I did set the permission to false. I can't spawn Bosses outside of the region, but I can still spawn multiple Bosses in the region which is annoying....

**Comment by kangarko** [comment]
@JavaFactoryDev @lackoSK

**Comment by JavaFactoryDev** [comment]
I will have a look^^

**Comment by lackoSK** [comment]
Okay,

We have fixed it it. You will be able to download it in the most recent update of the boss. ^^

Thanks to you for reporting this issue. 

Regards,
lackoSK

**Comment by JavaFactoryDev** [comment]
Thanks you for reporting this issue, we have fixed it with Boss 3.6.3.

Regards,
Leonhard from MineAcademy
