### ISSUE TITLE
Lands Plugin - Compatibility

### ISSUE THREAD

**Issue by KW2-GFX** [kangarko/Boss#502]
Greetings lads, would it be possible to add Lands compatibility ?
The lands plugin you can disable mob spawning on claimed chuncks, however that doesn't stop Boss entities to spawn on claimed areas, during the day and also during the night.

Here is the Land API : https://github.com/Angeschossen/LandsAPI
Thank you for you comprehension,

- Steph.

**Comment by lackoSK** [comment]
Hey,

Thanks for your suggestion. We will consider adding it.

**Comment by kangarko** [comment]
@KW2-GFX I apology for the delay, I am myself going to personally take this for you, I already contacted the developer at https://github.com/Angeschossen/LandsAPI/issues/3

**Comment by JavaFactoryDev** [comment]
Any issues?
