### ISSUE TITLE
New Foundation library not compatible with Aprils's Release of BossAPI

### ISSUE THREAD

**Issue by crazyeightlikesapples** [kangarko/Boss#503]
/K:/Minecraft_Dev/plugin_dev/Zara-Survival/src/main/java/com/zaramc/Survival/PlayerCache.java:[210,77] cannot access org.mineacademy.fo.helper.FoSerializable

I assume this package was renamed or moved from foundations library since April when BossApI was released?
Yes I have the newest foundations library

Hopefully it isn't too much work to fix, however it is critical to my application.

**Comment by kangarko** [comment]
@crazyeightlikesapples apology for the delay, did you get to solve this?

**Comment by crazyeightlikesapples** [comment]
yes I did, thank you
