### ISSUE TITLE
Error on console. Startup.

### ISSUE THREAD

**Issue by SoraShiunin** [kangarko/Boss#504]
Error on server startup. Said to post error.log here. So here it is. Plugin seems to work fine.
[error.log](https://github.com/kangarko/Boss/files/4030336/error.log)

Happy new year~

**Comment by lackoSK** [comment]
This error is only when starting up the server? Can you try to re-download the plugin?

**Comment by SoraShiunin** [comment]
Yes. Same error after redownload.

**Comment by kangarko** [comment]
@JavaFactoryDev

**Comment by kangarko** [comment]
Use PaperSpigot for 1.13.2 not CraftBukkit. You can get it for free here: https://papermc.io/api/v1/paper/1.13.2/653/download All plugins should be compatible

**Comment by SoraShiunin** [comment]
I'm using Spigot. I cannot use Paper, it is imcopatible with certain disguise and pet plugins I have.

**Comment by kangarko** [comment]
Ensure you are using latest 1.13.2 Spigot out there, right now it says you use CraftBukkit not Spigot

**Comment by SoraShiunin** [comment]
![Screenshot_2767](https://user-images.githubusercontent.com/23641964/71975708-8aecea00-320c-11ea-8b18-af103230cac9.png)

**Comment by JavaFactoryDev** [comment]
It says that its running Craftbukkit^^

**Comment by SoraShiunin** [comment]
> It says that its running Craftbukkit^^

"Version git-Spigot"

**Comment by JavaFactoryDev** [comment]
Thats the version

**Comment by SoraShiunin** [comment]
How do I get Spigot and why are all other 70 plugins working fine .-. ?
I got it from Buildtools, used console commands and put the spigot as my server jar.

**Comment by kangarko** [comment]
This will be fixed in the next Boss version :) @lackoSK
