### ISSUE TITLE
Boss regions or WG regions not work

### ISSUE THREAD

**Issue by WhiteFrost06** [kangarko/Boss#505]
Hello, all is in the title!

Whether regions with /boss region or regions with WorldGuard regions are not work in my server: I follow steps and bosses won't spawn, it's necessary for me because I have an rp server with dungeons so If the boss won't spawn, what can I do? I can't try spawners with PaperMC so I need this to work, ty by advance!

**Comment by JavaFactoryDev** [comment]
Hey WhiteFrost06,

Thanks for using Boss & reporting this issue.
please send us our boss.zip folder.

If we can confirm this issue we will fix it asap.

Regards,
Leonhard from MineAcademy

**Comment by WhiteFrost06** [comment]
[Boss-3.5.9.zip](https://github.com/kangarko/Boss/files/4049063/Boss-3.5.9.zip)

That's it (Inside this ZIP you have my Boss folder with my config and the jar)

**Comment by JavaFactoryDev** [comment]
Hi WhiteForst06,

Thanks for the Boss.zip I've received it.
Please don't upload the .jar File of Boss.
We will have a look.

But now its time for you to describe the issue further:

For clarification: 
What do you mean with not working: Arena Bosses spawning in these regions or aren't these regions showed in the regions-command?

Regards,
Leonhard from MineAcademy.

**Comment by WhiteFrost06** [comment]
Regions showed with commands, active, but the boss don’t spawn inside. So I have (example) region activated by the /boss create then in the GUI or the world guard region activated in the GUI, so my main problem is the apparition of the mob: it is not in active regions

**Comment by WhiteFrost06** [comment]
By the way, sorry for the upload of the JAR im dumb hahaha

**Comment by WhiteFrost06** [comment]
PS: The boss appear with eggs or command /b spawnpl or /b spawn, it not work ONLY with regions

**Comment by lackoSK** [comment]
Do you have set the region flag (allow spawn monsters) to true?

**Comment by WhiteFrost06** [comment]
For WG regions? Mob-spawning is allowing yeah, I’ll retry the action because mob spawn in my world too, so in regions I guess but I’m not sure, I’ll see tonight and I’ll be back in this issue, thanks! cya

**Comment by lackoSK** [comment]
Okay, let me know!

**Comment by WhiteFrost06** [comment]
Hey! That's not work again, I make the region again and mob-spawning is allowed. No boss appear :/

**Comment by JavaFactoryDev** [comment]
Hey WhiteFrost06,

Thanks for using Boss & Reporting this issue. We will fix it asap.
Might you please tell us which version of WorldGuard you're using.
If you have updated your Boss folder, it would be nice if you would be able to send it to us again, so we have the newest version.

Regards,
Leonhard from MineAcademy

**Comment by JavaFactoryDev** [comment]
User not responding - The issue will be reopened if a response is given.
