### ISSUE TITLE
Data of Spawners 

### ISSUE THREAD

**Issue by EVBlue** [kangarko/Boss#507]
I need data where the location of boss spawners is saved because I plan to copy worlds, and after copying the world of Multiverse-Core 2, the spawner becomes normal

**Comment by JavaFactoryDev** [comment]
Please follow #432

**Comment by lackoSK** [comment]
Hey,

Please, can you follow it so we can take care of your issue and fix it sooner ^^

Thanks!

Regards,
lackoSK

**Comment by lackoSK** [comment]
Closing the issue due to no response of the customer
