### ISSUE TITLE
Plugin Ignoring Configs?

### ISSUE THREAD

**Issue by SilkPenny** [kangarko/Boss#509]
I have tried without success since December to get support in Discord, so clicked the link on the Spigot page to come here for support.  It's entirely possible that something is wrong with my configuration, but with timed spawning, we have bosses spawning underground, outside the max radius and approximately every few minutes regardless of the time setting.

https://pastebin.com/xbcCsRPh

Above is current configs; the zipped file contains the rest of the folder.  We are presently on 1.15.2, but have had these issues since 1.14.4.  Currently running Boss 3.6.4

[Boss2.zip](https://github.com/kangarko/Boss/files/4119148/Boss2.zip)

**Comment by lackoSK** [comment]
Hello,

Can you please update to the most recent version of Boss? 

Thanks.

(Also send the files after update)

Regards,
lackoSK

**Comment by SilkPenny** [comment]
As noted above, we are running the most recent version of Boss - 3.6.4 - unless the Spigot page does not have the most recent version?

**Comment by lackoSK** [comment]
Hey, I'm sorry maybe miss looked on it. You are running the latest.

Can you set the debug to "spawning" and send us the output? 

Thanks!

**Comment by SilkPenny** [comment]
I changed debug to spawning and tried /boss reload, which resulted in the following, from console and the error log...

https://pastebin.com/vgtdqfJH

We have a scheduled restart incoming and will monitor after that?

**Comment by SilkPenny** [comment]
https://pastebin.com/0X8t9aiV

**Comment by JavaFactoryDev** [comment]
Hey SilkPenny,

Sorry for the delay, the Exception you send us was caused by another plugin which tries to use the Boss API which wasn't there in the older versions of boss.

However,
We've already fixed this in more recent versions of boss, can you try updating to the latest one?

Regards,
- Leonhard from MineAcademy

**Comment by SilkPenny** [comment]
We're up to date and the problem continues.  Do you know what plugin could be causing the problem?

**Comment by SilkPenny** [comment]
For the past few weeks, the plugin does not work at all.  We can use boss spawn eggs, but timed-spawning is doing nothing.  Is there an issue in my configs?

https://pastebin.com/cPFWHcNN

**Comment by kangarko** [comment]
@JavaFactoryDev

**Comment by SilkPenny** [comment]
I tried a fresh install again and this morning, it appears they are not only working again, but adhering to the configs for timed spawning!  I'll close the issue and reopen if we have problems again.
