### ISSUE TITLE
1.13.2 - Bosses spawning behind the minecraft barrier

### ISSUE THREAD

**Issue by EVBlue** [kangarko/Boss#510]
Bosses spawning behind the minecraft barrier. I think this might be a bug
Using an open thread, I would also like to ask about the function of removing the name of the world from the placeholder {location}
Sorry for my English ;)
[Boss.zip](https://github.com/kangarko/Boss/files/4124536/Boss.zip)

**Comment by lackoSK** [comment]
Hello,

Apologies for the late reply, 

I do not clearly understand your issue, can you explain it? 

Thanks!

Best,
lackoSK

**Comment by EVBlue** [comment]
I have a server survival and Minecraft border set to 2000 in each direction. When I tested the plugin on the smaller 15x15 barrier, boss spawn off the barrier

**Comment by lackoSK** [comment]
Hello,

Did you set it to spawn only within the space? 

It may be affected by chunks.

Set debug in settings.yml to "[spawning]" and send us the output.

regards,
lackoSK

**Comment by JavaFactoryDev** [comment]
The user is not responding.

Please respond to reopen this issue.
