### ISSUE TITLE
Teleport boss back to center of a region

### ISSUE THREAD

**Issue by skerit** [kangarko/Boss#511]
I enabled the option to teleport bosses back into the region once they move out of it, but it just teleports them back a few blocks. So they keep on trying to leave the region, and it looks a bit silly.

Is it possible to teleport them back to the center of the region, or arround the spawner they spawned from?

**Comment by lackoSK** [comment]
Hello,

No, it's not possible. But I will add it within a few days ^^ (If I will have time)

Regards,
lackoSK

**Comment by JavaFactoryDev** [comment]
Hello skerit,

We added this feature was implemented in version 3.6.7 of Boss.

Thank you for requesting it:)

Regards,
- Leonhard from MineAcademy
