### ISSUE TITLE
BossDeathEvent does not exist in the API

### ISSUE THREAD

**Issue by skerit** [kangarko/Boss#512]
I'm using the BossQuest extension for the Quest plugin, but it fails to load on 3.6.7:

`Plugin Quests v3.8.4-b56 has failed to register events for class me.pikamug.BossQuestsModule.BossKillObjective because org/mineacademy/boss/api/event/BossDeathEvent does not exist.`

Someone else actually reported this in an issue on the BossQuest repository (https://github.com/PikaMug/BossQuestsModule/issues/2) where @kangarko even replied, but then the original reporter said it was fixed in 3.6.5.

But now it seems to be happening again. I downgraded to 3.6.1 and that seems to work for now.

**Comment by JavaFactoryDev** [comment]
Hey skerit,

Thank you for using Boss & reporting this issue.
We have fixed it with the latest version Boss 3.6.8

Regards,
- Leonhard from Mineacademy
