### ISSUE TITLE
1.12.2 Magma Cube bosses ignoring "Spawn Babies" Option + another issue

### ISSUE THREAD

**Issue by ElFlyGod** [kangarko/Boss#513]
1) Magma cubes are ignoring the "spawn babies" setting and are splitting anyway.

2) Mobs are sometimes spawning half way inside of blocks and getting stuck when spawning them inside worldguard regions

Plugins: Just worldguard

**Comment by JavaFactoryDev** [comment]
Please follow #432

**Comment by JavaFactoryDev** [comment]
Hey ElFlyGod,

As stated in #432 we need your Boss-Folder as a .zip file to have a look at your issue.

Regards,
- Leonhard from MineAcademy

**Comment by JavaFactoryDev** [comment]
Will be reopened when we receive the data we need.

**Comment by kangarko** [comment]
@JavaFactoryDev next time just take the information he provided and test it yourself please
