### ISSUE TITLE
Just a few question

### ISSUE THREAD

**Issue by TanKakashi** [kangarko/Boss#514]
I saw how their were customs spawn at different times I just wanted to know how it works and if it can be a timer spawn so after a X amount of time the boss/mob will respawn if there is a way this can be done and someone to tell me I will 100% purchase this plugin.

**Comment by JavaFactoryDev** [comment]
Hey TanKakashi,

Thank you for asking this question.

We apology the delay.

You can archieve this using times spawning ass shown in the wiki.

However, I dont think it is possible to respawn a boss after a specific durarion.


Regards,
- Leonhard from MineAcademy
