### ISSUE TITLE
Spawner question

### ISSUE THREAD

**Issue by BobbyMere** [kangarko/Boss#515]
Is there a way to put a hard mob cap limit on a spawner? There's a mob cap for a specific area where the mob spawns, but if the mobs go outside of that spawn zone, the cap is not effected.

**Comment by JavaFactoryDev** [comment]
Hey BobbyMere,

thank you for using Boss & asking this question here.

You can find the answer in the wiki under the point „Spawning-limits“


Regards,
- Leonhard from MineAcademy
