### ISSUE TITLE
[1.8.8] Multiple bosses spawning at once (Factions & ProtocolLib Errors on Boss Spawn)

### ISSUE THREAD

**Issue by LilDevs** [kangarko/Boss#519]
Heyo, For some reason timed spawning spawns like 50 bosses, not in the region and all over the warzone in my world. I get this error whenever the bosses spawn.
`5.02 00:07:54 [Server] INFO Reloading plugin Boss v3.6.7
25.02 00:07:54 [Server] WARN [ProtocolLib] [PacketFilterManager] Verifier error: Cycle detected in dependency graph: Factions v1.6.9.5-U0.2.1-RC-1.6.2-RC-2.3.1
25.02 00:07:54 [Server] INFO Loading bosses (2) ..
25.02 00:07:54 [Server] INFO > Loading SkeletonKing
25.02 00:07:54 [Server] INFO > Loading SkeletalKnight
25.02 00:07:54 [Server] INFO ______________________________________________________________
25.02 00:07:55 [Server] WARN Exception in thread "Craft Scheduler Thread - 358" 
25.02 00:07:55 [Server] WARN Exception in thread "Craft Scheduler Thread - 357" 
25.02 00:07:55 [Server] WARN org.apache.commons.lang.UnhandledException: Plugin Boss v3.6.7 generated an exception while executing task 31137
25.02 00:07:55 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
25.02 00:07:55 [Server] INFO at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
25.02 00:07:55 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
25.02 00:07:55 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
25.02 00:07:55 [Server] INFO at java.lang.Thread.run(Thread.java:748)
25.02 00:07:55 [Server] INFO Caused by: java.util.ConcurrentModificationException
25.02 00:07:55 [Server] INFO at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719)
25.02 00:07:55 [Server] INFO at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:752)
25.02 00:07:55 [Server] INFO at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:750)
25.02 00:07:55 [Server] INFO at org.mineacademy.boss.lib.fo.collection.super.serialize(SourceFile:169)
25.02 00:07:55 [Server] INFO at org.mineacademy.boss.double. .nUL.const(SourceFile:96)
25.02 00:07:55 [Server] INFO at org.mineacademy.boss.double. .aq.strictfp(SourceFile:1218)
25.02 00:07:55 [Server] INFO at org.mineacademy.boss.double. .aq.native(SourceFile:1191)
25.02 00:07:55 [Server] INFO at org.mineacademy.boss.double. .COM3.do(SourceFile:127)
25.02 00:07:55 [Server] INFO at org.mineacademy.boss.double. .COM3.if(SourceFile:70)
25.02 00:07:55 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
25.02 00:07:58 [Multicraft] Skipped 585 lines due to rate limit (30/s)`
[Boss.zip](https://github.com/kangarko/Boss/files/4248927/Boss.zip)

**Comment by JavaFactoryDev** [comment]
Hey LilDevs,

Thank you for using Boss & reporting this issue here.
Can you please upload your exception here: pastebin.com

Regards, 
- Leonhard from MineAcademy

**Comment by LilDevs** [comment]
@JavaFactoryDev https://hastebin.com/teluwiyamu.rb

**Comment by JavaFactoryDev** [comment]
Hey LilDevs,

thank you for reporting this issue,
it will be fixed until the next release.

Regards,
- Leonhard from MineAcademy

**Comment by LilDevs** [comment]
Still not fixed, Same issue/error

**Comment by JavaFactoryDev** [comment]
Hey LilDevs,

sorry for the delay,
as far as I know this issue should have been fixed.

I am sorry for not posting this here.

Regards,
- Leonhard from MineAcademy

**Comment by JavaFactoryDev** [comment]
User doesn't respond.
