### ISSUE TITLE
1.12.2 (Paper fork): Boss sometimes throw error in console with WorldGuard

### ISSUE THREAD

**Issue by ArcadeFighter** [kangarko/Boss#522]
Boss 3.7.1
Paper Fork 1.12.2

When i start server, it paste error from Boss. We using little bit different WorldGuard (optimized version). And this error is same on regular WorldGuard, please can you check where is issue? (WorldGuard: 6.2.2-SNAPSHOT;8eeab68)

Error log:
https://pastebin.com/97R45i3S

Here is Boss folder:
[Boss.zip](https://github.com/kangarko/Boss/files/4334165/Boss.zip)

**Comment by JavaFactoryDev** [comment]
Hi AracadeFighter, 
it seems like your WorldGuard is incompatible with the needed WorldGuard.
As the exception tells you, the class com.sk89q.worldguard.WorldGuard is missing.

This is not an boss-issue. 
You could just add this class to your WorldGuard version or just don't name it WorldGuard so
Boss won't detect it as WorldGuard.

Regards,
- Leonhard from MineAcademy
