### ISSUE TITLE
Suggestion: Support Players and Player skins

### ISSUE THREAD

**Issue by LilDevs** [kangarko/Boss#523]
This plugin seems like it has very great potential, but there is little to no custom-ability in my perspective. I think individuals would like to have the choice to chose a player type aswell, so if you want a specific mob, the player skin would be MHF_Crepper or the skin of the player they want to fight and the boss will actually be able to hold items and attack doing physical damage.

Also, Add Custom Enchants to be able to work with the bosses gear. I tried to make the boss have custom enchants, but it does not work. The plugin I am using is AdvancedEnchantments.

Finally, I think that these would be amazing features as they give the player more custom-ability over the bosses that they choose to make and it will attract more potential buyers.

**Comment by JavaFactoryDev** [comment]
Hey LilDevs,

thank you for providing this suggestion.

We already know about it.
We will implement it in Boss-4.0 on which we are already working on.

Regards,
- Leonhard from MineAcademy

**Comment by Baktus79** [comment]
#637
