### ISSUE TITLE
[Suggestion] Kill enough Mobs to spawn a personal boss. 

### ISSUE THREAD

**Issue by NextImBlack** [kangarko/Boss#524]
Hey! 
I don't make a suggestion from a lot of time, and I got some time to do it: I wanna suggest a feature that allows you to spawn a boss once you have killed enough entities of that category; for example, I wanna spawn a Zombie Boss, in the Configuration file of the boss I will add a required number of mobs to be killed in order to spawn it, once you have got that kills, a lot of particles will spawn and the boss will appear. To allow more customization, I would like to suggest the ability to edit the title of the boss, so you can add Placeholders for HPs, Boss name, etc (Above his head to be exact). An optional feature for this thing could be the despawn <b>despawn timer</b>, you can set a time to kill the boss, so, for example, if you don't kill it within 2 minutes, it will disappear and you fail the boss, you may also add another line in the boss head that indicates the expiration of it. 

Please let me know if you don't understand something, I'll be available to explain everything.

**Comment by JavaFactoryDev** [comment]
Hey NextImBlack

thank you for providing these suggestions,
we will consider adding them to Boss 4 which is already in the early stages of development.

However, the feature to change the name of the is already included in current versions of boss.

Be prepared for new awesome stuff.

Regards,
- Leonhard from MineAcademy
