### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by LucidAPs** [kangarko/Boss#526]
Minecraft : 1.15.2
Tuinity : Build 13
Java : 11
Boss : 3.7.1

Error with lots of lag.
https://pastebin.com/raw/mfRCE3g9
Configs:
[config.zip](https://github.com/kangarko/Boss/files/4366216/config.zip)

**Comment by JavaFactoryDev** [comment]
"THIS IS NOT A BUG OR A CRASH"

**Comment by LucidAPs** [comment]
OKEY!!! THANKS FOR THE ALL CAPS!!

**Comment by kangarko** [comment]
@JavaFactoryDev next time please have a more thorough and professional explanation
