### ISSUE TITLE
[1.14.4]region spawn doesn't work

### ISSUE THREAD

**Issue by sgary7** [kangarko/Boss#527]
i have tried boss,residence,worldgurad region spawn, all didn't work.
and how can i translate gui into other language？
 
server paper 1.14.4 build 243
plugin ver. 3.7.0
 
[Boss.zip](https://github.com/kangarko/Boss/files/4453520/Boss.zip)

**Comment by reussy** [comment]
open the .jar with WinRar and go into the "localization" folder and they have different languages

**Comment by Eik0** [comment]
Same here, no spawning in regions

**Comment by JavaFactoryDev** [comment]
Hey sgary7,

I am sorry for the delay can you try using Boss-regions instead of world guard regions and tell me whether it is working now?

Regards,
- Leonhard from MineAcademy

**Comment by sgary7** [comment]
boss regions also didn‘t work

**Comment by JavaFactoryDev** [comment]
I will have a look

**Comment by kangarko** [comment]
@JavaFactoryDev

**Comment by JavaFactoryDev** [comment]
Hey sgary7,

I just had a look:
Are other spawn-types working



Regards
Leonhard from MineAcademy

**Comment by sgary7** [comment]
Are other spawn-types working?
**yes,world spawn and condition spawn all work**
Do vanilla mobs spawn on these regions?
**yes**
Does this only happen on 1.14.4? (Have you seen it working on different versions? If you haven't tested it just don't mind)
**only test in my 1.14.4 server**

**Comment by JavaFactoryDev** [comment]
I am sorry for the delay: It seems very likely that you have some anti-lag plugin enabled which causes boss to stop executing its tasks.

**Comment by JavaFactoryDev** [comment]
Can you send me a list of plugins that you are using.

**Comment by JavaFactoryDev** [comment]
Reopened when user will respond.
