### ISSUE TITLE
Changing item for spawn egg creates a black and purple undefined item

### ISSUE THREAD

**Issue by Spoggs** [kangarko/Boss#528]
I have tried changing the spawn item to several things like nether star and bones and now I cant even change it back to a normal egg. :/
![c9df50ca74a8c906cad53a3aa285c232](https://user-images.githubusercontent.com/63387929/78860707-b50a9f80-79e7-11ea-8113-7d04731ce2a6.png)
![d76691637c8fd98943bffb4f742aac4c](https://user-images.githubusercontent.com/63387929/78860709-b76cf980-79e7-11ea-9789-bc6791ac61af.png)

**Comment by JavaFactoryDev** [comment]
Hey Spoggs,

As Boss tells you the item you were trying to use it now valid.
You can change the item in your BOSS_NAME.yml file

Regards,
- Leonhard from MineAcademy
