### ISSUE TITLE
Spawn naturally

### ISSUE THREAD

**Issue by reussy** [kangarko/Boss#529]
I have a question, based on what I have been looking at and as I have configured the plugin, the natural spawneo depends on the conditions that are set.
But, if the bosses are configured by worlds, worlds where there will be no users normally, the boss will spawn or there must be at least one user in that world.
I ask this because when I am out of the world neither of the two bosses I have created spawns and when I enter the world yes, it is possible to change that from settings.yml or it cannot.

**Comment by JavaFactoryDev** [comment]
Hex reussy,

thx for using boss & asking this question here.

Sorry for the delay.

However you can of course change this in your settings.yml / boss-file / the boss-menu (/boss menu)

Regards,
- Leonhard from MineAcademy
