### ISSUE TITLE
Boss mounts are sometimes babies

### ISSUE THREAD

**Issue by bc-hill** [kangarko/Boss#53]
![image](https://user-images.githubusercontent.com/7044511/36356745-0f68af3e-14ab-11e8-8127-f10542686c9d.png)

As above.  Seems like a small percentage of the mounts are babies.

Boss 1.5.10.  Let me know if you need more info.
Thank you!

Edit: Actually, it is more like 25% of them, at least with zombie horses.

**Comment by kangarko** [comment]
Thank you, that will be fixed!
