### ISSUE TITLE
1.8.8: Skills issue

### ISSUE THREAD

**Issue by BluueJay** [kangarko/Boss#530]
As a boss uses its' abilities against players, the skill messages don't send. 

For example when a boss uses the "Confuse Player" ability, it won't send anything in the chat notifying the player that the boss did it.
Confuse Player.yml in "skills" folder: https://pastebin.com/CyTjCWBB

---

Another problem I'm having is when a boss dies, the placeholder {killer} will only display one of the killers, this plugin has the feature to reward the last 5 damagers so how would I display the last 5 damagers in chat? 
I've seen past issues report similar questions a couple of years back and get closed saying it's planned so I'm wondering if it was added but not documented.

Here's my Boss plugin folder:
[Boss.zip](https://github.com/kangarko/Boss/files/4541107/Boss.zip)

Server version: Paper 1.8.8

Thanks.

**Comment by JavaFactoryDev** [comment]
Hey BlueeJay,

thank you for reporting this issue.
Please follow #432

**Comment by kangarko** [comment]
Closed due to inactivity, if you are still experiencing issues please comment below and we will get notified.
