### ISSUE TITLE
Disappearing drops

### ISSUE THREAD

**Issue by Jirsaacek** [kangarko/Boss#536]
Drops that are set in menu of boss just randomly disappear, sometimes all of them sometimes just few of them. Any idea what can cause this and how to fix it? Thanks :)

**Comment by kacperleague9** [comment]
i have no drops

**Comment by kangarko** [comment]
@JavaFactoryDev

**Comment by JavaFactoryDev** [comment]
Please follow #432

**Comment by kacperleague9** [comment]
[Boss.zip](https://github.com/kangarko/Boss/files/4621345/Boss.zip)
1.12.2

**Comment by 100petr** [comment]
paper 1.15.2
[Boss.zip](https://github.com/kangarko/Boss/files/4621369/Boss.zip)

**Comment by JavaFactoryDev** [comment]
Thanks for reporting this we will have a look now

**Comment by JavaFactoryDev** [comment]
Duplicate - News on #543
