### ISSUE TITLE
Run Commands on Mob Death

### ISSUE THREAD

**Issue by MythicCanadian** [kangarko/Boss#537]
I purchased the plugin and love it! I was just wondering if there is any way to make commands run when a boss dies. 
Thanks for any help!

**Comment by kangarko** [comment]
@JavaFactoryDev

**Comment by JavaFactoryDev** [comment]
Hey MythicCanadian,

Thank you for asking this question here.
This is not yet possible without using the API. (Just use the boss-death-event.)
Also, there is an extension for Boss that might help you: https://www.spigotmc.org/resources/bossesexpansion-addon-for-mythic-mobs-boss.57215/

However, it is already planned to add this feature in future versions of boss.

Regards
Leonhard from MineAcademy
