### ISSUE TITLE
Boss Spawn limit issue?

### ISSUE THREAD

**Issue by Vehzx** [kangarko/Boss#538]
Hi, having an issue trying to get a boss limit on my boss.

I set the boss to spawn every 3 hours, but for testing this I set it to 20 seconds.

I just want a limit of 1 of the boss to spawn every 3 hours, on each spawn every 3 hours the old boss should be removed so that it's just the new boss that spawned.

The boss does spawn every 20 seconds when testing, but there is no limit, they just keep spawning every 20 seconds.

I can see you can limit the bosses when using region spawning, but I just want the bosses to spawn randomly within the world like they are doing with my current setup.

If there is a way of limiting the spawns of the bosses to 1, and removing the old boss on each timed spawn, could you please show me how to do it, as I can't seem to find how to.

Boss config: https://pastebin.com/SPSGfTje
settings.yml config: https://pastebin.com/yP2ntbQb

**Comment by kangarko** [comment]
@JavaFactoryDev

**Comment by JavaFactoryDev** [comment]
Hey Vehzx,

Thank you for reporting that issue.

Just one question: Have you made sure, that the boss is still in the region it should be spawned in?

Regards
Leonhard from MineAcademy

**Comment by Vehzx** [comment]
I didn't give the boss a spawning region with worldguard or boss, as I don't need them.

For spawning the boss on timer, I am only using the open world biomes to spawn it

**Comment by JavaFactoryDev** [comment]
Same applies here: Did you make sure that the boss is in the same biome?

**Comment by Vehzx** [comment]
Yes, the only issue I have is I cannot limit the boss to spawn to a maximum of 1.

From what I can see, I can only limit the amount of the boss to spawn when using worldguard or boss regions.

How can I limit the boss to a maximum of 1 spawning every timed spawn?
Since i'm not using any regions and i'm just using biome spawning

**Comment by JavaFactoryDev** [comment]
Hey Vehzx, 

I've searched for something like to fix ur issue atm.
I think the best way of doing this is using a normal boss-spawner and "bossify" is by using the tools. The spawning is also timed, but you can also define a custom limit.

Regards, 
Leonhard from MineAcademy

**Comment by Vehzx** [comment]
Hm okay, will try this as a work-around, thanks

**Comment by JavaFactoryDev** [comment]
Please tell me it that works:)

**Comment by Vehzx** [comment]
Well I used a boss spawner to spawn the boss and a custom limit which does work how I want it to, but with the spawner obviously it cannot spawn the boss randomly through the world which is what I was aiming for.

However if there is no way to solve my issue of getting them to spawn throughout the world on a timed spawn, this will be fine i'm sure I can use this as a workaround :)

**Comment by JavaFactoryDev** [comment]
I will be searching for a solution, however this might take a while as such issues have to be replicated over the long run.

**Comment by JavaFactoryDev** [comment]
Seems like you didn’t apply ur limits in the settongs.yml.

**Comment by JavaFactoryDev** [comment]
If you apply it the limits should work, too, couldn't find any issues so far.
