### ISSUE TITLE
[1.15.2] Equipment disappears right after putting it on

### ISSUE THREAD

**Issue by DogeTennant** [kangarko/Boss#540]
Ahoj, mám takovej problém na verzi 1.15.2, když chci u bosse editnout jeho equipment, tak tam něco nasadím, ale ovšem hned poté co odkliknu Return a vrátím se do equipmentu, tak ať už jsem tam dal cokoliv tak to zmizelo (nezáleží jestli to byl armor nebo něco do ruky a jestli to byl naprosto vanilla item nebo s nějakýma tagama). Item ihned zmizí i když pouze přepnu na Editing Items (click to edit drop chances)

Plugin je na verzi 3.7.1 jelikož 3.7.2 nějak nejde stáhnout, ale stejně jsem si nevšiml že by se v té verzi nějaký takový bug opravoval, takže by to asi nepomohlo
Server běží na 1.15.2 na Paperu

Tohle je config i když si nedokážu představit co tam by to zrovna kazilo: https://pastebin.com/epWmWnsk

Předem díky za pomoc!

edit: Nevím jestli to pomůže, ale pokusím se podat další informace, které by co nejdříve vedly k vyřešení problému, jelikož to potřebuji celkem rychle :D

Do Loot Table lze dát jakékoliv itemy a po smrti z moba také vypadnou, takže tam problém není, co jsem tak zkoušel, tak je to opravdu jen u toho equipmentu. Taky se jedná o Zombie, takže si nemyslím že by se tam stala nějaká chyba jako že bych chtěl házet armor na slepici nebo něco.. :D

edit2: V konzoli jsem našel pouze toto: 
[07:21:49] [Server thread/WARN]: [Boss] Loaded class com.comphenix.protocol.events.PacketAdapter from ProtocolLib v4.5.0 which is not a depend, softdepend or loadbefore of this plugin.
[07:21:49] [Server thread/WARN]: [Boss] Loaded class net.milkbowl.vault.economy.Economy from Vault v1.7.2-b107 which is not a depend, softdepend or loadbefore of this plugin.

Dále pak jsem zjistil že tento problém nemáme na našem test serveru, ovšem mi uniká co je na našem test serveru jiné, jelikož jsou tam stejné pluginy, stejná verze a je tam i Paper stejně jako na našem main serveru.

edit3: Zde ještě dodávám config z test serveru https://pastebin.com/yPVpkAbH

edit4: Jo a jak na našem test serveru tak na main serveru je stejná verze pluginu a to jak už jsem zmínil 3.7.1, i přes to však z nějakého důvodu tento problém nenastává na test serveru, ale na main serveru (kde to doopravdy potřebujeme) ano

**Okay po dalším testování s pluginem jsem narazil na 2. problém.**

Nevěděl sem jestli založit nový topic nebo to nechat tady, každopádně to zatím dám sem a pokud to bude vadit udělám nový

Když chci aby se mobové spawnovali v regionech tak to nefunguje. Všechny ostatní způsoby spawnování fungují (podle biomu, světa atd..), ale regiony prostě ne. Používám přímo Boss Regions (WorldGuard, Towny, atd.. nemáme), vyberu dva body, dám příkaz /boss region add jmeno, ověřím si že fakt existuje, vezmu bosse, nastavím mu spawn ve světě ve kterém jsem na 100% (ujistil sem se tak 10x že je to správnej svět), pak jdu do Region Spawning a tam zapnu region spawning do toho regionu (a určitě jsem si nespletl region protože je to jedinej kterej tam je) a je jedno co v něm nastavím, jestli aby se spawnul 1 boss nebo unlimited, nikdy se nespawne ani jeden a kontroloval sem i podzemí i když tam by se objevit neměl, jelikož byl boss nastavený na výšku 64-256 + region byl vybraný někde ve výšce 85-90. Když tam bosse spawnu pomocí vajíčka tak to "funguje" v tom smyslu že ho nemůžu spawnout mimo ten region a pokud jsem tam nastavil limit tak ho ani nemůžu spawnout víckrát než je povoleno, ale sám od sebe se tam prostě za žádnou cenu nespawne - co se týče informací o serveru, verzi atd.. všechno platí stejně jako u předchozího problému až na jednu věc, že ten region spawning nefunguje ani na testu, kde se můj první problém nenacházel, každopádně tohle je na obou serverech..

**Comment by JavaFactoryDev** [comment]
Please use english
