### ISSUE TITLE
[1.15.2] Equipment disappears right after putting it on and Region spawning doesn't work

### ISSUE THREAD

**Issue by DogeTennant** [kangarko/Boss#541]
Okay first of all, I'm really sorry about my previous post not being in English, but I expected kangarko to respond so I wrote that in Czech, because he would understand it, so once again I'm sorry.
----------------------------
**Issue no. 1**

Hello, I have this problem on version 1.15.2, when I want to edit boss equipment, then I simply can't, whatever I put in the slots (they are the correct slots) it simply disappears after I click "Return". Also it doesn't matter if I put it as an item in hand or as an armor item or if it a completely vanilla item or something modified (custom item). The items even disappear when I just want to edit drop chances, I click the option and the items disappear. Plugin version is 3.7.1 since I can't download the 3.7.2 one, but since the only thing that changed is some "Lands" support, I suppose it wouldn't help anaways. Server runs on 1.15.2 Paper.

This is the config: https://pastebin.com/epWmWnsk

Also there's no problem with putting stuff into the Loot Table, I can put items there, even custom items and edit their drop chances with no issues, so the only problem is the equipment. In addition the mobs that I've tried were Zombie and Skeleton, it isn't like I was trying to put armor on a chicken or something :D

However I noticed something weird, on our test server the equipment is working. However the server is almost identical, runs the same server version and plugin version and almost all the other plugins are the same too.

This is the config from our test server: https://pastebin.com/yPVpkAbH

**And this is the only thing that I found in the console:** (main server, not the test server)
[07:21:49] [Server thread/WARN]: [Boss] Loaded class com.comphenix.protocol.events.PacketAdapter from ProtocolLib v4.5.0 which is not a depend, softdepend or loadbefore of this plugin.
[07:21:49] [Server thread/WARN]: [Boss] Loaded class net.milkbowl.vault.economy.Economy from Vault v1.7.2-b107 which is not a depend, softdepend or loadbefore of this plugin.

**Issue no. 2**

Region Spawning simply doesn't work. All the version and config info applies from the previous issue. All the other ways of spawning work (World, Biom, etfc..), but regions simply don't. I use directly Boss Regions, because we don't use WorldGuard, Towny, etc.. I choose two regions, I type /boss region add name, I make sure the region actually exists, I set his spawn to the world I'm in (I made sure several times over), then I go into the Region Spawning option, I enable the spawning for the selected region (and I definitely didn't choose the wrong region, since there was only one created). However no matter the settings, the boss simply won't spawn in the region. I even checked underground, but I knew he wouldn't be there, since the region I created was like 85-90 in height and in the Native Conditions I set the height to 65 - 256 (all the other Native Conditions I left default). When I spawn the boss via spawn egg it kinda "works", by that I mean that I can't spawn him anywhere else other than the region and it also respects the limit I set in the region. But he just won't spawn there by himself. Also this problem appears on our test server aswell, this isn't exclusive to our main server..

Thanks in advance for your help and once again I'm sorry for using Czech haha.

**Comment by JavaFactoryDev** [comment]
Hey DogeTennant,

Thank you for reporting this issue here.

First of all: No worries - but usually me not kangarko responds here.

Regarding your issues: Thank you so much for the detailed description, this will really help us.
However - We need your boss folder to fix it. Can you upload it please?

Regards
Leonhard from MineAcademy

**Comment by DogeTennant** [comment]
Hi, of course here it is

Main server: http://www.mediafire.com/file/qcpv40kmm2zc69d/Boss.7z/file

Test server: http://www.mediafire.com/file/vsjyj9u7cnuakb3/Boss%25282%2529.7z/file (not sure if needed, but included anyways)

**Comment by JavaFactoryDev** [comment]
Hey, I think I've found ur issue: You can't place anything in there because you're using hotkeys.
However, doing it manually should work

**Comment by JavaFactoryDev** [comment]
Please tell me if this is wrong - Issue will be reopened then.

**Comment by DogeTennant** [comment]
Hello, that is not the case, I was doing it manually since the very beginning, here a video example:

https://www.youtube.com/watch?v=oM7VReERQlc&feature=youtu.be

Still not working on the newest version of the Boss plugin (3.7.3)


Also the boss region spawning still doesn't work on the newest version, here's a video example:

https://www.youtube.com/watch?v=najR-6v6w0Y&feature=youtu.be

All the config settings and the folder is still completely the same, except I just created a new boss for demonstration purposes.

**Comment by DogeTennant** [comment]
> Please tell me if this is wrong - Issue will be reopened then.

Hello, is this being looked into?
