### ISSUE TITLE
[1.15.2] Gamebreaking bug connected with player movement

### ISSUE THREAD

**Issue by DogeTennant** [kangarko/Boss#542]
Hello, today I discovered a bug with player movement being rendered almost impossible after a glitch with a "Freeze Player" ability.

**Requirements for the bug to happen:**

A mob with the ability "Freeze Player"
A player with the ability to use "/fly" command  (on our server VIP players have it and of course, our staff)
Fly around fast while the mob/s will try to catch you into the web
Once you get caught, make yourself die (most likely you will die because of the mobs if you flew near the ground)

**What will happen afterwards:**
- This wont happen on every try, I managed to "bug" myself like this after like 25 tries.

The player wont be able to walk or sprint = but will be able to move while falling, swimming and jumping
The player wont be able to fly using the command /fly or even /gm (you can press double space to get into air, but after that you cant move in any way, not even down, the only thing you can do is double press space again to get down)

**What have I tried:**

restarting the server
relogging
killing the player (or myself)
switching worlds (multiworld)
Killing myself/the player in a different world
giving speed potion effect
getting stuck in the web again and dying (again)
getting stuck in a normal web and dying there
getting stuck in a web (both normal and the freeze player ability) and just teleporting to the spawn
removing the plugin after the restart

There's one thing that kinda works, but is in no way a solution and that is equip something with a speed modifier (not the speed potion effect, but the attribute) when I have it equipped and I set the item's speed modifier to the default walk speed, I can run around and sprint just normally, but I still cant fly as speed modifier doesn't affect fly speed.

More things I tried after finding this out

equipping a speed mod. armor and dying with it
equipping a speed mod. armor switching worlds and back
equipping a speed mod. armor switching world and dying there
equipping a speed mod. armor and relogging/restarting (tried both)

However everytime after I took off that armor, my speed returned to 0

**My opinion on what might've caused it:**
Well I noticed that when the mobs use this ability, unless I jump into the cobweb, my speed becomes zero until the cobweb disappears. As I said you have to die while in the cobweb for the bug to happen, so my theory is that when your speed is zero and you die in the cobweb, the zero speed attribute stays with you and simply can't disappear and the only way you can get partially rid of it, is by adding a positive speed mod. but of course that will only solve walk and sprint and not fly and also it's just a really silly solution overall.

Also the server runs on Paper.

If you need my config and boss folder then it's in my other issue posted here: https://github.com/kangarko/Boss/issues/541 everything in this topic is the same as right now, the files are still identical so it should be enough, I hope..

Luckily "only" one player and me got bugged like that and since then I removed the entire plugin until this gets fixed, but still this is a huge bug and could easily break the game for many players.

Thanks in advance for your response! (Also I will try to take a video replicating the bug, but not sure I will manage to do it).

**Comment by DogeTennant** [comment]
Okay, I figured out a solution:

1. Downloaded NBTExplorer
2. With the program I found and opened my my UUID.dat in the worlds playerdata folder
3. Opened it and found out that the Freeze Ability and death afterwards changed my:
a. flying to 0
b. flySpeed to 0
c. walkSpeed to 0
d. generic.MovementSpeed to 0
4. As seen here (already fixed) but everything I mentioned was set to 0
![playerdata](https://user-images.githubusercontent.com/35350058/81873010-27d4e080-957b-11ea-9bba-b81883a50b7d.png)

So I found the solution, but still the plugin really shouldn't mess with these stats like that, as it is impossible for anyone to fix except for the people who have access to the server files (which usually is like one or just very few people) and even they might not be able to know what to do. 

I will still try to replicate the bug if I manage to do so.

**Comment by JavaFactoryDev** [comment]
Hey DogeTennant ,

Reporting this issue here.
Take your time to reproduce it.

Regards
Leonhard from MineAcademy

**Comment by DogeTennant** [comment]
Hello, so I did it, I had to make the video into two parts though, because I had to rejoin the server and thus putting in my password (we have an AuthMe plugin)

Part 1: https://www.youtube.com/watch?v=lgzJfT2VFpE&feature=youtu.be
Part 2: https://www.youtube.com/watch?v=1mPuZoI-E3M&feature=youtu.be

**Comment by JavaFactoryDev** [comment]
Thank you for doing so.
We try to reproduce it and schedule a time to fix it.

**Comment by JavaFactoryDev** [comment]
Fixed with 3.7.3, however you can't, of course, be 100% sure, please report when this issue occurs again.
