### ISSUE TITLE
[1.15.2] Drop gets removed from drop list after a boss dies one time

### ISSUE THREAD

**Issue by WhatsTheBadNews** [kangarko/Boss#543]
**What is your current situation, desired situation and your problem?**
My current situation is that when I add an item to a bosses drop list, it will only stay there until a boss dies once. My desired situation is that when a boss dies, it drops the item, but the drop stays in the drop list so that the next time that boss is fought it will still drop the same item.

I am using Boss-3.7.1 and Paper 282. I've tested this on my production server and on a test server with only the Boss plugin.

[Boss.zip](https://github.com/kangarko/Boss/files/4632089/Boss.zip)

**Comment by JavaFactoryDev** [comment]
Hey WhatsTheBadNews,

Reporting this issue here.
We will now try to reproduce and fix it.

Regards
Leonhard from MineAcademy

**Comment by WhatsTheBadNews** [comment]
It looks like other people have reported this problem as well.

Some people posted their configs in the closed issue #536 if you need more to test with.

**Comment by 100petr** [comment]
"Boss-drops are working pretty fine as far as I know."
-Leonhard, May 15 2020

**Comment by JavaFactoryDev** [comment]
Thank you for reporting this, I was unaware of it.
I will find time to have a look and schedule a time to fix it.

**Comment by Jirsaacek** [comment]
What do you mean by "unaware"? I already reported this before and I was told that nothing is wrong with your plugin. So it's not a problem, until more people starts to report issue? That's very bad mindset :)

**Comment by JavaFactoryDev** [comment]
I am sure I didn't say anything like that. The only thing I can remember is something like "I don't know of an issue"

But please stay patient here.
I can totally understand if you don't want to wait for others.

**Comment by kangarko** [comment]
@JavaFactoryDev can you please have a look into this? Thank you!

**Comment by WhatsTheBadNews** [comment]
I do not want to be rude, I understand life can get busy. But this has been a MAJOR issue on my server that was first reported almost a month ago (by others). This is one of the most popular premium plugins on Spigot, and the plugin page brags about how for Boss-like competitors "BUGS TAKE LONG TO FIX" and that Boss has "QUICK CUSTOMER SERVICE". At least in this instance, this has definitely not been the case.

**Comment by WhatsTheBadNews** [comment]
![image](https://user-images.githubusercontent.com/29821149/82804439-eb8d6400-9e47-11ea-843a-6555122d5e62.png)

**Comment by WhatsTheBadNews** [comment]
#536 #539

**Comment by JavaFactoryDev** [comment]
Fix until Thursday

**Comment by JavaFactoryDev** [comment]
General news: Boss drops are working fine if they are not custom items.
We will of course fix this.

**Comment by JavaFactoryDev** [comment]
Resolved with Boss 3.7.5. Please update.
