### ISSUE TITLE
New lands connection

### ISSUE THREAD

**Issue by OrangeCat555** [kangarko/Boss#544]
Boss gets this when trying to start after a server restart.

23.05 18:02:47 [Server] INFO java.lang.IllegalStateException: [Lands] Lands isn't enabled yet. Plugin Boss needs to be enabled after Lands.
23.05 18:02:47 [Server] INFO at me.angeschossen.lands.api.integration.LandsIntegration.checkEnabled(?:196)
23.05 18:02:47 [Server] INFO at me.angeschossen.lands.api.integration.LandsIntegration.initialize(?:165)
23.05 18:02:47 [Server] INFO at me.angeschossen.lands.api.integration.LandsIntegration.<init>(?:59)
23.05 18:02:47 [Server] INFO at me.angeschossen.lands.api.integration.LandsIntegration.<init>(?:39)
23.05 18:02:47 [Server] INFO at org.mineacademy.boss.lib.fo.model.z.<init>(SourceFile:2669)
23.05 18:02:47 [Server] INFO at org.mineacademy.boss.lib.fo.model.v.a(SourceFile:172)
23.05 18:02:47 [Server] INFO at org.mineacademy.boss.double. .cO.onEnable(SourceFile:271)
23.05 18:02:47 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
23.05 18:02:47 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:364)
23.05 18:02:47 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
23.05 18:02:47 [Server] INFO at java.lang.Thread.run(Thread.java:748)

**Comment by JavaFactoryDev** [comment]
Boss needs to be enabled before Lands.
Whats the issue with that?

**Comment by OrangeCat555** [comment]
Is that something a person with the plugin can do? 
I’m not sure how you wouldn’t make it enable after without listing it in plugin yml.

**Comment by JavaFactoryDev** [comment]
Actually this was thought as a workaround. But I think I already know the issue.
Fixed until next release.

**Comment by JavaFactoryDev** [comment]
Should be fixed with the latest version.
