### ISSUE TITLE
I need help with natural spawning, and potion effects

### ISSUE THREAD

**Issue by Xyrz** [kangarko/Boss#546]
I purchased and started using your plugin a week ago, and so far it looks pretty good. However, I am trying to have it where a percentage of the normal zombies/skeletons in the world get "bossified" automatically. I don't want to have to manually spawn in custom mobs, I want my players to be able to randomly encounter them wherever they go.

I cannot figure it out at all. I have played with all the settings and even tried to make everything 100% just to see if I can get things to spawn at all, but they won't. How do I get custom mobs to automatically spawn in the world?

Also, I tried to give potion effects (like poisoning the player) by turning on potions in the skills section, then selecting the desired potion effect in the other menu screen (forget what section) but when I test it, I can never get poisoned from the custom mob. Maybe I just don't understand the menus at all, but I need some help with how to get it to work properly.

I want to like this plugin, so I am asking for help, before I ask for a refund.

Please help me out.

**Comment by JavaFactoryDev** [comment]
Hi Xyrz,

thank you for asking this question here.

Are normal Mobs spawning in your world?
Might you send us ur boss-folder.

Regards,
Leonhard from MineAcademy

**Comment by Xyrz** [comment]
Yes, normal mobs do spawn in my world. Where do I send you my boss folder?

**Comment by JavaFactoryDev** [comment]
Here.

**Comment by Xyrz** [comment]
I am embarrassed to say this, but I only signed up for GitHub to get support for the Boss plugin. I don't know how to attach my Boss folder using GitHub. Dragging and dropping doesn't seem to work. I am also relatively new to hosting a Minecraft server. And I am new to using Linux/Ubuntu.

I am going to need more guidance here.

**Comment by JavaFactoryDev** [comment]
All good, no worries.
Thank you for singing up for github.
#432 contains gif showing what to do, might this help you?

**Comment by Xyrz** [comment]
My apologies, I have been incredibly busy the past couple of days and I barely have time tonight. But I compressed the folder (I feel dumb for not thinking of that) into a ".zip".

Again, my hopes is that monsters have a chance to be "bossified" automatically as players naturally explore the world. And I also need help with configuring potion effects.

And if monsters do start getting bossified, how does that work with a mob spawner block? Does the mob spawner also pop out bossified mobs automatically?

I appreciate your patience with my busy schedule and my apparent inability to understand you plugin fully.

[Boss.zip](https://github.com/kangarko/Boss/files/4739028/Boss.zip)
