### ISSUE TITLE
(spigot1.15.2) 3.7.5 Suggestion for the Boss Spawner range

### ISSUE THREAD

**Issue by SirVecchio** [kangarko/Boss#548]
Couldn't set it to be a suggestion, sorry.

Hi, i have a suggestion for the restriction of the boss movement inside a region.
If i set the mob to only walk inside a region, created with the /Boss tools, the boss will be automatically teleported back inside of it, but the main problem is the fact that a spawner set to only make appear a boss could spawn another wile the already existing one walk in the limit of the region and get pulled back.
I will suggest to make the process to teleport back a boss two to three blocks before the limit of the region.
So if i set a region a 60 blocks, and also the spawner of the boss, it will be brought back when it 57 blocks and the boss spawner will not trigger the event to make another one

**Comment by JavaFactoryDev** [comment]
Planned for Boss 4.
