### ISSUE TITLE
Question: What happens if boss follows a player outside boss region?

### ISSUE THREAD

**Issue by CraftSwede** [kangarko/Boss#55]
Hello.
On my server we're currently building a "Wild Land" where we will have griefing, raiding and PvP allowed. Also to spice things up I would like to add this plugin once Wild Land is finished building. So this area will be surrounded by a tall wall that surrounds it. Within this wall I plan on setting up a boss region. 

But what I am interested in knowing is; if boss chases down a fleeing player to the borders of boss region. Can I have it set up so that the boss NEVER crosses the boss region border. Neither can destroy anything outside this region as well? 

Reason I don't want it able to injure anything outside the boss region is because I want the wall that surrounds the region to remain intakt even if it takes a lot of hits from bosses that sends exploding attacks towards a player and hit the wall instead.

I hope I'm not too unclear in what I am after here? ^^

**Comment by kangarko** [comment]
Hello,

at present we do not control Boss' behaviour outside of their region. The Boss will continue to act normally as if in region. You should add barries or similar blocks to prevent Bosses from escaping. Here's an explanation why Boss won't modify the AI: https://github.com/kangarko/Boss/wiki/Common-Issues#can-you-make-animals-aggressive--add-better-ai

**Comment by CraftSwede** [comment]
Alright. Thank you for the answer 👍
