### ISSUE TITLE
(spigot1.15.2) 3.7.5 - Another (different) suggestion for Boss spawner 

### ISSUE THREAD

**Issue by SirVecchio** [kangarko/Boss#550]
Hi, I have a suggestion about regions and boss spawners.
If I set the spawn range of a boss to 60 blocks, the boss will randomly spawn within this range.
The issue with this is that if I set the region to 10x10 blocks (the size of a mini dungeon), create a mob spawner and set it to only allow a single boss to exist inside that 10x10 region at any given time (by setting the boss spawn range to 5 blocks, as the spawner would be in the middle of the area), then the boss spawns in a random location inside this 10x10 area, instead of a defined spot.
My suggestion is to separate the “boss spawn” and the “boss check” aspects by adding an option to the mob spawner menu, so that an exact location can be set for the boss to spawn at every time, istead of it spawning at a random location in the checked area.

Idea in a photo below:

![photo_2020-05-30_12-22-48](https://user-images.githubusercontent.com/66133102/83325992-0d844d80-a271-11ea-8c81-ac5f26fe87b0.jpg)

**Comment by JavaFactoryDev** [comment]
Thank you so much for sending us this ideas. Will be considered to boss-4.
