### ISSUE TITLE
1.15.2: Equipment disappears right after putting it on and Region spawning doesn't work

### ISSUE THREAD

**Issue by DogeTennant** [kangarko/Boss#554]
Hello, I was reporting these two issues and the Thread got closed without solving the problem, I tried creating a new posts over there, but it was not being noticed, so I'm creating a completely new thread, but I'll just link the old issue here, because everything applies the same. Except that I've tried everything now on the newest version 3.7.6 and still none of these two issues are solved.

https://github.com/kangarko/Boss/issues/541

Thank you for your help in advance!

**Comment by SirVecchio** [comment]
They close the issue that doesn't follow the #432 guide line

**Comment by JavaFactoryDev** [comment]
Hey DogeTennat,

Your issue got closed because you didn't follow the guidelines described in #432 as @SirVecchio already pointed out.

This thread also doesn't contain the needed information however the other thread does.
I will have a look at it now.

Regards
Leonhard from MineAcademy

**Comment by DogeTennant** [comment]
I know that this thread doesn't follow the guidelines I just made it to inform you about the other thread, because noone was responding and I dont know how to send a private message

**Comment by DogeTennant** [comment]
Tried deleting it now, but it didnt fix either of the issues (deleted the folder while the server was turned off)

**Comment by kangarko** [comment]
@DogeTennant I apology for that we did not come back to you. I am archiving the issue page, if you still have a problem please reopen a new ticket at https://support.mineacademy.org
