### ISSUE TITLE
Boss 1.5.12 - Minions ISSUE

### ISSUE THREAD

**Issue by fede1132** [kangarko/Boss#56]
My log [here](https://paste.ee/p/6WPCd).

**Comment by fede1132** [comment]
New logo [here](https://paste.ee/p/i1nv7).

**Comment by kangarko** [comment]
Sorry it says Paste not found. Please use pastebin.com and setup the expiration at least one week.

**Comment by kangarko** [comment]
Closing in continuation of https://github.com/kangarko/Boss/issues/57
