### ISSUE TITLE
1.15.2: Boss can spawn in wild when set to spawn in only specfic region

### ISSUE THREAD

**Issue by JewelAprils** [kangarko/Boss#560]
Hello All,
I am having trouble with the egg spawning region. I only want the boss to be spawned in a specific region and I have it set to that region but if I spawn it in the wild as not a server operator it spawns in the wild with the spawn egg. I don't want this to happen, I only want it to spawn in that specific region I set with the emerald region setter. I have set everything to 0 that way it wont naturally spawn in any world besides the world where its set to spawn in that particular region. Unfortunately, my hosting doesn't let me take out files and download them.
Thanks for your time and patience

**Comment by JewelAprils** [comment]
This is all I could get
[Boss.zip](https://github.com/kangarko/Boss/files/4761831/Boss.zip)

**Comment by SirVecchio** [comment]
It worked on me once on a previous version this kind of thinks
I will have loved letting normal player spawn boss egg in specific point to let them start a dungeon by themselves

**Comment by JavaFactoryDev** [comment]
HI JewelAprils,

thank you for reporting this issue here,
we will have a look soon;)

Regards
- Leonhard from MineAcademy
