### ISSUE TITLE
problem with license?

### ISSUE THREAD

**Issue by zPluTon** [kangarko/Boss#561]
hello the boss plugin maybe it doesn't work because of a license (already happened in the past with another plugin), previously I had a server to test the pl and I had loaded boss to test it, but now I can't pass it on the server that I have could you help me? my name on spigot GhoBloST

**Comment by JavaFactoryDev** [comment]
Hi zPluTon,

Thanks for asking this question here!

Boss has no inbuild licensing system.

Regards
Leonhard from MineAcademy

**Comment by zPluTon** [comment]
ah ok, why doesn't it work, insert the plugin, restart the server and looking through the pls it turns out to be red, is there something blocking the pl?
