### ISSUE TITLE
The server does not read the pl

### ISSUE THREAD

**Issue by zPluTon** [kangarko/Boss#562]
After the other request I realized that it is not a license error but what error? I put the pl in the plugins folder, I restart the server but once all the pls are loaded it does not generate the folder but it is in red (BOSS plugin) how come? is interfering some other pl? what are the pls it doesn't support?

**Comment by JavaFactoryDev** [comment]
Hi zPluTon,

Thanks for asking this question here.
Can you please give us some startup log?

Regards
Leonhard from MineAcademy

**Comment by JavaFactoryDev** [comment]
Please respond

**Comment by zPluTon** [comment]
I use a 1.8 version, does the plugin need a higher version? type 1.8.8?

**Comment by JavaFactoryDev** [comment]
Boss only supports 1.8.9+ (as stated on the spigot-site)
Can you please provide us a startup log?

**Comment by JavaFactoryDev** [comment]
Please respond.
