### ISSUE TITLE
1.16.1: boss loot/xp

### ISSUE THREAD

**Issue by Scyvival** [kangarko/Boss#566]
[](https://www.youtube.com/watch?v=X04Tgt5Spd0&feature=youtu.be) - boss xp is not dropping like its supposed to for the set amount. the boss loot table is not triggering like its supposed to. some bosses have a 90% drop rate and it still does not drop when we do like 10-50 boss testings even when every drop is enabled. the bosses are also not spawning the death minions on death every time either. 

[Boss Folder.zip](https://github.com/kangarko/Boss/files/5013028/Boss.Folder.zip)

**Comment by Scyvival** [comment]
https://www.youtube.com/watch?v=X04Tgt5Spd0&feature=youtu.be

**Comment by JavaFactoryDev** [comment]
Hi,

thanks for reporting this issue!

Regards
Leonhard

**Comment by Scyvival** [comment]
any thoughts to a solution?

**Comment by kangarko** [comment]
I was fixing some of our backend systems, you will be able to read more of our changes at mineacademy.org/blog later on. Leonhard will have a look within 24 hours. Thanks.

**Comment by Scyvival** [comment]
Alright thank you, 
just something to add onto with testing a few different bosses now if you dont watch the video

-If a boss is set to only drop experience it will drop the amount of experience 100% of the time. Tested with multiple different bosses.
-The moment you add loot items to be dropped from a boss, it conflicts with the experience and items themselves and completely randomizes it. 
-If experience is set to 0 and items only, it still randomizes drops and does not even drop items sometimes.

**Comment by Scyvival** [comment]
also 
- we have a new boss spawning even with 0% in world spawn and no biomes, we  think it is due to the repeat of having two different skeleton mobs- which might tie into duplicated other bosses but the two bosses have completely different settings.

**Comment by AngellitoX** [comment]
Hello Scyvival,

Thank you so much for reaching us with your concerns.
Right now the workload is a bit much right now, but I can asure you that all the issues listed here will be fixed this week.

Thank you for the patience in advance!
Angel from MineAcademy.org

**Comment by Scyvival** [comment]
[Boss Folder Scyvival v2.zip](https://github.com/kangarko/Boss/files/5031263/Boss.Folder.Scyvival.v2.zip)
Alright, thank you for  the update Angel. 
I just wanted to give an updated folder of our bosses since we keep trying to find solutions.

**Comment by Scyvival** [comment]
this also included thew new bosses somehow spawning with 0% worldspawn

**Comment by Scyvival** [comment]
[](https://www.youtube.com/watch?v=Oe5N94Abnb0&t=13s)
we opened our nether  today and here is a video regarding our broken blaze boss

**Comment by Scyvival** [comment]
https://www.youtube.com/watch?v=Oe5N94Abnb0&t=13s

**Comment by kangarko** [comment]
Hi there!

I apology for reporting this severe problem and not getting a fix earlier.

I patched Boss not correctly iterating through all drops and stopping after the first (random) one. Also be sure to disable Single Drops otherwise the drops would stop after the first successful one, if that is not your intention: https://i.imgur.com/bYr05v2.png

For the world spawning issue, I made it run sync (was async) so it will be stable and should work as expected. If not, write ["spawning"] to your Debug key in settings, and please open a new ticket with that console debug information.

Thanks
