### ISSUE TITLE
1.15.2: Issue with PlaceholderAPI (Javascript)

### ISSUE THREAD

**Issue by TwerkRekt** [kangarko/Boss#567]
Hello, 
So there you go, the javascript with placeholderapi seems completely incompatible with the boss plugin, I'm going to see placeholderapi support first, these told me to come see you so you can fix the problem

**Comment by kangarko** [comment]
Thanks, I have opened a ticket yesterday on PlaceholderAPI, not really sure what is going on there, need more information from their developer.

https://github.com/PlaceholderAPI/PlaceholderAPI/issues/426

**Comment by kangarko** [comment]
Just a headsup, submitted them a pull request for their expansion that fixes this.

**Comment by kangarko** [comment]
Just reviewed, clip did not update JavaScript expansion just yet but pulled my request: https://github.com/PlaceholderAPI/Javascript-Expansion/commit/4e4ff336b23191db6f0799933fb6e311634bcbce 

Please be patient until he updates his expansion pack for PlaceholderAPI. I am now closing this.
