### ISSUE TITLE
1.16.1: Bosses are not spawning naturally...

### ISSUE THREAD

**Issue by wantduck** [kangarko/Boss#576]
Bosses not spawning naturally,
all biomes enabled, 
spawn chance in only world at 100%
no specific spawn time (example: time night) everything is default

**Comment by kangarko** [comment]
Please upload your ZIP folder so I can have a look.

**Comment by wantduck** [comment]
Sorry, got it fixed, I had deleted the world folder and made a new world,
it did not update its name, my fault.
