### ISSUE TITLE
1.16.1: Getting java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by Lariesse** [kangarko/Boss#578]
I wanted to use `/boss reload` command but I always get the same problem as seen in the image:

[Image](https://i.imgur.com/W6nxZpw.png)

In order to update changes in the internal files of the plugin it's always necessary to restart the server completely.
This also happens in a brand new Boss folder without any modifications.

Console error: [Console](https://mcpaste.io/fbf5295fb9b03661)

**Comment by kangarko** [comment]
Thanks, this will be fixed in tonight's release!
