### ISSUE TITLE
Zombie Boss don't spawn

### ISSUE THREAD

**Issue by Skygamer777** [kangarko/Boss#582]
<!---
To report a problem or a bug with this plugin, please follow the three steps below:

**IMPORTANT** If you Bosses are NOT spawning / having issues with them, please upload your folder as a ZIP (see step 3)!

1) Put your Minecraft version in the title.
Example: 1.15.2

2) Be clear: What is your current situation, the desired situation, and your problem?
I created a Zombie boss and activated region spawning but the boss didn't spawn. 

3)
[Boss.zip](https://github.com/kangarko/Boss/files/5092298/Boss.zip)

**Comment by kangarko** [comment]
Closing, ignored template and no reply. Please comment below and follow the instructions.
