### ISSUE TITLE
Per-mob skill customization

### ISSUE THREAD

**Issue by PrestoCS** [kangarko/Boss#583]
Hi there, I really like this plugin, and the skills available, however personally I think some of them are underpowered, obviously I can edit some paramaters of the skills via their YML files, but I think it would be great if each boss had a separate skills.yml, 

For instance, I would like one boss to use the throw player skill, as this is his main attack I buffed the throw power to 20, but then if I make a new boss, and also want him to have the throw player skill, I dont want it to be as powerful. I know mythic mobs has a way of doing this by being able to create new skills. If per-mob skills customization is not possible, giving us the option to create our own skills would still be nice as a workaround, so I can make a PowerfulPlayerThrow and a NormalPlayerThrow

Thanks!

**Comment by LeehamElectronics** [comment]
I'd also like to see this feature implemented.
Thanks

**Comment by kangarko** [comment]
Unfortunately I don't have the resources to add this right now but I may in the future
