### ISSUE TITLE
1.16.1 : I cannot customize skill.Skills not working

### ISSUE THREAD

**Issue by GigiTeddy** [kangarko/Boss#584]
Hello,
Im trying to create a slime boss that has a potion slowness effect. But when i click on the potion in menu it just says that i activated the effect but nthing more. It shows nothing in the chat to type and change or modify the effect. 
This appear to be happening with every skill here. What should I do.
I updated the pluggin version  to 3.8.4
Thanks.

**Comment by kangarko** [comment]
Hi,

Oh I see. Unfortunately at present Boss only offers one global skill setting. You can customize what potions the player will be given by the Potion skill here: https://i.imgur.com/FScLuhX.png

In the near future we of course plan to implement per-Boss skill configuration. Thank you for your understanding.
