### ISSUE TITLE
Edit NBT Data of bosses in the .yml file

### ISSUE THREAD

**Issue by Lukos31** [kangarko/Boss#585]
Hi, i've been looking for a plugin for a while that allows adding nbt data to custom mobs to summon, and i think it would fit in with Boss quite well. Using NBT editing there are a multitude of options available for customizing mobs, and only a fraction of these are covered by the plugin's current features. As an example, here is a mob i made that summons potions to buff itself, as well as various other particles/entities. 
![2020-08-20_15 33 23](https://user-images.githubusercontent.com/69782564/90723759-78877280-e2fc-11ea-891e-e62da0946358.png)

As far as i know, there is no straightforward way of turning these sorts of mobs into bosses, but if NBT data could be set in the .yml file this would make everything immensely easy.
At the moment, although the plugin is quite flexible in what it offers, i can't help but feel limited without being able to create mobs with such precision. There is a workaround that i have been using, executing /data commands upon summoning the boss, but this is quite cumbersome and can cause problems when making large edits.

**Comment by kangarko** [comment]
Unfortunately I don't have the resources to add this right now but I may in the future
