### ISSUE TITLE
Multiple killers

### ISSUE THREAD

**Issue by NetflixFeelings** [kangarko/Boss#587]
Hello, I bought the plugin a little over a month ago and am just now setting it up. I was creating a boss and adding the death commands. I realized I could broadcast who killed the boss (like so: https://gyazo.com/d165a5913b467bc06d7a2fe9993215c8) My question is can I make it to where it shows the top 3 killers? Like the following example:

The {boss} boss has been defeated!
                Top Killers:
    #1 - {name} - {damage dealt}
    #2 - {name} - {damage dealt}
    #3 - {name} - {damage dealt}

**Comment by AngellitoX** [comment]
Hello, as for now it's not possible as Boss only takes the actual killer. I'm sure it can be added in a near future. I'm keeping this opened as a feature suggestion.

Thank you!
Angel from MineAcademy.org

**Comment by NetflixFeelings** [comment]
> Hello, as for now it's not possible as Boss only takes the actual killer. I'm sure it can be added in a near future. I'm keeping this opened as a feature suggestion.
> 
> Thank you!
> Angel from MineAcademy.org

Alright, thanks for answering my question!

**Comment by kangarko** [comment]
Thanks, something definitely to consider.

**Comment by Firosee** [comment]
I would love to see this feature!

**Comment by kangarko** [comment]
It is partially available: https://github.com/kangarko/Boss/wiki/Drops#inventory-drops-and-pvp-spreads
