### ISSUE TITLE
1.16.1 - Do bosses work with custom enchantments?

### ISSUE THREAD

**Issue by kinghubbs** [kangarko/Boss#588]
If I were to put any of the custom enchantments on the custom mobs, would the enchantments still work?

The custom enchant plugin is AdvancedEnchantments.

I am wondering if you would know this answer. I also sent a question to the developer of AdvancedEnchantments and still waiting for a response, and I don't feel it hurts to ask here.

**Comment by AngellitoX** [comment]
You mean using them on their equipment? I believe it should work because all Boss do is take whatever you put into them. If they don't work as they should, I believe we can find a solution for that shortly.

Let us know!
Angel from MineAcademy.org

**Comment by kinghubbs** [comment]
They seem to not work sadly :(
I did some testing and when a player uses lets say a poison enchant on their sword it will poison mobs/other players but i sat there and let multiple different custom bosses hit me with a that poison enchant for a while and nothing happened

**Comment by kangarko** [comment]
I apology, but that plugin appears to be incompatible. You will be able to utilize our better skill system to supplement what you need in a future version of Boss.
