### ISSUE TITLE
1.16.1 Ender Dragon staying in place

### ISSUE THREAD

**Issue by SaltedBiscuit** [kangarko/Boss#593]
Im getting my spawners to spawn my enderdragon finally, but he just stays in place, flapping his wings, doing an occasional roar. No breath bombs or anything. He spawns in the overworld. I don't have him locked in any regions or anything. Not sure why he wont move.

EDIT: if you damage him to below about 150 hp he will just fly off in one direction and keep going, noclipping through blocks.

**Comment by AngellitoX** [comment]
Hello, I have personally experienced the exact same situation with a SkyWars plugin which spawns an ender dragon upon time finish and the same thing happens.

It looks like the Enderdragon spawned with a command in a world that it's not The End causes the dragon to glitch. Can you please confirm this using commands such as `/summon` or `/spawnmob`?

**Comment by kangarko** [comment]
Unfortunately Spigot nerds these mobs for some reason, does not appear to be fixable at the moment.
