### ISSUE TITLE
Mobs Not Spawning Naturally + Can't edit skills

### ISSUE THREAD

**Issue by ImRealsy** [kangarko/Boss#594]
Hey,

Bosses don't spawn naturally within a region unless I turn off check-conditions, which they then spawn everywhere around the world. 
Also is there a way to change skill effects? for example can't seem to find a way to change the minion type spawned and potion effects?

thanks 

[Bosses.zip](https://github.com/kangarko/Boss/files/5113786/Bosses.zip)

**Comment by kangarko** [comment]
You can change skills globally in the skills/ folder in Boss. Per-Boss skill config will come in the near future.

I recommend you try to self-diagnose the spawning issue reading https://github.com/kangarko/Boss/wiki/Common-Issues#bosses-are-not-spawning-naturally and the issue below it. If still unsure reply below.
