### ISSUE TITLE
How do I make Custom Mobs spawn naturally??

### ISSUE THREAD

**Issue by LeehamElectronics** [kangarko/Boss#595]
Hi, I'm using the latest version of Boss and I am trying to make custom mobs spawn in one of my worlds. At the moment it seems that it is only possible to spawn mobs that replace other vanilla spawning mobs like zombies and creepers. 
I want to make a custom (ravager) mob spawn like zombies do.
Is it possible to do this with this plugin? 
Thanks

**Comment by kinghubbs** [comment]
I am having this issue as well, any fixes?

**Comment by kangarko** [comment]
Yes of course, see Timed_Spawning option in settings.yml then set rules in Spawning menu for Boss. 

If having issues read https://github.com/kangarko/Boss/wiki/Common-Issues#bosses-are-not-spawning-naturally
