### ISSUE TITLE
1.8.8: Pig_Zombie spawn egg is a Stone Block

### ISSUE THREAD

**Issue by Nrc0611** [kangarko/Boss#596]
As the title says it appears to be a stone block. It was working fine in 3.8.1 but when I updated to 3.8.4 it is now stone.
https://gyazo.com/8e10e7fab1a71b822f8dea8cf6cf85d0

**Comment by LeehamElectronics** [comment]
Have you tried changing the eggs icon in the boss's settings? Left click and change the icon, see if it makes any difference.

**Comment by LeehamElectronics** [comment]
Ohh I see what your issue is now. Do you have via version or via backwards installed?

**Comment by Nrc0611** [comment]
I have viaversion, but I need to update it I'm not sure its working properly atm

**Comment by Nrc0611** [comment]
Ok I just updated it and that didn't affect it. I am using viaversion 3.1.0

**Comment by Nrc0611** [comment]
I also tested this on my 1.8 test server without viaversion and its also a stone block.

**Comment by kangarko** [comment]
Haha I thought people liked stones!

Just kidding, this will get patched ;)

**Comment by Nrc0611** [comment]
Lol thanks!
