### ISSUE TITLE
1.16.2: Is there a tutorial to create custom skills?

### ISSUE THREAD

**Issue by RubizZ** [kangarko/Boss#598]
I took a look about Boss and I saw I can create custom abilities, is to difficult create them or is there any guide/demonstration of the process to create an ability? And then, I can decide if I will buy the plugin or I can't do what I want with it

**Comment by kangarko** [comment]
Currently only for developers: https://github.com/kangarko/Boss/wiki/Developer-API

In the future we may add this without coding skills needed.
