### ISSUE TITLE
1.16.2: Damage multiplier not working for drowned throwing tridents

### ISSUE THREAD

**Issue by tomwoodrough** [kangarko/Boss#601]
Increasing the damage multiplier for drowned when I've equipped them tridents doesn't increase the damage of them

MC Version 1.16.2

**Comment by kangarko** [comment]
How to reproduce? Works for me: https://i.imgur.com/YV9fuRI.png

Please set Debug to "[damage]" exactly in settings.yml and test for console messages showing the multiplier when hit by a trident. Also please update to the next version when it is ready later today.

**Comment by AngellitoX** [comment]
Hello, I'm closing this for now as there hasn't been any reply since then.

Consider commenting below if your issue persists.
Thank you!
Angel from MineAcademy.org
