### ISSUE TITLE
1.16.2: Piglin Brute broken

### ISSUE THREAD

**Issue by ShockCharge** [kangarko/Boss#602]
1. It does spawn but dissapears after few seconds.
2. The Boss menu refuses to go back when you edit something it exits immediately.
3. Here are the proofs and errors:

Error: https://hastebin.com/everokujoc.sql
Picture: https://imgur.com/a/OwIkGdq

I am on the latest version 3.8.5:

Proof: https://imgur.com/a/oi7doHi

**Comment by ShockCharge** [comment]
Server version: 1.16.2 Paper

Proof: https://imgur.com/a/nGtdsjS

**Comment by AngellitoX** [comment]
Hello there! Thank you for reporting this issue. Piglin Brute hasn't yet been added to Boss as this entity was added in the 1.16.2 releases. 

We will take a look and add it for sure in the next couple of days. Thank you for letting us know!
Angel from MineAcademy.org

**Comment by kangarko** [comment]
Thanks, will be fixed next week, I had to travel and I am only catching up security patches.

**Comment by kangarko** [comment]
The error will be solved in the next version. Please note that Piglin Brute and Pillager do not support babies.
