### ISSUE TITLE
Bosses see staff in v, players in disguise

### ISSUE THREAD

**Issue by mrcoffee1026** [kangarko/Boss#603]
Staff in vanish (or plugin PremiumVanish) are still being seen and attacked by Bosses.
Players in disguise (as provided by libdisguises) are also seen and attacked by bosses even though there is a setting for this we have disabled:
MonstersIgnoreDisguises: true
may or may not be one and the same issue.

Would be better if bosses did not attack staff while hidden, and should treat players in disguise as though they were hidden as all the other mobs do.

**Comment by AngellitoX** [comment]
Hello again!

Thank you for reporting it. There's definitely something going on with the vanish ignore feature. We will take a look to this in the next couple of days.

**Comment by kangarko** [comment]
The only option that does not ignore vanished players and directly changes targeting is the Fight.Auto_Retarget. I made that option now ignore vanished players to the next release.
