### ISSUE TITLE
1.16.1 Equipment issues

### ISSUE THREAD

**Issue by JnPol** [kangarko/Boss#604]
I have the same issue as this closed issue report "A problem with equipment #277"
Equipment dissapears as soon as you place it in the menu. It only happens in one of our server even when both our server having the same plugin "OpenInv" 

My question is, how is it fixed ? cause i cant just simply delete OpenInv, we need it, so do i modify settings? and which ones? Cause i have tried and cant find the answer, Thank you.

I can provide Files or Pictures if need it

**Comment by AngellitoX** [comment]
Hello there! It looks like OpenInv might be using an event handler which makes it incompatible with Boss, or probably the other way around. 

Have you tried using Essentials or CMI open inventory feature? Probably that could help you in the meantime while we look into it.

Thank you!
Angel from MineAcademy.org

**Comment by JnPol** [comment]
Essentials works only for Online Players, i will test CMI, Thanks !

**Comment by AngellitoX** [comment]
Alrighty, I'm closing this in good faith this can be resolved.

If you ever need more help, please consider commenting below so we can keep discussing about it.
Have a good day!
