### ISSUE TITLE
1.13.2: Boss Health

### ISSUE THREAD

**Issue by FrostSanta** [kangarko/Boss#605]
Hi, i want to ask about boss health. How to set the boss health more than 2048HP? Is there a way to change the limit?

**Comment by AngellitoX** [comment]
Hello there, I believe that currently 2048HP is the max limit. You could setup different armour in order to make it stronger if that's what your looking for. 

I'm sure this can be added as an improvement for future releases. Thank you!
Angel from MineAcademy.org

**Comment by kangarko** [comment]
You can increase this in spigot.yml file ;)
