### ISSUE TITLE
1.13.2: Cant edit weapon, armor, drops

### ISSUE THREAD

**Issue by FrostSanta** [kangarko/Boss#607]
Hi, i have this problem that i cant put custom items like renamed items in the menu for changing drops, weapons(equipments), armor(equipments) it says Oups! There was a problem with this menu! Please contact the administrator to review the console for details(in game)
And the console pop this message
https://pastebin.com/J206jgPk
[error.log](https://github.com/kangarko/Boss/files/5153918/error.log)

**Comment by kangarko** [comment]
Thanks for reporting, please test the next version coming up tonight.

**Comment by FrostSanta** [comment]
Hi, it still give me a error when i place the items at the slot. It drops the item when i want to put it on the slot. Can you help me please.

**Comment by AngellitoX** [comment]
Hello there, reopening as requested. Thank you for contacting us again!

**Comment by FrostSanta** [comment]
It still didnt let me put named items and sometimes i cant put normal items too.

**Comment by kangarko** [comment]
Please report me the error you are getting with the 3.8.7 version.

**Comment by kangarko** [comment]
Sorry, I just fixed that! Next version will come up tonight.
