### ISSUE TITLE
FactionsX Support

### ISSUE THREAD

**Issue by EvilSlime** [kangarko/Boss#612]
**1) How it would benefit others? (Not just you, but 1,000s of others people using the same plugin.)**
Most new servers will be using FactionsX

**2) What would happen if we won't implement this feature? How's your server being affected?**
It would give support for the latest Faction plugin

**3) If suggesting something new - Can the old system be modified/improved instead?**
Yes, add their API

**Comment by kangarko** [comment]
How exactly do you want this support to work?

**Comment by EvilSlime** [comment]
So you can make a boss only spawnable with an egg in for example warzone

**Comment by EvilSlime** [comment]
The feature I wanted isn't a thing anyways, I want people to only spawn bosses with an egg in certain area's.

**Comment by Nrc0611** [comment]
U don't need it to work with only spawning in warzone, just make a world region in the warzone area (U should be doing this anyway to prevent ur warzone getting cannoned/cegged)  and then you can make it so it only spawns in that region with a egg. I use that feature on my faction server.

**Comment by EvilSlime** [comment]
> U don't need it to work with only spawning in warzone, just make a world region in the warzone area (U should be doing this anyway to prevent ur warzone getting cannoned/cegged) and then you can make it so it only spawns in that region with a egg. I use that feature on my faction server.

How'd you do it? I can't get it to work.

**Comment by kangarko** [comment]
@EvilSlime so with these settings, your bosses still spawn everything not only in WarZone?

**Comment by EvilSlime** [comment]
Exactly

**Comment by kangarko** [comment]
Got it. Currently I am super busy working on ChatControl and that plugin is barely popular at all (you're the only one requesting it) so I'll implement it when I have time later on.

**Comment by kangarko** [comment]
After a careful consideration this has to be dropped due to lack of time. We may re-introduce it when our spawning system gets  overhauled in the future.
