### ISSUE TITLE
Prevent Enderdragon Portal

### ISSUE THREAD

**Issue by EvilSlime** [kangarko/Boss#615]
**1) How it would benefit others? (Not just you, but 1,000s of others people using the same plugin.)**
This speaks for itself. 

**2) What would happen if we won't implement this feature? How's your server being affected?**
I will not use Ender Dragons as bosses.

**3) If suggesting something new - Can the old system be modified/improved instead?**
Not sure?

**Comment by AngellitoX** [comment]
Hello there, is your suggestion about removing Enderdragon? Sorry, I didn't get it right.

**Comment by EvilSlime** [comment]
No, on enderdragon death a portal spawns. It is possible to prevent this portal from spawning I woud like to see this feature in this plugin.

**Comment by kangarko** [comment]
As of right now, bukkit doesn't fire this event for this (despite deprecating EntityCreatePortalEvent for it), sorry we cannot catch it properly.

**Comment by kangarko** [comment]
After failed attempts to block it myself I've checked how worldguard does it: https://github.com/EngineHub/WorldGuard/blob/691325c8f03c0f0d53a49b96d1a80fa074a42323/worldguard-bukkit/src/main/java/com/sk89q/worldguard/bukkit/listener/WorldGuardEntityListener.java
