### ISSUE TITLE
Charged twice

### ISSUE THREAD

**Issue by ShadOhh** [kangarko/Boss#617]
Hey, there I just recently made a purchase of the plugin Boss the one that cost 19pounds. I just found out my card has been charged twice. Can I get one of the charges refunded back to me? If you need any proof of email or PayPal ids I can gladly provide them for you

**Comment by ShadOhh** [comment]
#1) 93408892KG029854B
#2) 5L6032477Y932901F

**Comment by AngellitoX** [comment]
Hello there! Thank you so much for reaching us out. I'm pinging @kangarko so he can handle this properly, and marking it as urgent.

If you ever have any other problem, please feel free to contact us anytime!

**Comment by kangarko** [comment]
Your second transaction says "Pending until 11 Sep 2020", I cannot refund it, it will probably get denied. If it won't get denied, please comment below.
