### ISSUE TITLE
1.16.2: Bosses do a lot of skill spamming

### ISSUE THREAD

**Issue by Lariesse** [kangarko/Boss#618]
Hi, since the last version (v3.8.8) the bosses do a lot of skill spamming, I even tried increasing the delay in the skill files but it didn't work, they keep using for example 10 TNTs at the same time

You can watch this video, please watch the full video
https://youtu.be/wZJwPwrWuBw

**Comment by AngellitoX** [comment]
Hello there!

Probably the values are not getting recognised due to some changes to the skill system. Pinging @kangarko so he can take a look to this.

Thank you for reaching us out!
Angel from MineAcademy.org

**Comment by mrcoffee1026** [comment]
i'm getting the same thing on my server:

![PajeKJGlTKC6VFBMl78uvQ](https://user-images.githubusercontent.com/3322491/92984285-26f38300-f477-11ea-90e1-55e258151923.png)

**Comment by kangarko** [comment]
@mrcoffee1026 what's the delay on those skills in your skill/ folder?

**Comment by Lariesse** [comment]
> @mrcoffee1026 what's the delay on those skills in your skill/ folder?

In my case the problem happens with the default values and even if I increase the values

**Comment by kangarko** [comment]
Understand. Will resolve this in 1-2 days.

**Comment by mrcoffee1026** [comment]
Yeah I haven't changed the delays, I believe the defaults are 30s-1min for all.

**Comment by kangarko** [comment]
Thanks, will be fixed tonight.
