### ISSUE TITLE
1.8.9 - Mob Spawning Issue

### ISSUE THREAD

**Issue by NetflixFeelings** [kangarko/Boss#619]
Hey, I gave a player a boss spawn egg and told him to go to /warp pvp to test it for me. It says "Hey! Sorry, but you can't place things here." I know worldguard is throwing that message. The mob-spawning flag is allowed though.

**Comment by NetflixFeelings** [comment]
He can place the enderman boss, but not this iron golem boss?

**Comment by NetflixFeelings** [comment]
Also is the cap 2048 hp or something?

**Comment by AngellitoX** [comment]
Hello there, the placing message from WorldGuard is related to the block-place flag, not mob-spawning.

As for the HP, you can modify it on spigot.yml file.

I'm marking this as solved. If you require further help, please comment below.

Have a good day!
Angel from MineAcademy.org
