### ISSUE TITLE
Run command on death

### ISSUE THREAD

**Issue by iMxAndyy** [kangarko/Boss#62]
Plugin suggestion

A new option in the menu for each boss under 'death' 
To add the option for us to add a command that will run when the boss dies. 
With the option to toggle if it runs from console or from player that killed it.

This will allow us to run a broadcast command to announce that a boss died. or to reward the player with something other than a drop. Maybe money with a eco give command. 
It would also be helpful to have a <player> variable to use in the command to reference the player that killed the boss. (if that's possible to track)

Thanks

**Comment by kangarko** [comment]
Thanks! You can set commands manually in boss yml file, but the next version will have them in the menu as well.
