### ISSUE TITLE
1.16.2: Questions regarding spawning

### ISSUE THREAD

**Issue by CouplofGamers** [kangarko/Boss#621]
I have attempted to get my test boss to spawn but cannot for the life of me get it to work. Basically I need the boss to spawn when entering an area. I selected my area with the boss tool and changed it to stay within the region. I read the guide and it says to use world guard regions to run the spawn command upon entering the region but I cannot find a way within world guard to run this command? This would be my preferred method but how can I do this? But after that didn't work I then tried to use the spawner (I am running paper) and set it to spawn 20 ticks and only spawn 1. I couldn't even get that to work. Spawning is allowed and I am within the region as well as the spawner but nothing. What am I doing wrong? Again I would prefer to use the world guard region method but cannot find a way for it to execute the spawn command, am I missing something? Thank you!

**Comment by kangarko** [comment]
Hey there,

I recommend you see this question and use the recommended third party plugin: https://github.com/kangarko/Boss/wiki/Frequent-Questions-and-Tips#is-it-possible-to-let-bosses-spawn-if-you-enter-a-region
