### ISSUE TITLE
Purchase went through...

### ISSUE THREAD

**Issue by ShadOhh** [kangarko/Boss#622]
Hey, I made this post about my card being charged twice? The 1st transaction and the 2nd transaction actually went through and I purchased it twice... Can you please refund one of them?

Heres the Purchase IDs

5L6032477Y932901F
93408892KG029854B

**Comment by ShadOhh** [comment]
And the amount has already been withdrawn from my bank.

**Comment by kangarko** [comment]
Hi there,

Sure, would you like a refund or would you like to receive extra 2 premium plugins from MineAcademy for free for a lifetime instead?

**Comment by ShadOhh** [comment]
Money refunded please :)

**Comment by kangarko** [comment]
Thanks, refunded. I also readded "ShadOh" back to Boss buyers.
