### ISSUE TITLE
Qucick Question, give multiple Boss Eggs to player at once?

### ISSUE THREAD

**Issue by LeehamElectronics** [kangarko/Boss#626]
Is there a way to give players multiple eggs of the same Boss with a single command? Something like this:
/boss egg SuperCreeper mail2001 64
Unfortunately it only gives the player a single egg, am I doing something wrong?
Cheers

**Comment by AngellitoX** [comment]
Hello, it should be possible as far as I know. Probably either something changed recently or it was never added. Pinging @kangarko to sort this out for us.

Thank you Leeham!

**Comment by kangarko** [comment]
Thanks, I will add this to the next version!
