### ISSUE TITLE
1.15.2: i have an outdated version and i cant update

### ISSUE THREAD

**Issue by fredster90001** [kangarko/Boss#627]
Hi, I have boss 1.15.2 and I can't update to 1.16.2. Is there anyway I can get an updated version?

**Comment by kangarko** [comment]
Yes, use Boss latest version. It will work on 1.16.

**Comment by fredster90001** [comment]
I cant get the newest version, my account got hacked.

**Comment by kangarko** [comment]
I believe I already replied on SpigotMC.
