### ISSUE TITLE
[easy] Converting - add % to menu to configure chance

### ISSUE THREAD

**Issue by LeehamElectronics** [kangarko/Boss#631]
- Hi, I am using the latest version of Boss and I am very confused about setting up spawning. I want to have some Bosses spawn in a world randomly with a certain percentage of spawning. I would also like some Boss's to be spawned by converting certain vanilla mobs into Boss's, however I can not see HOW to actually do this.

- The Wiki shows that you can simply increase the spawning percentage of your Boss per world in the GUI, however that only increases the percentages that a Boss will randomly spawn, I need to know how to set it to CONVERT a vanilla spawning mob into a Boss mob. 

- For example I want my super_creeper Boss to replace normal spawning creepers 50% of the time when a vanilla creeper spawns in my world. How can I do this?

Thanks in advanced!

**Comment by kangarko** [comment]
Sorry, the converting is currently very limited and will convert at 100% all the time. I can look into adding new options to the menu.

**Comment by LeehamElectronics** [comment]
> Sorry, the converting is currently very limited and will convert at 100% all the time. I can look into adding new options to the menu.

Okay that's fine, but how do you actually enable converting? I can not see how to do this.
Thanks

**Comment by LeehamElectronics** [comment]
I feel like the wiki needs a clear explanation showing us how to specify whether mobs should be spawned or converted because I still can not find the option to enable converting or spawning in the menu...

**Comment by kangarko** [comment]
Got it, since the last update you open the Spawning menu and there is a button for spawn % chance for converting. That will inherit settings from spawning, so that you must first set the spawning in your world to 100% for the converting to even take place. Bit weird, may rewrite this in Boss4.

**Comment by LeehamElectronics** [comment]
Yes if you could change this to something like a toggle button inside the GUI to switch between converting and random spawning mode that would be so much better!
Thanks

**Comment by kangarko** [comment]
Sorry, the system that handles it is from 2017 and is not catching up with this. I am considering to rewrite it to something like this:

![a](https://i.imgur.com/ImJR7DI.png)

What do you think?

**Comment by LeehamElectronics** [comment]
Sorry I'm a bit confused with the picture there, I'll make a mock up GUI and send it to you to see what you think if that's okay.
Thx

**Comment by LeehamElectronics** [comment]
Here is the mock-up for you Matej,basically it shows how you can have a separate menu for both 'Random Spawning' and 'Random Converting' that way the user can configure both Random Spawning and Random Converting Separately, without loosing any functionality. Let me know what you think.
Thanks
[New-Menu-1.png](https://postimg.cc/7b9FmtD2)

**Comment by kangarko** [comment]
Got it, thank you. Well that would just 2X our current average system.

What I was thinking is basically condition-like system you're familiar with from ChatControl. You define a condition like you do with rules "match XXX", instead, here you you define a trigger "trigger spawn" (that will then apply on each vanilla spawn) and you simply place your rules operators just as you would in ChatControl and go from there.

That system would radically allow much more flexibility, options and add _all_ of the missing or requested spawning Boss features.

**Comment by LeehamElectronics** [comment]
Okay I'm just not sure how you would implement that into a GUI but if you think it will work that's great, when do you think we can expect to see this spawning system working?
Thanks

**Comment by kangarko** [comment]
There's no ETA right now, probably someone else would have to take over this in the next months.

**Comment by kangarko** [comment]
Closing since such is already on our roadmap
