### ISSUE TITLE
1.13.2:Cant edit boss drops, tools, weapons, armor

### ISSUE THREAD

**Issue by FrostSanta** [kangarko/Boss#633]
I still cant edit weapons, drops, tools, and armor with drag and drop system. I have already issue this before but it still didnt work for me. I tried using normal minecraft items and item got a custom name and lore in it but it drops and pop an errors.
https://pastebin.com/XicWAZWn < this is the error that comes out in console
[error (1).log](https://github.com/kangarko/Boss/files/5283059/error.1.log)  < the error log

if the boss jar/folder needed ill put mine

**Comment by kangarko** [comment]
Thank you. I will fix that in the next version, let me know in the comment below if you will still be experiencing this.
