### ISSUE TITLE
1.16.3: Illusioner Messages Repeat

### ISSUE THREAD

**Issue by mrcoffee1026** [kangarko/Boss#636]
With Illusioner Mob (only this one as far as I know)... as they "clone" themselves into 3-5 other mobs I believe is where this issue comes from... the boss messages - for example from the enderman teleport skill:
```
- I was lonely far away from you, so I came by to say hey
- Say hey! {boss} has &cteleported itself to you &7!
- I thought we were friends, so here I come!
```
Appears to be repeated for each and every one of the clones of itself instead of just the actual boss you can attack.  It will even randomly alternate the messages within the same teleportation.  Not sure if this is fixable or not, I know you've already applied a fix to get messages to stop being repeated multiple times from the same boss but this appears to be an exception since it has mutliple entities attached to it.

Boss 3.8.11
Paper 204

**Comment by kangarko** [comment]
By cloning themselves you mean on minions?

**Comment by kangarko** [comment]
If yes, I can make minions not have a skill, create a setting toggle for that.

**Comment by mrcoffee1026** [comment]
No it's not minions... it's something specifically that an illusioner does and no other mob does:  it will split into 5 copies of itself, where only the center of them is the thing that can be hit.  If you strike a blow directly in between them all they briefly come back to that position as a single mob then again separate into parts.  It makes them difficult to target and kill overall, but the messages seem to be being sent by each of the "pieces" of this mob instead of by the singular controlling entity.

**Comment by kangarko** [comment]
Seems like a "wontfix" for now. I'm putting a todo in my list and closing due to time constrains. Will be sorted out in the next major rewrite (no ETA).

**Comment by mrcoffee1026** [comment]
alright thanks!
