### ISSUE TITLE
1.16.3: Using player skins on bosses

### ISSUE THREAD

**Issue by Baktus79** [kangarko/Boss#637]
I previously saw a post here about player skins being worked on. Is this a project that has been scrapped or is it still under development? If so, do you have an ETA? 

I just bought Boss and think this plugin has great potential. The only thing I missed were custom particle effects and player skins.

**Comment by LeehamElectronics** [comment]
Great idea, I would like to see this implemented too.

**Comment by LeehamElectronics** [comment]
Perhaps an option to set the boss to the skin of the player looking at using protocol lib to change the skin displayed per player. And of course the ability to type in the UUID or username of a player to set that boss's skin to that.

**Comment by kangarko** [comment]
Thanks, we do plan using Citizens to spawn player NPCs and give them boss-like behavior though.
