### ISSUE TITLE
Spawner or region not working on 1.8.8

### ISSUE THREAD

**Issue by Sherineko** [kangarko/Boss#638]
1) 1.8.8 Paper

2) When I make a spawner in a certain area, the monster doesn't work or doesn't respawn at all, but the monsters that reappear are vanilla monsters, not from Boss monsters.

3)   a) Pastebin: https://pastebin.com/iKTney5h
      b) Image: https://ibb.co/vPq44WC

**Comment by kangarko** [comment]
Sorry this will never work, there is no API call we can make in 1.8.8 to get that method because it was added in later MC versions.
