### ISSUE TITLE
1.8.8: Players cannot deal damage at the same time.

### ISSUE THREAD

**Issue by Nrc0611** [kangarko/Boss#639]
As it says above for some reason in the latest version 3.8.11 if 2 players are dealing damage it will only take damage from one player at a time and will switch between them. Works fine on 3.8.10 but not on the latest.

**Comment by kangarko** [comment]
What do you mean by 'deal damage'?

**Comment by Nrc0611** [comment]
So I have a way of displaying the health and damage per player on a scoreboard and when 2 players hit at the same time only one of them goes up. But before both of them would go up. You can tell the difference cause it takes way longer for the boss to die.

**Comment by kangarko** [comment]
Thanks, so sorry for a late reply, I have put a note for this and will come back to you within 24h

**Comment by kangarko** [comment]
@Nrc0611 can you please ZIP me your config so I can reproduce under your exact Boss setup?

**Comment by Nrc0611** [comment]
Yeah sure sorry I saw the msg and forgot to do it here: 
[Boss.zip](https://github.com/kangarko/Boss/files/5331528/Boss.zip)

**Comment by kangarko** [comment]
I apology so much for a week's delay, had to leave Boss development for a while due to other works:

However upon looking into it and testing it with your Boss (albeit without equipment), it did decrease the health correctly: https://ufile.io/lm18yv93

Perhaps your scoreboard plugin is showing up false information? You can try enabling the healthbar from Boss and testing it this way please.

**Comment by Nrc0611** [comment]
The error was when u both hit at the exact same time it cancel outs the second persons damage. I will test with the newest version and post a video if its still a issue. Ill respond in the next few hours

**Comment by Nrc0611** [comment]
Ok, here you go. Apparently, it was always like this cause I just tested a couple of different versions:
https://www.youtube.com/watch?v=XsQE2gXA668&feature=youtu.be
(Boss health on the scoreboard is always off by 1 jsuk)

The problem is as you can see we both hit it at the same time but it will only register for one player at a time. I have damage indicators so you can see its real health.

**Comment by kangarko** [comment]
That does not look like an issue with Boss to me, have you tried vanilla mobs? Or try lowering Boss health to for example 30 and test it again. Such high values behave problematically because MC was never intended to be used such way.

**Comment by Nrc0611** [comment]
Hmm ok ill test it.

**Comment by kangarko** [comment]
Sorry that I was not able to help. I understand it may take some time but did you get to test this please?

**Comment by Nrc0611** [comment]
I've been testing this for a while and I just don't know. Even damage indicators thinks I am doing damage but the mob isn't actually receiving it. I tried removing all plugins to see if one of them was causing the issue but no. Idk what's wrong I am still looking into getting help from others to solve this problem.

**Comment by kangarko** [comment]
I'll investigate this further but so far I had no success, please remove those indicators for now.
