### ISSUE TITLE
Question about natural spawning.

### ISSUE THREAD

**Issue by jacopomozzy** [kangarko/Boss#64]
Dear,
I want to buy Boss, but I have a question.

It's possible to set that a custom mob can spawn only in a determinate biome? (ex. A mob spawn only in the desert)

Regards

**Comment by kangarko** [comment]
Hey, yes this is totally possible!

**Comment by jacopomozzy** [comment]
Fantastic, you'll have a new user of this plugin! :)

**Comment by kangarko** [comment]
Awesome :)
