### ISSUE TITLE
Minecraft Version: EnderDragon Boss Remove.

### ISSUE THREAD

**Issue by MaskyLedOn** [kangarko/Boss#641]
Hy i make the boss EderDragon , on World.. i remove the plugin with everyting .. and stil EnderDragon remain on map .. and little with little destroy my map .. now i remove the plugin with boss , but still i got the EnderDragon on the map .. can you please fix that? like i says i remove even the plugin .. and they are still there.

**Comment by kangarko** [comment]
We cannot remove Bosses after you remove the plugin. You need to install Boss again and use /boss scanner command to remove a Boss permanently from your entire world.
