### ISSUE TITLE
1.12.2: Boss spawn commands being sent even if the boss conditions deny its spawn

### ISSUE THREAD

**Issue by Firosee** [kangarko/Boss#642]
If i have commands on spawn of the boss, they are still executed even if the boss does not spawn due to not being allowed from its spawn conditions.

Proof of it saying it cant be spawned, but still executing the command: https://gyazo.com/4d4d7f20503746359b33690aeb7d446d

Proof of the command in the spawn-command section: https://gyazo.com/50c0e6fd533a44e9ddfbdbe1d10b743b

**Comment by Firosee** [comment]
I really need this to be fixed ASAP. It is causing spam messages on the server meaning i cant have the bosses enabled until then.

**Comment by Firosee** [comment]
This issue does not exist on version 3.7.0 and below, but that is a very old version to attempt to use lol

**Comment by kangarko** [comment]
Hey, please use the latest version coming up later tonight, we do not support anything older than that.

Just tested and it appears to work fine: https://i.imgur.com/l0tHrrh.gif

If it is still broken on that version, write to me below exactly how the Boss is spawned (egg? plugin?) and how it is blocked. And include your Boss folder as ZIP.

**Comment by Firosee** [comment]
This is still not fixed, sorry it took so long to test i honestly completely forgot that i opened this issue.

The boss is spawned via an egg, and its only suppose to work in specific worldgaurd regions, which it kinda works, it prevents the boss from spawning , however the spawn message is still being sent.

**Comment by Firosee** [comment]
@kangarko

**Comment by kangarko** [comment]
Can you please ZIP me your Boss folder and let me know what Boss is that?

Also what MC version are you running?

So to reproduce this problem I do have to just make a WG region or do I have to set any special flags there etc.?

**Comment by Firosee** [comment]
Version 1.12.2, And yes worldguard regions are being used, this happens even in the boss regions too.
[Boss.zip](https://github.com/kangarko/Boss/files/5410737/Boss.zip)

**Comment by Firosee** [comment]
If you use version 3.7.4, this issue does not happen - so whatever changed in the next version after this one, broke it.

**Comment by Firosee** [comment]
@kangarko

**Comment by Firosee** [comment]
Also are you able to help me with another question? The custom skills is loading after bosses are initialized, so the skills get invalidated, meaning the bosses custom skill doesnt work. Is there any way to fix this on my end?

**Comment by kangarko** [comment]
What do you mean by custom skills? Are you using our API?

I'm going to test the region problem by Friday, short on time right now and tomorrow.

**Comment by Firosee** [comment]
Yes i am using the api but all the skills keep getting invalidated because boss plugin is loading before the custom skill plugin, so i need to know how to get the skills to validate properly

**Comment by Firosee** [comment]
Hey mate got any help with the api please? Bosses custom skills keep getting removed on restart because the custom skills is loading after bosses are initialized, so the skills get invalidated

**Comment by Firosee** [comment]
Potentially the issue with spawning is a version issue or something? Im on paperspigot 1.12.2 to help with testing.

@kangarko Did you manage to do any testing this weekend on this?

**Comment by Firosee** [comment]
i want to note that i have tested it using the bare minimum plugins : https://gyazo.com/b69a25e1165b3de5312728e2b4e3b2d3, and it still happens, which means it is not a compatibility issue with another plugin.

**Comment by kangarko** [comment]
@Firosee apology for the delay... have you tried adding your custom plugin to the "depend" key of plugin.yml ? https://bukkit.gamepedia.com/Plugin_YAML

If it still does not work, you can just wrap your code in your custom plugin that registers the skill like this:

```
new BukkitRunnable() {
  // hook into boss
}.run(yourPluginInstance)
```

This will ensure to load it after Boss when your server has finished loading.

Regarding the spawn issue, I just fixed that ;)

**Comment by Firosee** [comment]
@kangarko Thank you for fixing the issue with spawning, i will try that out in a bit.

Regarding the bosses addon, i tried adding the depend key into the plugin.yml of boss however sadly it causes this error : https://paste.helpch.at/veniyoxanu.sql and does not load.

We are attempting the second option now.

**Comment by kangarko** [comment]
Then just don't use it. It you wrap the code in a BukkitRunnable that's run after the server has started, it will work regardless.

**Comment by l3st4tPlugins** [comment]
So I'm the developer of the addon in question.
The issue, from the logs that my client sent me, is that Bosses seems loads the active skills part too early and causes them to invalidate them. https://pastebin.com/Q2Y3dS7K

Wrapping the code in a BukkitRunnable wouldn't work - it's not my code is loading too early, it's that Bosses is loading the skills data too early. I could try it though.

**Comment by kangarko** [comment]
Thanks for your explanation. I made the bosses load after the server has started, thus the skills will now get registered properly.

**Comment by Firosee** [comment]
@kangarko Cheers mate, addon now works as intended. <3
