### ISSUE TITLE
1.8.8: Mob Factions/Targets Configurable?

### ISSUE THREAD

**Issue by ethsmith** [kangarko/Boss#646]
In MythicMobs you can configure factions/entity targets for each mob so you can create basically body guards for the player that attack other mobs or skeletons that are only not hostile to other skeletons and so on. Is it possible to do this with Boss. 

The reason for me to even consider buying this is because although I can use MythicMobs on my 1.16 servers, it is not possible to use it on my 1.8 servers and if this is supported by Boss along with the 1.8.8 Minecraft version then I will feel good about buying it.

**Comment by kangarko** [comment]
Replied on SpigotMC.
