### ISSUE TITLE
1.8.8 Spigot How to setup timed spawns in specific regions

### ISSUE THREAD

**Issue by Whitevoyd** [kangarko/Boss#648]
I am trying to configure bosses to spawn every hour on the dot to spawn in certain regions i marked out with /b region. I could not quite figure it out. Also are you familiar with how ClearLag can exclude boss from being removed during entity resets?

Thank you,

**Comment by kangarko** [comment]
Hi there,

This is an article I believe will help you with your timed spawning question: https://github.com/kangarko/Boss/wiki/Frequent-Questions-and-Tips#can-i-spawn-bosses-individually-at-a-certain-time

Regarding ClearLagg, you would need to ask their support to use our Boss API and exclude Bosses. Or at least exclude named entities.
