### ISSUE TITLE
Suggestion : Tamed Bosses

### ISSUE THREAD

**Issue by SoraShiunin** [kangarko/Boss#65]
If this is possible.
If you were to tame a Boss wolf/ocelot/parrot & etc... 
They would keep their Boss stats, like attack damage,skills,effects, health.

**Comment by kangarko** [comment]
Thanks, for now I am leaving this open.

**Comment by JTGgamer** [comment]
I agree with this, great idea :)

**Comment by kangarko** [comment]
Merged into Roadmap.
