### ISSUE TITLE
HIGH PRIORITY - Unable to spawn {boss} in this location!

### ISSUE THREAD

**Issue by kylew6619** [kangarko/Boss#651]
Hello I keep getting this message with every boss I create. I set the regions and worlds and etc. And it wont let me spawn them.. Unable to spawn {boss} in this location!

**Comment by ofunny** [comment]
Same issue, I updated to the newest version today.
An suddenly it is no longer possible to spawn in my normal world, I called the world survival.

Can not say if it happened directly after update or later. But now no boss spawns in the normal world, also spawn eggs say the same. In nether all bosses could be spawned by egg!

**Comment by Xardas88** [comment]
Same for me. In my case it is for the griefprevention claim. 
Can you add a config for enable/disable the spawn in griefprevention claim pls?

**Comment by kangarko** [comment]
Guys please see https://github.com/kangarko/Boss/wiki/Common-Issues#bosses-are-not-spawning-in-regions and the question above it and follow the steps outlined there. If nothing works attach your debug information as per instructions from these questions.

**Comment by Xardas88** [comment]
There isn't an option to spawn boss in a GriefPrevention claim. I had to downgrade Boss to 3.8.12.
Maybe you can add it only for adminclaim.

**Comment by kangarko** [comment]
Thanks, I'll take that as suggestion with high priority.

**Comment by kangarko** [comment]
Unfortunately I don't have the resources to add this right now
