### ISSUE TITLE
1.14.4: Spawning mobs in a region + respawning

### ISSUE THREAD

**Issue by ChopChopoo** [kangarko/Boss#652]
It the following possible?

To have a limit of 10 bosses in a specific region, and then when a boss dies it automatically respawns after a short time window (example: 30 seconds)

**Comment by kangarko** [comment]
Yes in theory, you'd have to set a world or a chunk limit in settings.yml and then use Timed_Spawning option in the same file to automatically spawn new bosses, meaning they would reappear after the old one have died out.
