### ISSUE TITLE
Particle System suggestion

### ISSUE THREAD

**Issue by ZurielRedux** [kangarko/Boss#653]
System to allow boss's to give of simple particle effects so you can recognize them from further or add a thematic flair. I think this goes a long way to selling the idea that the boss is unique in appearance without having to resort to custom textures or models.

**Comment by LeehamElectronics** [comment]
Agreed, however Kangarko is doing a lot at the moment and probably won't have time to implement this for a while.

**Comment by kangarko** [comment]
Thanks, already aware of that and considering into next major rewrite.
