### ISSUE TITLE
1.8.9 - How do I disable this...

### ISSUE THREAD

**Issue by NetflixFeelings** [kangarko/Boss#654]
I want to disable players being able to spawn bosses anywhere but in my pvp arena. I just cannot find how to do this. Help?

**Comment by LeehamElectronics** [comment]
Use world guard to disable mob spawning in certain regions such as disable it globally and then enable it inside your PVP arena or vice versa, perhaps Kangarko could also add a world guard flag that hooks into world guard such as allow-boss-egg-spawn and allow-natural-spawn for more advanced customisation with world guard regions.

**Comment by NetflixFeelings** [comment]
I can't disable mob spawning in my skyblock world because there are no regions... Also why do they get clearlagged and how can I stop it?

**Comment by kangarko** [comment]
My best recommendation is to move your PvP arena into "minigames" world and disable clearlag there and use those flags as Leeham suggested.
