### ISSUE TITLE
1.16.3 Paper: Mobs spawning in floor

### ISSUE THREAD

**Issue by darknight99x** [kangarko/Boss#655]
Hi, thanks for the plugin. It's really unique.

Unfortunately I am having an issue with the Timed Spawning feature of my enemy mobs.

They are spawning a block deep into the ground at day time,  causing them to ignore the lighting conditions I have set for them.
Thank you, hope it can be fixed. [https://i.imgur.com/1TxfsPo.png](url)

[boss.zip](https://github.com/kangarko/Boss/files/5368889/boss.zip)

**Comment by kangarko** [comment]
Thank you I have added a fix in the next version.
