### ISSUE TITLE
Spawn with Command Blocks Doesn't Work

### ISSUE THREAD

**Issue by MasterNiros** [kangarko/Boss#656]
Hello,

When using a command block with /boss spawn <boss> to spawn a boss, the command expects <world> <coordinates> and does not simply accept /boss spawn <boss>. Entering tilde ~ ~ ~ and the world does not work as it can only be executed by a player.

It seems other variations of the command don't register. A possible work-around is adding support for targeting the nearest player (similar to vanilla's @p), enabling use with /boss summonp.

Thx :)
--Niros

**Comment by kangarko** [comment]
Do not use ~ in those coordinates, you need to enter explicit number to use them with a command block.
