### ISSUE TITLE
1.14.4: Timed spawning is not working correctly

### ISSUE THREAD

**Issue by ChopChopoo** [kangarko/Boss#657]
At first I got this message in the console:
Attempt to spawn Vindiman at Choporderpvp [129, 78, -17] for TIMED
11.10 11:42:05 [Server] Server thread/INFO Not spawning. Whitelist is set & Boss is not within any whitelisted region.

Then I realized that in the settings.yml for the boss "Vindiman" the limit is set to -1, and changed that to 5 and reloaded the boss plugin including restarting the server.

Now I'm getting this message:

11.10 11:48:09 [Server] Server thread/INFO Loading bosses (1) ..
11.10 11:48:09 [Server] Server thread/INFO > Loading Vindiman
11.10 11:48:09 [Server] Server thread/INFO Tutorial:
11.10 11:48:09 [Server] Server thread/INFO https://github.com/kangarko/Boss/wiki
11.10 11:48:09 [Server] Server thread/INFO Get help:
11.10 11:48:09 [Server] Server thread/INFO https://github.com/kangarko/Boss/issues

How do I fix this?

Zip file:
[Boss.zip](https://github.com/kangarko/Boss/files/5361015/Boss.zip)

Edit (hours later), I just turned on the server again to work on something else, and there were 2088 Vindiman bosses spawned in the world I added under Timed spawning, however none of them spawn in the region I want them to,

**Comment by Xidle** [comment]
@ChopChopoo 
Bro whenever I use the spawners for BossTM It does not even let me pick the boss for the spawner so timed boss spawns do not work for me can you educate me with a little bit of your knowledge on how to set this up, maybe? : )

Thank you !!
Xidle

**Comment by kangarko** [comment]
Hey there,

@ChopChopoo from your config I can read that your Boss only spawns in "Boss" region right now. If it spawns outside of it, please set Debug to [spawning] in settings.yml and post me console messages when it does.

@Xidle what MC version do you use? Ensure you run the latest Boss.

**Comment by Xidle** [comment]
@kangarko Hi there I am running on 1.16.1

**Comment by ChopChopoo** [comment]
@kangarko 

15.10 08:44:58 [Server] INFO Warning: We have detected that you are debugging 'spawning'. This will show up in your timings because we save each debug log to a file.
15.10 08:44:58 [Server] INFO !-----------------------------------------------------!
15.10 08:44:58 [Server] INFO NOTICE ON PERFORMANCE:
15.10 08:44:58 [Server] INFO Timed Spawning delay is less
15.10 08:44:58 [Server] INFO than 15 seconds (300 ticks).
15.10 08:44:58 [Server] INFO Performance may be affected.
15.10 08:44:58 [Server] INFO !-----------------------------------------------------!
15.10 08:44:59 [Server] INFO Loading bosses (1) ..
15.10 08:44:59 [Server] INFO > Loading Vindiman
15.10 08:44:59 [Server] INFO Tutorial:
15.10 08:44:59 [Server] INFO https://github.com/kangarko/Boss/wiki
15.10 08:44:59 [Server] INFO Get help:
15.10 08:44:59 [Server] INFO https://github.com/kangarko/Boss/issues
15.10 08:44:59 [Server] INFO ______________________________________________________________
15.10 08:44:59 [Server] INFO A new version of Boss is available.
15.10 08:44:59 [Server] INFO Current version: 3.8.14; New version: 3.8.16

**Comment by kangarko** [comment]
Update to 3.8.16. No Debug log was provided from any of you, I am closing this. Comment below following my instructions above if you still need help.
