### ISSUE TITLE
Can you please support MMOItems?

### ISSUE THREAD

**Issue by qwe938775** [kangarko/Boss#659]
Can you please support MMOItems?

If you can use MMOITEM equipment attributes and props
You can send this plug-in function to the extreme

**Comment by LeehamElectronics** [comment]
That would be nice👍

**Comment by qwe938775** [comment]
It doesn’t seem to be supported right now. Wearing equipment on monsters cannot deal with equipment attributes and effects.

**Comment by kangarko** [comment]
Sorry this appears to be incompatible due to the NBT tags used with it right now. I may reopen it in the future when rewriting Boss but for now there is no ETA.
