### ISSUE TITLE
Suggestion: Drops/Rewards for everyone

### ISSUE THREAD

**Issue by PengBread** [kangarko/Boss#66]
This should be a feature to be added in the plugin
- Give all the players that hit the boss rewards. [ Random Rewards for everyone that hit atleast a certain % of health to the boss ]
- Top 5 Damagers. #1 gets more rewards than the others

this is to be fair to every players instead of items dropping on floor then loot.

**Comment by kangarko** [comment]
Thank you, that is already in the road-map.
