### ISSUE TITLE
1.8 how to spawn boss in specific region with /b spawn command

### ISSUE THREAD

**Issue by Whitevoyd** [kangarko/Boss#660]
I am wondering how to spawn a boss with a command in a specific region. I want to run the command in McCron hourly and i can't figure out the /b spawn command.

Name of world : PvP
Name of Boss defined region: Bossmap.

Thank you,

**Comment by kangarko** [comment]
Hey, it is very simple, all you have to do is type:

`/boss spawn world x y z bossname` to your plugin or command block.

Replace world with your world name, and x y z with the coordinates where you want to spawn the boss. Finally, replace bossname with your Boss name.
