### ISSUE TITLE
1.8.8:  Boss skill cast distance

### ISSUE THREAD

**Issue by RobinnTR** [kangarko/Boss#662]
Even after the boss kills the player, she continues to throw her skills to her birthplace.

Feature I want:

config.yml > boss-skill-distance: 10 (block)

**Comment by kangarko** [comment]
What skill are you talking about?

**Comment by RobinnTR** [comment]
all skills and skills messages
example:
Boss teleport, Boss fireball etc.

**Comment by kangarko** [comment]
We have already fixed this problem before, ensure you have Boss 3.8.16.

**Comment by kangarko** [comment]
Closing in good faith that by upgrading this will get resolved, if still having issues comment below.
