### ISSUE TITLE
Rewards for top 5 damage dealers

### ISSUE THREAD

**Issue by Whitevoyd** [kangarko/Boss#663]
Hello I currently have it setup so that anyone who does damage within ~X amount of time receives a reward.

If is possible i can make it so anyone who deals over a certain threshold of HP gets more of a reward? Or rewards for top 5 damage dealers?

**Comment by WhatsTheBadNews** [comment]
I can vouch that my players would very much appreciate rewards tiers for top damagers.

**Comment by kangarko** [comment]
Thank you, seems like a lot of people are suggesting that so I am leaving this open for future implementation.
