### ISSUE TITLE
Boss commands being executed even if the boss is not in the correct region

### ISSUE THREAD

**Issue by Firosee** [kangarko/Boss#666]
If i have commands on spawn of the boss, they are still executed even if the boss does not spawn due to not being allowed from its spawn conditions.

Proof of it saying it cant be spawned, but still executing the command: https://gyazo.com/4d4d7f20503746359b33690aeb7d446d

Proof of the command in the spawn-command section: https://gyazo.com/50c0e6fd533a44e9ddfbdbe1d10b743b

Edit: Re-posted as old one was closed assuming the issue is fixed however it is not fixed. This still happens on the latest spigot version.

**Comment by Firosee** [comment]
Im also having a problem where i have paid someone to create a skill addon, however every single time the server gets restarted, the skill is removed from the bosses skill tree, and i need to re-add it every single restart.

Me and the developer have been trying to fix this amongst ourselves for weeks now and we have concluded that it is due to the boss plugin!

**Comment by Firosee** [comment]
I also want to note that the issue with the commands still being executed even if the boss cant be spawned in the specific area happens wether i use a spawn egg or do it via the command.

**Comment by Firosee** [comment]
This issue happens with both spawn eggs and the spawn command.

**Comment by Firosee** [comment]
Also are you able to help me with another question? The custom skills is loading after bosses are initialized, so the skills get invalidated, meaning the bosses custom skill doesnt work. Is there any way to fix this on my end?

**Comment by kangarko** [comment]
Thanks, I will test and reply to your old issue.
