### ISSUE TITLE
Unable to spawn {boss} at this location. 1.8.8

### ISSUE THREAD

**Issue by squirtplays** [kangarko/Boss#667]
Basically I set up a region in my /warp pvp world and I cannot spawn them in there with the /boss spawn or with the egg. Made sure the chances aren't too low and looked through the common asked questions post and still couldn't fix it, hope someone can help!

**Comment by bowdyyy** [comment]
same here, i got it working once. but even now nothing spawns

**Comment by Whitevoyd** [comment]
Are you allowing mob spawning in that area? is it denying spawn with WG flag or something. Happened to me before.

**Comment by squirtplays** [comment]
Yep that was it thanks
