### ISSUE TITLE
NEW ISSUE, READ THIRD COMMENT

### ISSUE THREAD

**Issue by bowdyyy** [kangarko/Boss#668]
I have created a mob, set it spawn in a region created with your region creator and set the world and chance to 100%, still nothing spawning. i see issues of similar issue on here

**Comment by bowdyyy** [comment]
allso when right clicking on the mob in the /boss menu it does not spawn, but with an egg it does!?

**Comment by bowdyyy** [comment]
Mob not spawning in caves, settings has it allowed and 0 -250 for spawning depth, still fails to spawn anything

**Comment by bowdyyy** [comment]
btw for anyone wondering, top problems were solved by going into settings file in the plugins folder and just changing world to the name of my world

**Comment by bowdyyy** [comment]
Mobs still not spawning in caves

**Comment by kangarko** [comment]
Please complete steps here: https://github.com/kangarko/Boss/wiki/Common-Issues#bosses-are-not-spawning-naturally

If still having issues, post the console log as per instructions there + your ZIP folder of plugins/Boss/ folder.

**Comment by bowdyyy** [comment]
https://pastebin.com/2x9VgKnZ

**Comment by bowdyyy** [comment]
> Please complete steps here: https://github.com/kangarko/Boss/wiki/Common-Issues#bosses-are-not-spawning-naturally
> 
> If still having issues, post the console log as per instructions there + your ZIP folder of plugins/Boss/ folder.

https://pastebin.com/2x9VgKnZ i can send files if you like

**Comment by bowdyyy** [comment]
https://mega.nz/folder/mJVkWLAR#9k58Vamv0HMKSNjDgCzerA

**Comment by kangarko** [comment]
I apology for a late reply.

It says "Not spawning. Whitelist is set & Boss is not within any whitelisted region"

So either remove whitelist or remove the regions to enable Boss to spawn everywhere.
