### ISSUE TITLE
1.8.8 spigot: Question about spawning boss hourly

### ISSUE THREAD

**Issue by Whitevoyd** [kangarko/Boss#671]
As suggested i am using mccron to spawn hourly. Although i do not want the boss to spawn if there is already one active boss in the defined region. Is this going to be possible? i set in the boss menu that only 1 boss should be allowed for each boss but spawning with the /b spawn command overrides it?

**Comment by kangarko** [comment]
It should be possible from the /boss menu -> spawning -> regions -> Boss regions -> then click on the region to select boss limit inside of it.
