### ISSUE TITLE
1.16.3: Boss dont spawn in region pls help

### ISSUE THREAD

**Issue by N3JK0SLO** [kangarko/Boss#673]
Hello, I've set up everything as instructed on the wiki, created a boss by the guide, created a region, and enabled it I still can't get a boss to spawn in a selected region that I made, but I have no problem spawning a boss using a spawner.  Is it not possible to spawn a boss in the region hourly or by a specific time daily?

**Comment by kangarko** [comment]
Please try reading https://github.com/kangarko/Boss/wiki/Frequent-Questions-and-Tips as it contains information on how to solve spawning in regions not working (timed spawning). You'll also find an answer to how spawn Bosses at a certain time of the day or an hour.
