### ISSUE TITLE
1.16.1 Boss Spawwner Error

### ISSUE THREAD

**Issue by Xidle** [kangarko/Boss#674]
**Description:**
   Hey guys I am getting an error message for selecting a boss inside of a Boss Spawner GUI? I found the error in the console and pasted it here, as well as a Screenshot of the ingame Error! Please Someone Help Me With This One I Have Been Looking For The Solution for Forever Now! Thank you, Sincerely Xidle       @kangarko 

**Console Error:**
20.10 19:47:45 [Server] INFO Boss 3.8.13 encountered a NoClassDefFoundError! Please check your error.log and report this issue with the information in that file.
20.10 19:47:45 [Server] INFO java.lang.NoClassDefFoundError: Could not initialize class org.mineacademy.boss.x.ei
20.10 19:47:45 [Server] INFO at org.mineacademy.boss.x.du$a.a(SourceFile:184)
20.10 19:47:45 [Server] INFO at org.mineacademy.boss.x.du$a.a(SourceFile:153)
20.10 19:47:45 [Server] INFO at org.mineacademy.boss.x.bp.a(SourceFile:345)
20.10 19:47:45 [Server] INFO at org.mineacademy.boss.x.bo.onMenuClick(SourceFile:77)
20.10 19:47:45 [Server] INFO !-----------------------------------------------------!
20.10 19:47:45 [Server] INFO Error clicking in menu a{}

**In-game Error SS:**
![Spawner Error](https://user-images.githubusercontent.com/71620837/96657027-186a7800-130f-11eb-92a2-0754a6b98ccc.jpg)

Thank you so much!

**Comment by kangarko** [comment]
Use 3.8.16

**Comment by puyafire** [comment]
Im using that version and get the same error

**Comment by kangarko** [comment]
Please repost me the error because the error lines have changed since.

**Comment by Xidle** [comment]
@kangarko Hey there, So I switched to that version and it seems to be very glitchy. My spawner will sometimes spawn the boss I select but all the settings in the spawner keep resetting. It also still gives the same error in-game to contact an administrator?

**Comment by kangarko** [comment]
What's the stack trace of that error? Please upload me that error to pastebin.com

**Comment by Xidle** [comment]
How could I go about finding the stack trace of the error?

**Comment by kangarko** [comment]
https://github.com/kangarko/Boss/wiki/Getting-Help-the-Right-Way
