### ISSUE TITLE
1.16.1: The plugin keeps conflicting with EcoEnchants

### ISSUE THREAD

**Issue by puyafire** [kangarko/Boss#676]
Both EcoEnchants and Boss are premium plugins and I do not wish to scrap either. How can I make them compatible? The Boss plugin disbles itself after a restart removing all my progress due to EcoEnchants.

**Comment by LeehamElectronics** [comment]
Does this still happen or how did you fix it?

**Comment by puyafire** [comment]
I downgraed Echoenchants and removed all the boss enitity yml files. Then reloaded both plugins and it worked. Note that ecoenchants cannot be put inot Boss or it becomes disabled.

**Comment by LeehamElectronics** [comment]
Might be worth implementing popular plugin hooks with Boss and plugins such as Advanced Enchants, MMO Items and artefacts and the plugin mentioned in this issue.
I'll do some testing some day and see what works and what doesn't, perhaps it can be added to the road map for boss to add custom item support...

**Comment by puyafire** [comment]
Well the creator of ecoenchants mentioneed his working on this.

**Comment by puyafire** [comment]
Slowly though

**Comment by kangarko** [comment]
Can you post your startup log when Boss disables itself? Any errors? I don't have much time but in case it's an easy fix I'll do that.
