### ISSUE TITLE
1.16.1: Boss name doesn't displayed on other multiverse worlds

### ISSUE THREAD

**Issue by Potato001312** [kangarko/Boss#677]
The problem I facing now is quite simple. I had MMOCORE, world guard, world edit, Multiverse, and boss plugin installed. Minecraft comes with a default world map, bosses on that world works pretty fine for me. But, problem kicks in when i created a few new world using multiverse.(NOT ALL NOT WORKING), For examples, I created a world name dungeon, boss works fine too, then I continue on other world, then i ran into an issue that the boss name are not displayed at all. I checked on the console, no error showed up, not even warns. Hope that I could get a solution here for my stupidity, thanks.

This is the boss plugin file
[plugins.zip](https://github.com/kangarko/Boss/files/5421613/plugins.zip)

**Comment by kangarko** [comment]
Are you running a mob stacking plugin? If yes, then unfortunately this is caused by that plugin.

**Comment by Potato001312** [comment]
YES! thank you!!!!
