### ISSUE TITLE
1.16.3: The bosses doesn't spawn in the region it is supposed to

### ISSUE THREAD

**Issue by ChopChopoo** [kangarko/Boss#678]
The bosses doesn't spawn in the region it is supposed to

[Boss (2).zip](https://github.com/kangarko/Boss/files/5423801/Boss.2.zip)

[latest log [Debug = spawning].zip](https://github.com/kangarko/Boss/files/5423805/latest.log.Debug.spawning.zip)

**Comment by kangarko** [comment]
You configured your Boss only to spawn in the Test1 region, so it won't spawn anywhere else.

I cannot see any spawning debug messages from your console log. You'll have to wait 90 seconds to get some or make the Timed_Spawning.Delay lower in your settings.yml then repost me your log.

**Comment by ChopChopoo** [comment]
The server was up for 7 minutes

[latest.zip](https://github.com/kangarko/Boss/files/5441646/latest.zip)

**Comment by kangarko** [comment]
Please add Choporderpvp to your worlds' list in Timed_Spawning in settings.yml
<img width="632" alt="Skjermbilde 2020-10-27 kl  17 26 57" src="https://user-images.githubusercontent.com/1918426/97331437-abf4f900-1879-11eb-8ebc-b808503c844a.png">
