### ISSUE TITLE
Option to make bosses never despawn until killed. 

### ISSUE THREAD

**Issue by iMxAndyy** [kangarko/Boss#68]
It would help to have an option for bosses to never despawn to allow us to create a dungeon boss that'll be there no matter what. 
this goes hand in hand with my last suggestion. 

if enabled the mob should remain where it is until killed and never despawn.
if not enabled despawn as normal.

**Comment by kangarko** [comment]
Hello, 

Bosses don't despawn by default because they are named and named entities don't despawn.
