### ISSUE TITLE
[suggestion] boss.gui.boss.delete

### ISSUE THREAD

**Issue by Mishrathium** [kangarko/Boss#681]
add a permission to not allow boss deletion by command or GUI.

Often we would like moderators to play with the BOSS gui. No accident has happened yet but adding a permission to completely stop boss deletion would be a future saver.

Boss delete in GUI should also have a "confirm" second menu for accidental slips.

thank you for your time and talent.

**Comment by kangarko** [comment]
Already answered this elsewhere.
