### ISSUE TITLE
boss.gui.delete.boss

### ISSUE THREAD

**Issue by Mishrathium** [kangarko/Boss#682]
add a permission like above to stop accidental or precent certain ranks from deleting a boss.
- This is an important future quality of life addition giving owners more control over who does what.

Also adding a confirm t/f GUI after selecting a boss for deletion to prevent accidents.

Thank you for your time and talent

**Comment by kangarko** [comment]
Hi there!

Thanks for your suggestion, however the entire GUI is not made to be accessible by ranks so we have no permissions system there. It is meant to only be accessed by staff.

Matej

**Comment by LeehamElectronics** [comment]
Probably shouldn't give out permission to people to make major changes like that, instead, have a test server or development server to allow people to test their Boss on. Or just make regular backups of ur Boss folder in case someone deletes a Boss.

@Mishrathium
