### ISSUE TITLE
Great plugin i have the suggestion are when i used command boss spawn on player sometimes it's not spawn if player are very close to the block so it world be great if u have an option to disable some kind of this not spawn.

### ISSUE THREAD

**Issue by mybrosavages** [kangarko/Boss#683]
Great plugin i have the suggestion are when i used command boss
spawn on player sometimes it's not spawn if player are very close to the block so it world be great if u have an option to disable some kind of this not spawn.

**Comment by kangarko** [comment]
Thank you for your suggestion, I have put it onto our list!
