### ISSUE TITLE
1.16.3: Spawner ignore limit in region

### ISSUE THREAD

**Issue by ludgart** [kangarko/Boss#686]
Hello,

I'm using the server software paper with the version 1.16.3 and the boss version 3.8.17. 
I found out, that the region limit is not working properly. There are no errors in the console.
I placed one spawner with 20 ticks in my boss region. After awhile there was more as 10 entities.

Regards
ludgart

**Comment by kangarko** [comment]
I apology, this limit is currently not functional on that version because of Paper changes.
