### ISSUE TITLE
1.16.3: Drop chances below 0.00x

### ISSUE THREAD

**Issue by ludgart** [kangarko/Boss#687]
Hello,

I'm using the server software paper with the version 1.16.3 and the boss version 3.8.17.
I found out, that the drop chances under below 0.00x not working. I tried it with 0.009 without success.

Regards
ludgart

**Comment by kangarko** [comment]
Hi,

I really don't want to reply to your second ticket with the same no, but we simply don't support drop chances below 0.00x. This however can be added so stay tuned for a future release :)
