### ISSUE TITLE
1.16.3: Wither Skeleton stop attacking while day

### ISSUE THREAD

**Issue by ludgart** [kangarko/Boss#688]
Hello,

I'm using the server software paper with the version 1.16.3 and the boss version 3.8.17.
I found out, that the Wither Skeletons stop attacking while day. Is there a way to fix?

Regards
ludgart

**Comment by kangarko** [comment]
Hi ludgart!

You can use the Auto_Target option to make them automatically retarget a player. You can set these settings according to the image below and it should work:
<img width="908" alt="Skjermbilde 2020-10-31 kl  18 18 37" src="https://user-images.githubusercontent.com/1918426/97785474-87fd2480-1ba5-11eb-9445-99604124fa5f.png">

**Comment by ludgart** [comment]
Hello, I already have these setting. That changed for me nothing. I think it change nothing, when I turn off the "override_on_attack".

Regards
ludgart

**Comment by kangarko** [comment]
Thanks I will review this. However I think it is a limitation due to https://github.com/kangarko/Boss/wiki/Frequent-Questions-and-Tips#can-you-make-animals-aggressive--add-better-ai
