### ISSUE TITLE
Region is not spawn boss 

### ISSUE THREAD

**Issue by hallday0024** [kangarko/Boss#69]
I create boss and create regions ues /boss tools to set fist Point and End Point.and
I add boss in region craete (egg Boss > spawing > Regions > Boss region > select Region ) 
and to setting time spawn 10 seconds in Settings.yml
and I waiting 60 seconds ,No spawn boss

I do not know what to do ?
:)

**Comment by kangarko** [comment]
Please read: https://github.com/kangarko/Boss/wiki/Common-Issues#my-bosses-are-not-spawning-naturally

Also, please post me your settings.yml and your Boss yml file.

**Comment by kangarko** [comment]
Closing, assuming fixed.
