### ISSUE TITLE
Questions before buying.

### ISSUE THREAD

**Issue by Slagersjongen** [kangarko/Boss#690]
Hi, im going to start up my first server soon, and i had a few questions.

1. Can i pay with a giftcard? You can choose any from amazon.com, link: https://amzn.to/2GcrUYJ

2. I want to make a few castles spread around my survival map, and put the bosses in there (so lets say 3-6 mobs from your plugin, that arent always loaded in because im not giving the exact coords to people and they wont be close to spawn) will this decrease the performance of my server a lot?

3. Do i need any other plugins to make this plugin work?

Thanks already for reading/replying to my message!

~ Slxger

**Comment by LeehamElectronics** [comment]
https://github.com/kangarko/Boss/wiki/Compatibility @Slagersjongen  
I do not think that Matej will accept 'gift cards'  I think he prefers PayPal, but I will let him answer that...

There is other info on the Wiki too that you should read first, I use Boss a lot and it does not consume CPU usage at all, it is very efficient and I highly recommend it.

**Comment by LeehamElectronics** [comment]
Yes but it is currently closed and you can only read announcements in it, that's all, for some reason I can not generate an invite link to the server so I can not invite you.

**Comment by Slagersjongen** [comment]
> Yes but it is currently closed and you can only read announcements in it, that's all, for some reason I can not generate an invite link to the server so I can not invite you.

How did you get into that server?

**Comment by kangarko** [comment]
Thanks for your interest!

Here's our Discord: mineacademy.org/discord

Boss is typically low-resource hungry, but depending on your configuration it may show up in timings. You will however be able to find your limit and easily configure the plugin to be efficient. 

Matej
