### ISSUE TITLE
1.16.3: Teleport to center is inefficient and cause damage

### ISSUE THREAD

**Issue by ludgart** [kangarko/Boss#691]
Hello,

I'm using the server software paper with the version 1.16.3 and the boss version 3.8.17.
I setup an boss region with "keep in zone". In my setting I enabled the "teleport to center". The problem is, it teleport the entitiy to the center of region without checking the location. In the most scenario it stuck in blocks and get damage.

Regards
ludgart

**Comment by kangarko** [comment]
Thanks, I will make it so the entity is teleport to the top most highest block with air.

**Comment by ludgart** [comment]
The best and efficient method would be to add a command to create the teleportBack location. If you take the higher block, then the problem will be still there, example if you have a cave and you teleport the monsters outside.

Regards
ludgart

**Comment by kangarko** [comment]
Thanks I will add this to our suggestions list!
