### ISSUE TITLE
1.16.3: Teleport (to center) cause endless loop

### ISSUE THREAD

**Issue by ludgart** [kangarko/Boss#692]
Hello,

I'm using the server software paper with the version 1.16.3 and the boss version 3.8.17.
I setup an boss region with "keep in zone". In my setting I enabled the "teleport to center". The problem is, it teleport the entitiy to the center of the region, but the entity still try to run to the specific location outside.
Here is an example as GIF: https://gyazo.com/9d8ef8e4c7823fb276c6740aded7c9f6

Regards
ludgart

**Comment by kangarko** [comment]
Unfortunately this is caused by poor possibilities we can do with the Bukkit API system. In Boss 4 we are going to use a special library to offer the customization of how a mob behaves, that will solve this problem.
