### ISSUE TITLE
1.16.3: Spiders are fighting against each other

### ISSUE THREAD

**Issue by ludgart** [kangarko/Boss#696]
Hello,

I'm using the server software paper with the version 1.16.3 and the boss version 3.8.17.
I created two different spiders with the setting "targetable" to false. When both spawn in the near, they are starting attacking.
There are no errors in the console.

Regards
ludgart

**Comment by kangarko** [comment]
Please set Debug to [target] in the next version of Boss and report me your console messages when that happens again.

**Comment by ludgart** [comment]
Hello,

I changed in the config "Creatures" to false. Now the monsters stopped attacking each other.

Regards
ludgart

**Comment by kangarko** [comment]
Great, so I am marking this as closed.
