### ISSUE TITLE
1.8.8: Is plugin up to date

### ISSUE THREAD

**Issue by Zentriixx** [kangarko/Boss#698]
Hello,

Upon launching the server Boss does not enable because of an issue which im unsure of how to fix. Below listed is the error.log generated by Boss.
[error.log](https://github.com/kangarko/Boss/files/5469332/error.log)

**Comment by kangarko** [comment]
Open settings.yml, find

`Prefix: '&c&lValane &4&lBOSS's &8//&7'`

Replace it with

`Prefix: "&c&lValane &4&lBOSS's &8//&7"`
