### ISSUE TITLE
Question about purchasing.

### ISSUE THREAD

**Issue by Slagersjongen** [kangarko/Boss#699]
Hi, you closed my ticket yesterday, but you forgot the most important question 😂

So here it is:

Can i pay with a giftcard? You can choose any from amazon.com, link: https://amzn.to/2GcrUYJ

I could order you anything else on amazon too (i dont mind if its 10$ more because im using a different payment method)

**Comment by kangarko** [comment]
No sorry, we only accept PayPal and credit cards at the moment. If you want to pay with any credit card, send your name and email to support@mineacademy.org and I'll send you an invoice.

No other payment methods are accepted at the moment.

**Comment by Slagersjongen** [comment]
hi, can we talk on discord so i can contact you better? my tag is Slxger#0001

**Comment by kangarko** [comment]
No sorry, if you need anything comment below or PM me in private via SpigotMC (kangarko).
