### ISSUE TITLE
Issue spawning and seting commands

### ISSUE THREAD

**Issue by algarrobo83** [kangarko/Boss#7]
Seting up spawns does not work, setting up time does not work, changes made on the gui does not take effect. Boss does not spawn. https://imgur.com/a/rtDCb

Console with debug:

https://gyazo.com/87b7e4215855855c88e2304e868240b7

https://gyazo.com/1718fbb691269f453081d39372e291c1

**Comment by kangarko** [comment]
Have you tried the vanilla monster egg from creative inventory? Not the Boss one from /boss egg but the native one from Minecraft. It is transformed?

**Comment by algarrobo83** [comment]
What we do is create a region with the desired boss, region, time of the day and light, and it does not spawn. That is the problem, we can spawn the monsters from both of the egs.

**Comment by algarrobo83** [comment]
Also the menu does not get updated.

**Comment by algarrobo83** [comment]
https://gyazo.com/ae5459e844623cc588f374c59e816a4c

**Comment by kangarko** [comment]
I have resolved that nasty bug, good notice!
