### ISSUE TITLE
I have an 2 idea!

### ISSUE THREAD

**Issue by mybrosavages** [kangarko/Boss#701]
1) It would be great if the boss have the player own boss like when boss spawn for that player when other player kill it only player the console or admin spawn to can only pick up in the time until if that player not pick it up the other will get it

2) I would like to have the boss type player with skin that can added in each of it 

sorry for my gamma the first idea like slayer system on hypixel skyblock u can google for it i think the system are very great

**Comment by LeehamElectronics** [comment]
I agree I would love to see these two things, would be great for my other mini games plugs too. I think these have already been recommended to Matej, check the road map for details

**Comment by kangarko** [comment]
Thank you, most or similar to this is already on the road map :)
