### ISSUE TITLE
1.16.4: Error for Itemstack NMSCOPY

### ISSUE THREAD

**Issue by OrangeCat555** [kangarko/Boss#702]
Not sure what directly causes it but this error appears in the console every few seconds. Using 2.8.18 on 1.16.4 paper.

04.11 04:42:21 [Server] WARN org.mineacademy.boss.x.dU: Method 'null' not loaded! 'ITEMSTACK_NMSCOPY'
04.11 04:42:21 [Server] WARN at org.mineacademy.boss.x.dY.a(SourceFile:165)
04.11 04:42:21 [Server] WARN at org.mineacademy.boss.x.dM.e(SourceFile:32)
04.11 04:42:21 [Server] WARN at org.mineacademy.boss.x.dQ.a(SourceFile:539)
04.11 04:42:21 [Server] WARN at org.mineacademy.boss.x.dC.n(SourceFile:510)
04.11 04:42:21 [Server] WARN at org.mineacademy.boss.lib.boss.util.c.a(SourceFile:23)
04.11 04:42:21 [Server] WARN at org.mineacademy.boss.x.O.onClick(SourceFile:68)
04.11 04:42:21 [Server] WARN at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor583.execute(Unknown Source)
04.11 04:42:21 [Server] WARN at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
04.11 04:42:21 [Server] WARN at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
04.11 04:42:21 [Server] WARN at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
04.11 04:42:21 [Server] WARN at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
04.11 04:42:21 [Server] WARN at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:503)
04.11 04:42:21 [Server] WARN at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:470)
04.11 04:42:21 [Server] WARN at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:154)
04.11 04:42:21 [Server] WARN at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1469)
04.11 04:42:21 [Server] WARN at net.minecraft.server.v1_16_R3.PacketPlayInBlockDig.a(SourceFile:40)
04.11 04:42:21 [Server] WARN at net.minecraft.server.v1_16_R3.PacketPlayInBlockDig.a(SourceFile:10)
04.11 04:42:21 [Server] WARN at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23)
04.11 04:42:21 [Server] WARN at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
04.11 04:42:21 [Server] WARN at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
04.11 04:42:21 [Server] WARN at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
04.11 04:42:21 [Server] WARN at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
04.11 04:42:21 [Server] WARN at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1135)
04.11 04:42:21 [Server] WARN at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1128)
04.11 04:42:21 [Server] WARN at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
04.11 04:42:21 [Server] WARN at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1089)
04.11 04:42:21 [Server] WARN at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1003)
04.11 04:42:21 [Server] WARN at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177)

**Comment by kangarko** [comment]
1.16.4 not ready yet, please wait for the update
