### ISSUE TITLE
1.16.3: Boss limit

### ISSUE THREAD

**Issue by ludgart** [kangarko/Boss#703]
Hello,

I'm using the server software paper with the version 1.16.3 and the boss version 3.8.17.
I found out, when the boss spawn in the specific region and get killed by lava/water/falldmg and more it doesnt respect the boss region limit. In the next spawn cycle it say "Bosses in region xyz over limit 1.", but the boss is not alive. Normally it should spawn.

There are no errors in the console.

Regards
ludgart

**Comment by kangarko** [comment]
Thanks, will get fixed.
