### ISSUE TITLE
Minecraft Version: Not working with 1.16.4

### ISSUE THREAD

**Issue by ionixxz** [kangarko/Boss#704]
Hello tried to upgrade my 5 servers to 1.16.4 and the boss plugin and 1 of our other gate plugins does not work when my staff member goes in to open up the menu he gets an error stating there was an issue and it crashes

We reverted the server back to 1.16.3 when will an update to 1.16.4 be released

Thanks

**Comment by kangarko** [comment]
We are working on it and an update will come out tonight
