### ISSUE TITLE
1.16.1: Are there any Boss configurations available?

### ISSUE THREAD

**Issue by PeterDorvay** [kangarko/Boss#705]
Hi there.

I'm on spigot 1.16.1 using the latest plugin version. I was wondering if there are any pre-made bosses available. I can't find any setups for sale on MC-market or other websites, and I was looking to purchase a couple pre-made bosses rather than have to create all my own. Please let me know if there are any configurations available.

Thank you!

**Comment by kangarko** [comment]
Not at present, but if you make one we encourage it to send it to matej@mineacademy.org and I can publish it for other creators as an inspiration 👍
