### ISSUE TITLE
Minecraft Version: 1.16.3 - Random Skill Delay?

### ISSUE THREAD

**Issue by moveit124** [kangarko/Boss#710]
In the how-to on git hub it says:

"Each Boss can have unlimited amount of skills. You can specify a random delay between a minimum and a maximum time for each skill individually."

How do you go about doing this (the delay)?

**Comment by kangarko** [comment]
When you install boss it will create /skills folder. In that folder, open up your skill files and configure it here:

Delay: 10 seconds - 15 seconds

That means the random delay is between 10 and 15 seconds
