### ISSUE TITLE
Minecraft Version: 1.8.8 (paperspigot)

### ISSUE THREAD

**Issue by BroGoDx** [kangarko/Boss#715]
1) Hello if a specific mob gets killed can the plugin broadcast the top 3 or 5 or 10 Players that did the best damage? And then reward specific top players? Like i wanna reward the top 3 or 5 or 10 damagers with unique rewards (Not the same reward)

2) Can i add custom enchantments in the armor of the mobs? I dont think it matters to this because its the enchantment plugin based question, i am wrong? (EliteEnchantments)

3) Can i buy the plugin from you and not from spigot (tax problems)?

4) Is there any sale coming up?

**Comment by kangarko** [comment]
1. We cannot make different broadcasts but we support reward spreads: https://github.com/kangarko/Boss/wiki/Drops#inventory-drops-and-pvp-spreads

2. Not sure, as long as you can drag and drop that armor into the Boss inventory it should work

3. No

4. No
