### ISSUE TITLE
1.16.3: Cannot customize equipment in-game

### ISSUE THREAD

**Issue by iVillager** [kangarko/Boss#717]
Hello. I'm getting mad because of this big issue.
When I try to set the equipment for a Boss, the items I put in there disappear. It happens with every Boss. I tried with Zombie, Skeleton, Wither Skeleton, Piglin etc. This issue doesn't apply to bosses that I have already customized. After the last update, I got this issue. I don't know how to fix it. I tried resetting configs, but it still happens. The biggest trouble is that I've no errors in console, so I don't know how to fix it. 
Screenshots:

https://ibb.co/17c34c3
https://ibb.co/YDtChnr
https://ibb.co/WVf0Xr1
https://ibb.co/DbRtWVw
https://ibb.co/5xTKsFx
https://ibb.co/S57rXbF
https://ibb.co/cNF99Ly

config.yml:

# -------------------------------------------------------------------------------------------
# 
#  Your file has been automatically updated at 11.11.2020 00:28:20
#  to Boss 3.9.1
# 
#  Unfortunatelly, due to how Bukkit saves all .yml files, it was not possible
#  preserve the documentation comments in your file. We apologize.
# 
#  If you'd like to view the default file, you can either:
#  a) Open the Boss-3.9.1.jar with a WinRar or similar
#  b) or, visit: https://github.com/kangarko/Boss/wiki
# 
# -------------------------------------------------------------------------------------------

Egg_Spawning:
  Max_Distance: 60
  Air_Spawn: true
  Spawn_If_Event_Cancelled: true
  Check_Regions: false
  Enforce_Latest_Egg_Version: false
  Item:
    Name: '&rSpawn {boss}'
    Material: MONSTER_EGG
    Glow: true
    Lore:
    - ' '
    - '&2&l< &7Left click for menu'
    - '&2&l> &7Right click to summon'
Timed_Spawning:
  Enabled: false
  Lightning: false
  Delay: 90 seconds
  Performance:
    Check_Conditions: false
    Check_Regions: false
    Chunk_Radius: 1
    Spawn_Underground: false
  Worlds:
  - '*'
  Bosses:
  - '*'
Converting:
  Enabled: false
  Lightning: false
  Ignore_From:
  - SPAWNER
Prevent_Vanilla_Mobs:
  Enabled: false
  Prevent_From:
  - NATURAL
  - CHUNK_GEN
  - SPAWNER
  - VILLAGE_DEFENSE
  - VILLAGE_INVASION
  - REINFORCEMENTS
  - INFECTION
  - CURED
  - DROWNED
  Entities:
  - '*'
  Worlds:
  - '*'
Limits:
  Apply_For_Commands: false
  Apply_For_Eggs: false
  Apply_For_Reinforcements: false
  Apply_For_Spawners: false
  Radius_Blocks: 64
  Global:
    Enabled: false
    Radius_Limit: 32
    World: 3000
  Individual:
    Enabled: false
    Radius_Limit: 24
    World: 1000
Region_Keeping:
  Enabled: false
  Port_To_Center: false
  Period: 20 ticks
Fight:
  Health_Bar: true
  Auto_Target:
    Override_On_Attack: false
    Creatures: false
    Players: true
    Delay: 10 seconds
    Radius: 15
Death:
  Run_Player_Commands_As_Player: false
Setup:
  Visualize_Regions: true
  Hook_ProtocolLib: true
  Sort_Bosses_In_Menu_Alphabetically: false
Iterate_Spawning_Tries: false
Command_Aliases:
- boss
- b
Prefix: '&8&lBOSS &8//&7'
Locale: it
Notify_Updates: true
Notify_Promotions: true
Log_Lag_Over_Milis: 100
Debug: []
Serialization: ''
Version: 6

**Comment by kangarko** [comment]
Thanks for reporting, let me know below if you still have this problem when the next version is out

**Comment by iVillager** [comment]
No, the plugin still doesn't work properly. Look at my Plugins, can you please tell me if you think there's a conflict with one of them:

Plugins (87): AdvancedChatTorch*, AdvancedEnchantments, AdvancedHelp, AutoCommandsPlus_Emaedit*, BannerBoard*, BetterRTP, BKCommonLib, BlockParticles, Boss, ChatManager, ChestShop, ChestShopLimiter, Citizens, ClearLag, Core, CoreProtect, CraftingStore, CrazyCrates, DeluxeCombat, DeluxeTags*, EffectLib*, EntityTrackerFixer, EpicBackpacks, Essentials, EssentialsChat, EssentialsSpawn, ExecutableItems, (WorldEdit)FastAsyncWorldEdit, FeatherBoard*, FlexAbilities*, FogusCore, GlowAPI*, GriefPrevention, GriefPreventionFlags, GUIPlus, HeadDatabase*, HolographicDisplays, HolographicExtension*, InteractionVisualizer, InteractiveChat, InvisibleItemFrames, ItemEdit, KixsAutoAnnouncerPremium, LagAssist, LightAPI, LightCleaner, LocketteX, LoneLibs, LPX*, LuckPerms, LuckPermsMVdWHook*, MiniaturePets, Multiverse-Core, MVdWPlaceholderAPI*, MyCommand, MysqlEconomyBank, NametagEdit*, OpenInv, OreoCore, PacketListenerApi*, PL-Hide, PlaceholderAPI, PlayerControl, PlayerWarps, PluginManager, ProtocolLib, QuantumShop, Quests, Referral, RPGRegions, ServerRestart, SimplePortals, SSX-Connector*, StaffFacilities, SurvivalMobs*, UltimateChairs, UltraCosmetics, Vault, ViaBackwards, ViaVersion, ViewDistanceTweaks, VoidGenerator, Voting*, VoxelSniper, WanderingTrades, WorldEditSelectionVisualizer, WorldGuard

**Comment by iVillager** [comment]
> No, the plugin still doesn't work properly. Look at my Plugins, can you please tell me if you think there's a conflict with one of them:
> 
> Plugins (87): AdvancedChatTorch*, AdvancedEnchantments, AdvancedHelp, AutoCommandsPlus_Emaedit*, BannerBoard*, BetterRTP, BKCommonLib, BlockParticles, Boss, ChatManager, ChestShop, ChestShopLimiter, Citizens, ClearLag, Core, CoreProtect, CraftingStore, CrazyCrates, DeluxeCombat, DeluxeTags*, EffectLib*, EntityTrackerFixer, EpicBackpacks, Essentials, EssentialsChat, EssentialsSpawn, ExecutableItems, (WorldEdit)FastAsyncWorldEdit, FeatherBoard*, FlexAbilities*, FogusCore, GlowAPI*, GriefPrevention, GriefPreventionFlags, GUIPlus, HeadDatabase*, HolographicDisplays, HolographicExtension*, InteractionVisualizer, InteractiveChat, InvisibleItemFrames, ItemEdit, KixsAutoAnnouncerPremium, LagAssist, LightAPI, LightCleaner, LocketteX, LoneLibs, LPX*, LuckPerms, LuckPermsMVdWHook*, MiniaturePets, Multiverse-Core, MVdWPlaceholderAPI*, MyCommand, MysqlEconomyBank, NametagEdit*, OpenInv, OreoCore, PacketListenerApi*, PL-Hide, PlaceholderAPI, PlayerControl, PlayerWarps, PluginManager, ProtocolLib, QuantumShop, Quests, Referral, RPGRegions, ServerRestart, SimplePortals, SSX-Connector*, StaffFacilities, SurvivalMobs*, UltimateChairs, UltraCosmetics, Vault, ViaBackwards, ViaVersion, ViewDistanceTweaks, VoidGenerator, Voting*, VoxelSniper, WanderingTrades, WorldEditSelectionVisualizer, WorldGuard

**Comment by kangarko** [comment]
Please remove all plugins but Boss and see if the issue persists, I cannot see anything
