### ISSUE TITLE
> No, the plugin still doesn't work properly. 

### ISSUE THREAD

**Issue by iVillager** [kangarko/Boss#721]
> No, the plugin still doesn't work properly. Look at my Plugins, can you please tell me if you think there's a conflict with one of them:
> 
> Plugins (87): AdvancedChatTorch*, AdvancedEnchantments, AdvancedHelp, AutoCommandsPlus_Emaedit*, BannerBoard*, BetterRTP, BKCommonLib, BlockParticles, Boss, ChatManager, ChestShop, ChestShopLimiter, Citizens, ClearLag, Core, CoreProtect, CraftingStore, CrazyCrates, DeluxeCombat, DeluxeTags*, EffectLib*, EntityTrackerFixer, EpicBackpacks, Essentials, EssentialsChat, EssentialsSpawn, ExecutableItems, (WorldEdit)FastAsyncWorldEdit, FeatherBoard*, FlexAbilities*, FogusCore, GlowAPI*, GriefPrevention, GriefPreventionFlags, GUIPlus, HeadDatabase*, HolographicDisplays, HolographicExtension*, InteractionVisualizer, InteractiveChat, InvisibleItemFrames, ItemEdit, KixsAutoAnnouncerPremium, LagAssist, LightAPI, LightCleaner, LocketteX, LoneLibs, LPX*, LuckPerms, LuckPermsMVdWHook*, MiniaturePets, Multiverse-Core, MVdWPlaceholderAPI*, MyCommand, MysqlEconomyBank, NametagEdit*, OpenInv, OreoCore, PacketListenerApi*, PL-Hide, PlaceholderAPI, PlayerControl, PlayerWarps, PluginManager, ProtocolLib, QuantumShop, Quests, Referral, RPGRegions, ServerRestart, SimplePortals, SSX-Connector*, StaffFacilities, SurvivalMobs*, UltimateChairs, UltraCosmetics, Vault, ViaBackwards, ViaVersion, ViewDistanceTweaks, VoidGenerator, Voting*, VoxelSniper, WanderingTrades, WorldEditSelectionVisualizer, WorldGuard

_Originally posted by @iVillager in https://github.com/kangarko/Boss/issues/717#issuecomment-727104685_

**Comment by kangarko** [comment]
let's continue on the old thread
