### ISSUE TITLE
Paper 1.16.1 

### ISSUE THREAD

**Issue by koyere** [kangarko/Boss#722]
bosses keep popping up even after elimination and some are even invincible.

secondly, they do not execute the commands when they die, nor do they give anything, although if they give them little items they do not give them, even when I set the possibility to 100%.

**Comment by kangarko** [comment]
If they keep spawning, ensure you set their Spawning --> Worlds to 0% for all worlds. To prevent them being invincible, check their properties and check if another plugin is not causing this.

Same for commands --> test with just Boss and no other plugin, but if it still won't work please post me your Boss YML file below.
