### ISSUE TITLE
Paper 1.16.3 | Ender Dragon boss but no movement

### ISSUE THREAD

**Issue by ajstahovec** [kangarko/Boss#723]
Hi there,
I'm having trouble getting my ender dragon to ender-dragon basically. He's spawned in, and flapping his wings, but he's not moving at all. Almost all attempts to get him to move have failed, including using knock back, and restarting the server. Hope you guys can help. I'll provide any extra info as requested. *I did make sure his AI is turned on — turned it on and off a few times.

**Comment by kangarko** [comment]
I apology, this is a problem from Spigot not from Boss, because we only call the server's method to spawn the mob. The server software handles its behavior, see https://github.com/kangarko/Boss/wiki/Frequent-Questions-and-Tips#how-can-i-send-custom-messages-or-commands-when-a-boss-diesspawns
