### ISSUE TITLE
1.16.3: Ender Dragon Movement

### ISSUE THREAD

**Issue by aerulion** [kangarko/Boss#724]
Hello there,
Today i faced the same problem described in issue #723 . 
After some further investigation it turns out that the cause for the enderdragon to stay hovering is the phase in which it spawns in. Since Minecraft 1.9 the dragon always spawns in the Hover Phase, even when using vanilla commands. However this issue is fixable by executing the following command right after the dragon has spawned: 
/data modify entity @e[type=minecraft:ender_dragon,limit=1] DragonPhase set value 0
Since it is possible to set the Dragon phase via the Spigot API ( https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EnderDragon.html#setPhase(org.bukkit.entity.EnderDragon.Phase) ), would it be possible to add the option to configure the phase in which the dragon boss will spawn in?

~aerulion

**Comment by kangarko** [comment]
Thank you, going to make the dragons fly and in the future we can make such option.
