### ISSUE TITLE
Issue with boss regions

### ISSUE THREAD

**Issue by jmancox330** [kangarko/Boss#725]
Version: 1.12.2
Hello! Whenever I set 2 regions in any world other than 1 of my main worlds, It says the region is created and saved but it doesn't get saved. Please help. Thanks.

**Comment by kangarko** [comment]
Any console errors? Please post me your Boss/ as ZIP folder and tell me which regions you made.

**Comment by jmancox330** [comment]
Yeah I found out the issue. My world name had 2 words in it, with a space in between. I fixed the issue by renaming it to 1 word.
