### ISSUE TITLE
Add invisibility to the 'riding' pet

### ISSUE THREAD

**Issue by PeterDorvay** [kangarko/Boss#728]
BossTM has the amazing feature where bosses can ride on top of other mobs. I think it would be really interesting if we could make the the mob that the boss rides on invisible. This would allow for things like chickens on top of blazes, where the blaze does the damage but is invisible, so it looks like the chicken is doing the damage.

Considerations:

1) How it would benefit others? Tons more unique boss potential, all passive mobs could technically be used as bosses if they're attached to an aggressive mob.

2) What would happen if we won't implement this feature? How's your server being affected? Nothing too serious. I just thought it would be a neat idea and it would help us implement a 'Turkey' boss, but it's just a rough idea we have.

3) If suggesting something new - Can the old system be modified/improved instead? Sort of- the mob that the boss sits on top of should have a couple more customizable options. My suggestion is to make one of these options invisibility!

**Comment by kangarko** [comment]
Thank you so much!
