### ISSUE TITLE
1.16.3: Any tutorial for create bosses

### ISSUE THREAD

**Issue by RafaelPerea** [kangarko/Boss#729]
Hi i need a some help with creating bosses, i will do a dungeon with worldguard region in my minecraft server 1.16.3 but i can't do well this, no respawn naturally.

Any help or any tutorial to see this?

Thx, Rafael Perea.

**Comment by kangarko** [comment]
We dont have a tutorial right now, you can simply use /boss new then follow the instructions and play with the menus. For more specific functions, read our Wikipedia, or, if you have questions, just ask me below, or open a new ticket.
