### ISSUE TITLE
1.16.4 : My boss entity is Snowman, how do I make it attack players with snowball?

### ISSUE THREAD

**Issue by RealisticCorn** [kangarko/Boss#732]
Hello, I am trying to make a snow golem boss using the entity snow man. But snowman isn't a hostile mob towards players. So is there a way to make the boss attack players?

**Comment by kangarko** [comment]
Please see https://github.com/kangarko/Boss/wiki/Frequent-Questions-and-Tips#can-you-make-animals-aggressive--add-better-ai
