### ISSUE TITLE
1.16.4 Timed region spawning issue

### ISSUE THREAD

**Issue by AidanDickinson** [kangarko/Boss#733]
I am attempting to create a dungeon in which the boss spawns every hour and if a boss exists, another one doesn't spawn, I have attached my settings.yml and my boss's code file as .txt
[settings.txt](https://github.com/kangarko/Boss/files/5593763/settings.txt)
[ZaydietheZombie.txt](https://github.com/kangarko/Boss/files/5593764/ZaydietheZombie.txt)

 I have the timed spawn in settings.yml set to 5 seconds for testing, but once I see that it does spawn the way I want it to I will bump it up to an hour

**Comment by AidanDickinson** [comment]
on a side note, if I remove the region, my boss spawns in some loaded chunk every 5 seconds, it's just adding the region that is causing it to not spawn

**Comment by kangarko** [comment]
Looks good, what's the issues with those files? Your limit is set to 1 in that region, so there's always should be only 1 boss: https://i.imgur.com/s2KbyC8.png

**Comment by AidanDickinson** [comment]
the issue is that no bosses are spawning ever when I have it set to a region, they only spawn when I let them spawn anywhere in the world

**Comment by AidanDickinson** [comment]
I did all of that and this is the console message I am getting
![image](https://user-images.githubusercontent.com/31255513/100391503-9eaa6600-3001-11eb-9b24-f4bf4e396708.png)

**Comment by kangarko** [comment]
Your Boss is set to only spawn during "Time: 0 - 1000" which is very tiny period. I recommend you delete that key from its yml file to see if that helps.

Also remove the ´ from zaydie'sden, sometimes apostrophes cause issues.

**Comment by AidanDickinson** [comment]
I did that, and about six spawned in 30 seconds then I killed them and none have spawned since

**Comment by kangarko** [comment]
Did it still say that the boss was not within any whitelisted regions when they stopped spawning?

**Comment by AidanDickinson** [comment]
yes

**Comment by kangarko** [comment]
I apology, can you try the next version and create a Boss region with /boss region instead of WorldGuard? Send me then your new console messages, I made a change.

**Comment by AidanDickinson** [comment]
![image](https://user-images.githubusercontent.com/31255513/100779030-c587e400-33d5-11eb-860d-01161a67613b.png)
![image](https://user-images.githubusercontent.com/31255513/100779114-e6503980-33d5-11eb-9bda-fad420607764.png)
The second picture showed up a lot more, but I did the the first one once or twice, the region is restricted to a height of 82-84, so I restricted spawning conditions to that height as well.

**Comment by kangarko** [comment]
The chances that the Boss will spawn in such a tiny room are very small,  I recommend you expand this region to be taller.

**Comment by AidanDickinson** [comment]
I expanded the height of the region and waited about 2 hours, 2 spawned at some point, despite there being a limit of 1, looking at the coordinates that it keeps attempting to spawn them at, it looks like it keeps trying to spawn them on the first floor of the tower, even though the region and the boss are on the second floor

**Comment by AidanDickinson** [comment]
I just saw one spawn, I have attached the console message for when it spawned, which doesn't make much sense because it shouldn't spawn at those coordinates, but even after it did it was actually in the region, so I don't know if those coordinates even mean anything 
![image](https://user-images.githubusercontent.com/31255513/101065083-b84c3000-3562-11eb-8d85-8a6edd600e1a.png)

**Comment by kangarko** [comment]
Can you try setting Timed_Spawning.Performance.Spawn_Underground to false whether this will have an effect?

**Comment by AidanDickinson** [comment]
When I set that to false no bosses spawned

**Comment by kangarko** [comment]
I did the investigation and found out that this is a limit with our system, unfortunately I cannot change this easily without rewriting the whole thing... But I put this into our suggestions with a high priority so it will get changed whenever I have time! Thank you for your patience.
