### ISSUE TITLE
1.16.3: Spawn in regions

### ISSUE THREAD

**Issue by RafaelPerea** [kangarko/Boss#734]
I don't know how to make them respawneen within this area naturally even though I'm the players in the region, I don't quite understand why I'm Spanish
![2020-11-25_12 45 51](https://user-images.githubusercontent.com/74801655/100223991-7dbc1500-2f1c-11eb-9367-521def39e451.png)

**Comment by kangarko** [comment]
Hey!

To make a Boss only spawn in a certain region, follow these steps:

1. Create a region there using /boss region
2. Create your boss, open /boss menu -> Bosses -> Your Boss -> Spawning. Then, in "Worlds" set your spawn chance on that world to non-zero such as 20%, then go back, then click Regions -> Boss Regions and select your region you made.
3. Enable TImed_Spawning in settings.yml
