### ISSUE TITLE
1.16.4 : Disable boss attack messages

### ISSUE THREAD

**Issue by DJ3in1** [kangarko/Boss#735]
Hi, 

I keep getting messages of the boss attacking me, shooting projectile etc when I am no fighting the boss, but that it is just the boss is near. Anyway I can disable that? I looked into all the configs and didnt seem to find any configs matching that. Please let me know how may I fix that, thank you very much!

DJ

**Comment by kangarko** [comment]
Yeah thats totally normal, it is how skills work. To hide that message, set Message in your skills/ folder for those skills to [] or "none"

![a](https://i.imgur.com/hZUO4xB.png)
