### ISSUE TITLE
1.16.1: Roof Natural Spawning

### ISSUE THREAD

**Issue by RafaelPerea** [kangarko/Boss#736]
When putting a roof on top of the boss region no spawnean, I have Spawn_Underground: true

1º Image is a test
![2020-11-26_01 26 12](https://user-images.githubusercontent.com/74801655/100294263-98c36f00-2f86-11eb-86cb-b441496394a8.png)
2º When i want to respawn
![2020-11-26_01 27 05](https://user-images.githubusercontent.com/74801655/100294305-aed12f80-2f86-11eb-8216-3352f896eb86.png)

Settings.yml:
![Captura de pantalla (39)](https://user-images.githubusercontent.com/74801655/100294384-f061da80-2f86-11eb-9bd6-3e51a185bd0d.png)
![Captura de pantalla (40)](https://user-images.githubusercontent.com/74801655/100294388-f48df800-2f86-11eb-950c-020feb471902.png)

**Comment by kangarko** [comment]
Sorry this is a limitation of the algorithm, we are searching from the ground up.
