### ISSUE TITLE
1.8.8: Bosses have unlimited heatlh

### ISSUE THREAD

**Issue by StefvanderMeer** [kangarko/Boss#737]
Bosses spawned via monster eggs are sometimes unable to be killed. They regenerate health really fast for some unknown reason, it does happen with all my bosses. 

Any bosses that are left behind for a while seem to get the issue. It happens randomly to some fresh bosses as well. Sometimes one player can damage it and the other player can't. I'm really not sure what is causing the issue or how it is created. Reloading by /boss reload gets the health bugged instantly it seems, same with restarts. It also happens without doing those 2 things. No console errors.

[Boss.zip](https://github.com/kangarko/Boss/files/5603389/Boss.zip)

**Comment by kangarko** [comment]
Hey!

I have done some initial testing without finding this problem: https://ufile.io/cv9ekxw9

Please update to the next version and set Debug to [damage] in settings.yml. It should print the same messages as I was getting in my console into yours. Send me those messages when the Boss stops taking damage. Also ensure no other plugin is interfering with Boss.

**Comment by StefvanderMeer** [comment]
https://pastebin.com/CAMXjeqs

They take almost no to little damage to sharpness 5 and regen way to fast.

**Comment by kangarko** [comment]
I was able to reproduce. Just delete and recreate the boss. Seems like it has to do with some attributes or potion effects.
