### ISSUE TITLE
Boss didnt use Skills to other Players than me..

### ISSUE THREAD

**Issue by AconTM** [kangarko/Boss#74]
hey,

i have setup my first Boss and everything is fine.. But i have tested the boss by another user
and the Boss didnt use any Skill wich i set.. when i attack the boss, he use all Skills but not
in the Fight with another Players ._. What am I doing wrong? ^^

Sorry for my Bad english, i hope you understand what i mean ^^

- AconTM

**Comment by kangarko** [comment]
Hello,

please post me your Boss yml file from /bosses.

**Comment by AconTM** [comment]
https://hastebin.com/nuzewuyiwi.lua

**Comment by kangarko** [comment]
It works for me, Hades is using all its skills:

![a](https://i.imgur.com/IV1GbiJ.png)

Any console errors? What's your Minecraft version? Have you edited skills/ folders, how?

**Comment by kangarko** [comment]
Actually, Boss only uses his skills towards the targetted player (the one that he is attacking towards). Some skills such as teleport target other players as well, but all of the skills you have only target the target player.
