### ISSUE TITLE
Cave spider Bosses attacking eachother

### ISSUE THREAD

**Issue by donvdp** [kangarko/Boss#740]
Running 
- Spigot 1.16.4 PaperMC build 282
- BOSS 3.9.2
[- My other plugins are listed here](https://timings.aikar.co/?id=4e80f272f48c49a3823fdd3367e26de4#plugins)

Ive been making a custom boss out of a cave spider, but the spiders keep attacking eachother and random mobs. I thought there would be a way to get them to attack only a player, but unfortunaly that doesnt seem to be the case.

ive expected the cave spider boss to behave the same as a vanilla cave spider.

to show you what i am experiencing ive made a small film about it. This movia contains natural cave spiders (from a spawner egg) to the BOSS cave spider. 

movie: [https://youtu.be/ocgNVPBiXvc](https://youtu.be/ocgNVPBiXvc)

**Comment by kangarko** [comment]
If you have autotarget specific setting enable, ensure to disable creatures in settings.yml:
 
![a](https://i.imgur.com/X0slVuk.png)

**Comment by donvdp** [comment]
This works like a charm, thanks mate !
