### ISSUE TITLE
1.8.8: Update API

### ISSUE THREAD

**Issue by ZetaStormy** [kangarko/Boss#741]
The API changed in the latest Boss version, so I am asking for an update to use it. Can you update it, please?
Also, in the [Developer API - Importing the API](https://github.com/kangarko/Boss/wiki/Developer-API#importing-the-api) wiki page there is a typo where it says `<version>provided</version>` instead of `<scope>provided</scope>`.
![screenshot-of-typo](https://i.imgur.com/nwSegSM.png)

**Comment by kangarko** [comment]
Thanks, but Boss is open source right now, you can just compile it yourself or purchase it.
