### ISSUE TITLE
1.16.4 Could not pass event PortalCreateEventMinecraft

### ISSUE THREAD

**Issue by LucidAPs** [kangarko/Boss#748]
Console Error
https://mcpaste.io/bb99fe2f7a6a2f0f

Error Log
https://mcpaste.io/9a2505e2286c483e

Plugin Folder
[Boss.zip](https://github.com/kangarko/Boss/files/5671371/Boss.zip)

**Comment by kangarko** [comment]
Thanks, will get fixed tonight.
