### ISSUE TITLE
PunishControl refund

### ISSUE THREAD

**Issue by shyshym96** [kangarko/Boss#749]
I purchased PunishControl some months back, and I now see it has been deleted. I was wondering about getting a refund for it. My username for Spigot is shyshym96, and the email for my paypal is eamerica96@gmail.com.

**Comment by kangarko** [comment]
I did not get your money because that was not a plugin of mine, and the other developer only had a 30 day refund policy, I apology. You can contact these guys: https://github.com/Simplix-Softworks

**Comment by shyshym96** [comment]
On their github there's 3 members listed Nico, Julian Staudt, and Leonhard.
Do you by chance know which member I need to reach out to, or does it
matter? Thank you so much for taking the time to respond to me.

**Comment by kangarko** [comment]
Leonhard
