### ISSUE TITLE
Looting affecting drop rates

### ISSUE THREAD

**Issue by Kalcight** [kangarko/Boss#75]
So after alot of testing I have determined that looting increases the drop rates of the custom items. I have a armor set that is at a %1 drop chance but it seems as if it is a super high chance as it drops so often. Any way around this or do I need to switch plugins?

**Comment by kangarko** [comment]
What do you mean by looting?

**Comment by kangarko** [comment]
We use the drop chances in two ways:
1) Equipment such as helmet, chest, leggings and boots use the native Bukkit's method setDropChance, and
2) The items in the Drops menu use our own method. This cannot be overrided by any other plugin.

**Comment by kangarko** [comment]
Closing due to no reply, let me know if it still persists.
