### ISSUE TITLE
SafeRunnable event causes regular heavy tps drops

### ISSUE THREAD

**Issue by TheoRetisch1** [kangarko/Boss#754]
I have very heavy, very regular TPS drops due to the SafeRunnable event. What can be done about this?

![Lag](https://user-images.githubusercontent.com/24480321/101994348-1941d980-3cc2-11eb-8b18-48dae2fb40b1.PNG)
![Lag2](https://user-images.githubusercontent.com/24480321/101994350-1b0b9d00-3cc2-11eb-8630-4059d8158740.PNG)

Timings: https://timings.aikar.co/?id=01a1e564b26e4d47b31f21f13518e30e
Hardware: Hardware: i9-9900K + NVMe SSD
Boss 3.9.6
Settings: https://pastebin.com/DMy1r6Z7
Server version: Tuinity-"d5bb4d2" (MC: 1.16.4)

**Comment by aerulion** [comment]
After some further investigation it seems the issue started after using the '/boss reload' command, and got even worse each time the command is used: 
![1fwbtY9](https://user-images.githubusercontent.com/43320714/101994841-ed285780-3cc5-11eb-9ee9-53236f91c20f.png)

**Comment by kangarko** [comment]
Can you guys please drop me your ZIP files? I did investigate, and we stop and start new tasks upon reloading the plugin properly so it should not cause any excess load.

Also, search for Chunk_Radius in settings.yml and set this to 1. This will decrease the load when spawning monsters.

**Comment by TheoRetisch1** [comment]
The lags came from the enabled option `Iterate_Spawning_Tries` thanks for your efforts so shortly before the project enters the open source phase!
