### ISSUE TITLE
Pillager does not want to attack - 1.16.4 (paper)

### ISSUE THREAD

**Issue by Drakemlumme** [kangarko/Boss#756]
bosses pillagers do not attack, even changing weapons (I have tested spawning normal pillagers to see if they attack, and they do attack)

**Comment by DJ3in1** [comment]
Do you have AI on?

**Comment by Drakemlumme** [comment]
yes, AI is enabled.
the pillager walks normally but just doesn't attack me.
I tested it alongside other bosses, and the other bosses do attack.

**Comment by kangarko** [comment]
https://github.com/kangarko/Boss/wiki/Frequent-Questions-and-Tips#can-you-make-animals-aggressive--add-better-ai
