### ISSUE TITLE
1.12.2: How to compile from open source?

### ISSUE THREAD

**Issue by KickSquareMC** [kangarko/Boss#758]
Hi, since you made it open source I'm assuming it's meant to be compiled. How do you compile it? I tried following the 3-step guide in the README, but couldn't figure it out after 2 hours.

**Comment by kangarko** [comment]
Have you read https://github.com/kangarko/Boss#compiling ? As long as you have Foundation on your disk next to Boss and have downloaded the libraries, it should work out of the box. I am using Eclipse. Unfortunately I can't provide compiling help since my resources have been limited

**Comment by kangarko** [comment]
Just create libraries/ folder in the source and get GriefPrevention and the other binary described in pom.xml
