### ISSUE TITLE
Minecraft Version: please add

### ISSUE THREAD

**Issue by doragoma** [kangarko/Boss#762]
1) 1.12.1 | I need this system

2) I need a feature that will spawn MOBs at a specified location periodically, and when the MOB dies, it will spawn at that location a few seconds later.

**Comment by kangarko** [comment]
Thanks, please see https://github.com/kangarko/Boss/wiki/Frequent-Questions-and-Tips#can-i-spawn-bosses-individually-at-a-certain-time
