### ISSUE TITLE
1.16.2: Boss ignores worldguard child regions

### ISSUE THREAD

**Issue by GamerMedic** [kangarko/Boss#763]
The Boss doesn't spawn within the desired worldguard region.

I have a worldguard region called spawn, and within this region is my Boss arena. I have put the arena within another wg region called bossarena, so the bossarena region is inside the spawn region.

I have set mob-spawning in the spawn region to false, but the bossarena region has mob-spawning set to true and my Boss doesn't spawn. If I set mob-spawning to true on the spawn region, then my boss spawns, but this defeats the purpose of the spawn region which should be peaceful for players.

I have a similar setup in another part of my spawn region where I have a child region inside spawn and mobs are spawning as expected (regular mobs, not Boss mobs).

n.b. I have submitted as a bug because I don't believe that ignoring wg region settings was intentional, and it's something that should be corrected.

**Comment by kangarko** [comment]
Thanks, not sure if I have the capacity to fix this right now but you can possibly use /boss region system within your region and enable mob spawning using WG there globally, but then select your boss only to spawn within our own system so they wont appear outside of it.
