### ISSUE TITLE
Minecraft Version: Your Question Title

### ISSUE THREAD

**Issue by BobbyMere** [kangarko/Boss#764]
I've been waiting yrs for your map to 4.0 and the ability for mobs to not be limited by vanilla mechanics and you drop the plugin right before reaching it. This is Poetic.

Everyone: Change to Mythicmobs as it has a ton more plugin support and a huge community. I stayed here after all these years hoping his road map would come. Maybe it'll come with "Boss Red"

**Comment by kangarko** [comment]
We did not drop it: https://mineacademy.org/the-death-of-spigot

**Comment by kangarko** [comment]
There is no Boss Red
