### ISSUE TITLE
Boss Red?

### ISSUE THREAD

**Issue by BobbyMere** [kangarko/Boss#765]
Is there a "Boss Red" version to go along with Chatcontrol Red?

**Comment by kangarko** [comment]
Nope. We're not having the time capacity to rewrite Boss 3 right now.

**Comment by BobbyMere** [comment]
Oh. I was really expecting you to release the long awaited update in a new paid plugin. You know, the 4.0 you said was coming 2yrs ago and I waited around for. 

People: Move to Mythicmobs as it has a ton more plugin support and much larger community. You also don't have to worry about the developer randomly dropping support and re-releassing a 'new' version as an entirely different plugin.

He made an announcement he knew he was planning on dropping support 9 month ago but decided to inform us just a few days prior.
