### ISSUE TITLE
Plugin purchase

### ISSUE THREAD

**Issue by JLucassz** [kangarko/Boss#768]
Hello, I really liked the plugin and would like to make the purchase, but I'm not getting it, when I click on paypal error message appears, I believe that the user who will receive the money is invalid, because with the other plugins all worked normal.  I hope it is resolved, I would like to get the plugin from you.

**Comment by JLucassz** [comment]
Please, answer me, I need your plugin

**Comment by DJ3in1** [comment]
There may be issues with mc developers as paypal are blocking alot of these developers, try contacting the developer directly!

**Comment by kangarko** [comment]
We are moving away from SpigotMC, see https://mineacademy.org/the-death-of-spigotmc

More information with the download link will follow shortly.

**Comment by tiofall** [comment]
Is there any date? i'm realy anxious to use your plugin

**Comment by kangarko** [comment]
https://github.com/kangarko/Boss/releases/tag/3.9.7
