### ISSUE TITLE
Run command on death % chance and boss bar

### ISSUE THREAD

**Issue by iMxAndyy** [kangarko/Boss#77]
There is already an option to run a command when a boss dies. 
It would be nice to be able to put a drop chance on that command. 

Sorry if this is also possible but I haven't seen anything in the configs about it. 

My second suggestion is that it would be nice to have an option in the menu to toggle boss bar for each boss. So that they are much like the wither and dragon bosses in vanilla. while the boss is alive and in range a boss bar would appear on screen for any bosses with the boss bar toggled on.

**Comment by kangarko** [comment]
Thank you, merged both into roadmap.
