### ISSUE TITLE
1.8.8: How do i move the direction the giant locs when spawning?

### ISSUE THREAD

**Issue by CrashyTop** [kangarko/Boss#771]
<!---
1.8.8: How do i move the direction the giant locs when spawning?

https://prnt.sc/w7gp0w

The giant is spawning in only one direction,

**Comment by CrashyTop** [comment]
I put the description, but it gave error. Anyway, giant spawning in one direction only. how do i change this direction?

**Comment by kangarko** [comment]
Sorry that's not possible at the moment, thank you for your suggestion tho!
