### ISSUE TITLE
Monsters cannot wear equipment. Video is attached

### ISSUE THREAD

**Issue by qwe938775** [kangarko/Boss#772]
Monsters cannot wear equipment. Video is attached

https://youtu.be/cnWMoEp-o7M

Cannot be equipped after re-establishing

https://youtu.be/9goFq5y3RCc

Version: paper-1.16.4-339.jar
Java: jdk-11.0.9_windows-x64_bin
Because paper-1.16.4-339.jar only supports Java11
And I only install Boss-3.9.7.jar

**Comment by kangarko** [comment]
Update to the latest Boss. If you get any errors post them below, it should work on Java 11.

**Comment by qwe938775** [comment]
I have the latest version and use Java 11.
The same problem

**Comment by kangarko** [comment]
Make su no other plugin is interfering — copy Boss to your local test server on your computer without other plugins and test if the problem remains.

**Comment by qwe938775** [comment]
Indeed, there is only your BOSS in my plugin folder, but the problem is not solved.

**Comment by qwe938775** [comment]
He is a clean file, which may require you to test

**Comment by kangarko** [comment]
Will continue investigating tomorrow

**Comment by kangarko** [comment]
@ElBananaa can you please test this?

**Comment by ElBananaa** [comment]
> @ElBananaa can you please test this?

Sure!

> He is a clean file, which may require you to test

Hey! Could you provide the boss file please? I'll run some tests on my side with it.

**Comment by kangarko** [comment]
Thanks, will fix later today in the next version :)
