### ISSUE TITLE
1.16.4: Boss equipment still not working on Boss 3.9.8

### ISSUE THREAD

**Issue by WhatsTheBadNews** [kangarko/Boss#777]
I first noticed this issue yesterday while using version 3.9.7. I just updated to 3.9.8 and the boss I tested still is not wearing equipment that it has used in the past. I've attached a copy of my bosses folder, you can test the "Rider" boss.

[bosses.zip](https://github.com/kangarko/Boss/files/5739553/bosses.zip)

**Comment by ElBananaa** [comment]
Hey! Merry christmas! Please refer to #772 #773 and #774 
This issue will be fixed in the next update.

**Comment by WhatsTheBadNews** [comment]
> Hey! Merry christmas! Please refer to #772 #773 and #774
> This issue will be fixed in the next update.

Merry Christmas!

I have seen those issues, but I was under the impression that 3.9.8 was the "fixed version" they were referring to. Given that the description of 3.9.8 (found here: https://github.com/kangarko/Boss/releases) is "Fix | Solved bosses equipment sometimes not being placed.", I thought it would be appropriate to report back that the update did not actually fix the problem for me. If I made a mistake in reporting this, my apologies.

**Comment by ElBananaa** [comment]
> > Hey! Merry christmas! Please refer to #772 #773 and #774
> > This issue will be fixed in the next update.
> 
> Merry Christmas!
> 
> I have seen those issues, but I was under the impression that 3.9.8 was the "fixed version" they were referring to. Given that the description of 3.9.8 (found here: https://github.com/kangarko/Boss/releases) is "Fix | Solved bosses equipment sometimes not being placed.", I thought it would be appropriate to report back that the update did not actually fix the problem for me. If I made a mistake in reporting this, my apologies.

No worries, better to report the same bug several times rather than not reporting anything at all. I just wanted to inform you that the subject had already been discussed ;)

**Comment by qwe938775** [comment]
After I updated to 3.9.8, the equipment is normal

**Comment by WhatsTheBadNews** [comment]
> > > Hey! Merry christmas! Please refer to #772 #773 and #774
> > > This issue will be fixed in the next update.
> > 
> > 
> > Merry Christmas!
> > I have seen those issues, but I was under the impression that 3.9.8 was the "fixed version" they were referring to. Given that the description of 3.9.8 (found here: https://github.com/kangarko/Boss/releases) is "Fix | Solved bosses equipment sometimes not being placed.", I thought it would be appropriate to report back that the update did not actually fix the problem for me. If I made a mistake in reporting this, my apologies.
> 
> No worries, better to report the same bug several times rather than not reporting anything at all. I just wanted to inform you that the subject had already been discussed ;)
> 
> EDIT: I just tried the latest version on my own server, and it works perfectly. Are you sure that you're running the latest version?
> Could you provide more informations? (If you could also provide a video, it would be great!)

Did you test on Java 14? I believe that is what my server is using and I think it may be the cause.

And yes I confirmed I am using the latest version of Boss (3.9.8).

**Comment by LucidAPs** [comment]
I'm having the same problem.

**Comment by WhatsTheBadNews** [comment]
Update: Downgraded to Java 11 and the problem still persists for me

**Comment by ElBananaa** [comment]
> Update: Downgraded to Java 11 and the problem still persists for me

Hey! Both my test and prod servers are under java 14, I don't use boss on my prod server, but it works fine on my test server. Could you try to create a local server with only boss installed (Use your actual boss folder, not the default one), and tell me if it works there.

**Comment by WhatsTheBadNews** [comment]
> > Update: Downgraded to Java 11 and the problem still persists for me
> 
> Hey! Both my test and prod servers are under java 14, I don't use boss on my prod server, but it works fine on my test server. Could you try to create a local server with only boss installed (Use your actual boss folder, not the default one), and tell me if it works there.

Howdy, I've found what seems to cause it for me. Armor works on Tunity 175, but breaks on Tuinity 176.  I imagine one of the Paper patches broke it, as 176 was just merging upstream Paper patches. But I couldn't tell you which one. Reverting to Tuinity 175 is NOT an option for me, as it contains a massive book dupe that was recently patched in Paper.

**Comment by ElBananaa** [comment]
> > > Update: Downgraded to Java 11 and the problem still persists for me
> > 
> > 
> > Hey! Both my test and prod servers are under java 14, I don't use boss on my prod server, but it works fine on my test server. Could you try to create a local server with only boss installed (Use your actual boss folder, not the default one), and tell me if it works there.
> 
> Howdy, I've found what seems to cause it for me. Armor works on Tunity 175, but breaks on Tuinity 176. I imagine one of the Paper patches broke it, as 176 was just merging upstream Paper patches. But I couldn't tell you which one. Reverting to Tuinity 175 is NOT an option for me, as it contains a massive book dupe that was recently patched in Paper.
> 
> https://ci.codemc.io/job/Spottedleaf/job/Tuinity/

Alright. I just tried with the latest version of paper on my server (paper-345), and it works perfectly fine, so I guess this is related to Tuinity.

Try to use the plugin under paper, and let us know if it fixes the issue.

**Comment by kangarko** [comment]
Use Paper. We don 't support third party forks since I don't have the capacity to support so many distributions.
