### ISSUE TITLE
1.12.2: Bosses refuse to spawn in a covered region

### ISSUE THREAD

**Issue by MythricHD** [kangarko/Boss#778]
Version: 3.9.7  Settings: https://drive.google.com/file/d/1j-meNrxram6fOX1Mq_ORhzWT7AZt7oE0/view?usp=drivesdk

So ive created a boss that i am trying to have spawn in the bridge inside of a terraformed cave, but regardless of what settings I try to change, bosses refuse to spawn inside of this covered area. Here is an example image of the spawn location: https://i.riftmc.co/o7rw3VcllD.jpg

Things I have tried:
Restrict spawning to y120-140 where the bridge is located. 
Turned `Spawn_Underground: true`
Turn `Spawn Under Water to true`
Restrict spawns to a boss region
Restrict spawns to a wg region

Everything has failed so far. The boss only spawns on top of the cave or below it. Never inside of it. You can reproduce this by creating a platform in the air and covering the top of the platform, you will get no spawns on the covered platform.
https://i.riftmc.co/0ydUvYP2OU.png Here is a visual representation of what I explained above.

Let me know if there is something I am missing or if this is indeed a bug.

**Comment by kangarko** [comment]
Thank you. Due to our system we start looking for the underground from the bottom up, and spawn bosses on the first lowest suitable location. Therefore they will never spawn in the middle. We can add this to our bucket list for the future to change this however we're not adding new features to Boss right now.

**Comment by MythricHD** [comment]
Alright unfortunate that they cannot spawn on covered y levels. Im going to try to use spawners to force the mobs to spawn. Any way to specify spawnable blocks for the spawners so they don't just spawn them in the air or is that not a feature?

**Comment by kangarko** [comment]
Hmm not right now, when we're back to feature phase then we can add this. You can just use /boss tools then get the spawner tool to mitigate this, or setup a command block to fire /boss spawn command
