### ISSUE TITLE
Improve skills: Per-Boss customization and Minions Improvement

### ISSUE THREAD

**Issue by JTGgamer** [kangarko/Boss#78]
It would be much better if you could use bosses as minions for the minion ability as it helps to make the boss' more hard and could even be used in context. 
E.g.
King = Main boss
Minions = Guards
If you would consider this it would be great :)

**Comment by kangarko** [comment]
Currently that's far from possible due to the way how skill system work, but I am leaving this open for the future.

**Comment by kangarko** [comment]
Merged.
