### ISSUE TITLE
Compatibility with other plugin

### ISSUE THREAD

**Issue by ValouProjet** [kangarko/Boss#780]
Minecraft version : 1.15.2 spigot
Version of Boss : latest (i downloaded it 2 days ago).

Hello ! some days ago i downloaded Boss and it's a vry good plugin, so first : thanks for that.
The plugin is working super well, this is not the problem, but it prevents another plugin of mine to work and more, when i have both plugins, my server doesn't even start...

The plugin is : https://www.spigotmc.org/resources/announcer-plus-hex-rgb-placeholderapi-json-toast.81005/

I already went on their discord and this is his response :

HIM : 
The issue is with another plugin in your server
I have no idea why this other plugin is attempting to load classes from AnnouncerPlus
but that issue is on their end, not mine

ANOTHER GUY :
if it is shaded shouldn't that stop other plugins to load it from AP jar?

HIM :
yeah i have no idea wtf is going on there lol
I looked up the Boss plugin as well, and it's not using cloud or commodore

These are the logs : https://pastebin.com/626CBfDp

Thanks for your answer, have a nice day !

**Comment by kangarko** [comment]
I have no idea either, but there's nothing wrong with Boss loading that class. That class - me.lucko.commodore.Commodore - has an error that needs to be fixed. I recommend you contact lucko regarding Commodore or whatever you're using. Thanks.
