### ISSUE TITLE
1.16.3: Boss kills itself with tnt

### ISSUE THREAD

**Issue by ChopChopoo** [kangarko/Boss#782]
I've made a boss that spawns tnt very often.

The problem is that it kills itself faster than the players kill it.

Is it possible to to disable the explosion damage for the boss?

**Comment by kangarko** [comment]
Sorry but this is a logistical bug in your setup, you either need to increase the boss' health or  make the tnt spawn slower.

**Comment by ChopChopoo** [comment]
Is there any Way to make The boss unable take damage from tnt?

The tnt does not kill it instantly but over a few minutes. However, Then people Can just kill it by Running around The tnt in order to kill it without even gitring The boss.

**Comment by kangarko** [comment]
Just increase a Boss' health by then, there's no way making him ignore TNT damage right now
