### ISSUE TITLE
Minecraft Version: Issue Title

### ISSUE THREAD

**Issue by SlimeLittle** [kangarko/Boss#784]
Hello, i'm using Boss latest version on minecraft 1.16.4, my boss menu attribute cant function, when i click it the anvil become glowing and can go to the next menu like before

**Comment by kangarko** [comment]
Hey, this is the expected setup - it only can be enabled or disabled - does not it work? Which function exactly?

**Comment by SlimeLittle** [comment]
Before that I click the anvil will pop out the gui like movement speed,
multiple damage ,bonus armour etc,but now cant find already

Matej Pacan <notifications@github.com> 于 2021年1月5日周二 上午1:49写道：

**Comment by kangarko** [comment]
Check if youre on the latest Boss version, if yes let me know your MC version and ZIP me your Boss folder so I can reproduce.

**Comment by SlimeLittle** [comment]
Sry, I dont have zip app unable to compress the file and send
I download the latest version from here
https://github.com/kangarko/Boss/releases
my mc version is 1.16.4
Matej Pacan <notifications@github.com> 于2021年1月5日周二 下午11:48写道：

**Comment by kangarko** [comment]
Without your config I cannot help unfortunately. Return to me when you can send it.
