### ISSUE TITLE
Minecraft Version:1.16.4 Custom potions

### ISSUE THREAD

**Issue by tiofall** [kangarko/Boss#788]
i'm trying to apply poison to a skeleton boss, so i made this on potion skill yml:
EfeitoVeneno:
  Effects:
  - POISON 2,  5 seconds
  Delay: 5 seconds - 10 seconds
  Message:
  - Veneno ativo

Now how could i apply this specific effect to a boss?
Tnx <3

**Comment by kangarko** [comment]
Please only use the GUI menu to add potions to bosses.

**Comment by kangarko** [comment]
For now the skill potion option is limited.
