### ISSUE TITLE
Passive Mob Aggression

### ISSUE THREAD

**Issue by SlayG-TR** [kangarko/Boss#79]
Hello, recently purchased your plugin and so far I love it. That being said, I noticed that bosses made using passive mobs do not show aggression of any sort.

Is there any plan to enable this functionality in some way? I'm unsure of the logistics behind it but figured I'd ask anyway.

Thanks!

**Comment by kangarko** [comment]
Hello,

no sorry, currently we don't plan this, reason: https://github.com/kangarko/Boss/wiki/Common-Issues#can-you-make-animals-aggressive--add-better-ai
