### ISSUE TITLE
1.16.3: Why does my boss pass the limit of 1

### ISSUE THREAD

**Issue by ChopChopoo** [kangarko/Boss#794]
The boss pass the limit of 1 in the region.

However it's not very often and I have to afk for about an hour so I posting logs won't do anything.  (EDIT It spawned)

The region is  around 100x100 blocks, spawn delay = 90 seconds, world spawn chance = 10

Any idea why this happens? If not then don't worry I'll stick with this for now.

[latest.log](https://github.com/kangarko/Boss/files/5830982/latest.log)

**Comment by kangarko** [comment]
It says it can't spawn the boss in the region because there's already another one in your log or?

**Comment by ChopChopoo** [comment]
> It says it can't spawn the boss in the region because there's already another one in your log or?

It says multiple times that it spawned it anway.

ttempt to spawn FE at Choporderpvp [21, 64, -292] for TIMED
[14:51:54] [Server thread/INFO]: [spawning] 	[OK] Boss FE Spawned.
[14:51:54] [Server thread/INFO]: [spawning] Attempt to spawn FE at Choporderpvp [52, 65, -287] for TIMED

even though there was one

**Comment by kangarko** [comment]
If the spawning does not occur and you see a message that it did, it may be another plugin such as an anti-lag plugin, a config in spigot.yml or bukkit.yml or server-properties preventing or limiting monsters spawn, or even worldguard or related residence plugins.

**Comment by ChopChopoo** [comment]
> If the spawning does not occur and you see a message that it did, it may be another plugin such as an anti-lag plugin, a config in spigot.yml or bukkit.yml or server-properties preventing or limiting monsters spawn, or even worldguard or related residence plugins.

While trying to fix the problems in my new thread, the limiting of the monsters were fixed.

**Comment by kangarko** [comment]
Awesome!
