### ISSUE TITLE
Boss names

### ISSUE THREAD

**Issue by GreenMasks** [kangarko/Boss#795]
Hello, i have a suggestion and an improvement that needs to be made by one of you guys, more and more members of my team started  to fall in love with the plugin called 'levelled mobs' the bad part about this plugin is that is also changing the bosses names from BOSS, as we are all buying BOSS to create an RPG Minecraft server Levelled Mobs are also needed, so I'm suggesting if you guys could add something so the names of bosses will not be changed anymore by the plugin mentioned

**Comment by kangarko** [comment]
Thank you! Right now we're not open for new features but that's something we definitely wanna add once we get to open feature phase again in Boss
