### ISSUE TITLE
1.16.3: Not spawning. Whitelist is set & Boss is not within any whitelisted regions +  World limits applied for Vindiboos

### ISSUE THREAD

**Issue by ChopChopoo** [kangarko/Boss#799]
2) Be clear: What is your current situation, the desired situation, and your problem?
Example: I want my chat to be formatted in vanilla but not the creative world. My current situation is it is being formatted everywhere. I made sure not to use reload and haven't found any console errors. What I am doing wrong?

I want the bosses to spawn in a 100x100 (ish) area.

Yesterday it was working, but when I woke up today all the different bosses got the "Whitelist is set & Boss is not within any whitelisted regions" spawning debug message.

Trying to fix it for multiple hours didn't solve the issue so I decided to delete the plugin folder and jar and then begin from scratch.

This is what I set up

[Boss.zip](https://github.com/kangarko/Boss/files/5866058/Boss.zip)

Then I got this message:

25.01 10:37:09 [Server] INFO Not spawning. Whitelist is set & Boss is not within any whitelisted regions: {BOSS=[Vinregion], TOWNY=[], WORLD_GUARD=[], RESIDENCE=[], FACTIONS=[]}
25.01 10:37:09 [Server] INFO Conditions not met
25.01 10:37:09 [Server] INFO Can't transform
25.01 10:37:09 [Server] INFO Attempt to spawn Vindiboos at Choporderpvp [-277, 221, -146] for TIMED
25.01 10:37:09 [Server] INFO [OK] Boss Vindiboos Spawned.
25.01 10:37:09 [Server] INFO Attempt to spawn Vindiboos at Choporderpvp [-268, 225, -149] for TIMED
25.01 10:37:09 [Server] INFO Not spawning. Whitelist is set & Boss is not within any whitelisted regions: {BOSS=[Vinregion], TOWNY=[], WORLD_GUARD=[], RESIDENCE=[], FACTIONS=[]}

25.01 10:38:39 [Server] INFO Not spawning. World Choporderpvp has 80% of spawning boss. Should spawn? false
25.01 10:38:39 [Server] INFO World limits applied for Vindiboos
25.01 10:38:39 [Server] INFO Can't transform

Only one mob has spawned and then I get the World limits applied for Vindiboos?

I'll pay you if you help me fix these problems

EDIT:

I made another region somewhere else and they spawn without problems.

25.01 11:20:39 [Server] INFO Attempt to spawn Vindiboos at Choporderpvp [32, 64, -276] for TIMED
25.01 11:20:39 [Server] INFO [OK] Boss Vindiboos Spawned.
25.01 11:20:39 [Server] INFO Attempt to spawn Vindiboos at Choporderpvp [18, 63, -293] for TIMED
25.01 11:20:39 [Server] INFO [OK] Boss Vindiboos Spawned.
25.01 11:20:39 [Server] INFO Attempt to spawn Vindiboos at Choporderpvp [27, 64, -281] for TIMED
25.01 11:20:39 [Server] INFO [OK] Boss Vindiboos Spawned.
25.01 11:21:00 [Server] INFO CONSOLE issued server command: /list 

Why is that?

The region is ca. the same size, same world, only a few hundred blocks away from each other.

EDIT:

Few minutes later and I get these messages again but once in a while they do spawn.

25.01 11:23:39 [Server] INFO Attempt to spawn Vindiboos at Choporderpvp [63, 71, -275] for TIMED
25.01 11:23:39 [Server] INFO Not spawning. Whitelist is set & Boss is not within any whitelisted regions: {BOSS=[Omod], TOWNY=[], WORLD_GUARD=[], RESIDENCE=[], FACTIONS=[]}
25.01 11:23:39 [Server] INFO Conditions not met
25.01 11:23:39 [Server] INFO Can't transform
25.01 11:23:39 [Server] INFO Attempt to spawn Vindiboos at Choporderpvp [45, 64, -313] for TIMED
25.01 11:23:39 [Server] INFO Not spawning. Whitelist is set & Boss is not within any whitelisted regions: {BOSS=[Omod], TOWNY=[], WORLD_GUARD=[], RESIDENCE=[], FACTIONS=[]}

How do I fix this?

**Comment by kangarko** [comment]
It seems natural, Boss is probably looking for the location above or below that region 3D area, and once it hits valid Y coordinates it spawns them. You can increase spawning intensity to mitigate this
