### ISSUE TITLE
[Suggestion] Hostile passive mobs

### ISSUE THREAD

**Issue by LogGits** [kangarko/Boss#8]
Can you make it so passive mobs become hostile and we can make custom bosses out of passive mobs? We want to use a baby cow as a mob boss it would be an awesome addition :)

**Comment by kangarko** [comment]
I would love to! However, this requires digging inside NMS and other nasty stuff which breaks each MC release and I have no experience it in. I may look forward into it in the future.

**Comment by LogGits** [comment]
What about horses? Also I found this interesting source: https://www.spigotmc.org/threads/tutorial-creating-custom-entities-with-pathfindergoals.18519/#post-193576 that may become useful if you were to add the feature in 🙂

**Comment by kangarko** [comment]
Hello,

thank you. Yes I am aware of that you can edit NMS to add custom AI but, this breaks each release and tends to lower stability as the server is obfuscated we can only guess what means what (unless someone else has tested it before hand).

**Comment by MrHumblePie** [comment]
Would absolutely love passive-aggresive (lol) mobs to be a thing.
