### ISSUE TITLE
1.16.5 Bosses seem to no longer convert.

### ISSUE THREAD

**Issue by SoraShiunin** [kangarko/Boss#802]
I'm not sure what happened, but bosses seem to no longer spawn and/or convert naturally.
All that changed was me changing server hosts and changed a few server files like server.properties, migrated the plugins and everything in it to new host.

Spawning debug with only me on the server, inside the "Haven" region, spawning zombies via spawner(Removed from ignore).

28.01 23:05:30 [Server] Server thread/INFO Attempt to spawn havenzombie at world [-541, 32, 4179] for CONVERTED
28.01 23:05:30 [Server] Server thread/INFO Not spawning. Whitelist is set & Boss is not within any whitelisted regions: {BOSS=[haven], TOWNY=[], WORLD_GUARD=[], RESIDENCE=[], FACTIONS=[]}
28.01 23:05:30 [Server] Server thread/INFO Conditions not met
28.01 23:05:30 [Server] Server thread/INFO Can't transform`

Boss plugin folder:
[Boss.zip](https://github.com/kangarko/Boss/files/5890258/Boss.zip)

**Comment by kangarko** [comment]
Hey, seems like Converting is adopting the "Haven" region condition, meaning they possibly won't convert outside of it — try removing that. However I am not sure, if you haven't touched Boss then may as well be something you did in the migration process.

**Comment by kangarko** [comment]
I wish you best of luck getting this resolved!

**Comment by SoraShiunin** [comment]
> I wish you best of luck getting this resolved!

Ok I think I figured it out. I looked at other issues, and haven is a huge region. I guess I have the same issue of them only spawning on the bottom. Thanks for replying.

**Comment by SoraShiunin** [comment]
Ok I did some testing and turns out, bosses stop converting on a region after a server restart. No matter how small or where the region is.

**Comment by kangarko** [comment]
Does it still say the same when it stops spawning as in your initial log?
