### ISSUE TITLE
1.8.8 : String for other plugins with bosses!

### ISSUE THREAD

**Issue by Whxtealex** [kangarko/Boss#803]
Hey i wanted to ask what the string is to give someone the boss over an Loot box for example in the config: boss egg Example %user%,%player% both of them Doesn't work in the Console it says: BOSS // Player %user% is not online! 
So that was my question i hope you guys can help me!

**Comment by kangarko** [comment]
Try {player} but I am not sure we support that

**Comment by Whxtealex** [comment]
Didn't worked are you going to add that in the future?

**Comment by kangarko** [comment]
Possibly, thanks for suggesting. However right now I m the only dev for all plugins so I had to put most on maintenance-only
