### ISSUE TITLE
Minecraft Version: Paper 443 [1.16.5]

### ISSUE THREAD

**Issue by Vehzx** [kangarko/Boss#804]
[Boss.zip](https://github.com/kangarko/Boss/files/5899001/Boss.zip)
1) Minecraft Version: 1.16.5
    Paper-443

2) So i'm trying to used the timed spawning feature along with region spawning to create boss rooms. As an example, in spawn i would have a portal leading to a boss room, and enclosed area where the boss would be spawned (through timed spawning, and limit to 1 in that region so multiple of the same boss do not spawn).

My issue is, if I have the boss only spawn through a worldguard region, and the boss room is not a square, then sometimes the boss will spawn outside of the room, as an example, lets say the boss room is a sphere, the worldguard region is a square, so the boss sometimes spawns ontop of the sphere (outside of the boss room). To try combat this, I enabled both the boss and worldguard region in the boss settings, and set both of their spawn limits to 1.

Now the boss just won't spawn through timed spawning, for testing purposes I made the timer 10 seconds, yet the boss does not spawn, however when I remove the regions from the boss in the menu for the boss, the timed spawner then works but spawns the bosses randomly throughout the world.

I believe this is just the timed spawner not working when both the boss regions and worldguard regions are selected, because I can still spawn the boss with an egg in the boss room when it is not working.

3) I attached my boss folder.

**Comment by kangarko** [comment]
Hey, I recommend you either use Boss spawners (aka physical spawner item) or check our Wiki for alternative ways to spawn a boss, because Timed Spawning will necessarily limit your spawning as you've seen in your case.
