### ISSUE TITLE
1.16.4 - Bosses not naturally spawning

### ISSUE THREAD

**Issue by bsamemes** [kangarko/Boss#809]
Using latest Paper 1.16.4 Server

Can't seem to get bosses to naturally spawn. I've tried toggling a bunch of different settings and used the guide in [the Wiki](https://github.com/kangarko/Boss/wiki/Common-Issues) and it still doesn't seem to work.

I've attached the settings & boss yml for review. 
[settings.txt](https://github.com/kangarko/Boss/files/5915391/settings.txt)
[ice.txt](https://github.com/kangarko/Boss/files/5915394/ice.txt)

**Comment by kangarko** [comment]
You've set your boss only to appear in your "Boss" region, disable that in your menu > spawning > regions and then he will spawn everywhere else.
