### ISSUE TITLE
Error while creating new boss

### ISSUE THREAD

**Issue by Myron0345** [kangarko/Boss#81]
**UPDATE: NEXT TIME I HAVE TO LOOK BETTER, IT WAS MY SERVER VERSION. I FIXED IT. 1.8 DOESNT WORK THOUGH**

**CONSOLE:**
I get this error when i do /b new test BLAZE. Then the plugin disables.

53:40 INFO]: Myron0345 issued server command: /b new
53:48 INFO]: Myron0345 issued server command: /b new test BLAZE
53:48 INFO]: BOSS // Created default file: test.yml
53:48 INFO]: BOSS // A new Boss was successfully installed: test
53:48 INFO]: BOSS // Boss 1.6.3 encountered a NoSuchMethodException! Please
k your error.log and report this issue with the information in that file.
53:48 WARN]: java.lang.ExceptionInInitializerError
53:48 WARN]:        at me.kangarko.boss.final. .a.<init>(SourceFile:25)
53:48 WARN]:        at me.kangarko.boss.final. .aUx.protected(SourceFile:85)

53:48 WARN]:        at me.kangarko.boss.final. .Con.CoM8(SourceFile:312)
53:48 WARN]:        at me.kangarko.boss.final. .Con.getHealth(SourceFile:308

53:48 WARN]:        at me.kangarko.boss.final. .Con.short(SourceFile:158)
53:48 WARN]:        at me.kangarko.boss.final. .Con.protected(SourceFile:96)

53:48 WARN]:        at me.kangarko.boss.final. .aUx.<init>(SourceFile:62)
53:48 WARN]:        at me.kangarko.boss.final. .aUx.protected(SourceFile:70)

53:48 WARN]:        at me.kangarko.boss.final. .aM.protected(SourceFile:81)
53:48 WARN]:        at me.kangarko.boss.command.NewCommand.handleSubCommand(
ceFile:46)
53:48 WARN]:        at me.kangarko.boss.final. .com4.handleCommand(SourceFil
2)
53:48 WARN]:        at me.kangarko.boss.final. .CoM3.onCommand(SourceFile:57

53:48 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginComman
va:44)
53:48 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCo
dMap.java:141)
53:48 WARN]:        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCo
d(CraftServer.java:646)
53:48 WARN]:        at net.minecraft.server.v1_8_R1.PlayerConnection.handleC
nd(PlayerConnection.java:1115)
53:48 WARN]:        at net.minecraft.server.v1_8_R1.PlayerConnection.a(Playe
nection.java:950)
53:48 WARN]:        at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(Packe
yInChat.java:26)
53:48 WARN]:        at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(Packe
yInChat.java:53)
53:48 WARN]:        at net.minecraft.server.v1_8_R1.PacketHandleTask.run(Sou
ile:13)
53:48 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(U
wn Source)
53:48 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
53:48 WARN]:        at net.minecraft.server.v1_8_R1.MinecraftServer.z(Minecr
erver.java:696)
53:48 WARN]:        at net.minecraft.server.v1_8_R1.DedicatedServer.z(Dedica
erver.java:316)
53:48 WARN]:        at net.minecraft.server.v1_8_R1.MinecraftServer.y(Minecr
erver.java:634)
53:48 WARN]:        at net.minecraft.server.v1_8_R1.MinecraftServer.run(Mine
tServer.java:537)
53:48 WARN]:        at java.lang.Thread.run(Unknown Source)
53:48 WARN]: Caused by: me.kangarko.boss.final. .com9: Report / java.lang.No
MethodException: org.bukkit.craftbukkit.v1_8_R1.CraftWorld.createEntity(org.
it.Location, java.lang.Class)
53:48 WARN]:        at me.kangarko.boss.final. .LPT9.<clinit>(SourceFile:109

53:48 WARN]:        ... 27 more
53:48 WARN]: Caused by: java.lang.NoSuchMethodException: org.bukkit.craftbuk
v1_8_R1.CraftWorld.createEntity(org.bukkit.Location, java.lang.Class)
53:48 WARN]:        at java.lang.Class.getDeclaredMethod(Unknown Source)
53:48 WARN]:        at me.kangarko.boss.final. .LPT9.<clinit>(SourceFile:96)

53:48 WARN]:        ... 27 more
53:48 INFO]: BOSS // *-----------------------------------------------*
53:48 INFO]: BOSS //  Failed to setup reflection!
53:48 INFO]: BOSS //  MC version: v1_8
53:48 INFO]: BOSS //  Plugin is now disabled.
53:48 INFO]: BOSS // *-----------------------------------------------*
53:48 INFO]: [Boss] Disabling Boss v1.6.3
53:48 WARN]: java.lang.NoClassDefFoundError: Could not initialize class me.k
rko.boss.final. .LPT9
53:48 WARN]:        at me.kangarko.boss.final. .a.transient(SourceFile:47)
53:48 WARN]:        at me.kangarko.boss.final. .a.<init>(SourceFile:32)
53:48 WARN]:        at me.kangarko.boss.final. .aUx.protected(SourceFile:85)

53:48 WARN]:        at me.kangarko.boss.final. .Con.CoM8(SourceFile:312)
53:48 WARN]:        at me.kangarko.boss.final. .Con.getHealth(SourceFile:308

53:48 WARN]:        at me.kangarko.boss.final. .Con.short(SourceFile:158)
53:48 WARN]:        at me.kangarko.boss.final. .Con.protected(SourceFile:96)

53:48 WARN]:        at me.kangarko.boss.final. .aUx.<init>(SourceFile:62)
53:48 WARN]:        at me.kangarko.boss.final. .aUx.protected(SourceFile:70)

53:48 WARN]:        at me.kangarko.boss.final. .aM.protected(SourceFile:81)
53:48 WARN]:        at me.kangarko.boss.command.NewCommand.handleSubCommand(
ceFile:46)
53:48 WARN]:        at me.kangarko.boss.final. .com4.handleCommand(SourceFil
2)
53:48 WARN]:        at me.kangarko.boss.final. .CoM3.onCommand(SourceFile:57

53:48 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginComman
va:44)
53:48 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCo
dMap.java:141)
53:48 WARN]:        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCo
d(CraftServer.java:646)
53:48 WARN]:        at net.minecraft.server.v1_8_R1.PlayerConnection.handleC
nd(PlayerConnection.java:1115)
53:48 WARN]:        at net.minecraft.server.v1_8_R1.PlayerConnection.a(Playe
nection.java:950)
53:48 WARN]:        at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(Packe
yInChat.java:26)
53:48 WARN]:        at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(Packe
yInChat.java:53)
53:48 WARN]:        at net.minecraft.server.v1_8_R1.PacketHandleTask.run(Sou
ile:13)
53:48 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(U
wn Source)
53:48 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
53:48 WARN]:        at net.minecraft.server.v1_8_R1.MinecraftServer.z(Minecr
erver.java:696)
53:48 WARN]:        at net.minecraft.server.v1_8_R1.DedicatedServer.z(Dedica
erver.java:316)
53:48 WARN]:        at net.minecraft.server.v1_8_R1.MinecraftServer.y(Minecr
erver.java:634)
53:48 WARN]:        at net.minecraft.server.v1_8_R1.MinecraftServer.run(Mine
tServer.java:537)
53:48 WARN]:        at java.lang.Thread.run(Unknown Source)
53:50 INFO]: Myron0345 issued server command: /pl

**Comment by kangarko** [comment]
Do you use CraftBukkit, Spigot, PaperSpigot or TacoSpigot? I tested under TacoSpigot 1.8.8 and went without issues. You can test TacoSpigot from here: https://expirebox.com/download/8525d6c768747620eb7378d22013fcad.html.  All plugins should be compatible.

**Comment by kangarko** [comment]
Closing due to no reply, feel free to comment below if you still have issues.
