### ISSUE TITLE
1.16.3: Issues compiling the project after importing

### ISSUE THREAD

**Issue by ChopChopoo** [kangarko/Boss#810]
Are Heroes and GriefPrevention dependencies of the boss plugin?

Seeing as how Heroes costs $20, I tried building the Maven Project after removing that dependency from the pom.xml as well as grief prevention. That didn't fix the issue though and I still got errors relating to those plugins. I'm not sure how to build the Boss plugin without those dependencies.

How do I fix this?

**Comment by kangarko** [comment]
Sorry I don't have time providing compiling help

Try compiling Foundation library on your disk in the same folder where you have Boss and remove that dependency from there too
