### ISSUE TITLE
Support for Multiverse Core

### ISSUE THREAD

**Issue by Bipedfriend173** [kangarko/Boss#811]
I use the multiverse-core plugin (it creates more worlds) I use it for my boss world but sadly this plugin doesn't work with this world plugin, I would love if you added support for it!

**Comment by kangarko** [comment]
What do you mean by "it doesnt work"?

**Comment by kangarko** [comment]
I think you communicated this via email so I just replied over there

**Comment by Bipedfriend173** [comment]
The bosses wont spawn in the world

**Comment by kangarko** [comment]
Check your multiverse settings if you allowed monster spawning and read our Wiki guide on troubleshooting this
