### ISSUE TITLE
Boss timer

### ISSUE THREAD

**Issue by MystiCub** [kangarko/Boss#812]
Hi,
I want to suggest the following which would be very useful for some mechanics.

You could add a specific time for a "Boss" to appear and if one player hasn't killed him yet, another doesn't appear until someone manages to kill him.

Thanks!

**Comment by kangarko** [comment]
Thanks, for now you can see alternative approaches outlined at: https://github.com/kangarko/Boss/wiki/Frequent-Questions-and-Tips
