### ISSUE TITLE
Minecraft Version: Paper 1.12.2

### ISSUE THREAD

**Issue by khoiangel** [kangarko/Boss#813]
05.02 19:10:57 [Server] ERROR Could not pass event PortalCreateEvent to Boss v3.9.7
05.02 19:10:57 [Server] INFO java.lang.NoSuchMethodError: org.bukkit.event.world.PortalCreateEvent.getEntity()Lorg/bukkit/entity/Entity;
05.02 19:10:57 [Server] INFO at org.mineacademy.boss.listener.EntityListener.onPortal(EntityListener.java:330) ~[?:?]
05.02 19:10:57 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor450.execute(Unknown Source) ~[?:?]
05.02 19:10:57 [Server] INFO at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1618]
05.02 19:10:57 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1618]
05.02 19:10:57 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1618]
05.02 19:10:57 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.12.2.jar:git-Paper-1618]
05.02 19:10:57 [Server] INFO at net.minecraft.server.v1_12_R1.BlockPortal$Shape.createPortal(BlockPortal.java:377) ~[patched_1.12.2.jar:git-Paper-1618]
05.02 19:10:57 [Server] INFO at net.minecraft.server.v1_12_R1.BlockPortal.b(BlockPortal.java:78) ~[patched_1.12.2.jar:git-Paper-1618]
05.02 19:10:57 [Server] INFO at net.minecraft.server.v1_12_R1.BlockFire.onPlace(BlockFire.java:330) ~[patched_1.12.2.jar:git-Paper-1618]
05.02 19:10:57 [Server] INFO at net.minecraft.server.v1_12_R1.ItemStack.placeItem(ItemStack.java:277) ~[patched_1.12.2.jar:git-Paper-1618]
05.02 19:10:57 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:551) ~[patched_1.12.2.jar:git-Paper-1618]
05.02 19:10:57 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1011) ~[patched_1.12.2.jar:git-Paper-1618]
05.02 19:10:57 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[patched_1.12.2.jar:git-Paper-1618]
05.02 19:10:57 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.12.2.jar:git-Paper-1618]
05.02 19:10:57 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1618]
05.02 19:10:57 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_272]
05.02 19:10:57 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_272]
05.02 19:10:57 [Server] INFO at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[patched_1.12.2.jar:git-Paper-1618]
05.02 19:10:57 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[patched_1.12.2.jar:git-Paper-1618]
05.02 19:10:57 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
05.02 19:10:57 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1618]
05.02 19:10:57 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1618]
05.02 19:10:57 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_272]

**Comment by kangarko** [comment]
Thanks, will be fixed. Make sure you updated from GitHub > Releases then.
