### ISSUE TITLE
1.16.5: Plugin isn't still used and HAS THE MOST PERFORMANCE EFFECT

### ISSUE THREAD

**Issue by bobhenl** [kangarko/Boss#815]
Hi, I still don't use boss, we were still in phase that we're trying to make bosses, but it's still not done and they aren't spawning anywhere... but BOSS is one of the most difficult plugins for performance. https://timings.aikar.co/?id=6dcecedba6534f87998424bce4dd5d9d#plugins

any idea why?
[Boss.zip](https://github.com/kangarko/Boss/files/5951227/Boss.zip)

**Comment by kangarko** [comment]
Timings don't like how we combined every single task in Boss into a SafeRunnable, that basically means there's tons of tasks but Timings groups them as one.

Unless there's a real lag on your server we have no experience with this being a problem.

Also there's tons of documentation on optimizing Boss in the wikipedia. Best of luck!

Matej

**Comment by bobhenl** [comment]
Is it really ok?
![image](https://user-images.githubusercontent.com/18662086/108751888-188bb600-7543-11eb-8acf-910e569c5f82.png)

https://spark.lucko.me/#fy5sZjkHGG
https://timings.aikar.co/?id=a4a582ba31ee4bed81a8e890c80d8954#plugins

**Comment by kangarko** [comment]
Yes.

Because timings is not smart enough here, our SafeRunnable is the collection of multiple runnables.

If you count

SpecializedCrates + MetricsBase + SensibleToolboxPlugin you get 3 + 2 + 2 = 7%.... that is 2X more than our runnable and that is exactly what is going on.
