### ISSUE TITLE
Paper 1.16.4: Boss don't spawn in regions of /boss region or another regions

### ISSUE THREAD

**Issue by JXAKO** [kangarko/Boss#817]
Hello, what I want to do is that a boss named "CreeperNinjaNv1" spawn in a boss region named "cuevaspolvorientas" in the world "farmisland0", but doesn't spawn, I already have the option of spawning in the worlds "farmisland0" at 100%, and even if not spawn not one, am I doing something wrong? the world is in difficulty hard and I want spawn on any level of light. the region is a cave created and covered. I tried to create a worldguard region and that spawn in that region and neither. thank you
PS: I don’t speak English

[Boss.zip](https://github.com/kangarko/Boss/files/5962233/Boss.zip)

![image](https://user-images.githubusercontent.com/78884510/107584910-0a9d7300-6bdc-11eb-833e-210aa6b307c6.png)

![image](https://user-images.githubusercontent.com/78884510/107584873-01aca180-6bdc-11eb-9027-c7558f38ba26.png)

![image](https://user-images.githubusercontent.com/78884510/107584860-fb1e2a00-6bdb-11eb-85df-d25d3f6ea5e6.png)

![image](https://user-images.githubusercontent.com/78884510/107585708-7af8c400-6bdd-11eb-811e-142a0ed9a0bc.png)

![image](https://user-images.githubusercontent.com/78884510/107584754-cb6f2200-6bdb-11eb-8c76-c3221a179633.png)

![image](https://user-images.githubusercontent.com/78884510/107584673-a67aaf00-6bdb-11eb-9f1e-a5d4930f9eea.png)

**Comment by C00kiemax** [comment]
Are there also some other WorldGuard Regions?
You can check that with leather clicking on the ground or lookup your WorldGuard Regions with /rg list

**Comment by JXAKO** [comment]
still doesn't work, and i have no world guard region in that world

**Comment by kangarko** [comment]
You can use a solution proposed here: https://github.com/kangarko/Boss/wiki/Frequent-Questions-and-Tips#is-it-possible-to-let-bosses-spawn-if-you-enter-a-region
