### ISSUE TITLE
Boss specific spawning

### ISSUE THREAD

**Issue by ZappySK** [kangarko/Boss#818]
Hey guys, i created boss, and i want to set the spawning time like when someone kill the boss, that the boss spawn after 2 days.. so if i kill boss, the same boss spawns after 2 days after kill.. how can i get this? I will be happy for help, have a nice day ;)

**Comment by kangarko** [comment]
Hey,

Please see: https://github.com/kangarko/Boss/wiki/Frequent-Questions-and-Tips#can-i-spawn-bosses-individually-at-a-certain-time

**Comment by ZappySK** [comment]
okay thank you, and how to to run my own command on boss spawn? i set to this and after spawn it types in console "Unknown command" but if i use command via player, the command works
![image](https://user-images.githubusercontent.com/76651966/107974852-7c4c3700-6fb7-11eb-8636-a3dbe652d20b.png)

**Comment by kangarko** [comment]
Try removing the initial / from the command... or simply the /boss-spawn-tier1 command does not exist
