### ISSUE TITLE
Questions to BOSS Plugin

### ISSUE THREAD

**Issue by C00kiemax** [kangarko/Boss#820]
I play Minecraft in the Version 1.16.2 and I have 3 Questions to the Plugin

1. 
Can you set a boss to appear when a player enters a WorldGuard region and a second boss to spawn only after the first has been defeated?
2. 
Can you set that the boss cannot leave a certain region?
3. 
When I wanted to buy the plugin, it didn't work.
https://prnt.sc/ze7azx

I would be happy to hear from you soon

**Comment by kangarko** [comment]
To spawn only when entering regions, see https://github.com/kangarko/Boss/wiki/Frequent-Questions-and-Tips#is-it-possible-to-let-bosses-spawn-if-you-enter-a-region

To get boss, read https://github.com/kangarko/Boss/issues/776

**Comment by C00kiemax** [comment]
Okay thank you very much, but what can i do now because of my third problem?
