### ISSUE TITLE
1.16.4: Does Boss Have A Spawner Feature?

### ISSUE THREAD

**Issue by IAmOrion15** [kangarko/Boss#821]
So my question is kind of simple but I didn’t find the answer anywhere. Does Boss have a spawner feature like mythic mobs does? I know you can get spawn eggs but I’d like to use spawners for my dungeons.

**Comment by kangarko** [comment]
Yes you can use /boss egg to get a Boss Spawn egg or /boss tools to obtain a spawner block that will spawn your boss. Also see Common Questions in the wiki for additional options.
