### ISSUE TITLE
Boss attack

### ISSUE THREAD

**Issue by ZappySK** [kangarko/Boss#822]
Hey, on the photo you can view, that there is barrier betweeen arena with boss and the safe spot, when i am behind the barrier, i can get pull up to the air and get poitions from boss, but i am behind barrier, how can I disable this? Please help me, i have no idea.. thank you
![image](https://user-images.githubusercontent.com/76651966/108274555-579dbe00-7175-11eb-9362-3bf920d546eb.png)

**Comment by ZappySK** [comment]
![image](https://user-images.githubusercontent.com/76651966/108274662-7ac86d80-7175-11eb-9fe9-6be3603fe6a1.png)

**Comment by DJ3in1** [comment]
The bosses attack players in a radius, and blocks don't really stop them from doing that, maybe try turning the follow radius to a little bit smaller? Im not sure if there are other ways to fix this!

**Comment by kangarko** [comment]
Yeah that seems like something in control of the pathfinder from native MC server, we do not manipulate a Boss behavior.

If you are talking about skills, then unfortunately these won't check if the distance contains an invisible wall.

**Comment by ZappySK** [comment]
So what i need to do?

**Comment by kangarko** [comment]
Možno by si mohol vytvoriť dvojitú bariéru. Tým pádom by vznikol vnútorný okruh, ako brzda pred tým, žeby Boss zaregistroval hráča v okolí. Alebo môžeš znížiť radius v danom skille.
