### ISSUE TITLE
1.16.5 Paper : Boss not being able to spawn in World Guard regions

### ISSUE THREAD

**Issue by DJ3in1** [kangarko/Boss#823]
Hi,

I have made a region overlapping another region, but I set the priority so this smaller region can spawn mobs. Normal mobs are spawning fine but I cannot spawn any bosses, it says unable to spawn boss in this location!

Please help!

Thanks alot

**Comment by kangarko** [comment]
That boss message indicated that WorldGuard is still blocking the spawn. Try disabling the two options Check_Regions in settings.yml to see if that helps, if not then find that flag blocking it in WorldGuard and see our troubleshooting guide along with Common Issues on the Wiki, best of luck! :)
