### ISSUE TITLE
1.8.8 : BossSpawningRegion

### ISSUE THREAD

**Issue by SAC2COURSE** [kangarko/Boss#825]
Hi sry for my english i'm french , i create boss region for make spawn my boss , i create a boss region but i never see on spawn (all chance paramaeter = 100%)
then i create a worldguard region (plugin detected) but still no boss, other vanilla mob still spawn in the same area 
no error in my console, same in the plugin folder no error, please HELP ME
[Boss.zip](https://github.com/kangarko/Boss/files/6012693/Boss.zip)
 
ps: ur plugin is amazing.

Thank you.

**Comment by kangarko** [comment]
Which Boss is not spawning in regions?

**Comment by Wazored** [comment]
I have the same problem. 


[Boss.zip](https://github.com/kangarko/Boss/files/6026632/Boss.zip)

**Comment by SAC2COURSE** [comment]
Spiderminion, but the vanilla spider spawn as spiderminion

**Comment by kangarko** [comment]
So sorry for this taking way too long!

I had opened your file and found that you had Biomes set for:

  Biomes:
    SAVANNA: 100%
    SAVANNA_MOUNTAINS: 100%
    SAVANNA_PLATEAU_MOUNTAINS: 100%
    SAVANNA_PLATEAU: 100%

And you had the WorldGuard Region set to spawnspider with 50% chance.

That means your Boss would only spawn in those biomes and nowhere else even if they are in that biome. Reset your biomes.
