### ISSUE TITLE
1.16.4 A Few Questions

### ISSUE THREAD

**Issue by IAmOrion15** [kangarko/Boss#830]
Hello! I have a few questions about the plugin!
1. Is there is limit to how many bosses you can make in the GUI? 
2. Is there a way to prevent stuff like piglins turning into zombified piglins? Or enderman from teleporting.
3. Is there a way to limit how many bosses a spawner can have? For example, it won’t spawn another boss if 2 are already alive in its range.
4. Will there be 1.17 support for the warden mob and glow squids?

Thank you for your time!

**Comment by kangarko** [comment]
Hello!

1. No
2. Hmm you can disable their AI in Attributes or Specific Settings section that would probably get the job done.
3. Yes in the recent MC versions a spawner should have that option if you open a spawner's GUI.
4. Yes as long as they use the standard Spigot way of spawning which is 99.9% chance they will.

Thanks and wishing you all the best!
Matej
