### ISSUE TITLE
Boss to Switch Hand Items

### ISSUE THREAD

**Issue by BlackGamer000** [kangarko/Boss#84]
Boss Inventory Extension

Good evening! I think this proposal is very interesting, I will now talk about it in the Specific.

Practically in the Day, while I was preparing a boss for the Events I was thinking of the additions within the armor's setup // Boss's sword, then in Substance ... I wanted to ask if it would be possible to add the following things:

1) Adding the possibility of Making the armor and the Sword switch to the Boss, So if it has a sword and also an Arch can change the latter randomly.

2) Adding the possibility that the boss can drink the potions (always settable from the Armor)

The proposals are simple and short but quite nice.

Goodbye and thanks ;)

Small Note: Will there be a reopening of the Discord Server? Ah and ... I apologize for this uncomfortable question :c

**Comment by kangarko** [comment]
Hello,

1. What do you mean? Are you suggesting that the Boss should switch its item in its hand randomly?

2. Sorry that's not possible on the server, but, you can give Boss permanent potion effects or simply spawn a Witch Boss.

I am not planning to reopen Discord at the moment.

**Comment by BlackGamer000** [comment]
Hello, Thanks for the Response

Let me explain better. 

Basically the Boss will be able to change weapons such as Bow, Sword, Other and Even the armor, This can be set via an Inventory like that of Default Users.

2) Ah, ok Thanks c:

3) Okay, Thanks for The Response c:

**Comment by kangarko** [comment]
Great, I understand, I am leaving this open to add it in the future 🚀

**Comment by kangarko** [comment]
This issue has been moved to roadmap.
