### ISSUE TITLE
1.16.5 Command Help

### ISSUE THREAD

**Issue by masosoup52** [kangarko/Boss#844]
The command /boss egg wont work when I put it in another config. My first thought would be the place holder for the player name in the other pluings but im not sure. Im using cloud crates, and for the command I type in boss egg Emp %player% 1. This results in nothing being given to me in my inventory.

**Comment by kangarko** [comment]
Sorry this is unsupported, perhaps try using {player} instead of %player% but we cannot guarantee how other plugins will interact with BOSS
