### ISSUE TITLE
1.12.2: Invincible Bosses

### ISSUE THREAD

**Issue by MythricHD** [kangarko/Boss#846]
Version 3.9.9

https://i.riftmc.co/UrixGjZapy.png
https://i.riftmc.co/DAO3T0r0mV.png

 As you can see sometimes a boss will spawn and players are unable to kill the boss but it will still attack them. We tried throwing harming potions on it but it was still invincible to the effect. This happens randomly for different bosses throughout the world, its not easily replicable but after a few spawns it will happen.

We use the boss API to spawn the mobs if that could have any effect but besides that everything is pretty normal for the bosses.

**Comment by kangarko** [comment]
If you are accessing Boss programatically, check its health by calling getHealth for the Boss' entity. Then check if the Boss has any conflicting attributes or even the isInvulnerable flag. I am afraid this is coming from an external source not Boss plugin itself, at least if not configured that way.
