### ISSUE TITLE
Option for despawn?

### ISSUE THREAD

**Issue by SoraShiunin** [kangarko/Boss#85]
As of the last update(1.6.5) the despawn rate changed, I'm using natural spawns for a couple of bosses at a 1-3% chance of spawning and the server just fills up with bosses pretty much everywhere before any actually despawn.

**Comment by kangarko** [comment]
Hello,

you're right, there is no despawn rate since that release. The despawn was actually a mistake and Bosses are persistant. You can use individual or global limits or limit your Bosses per region to limit their amount.
