### ISSUE TITLE
1.16.5 - Chance to spawn mob and turn off lightning

### ISSUE THREAD

**Issue by NewJeb** [kangarko/Boss#851]
First of all, I wanted to say thank you for the wonderful plug-in, I have never met a better plug-in for bosses and I am very grateful for the fact that it also became free! I have such a question, is it possible to somehow make the chance of a mob spawning less than 1 percent, but not 0. I tried to put a decimal number through the config, but nothing came of it. And also such a question, how can you turn off lightning when spawning bosses?

**Comment by kangarko** [comment]
Thank you!

I understand you want to specify 0.X to 1% spawn rates, that is planned however we are not adding new features right now.

The lightning option can be found in settings.yml in Spawning.
