### ISSUE TITLE
How do i enable timed spawning for the boss in worlds that players are not in.

### ISSUE THREAD

**Issue by questionaccount1** [kangarko/Boss#852]
Title says it all, i dont want the players to have to be within a radius of the boss for it to spawn, i want the boss to just spawn within the region on timed spawn. If it's possible plz lmk! ty for the amazing plugin!

**Comment by questionaccount1** [comment]
Check Chunk_Radius (how close a player must be to a region) and Delay (how often at least one Boss spawns).
^ the opposite of this, like if a player was in main world , and no players were in the nether, the bosses would still randomly spawn on timer

**Comment by kangarko** [comment]
Sorry this is not possible right now

**Comment by kangarko** [comment]
Or you can use a third party plugin that will invoke /boss spawn command
