### ISSUE TITLE
1.16.5: 3.10.0 Drops not saving since update

### ISSUE THREAD

**Issue by iFalcon720** [kangarko/Boss#853]
Pretty self-explanatory problem; The GUI for drops / drop chances doesn't save since the update. I saw the update changed something with drops, but I'm no expert in Java so I couldn't say if there's a typo there anywhere.
In case it's relevant, we're using Paper 570

**Comment by kangarko** [comment]
Set Debug to ["drops"] in settings.yml, restart and let me know what the console says when the boss is about to drop an item.

So when you reopen the menu there is no drops? Any console errors?

**Comment by iFalcon720** [comment]
If I go to the drops section of the boss GUI, and put anything in, leaving the GUI, trying to change the drop chances or anything else just clears the drops I put in. Theres no errors in console with the drops debug enabled as there technically aren't any drops saved. Here's a short video of what's happening when I try to add drops to a boss:
https://i.gyazo.com/2b915f8ef8766dd3c66f6aed83b93e32.mp4

**Comment by iFalcon720** [comment]
Also it seems that there's *some* saving happening, as the config files for the bosses have some drops I added, however the GUI doesn't reflect that and items only appear after a restart, where trying to change the drop chances clears the GUI anyway

**Comment by kangarko** [comment]
Can you please test on a clear server with Boss only? Seems to be this could be caused by a third party plugin as well.

**Comment by kangarko** [comment]
Will fix this in the next release
