### ISSUE TITLE
1.13.2: BOSS SPAWNING

### ISSUE THREAD

**Issue by ethxrnity** [kangarko/Boss#854]
Hi, I have such a minor problem. For my custom boss, I set it to spawn in a specific boss region (where it has the right to spawn). Unfortunately, when I set all the necessary things + in settings.yml set after how long it should spawn, even so, the boss will not sleep for himself. In addition, if I spawn more than once in the region, despite the fact that I have set only one in the region, I can still put more of them there.

Is there a way to fix that, or am I doing something wrong?

**Comment by kangarko** [comment]
Check that your boss truly doesn't leave the region, if they do, we will spawn another one even if they come back. Also check our Wiki for common pitfalls. 

Have a great day!
