### ISSUE TITLE
TPS taking hits?

### ISSUE THREAD

**Issue by Edwards07256** [kangarko/Boss#86]
Hey there, love the plugin but I have one pretty big issue. My TPS is taking huge hits when this plugin is enabled. Then as soon as I remove it, voila back to normal. I took some benchmark tests and let it run for a bit and these are the results.

https://timings.spigotmc.org/?url=melugohile

I can paste in my whole directory of plugins, possible problems with another plugin that is on my server? I am not sure at this point but if someone has a suggestion I will listen!

**Comment by kangarko** [comment]
Please ZIP me your Boss folder so I can look at your settings.

**Comment by Edwards07256** [comment]
[server40358 - 11 Apr 2018 21_4_20.zip](https://github.com/kangarko/Boss/files/1901072/server40358.-.11.Apr.2018.21_4_20.zip)

**Comment by kangarko** [comment]
Sorry for the delay, can you please test with the option Region_Keeping.Enabled on false? This will make Bosses run outside of their regions (only if you have set it so) but we need to test from where the lag is coming from.

**Comment by Edwards07256** [comment]
Didn't see you replied, but it seems a lot better man! Thanks I appreciate the help great plugin by the way, never seen a plugin like this before!
