### ISSUE TITLE
1.16.5 / 3.10.1 Boss drops still not saving

### ISSUE THREAD

**Issue by iFalcon720** [kangarko/Boss#860]
Same issue as before, drops not saving, though I noticed only the 'last' drop is saved. For example if I place 9 items in the top row of the drop gui, when I reload the boss plugin (which is the only way to update the drops atm) only the 9th shows up.
Current Boss Folder: https://www.mediafire.com/file/qny8f8hm2k3depy/Boss.rar/file

**Comment by kangarko** [comment]
Thanks, so sorry for a late answer, I'll be taking a look in 24h

**Comment by kangarko** [comment]
Identified and solved this, the next version will get out tonight :)
