### ISSUE TITLE
1.16.5: Can I still spawn an illusioner as a Boss?

### ISSUE THREAD

**Issue by Yeetlord64** [kangarko/Boss#863]
in 1.16, The Illusioner is no longer a spawnable egg. Will I still be able to make this mob a boss even though it is not an egg?

Thanks

**Comment by kangarko** [comment]
No sorry, we only support what the SpigotAPI gives us, regarding these kinds of bosses that derive from base mobs we're no longer adding this as a feature to Boss since it's maintenance-only now.
