### ISSUE TITLE
1.8.8 - v3.10.3: java.lang.NoSuchMethodError: org.yaml.snakeyaml.Yaml.<init>

### ISSUE THREAD

**Issue by noahmanscher** [kangarko/Boss#864]
I've been using Boss-3.8.15 (paid before open-source) without any huge issues, but today I decided to upgrade to the latest version, and I'm getting this error on server start:
[https://pastebin.com/h0LHbKy7](https://pastebin.com/h0LHbKy7
)
I'm not sure if this is a bad config issue (YAML-relatederror), but I didn't touch them at all before restarting.

Boss.zip attached
[Boss.zip](https://github.com/kangarko/Boss/files/6325017/Boss.zip)

**Comment by kangarko** [comment]
My bad, I shaded a library hours before fixing a problem in 1.8.8, will release a new version tonight.
