### ISSUE TITLE
Boss Natural Spawning - 1.8.9

### ISSUE THREAD

**Issue by Drevya** [kangarko/Boss#866]
I created different 10 bosses. They all have different setting, skill etc. All of them have to be born at different times for the setup I'm targeting but i didn't but I couldn't find anything for this topic. Can you help me for this ? I will need to find a solution for this for I can finish setup. The section on our Minecraft server depends on this.

**Comment by kangarko** [comment]
I am sorry for a late reply! You can check out this article to see how you can spawn Bosses at different times throughout the day/week: https://github.com/kangarko/Boss/wiki/Frequent-Questions-and-Tips#can-i-spawn-bosses-individually-at-a-certain-time
