### ISSUE TITLE
boss limit

### ISSUE THREAD

**Issue by iMxAndyy** [kangarko/Boss#87]
it would be helpful to be able to limit how many of each boss can exist at any one time. 

so if i wanted a boss to spawn every hour but never be more than 1 alive i could limit that boss to 1. so that it cant spawn another if one already exists

**Comment by SoraShiunin** [comment]
https://github.com/kangarko/Boss/issues/85
On issue 85. I cannot find a way to limit bosses globally.
I like this suggestion.

**Comment by iMxAndyy** [comment]
It would still be helpful to have an option to limit it to only 1 of a specific boss at any one time. 
Could have an option for that. and just run the butcher command for that boss whenever a new one spawns. 
Currently, if I try to set up something to both spawn and butcher that boss it rarely works.

**Comment by kangarko** [comment]
Please see Limits option in settings.yml, where you can limit how many Bosses can exist at once, per Boss or globally.

![a](https://i.imgur.com/RpG89u3.png)

**Comment by iMxAndyy** [comment]
But this only seems to limit the amount of them that can spawn naturally. 
I have some harder bosses setup to spawn by command at set intervals. 
But if the previous boss was never killed then when the next one spawns there will be 2 of them. which quickly becomes impossible to beat. 
I need a way to set the limit for that boss to 1. so that if I spawn a new one and one already exists. it either kills the old one or doesn't spawn the new one. 

I currently have to setup a butcher command to run a minute before the spawn command but having lots of these jobs setup to run as I add more and more bosses will quickly become hard to manage and having a built-in way to limit them would be very helpful.

**Comment by kangarko** [comment]
Do you have a Commands Block to spawn the bosses, or how do you spawn them?

**Comment by iMxAndyy** [comment]
I have console tasks set to run every few hours to respawn the boss. 
using the '/boss spawn world x y z' command

Doing this seems to override any limits I have set in settings.yml

**Comment by kangarko** [comment]
In the next version I have added an option to apply limits for commands and eggs as well :)
