### ISSUE TITLE
1.16.5: Spawn timer

### ISSUE THREAD

**Issue by LucasitoInDev** [kangarko/Boss#879]
**1)** 1.16.5: How to setup the respawn timing?

**2)** I'm trying to **configure the spawning timings for my boss**, I've searched for information in the wiki and with the **/boss menu** command but I don't see anything about it.

What I want to do is that, **when a boss is killed by a player**, it will spawn every **45 minutes in the same worldedit region**, with limitation to **1 boss per region**.

**Comment by kangarko** [comment]
Thanks! I believe most of your questions are answered at 

https://github.com/kangarko/Boss/wiki/Frequent-Questions-and-Tips

We're not planning on adding more features/suggestions to Boss at this time.
