### ISSUE TITLE
Individual timed spawning for bosses in a region

### ISSUE THREAD

**Issue by sirben99** [kangarko/Boss#88]
Hey! I have a sugcection about the region spawning. Plus one other queston/suggection too,

1. Would it be possible to add individual time spawning for bosses that spawn in a region? What i mean by that there is a option in the config file for timed spawning but it affects every boss. I would like to make a boss arena where lets say every 30 min it checks the spawn condisions (in this case the boss spawns in world "world" with 10% change) and every 30 min it will try to spawn the boss with the 10% change.
Long story short: Timed spawning but individual in bosses. (Kinda made that unnessaseraly long)

2. Would it be possible to block certain commands when the boss spawn in that region? Expample when the boss spawns you woudnt able to use /spawn or /home etc in that region. And when the boss dies your able to use those commands agane. But only when your in the region so it doesent disable/enable them server wide. And when the player dies in the region would it be possible that the deadth triggers a command too?

3. If the first one is possible, is it possible to add the boss spawnpoint? Example right click a block in the region and it will spawn on that block (or in air and drops down) instead of spawning randomly somewhere in the region.

I know this is maybe not what the plugin is made for but i figured to ask anyway
(Cant succees in life if you dont ask or something like that :P)

Thanks for reading and have a good day!

Edit: Oh and would it be possible to deny of placing a spawn egg in a specifict world? Example i could place a spawn egg in world Boss but i couldnt place it in world survival? Could this be optinal with individual bosses? Example i could place lets say a villager that gives you money when you kill it in the survival world but you couldnt place it in the Boss world.

Edit 2: This is propably outside what the plugin is meant to be but would it be possible to implement a party like system for the spawn egg? So that when the boss is spawned only the players in that spesifik party (maybe faction or towny support too?) can hurt and kill the boss. And also get rewards from the boss?

Edit 3: Would it be also possible to add region specivic command? Example if you kill a boss with friends and lets say put a command in the bosses death /kit Boss player it would give the players only in the region the kit boss (EssentilasX)
 
What i mean by all this that lets say those things above were implemented. The main goal of these features would be build the ultimate boss arena possibility.  So when the player gets the spawn egg, he would only able to place the spawn egg in the region defined by this plugin (/boss region). Then the player/players would have to go to a party (/boss party?) to be able to spawn the boss. When the boss spawns it would deny sertain commands (like /spawn or /tpa or /home etc) and deny other players outside the party from entering the arena where the boss is (and display a message like "There is already a boss fight going on"). When the player is killed in the boss fight (In that region) it would run a command. (Would it be possible to do sertain commands for the region like clear items on the ground?).
There also would be a timer on when the boss will be killed (Lets say you have 1 hour to kill the boss or else it will be killed. It woudnt drop it items however). And lastly when the boss is killed, the commands will the enabled agane and new boss can be spawned. (There would be a cooldown when that party could summon a new boss? And also cooldown for a party creation?)

This propably sounds like a train gone off rails but i feeled like to ask these possibilities. Sorry if this went too much off rails. (This could be a plugin or a addon for the Boss plugin in it self tbh xD)

**Comment by kangarko** [comment]
Hello!

1. Yes, definitely. This feature is scheduled in the next major feature update.

2. No sorry, this is out of realms of the Boss plugin, but if you know basic Java you can listen to BossSpawnEvent in our API and make it yourself.

3. I will look into it when adding 1., it seems definitely exciting!

For Edit: To deny spawner eggs, you can take advantage of the upcoming BossEggEvent in the next version, where you simply listen to the world in which the egg was used and cancel the event.

For Edit 2: Sorry, this is too much outside of Boss and my time schedule.

For Edit 3: You can add commands only per-Boss, not per-region, so not currently.

Sure, thank you for describing it so in details, I am definitely looking forward to add some of it in the future!

Thanks.
