### ISSUE TITLE
Minecraft Version: 1.17 - Delighted to have known this plugin

### ISSUE THREAD

**Issue by Pakumm** [kangarko/Boss#880]
Hello Kangarko, I bought your plugin in 2018, and to play with childhood friends, I am very happy to put the free plugin and make known to those who could not get it. I hope you do very well in your projects, if you update this great plugin for 1.17 it would be great, I will wait for it as well as the hf3, I hope it does not live in my memories hahaha, good luck and success I will be attentive here in any news

**Comment by kangarko** [comment]
Thank you <3 Yes we will plan on updating all plugins to 1.17 and beyond!
