### ISSUE TITLE
1.17 Deletes saved mobs.

### ISSUE THREAD

**Issue by IAmOrion15** [kangarko/Boss#883]
Hey kang! Orion again! So I recently updated my server to 1.17 paper and put the new version of Boss in the plugins folder and replaced the old .jar file (I did not touch the config file as I want nothing changed). However, when I restarted the server, all the bosses that were saved to spawners were gone. For example, if I had a "Mummy" mob which is just a husk with custom stuff, it only spawns husks now. If you could look into this, it would be a big help! Thank you! :)

**Comment by kangarko** [comment]
I unfortunately cannot help with this since Boss never removes any entities, this is likely caused by Paper's/Spigot's early builds somehow getting rid of these entities, I recommend you try again with their latest build and if it still does remove entities then raise a ticket with them.
