### ISSUE TITLE
1.16.5: What is wrong with my spawner?

### ISSUE THREAD

**Issue by AirCraze** [kangarko/Boss#884]
To ask us anything, please follow these directions:

1) Please include your Minecraft version in your title:
Example: 1.16.1: How to setup the menus?
### **1.16.5 paper**
2) Try to keep it simple and clear, providing us all information necessary to answer your question. You can use imgur.com to upload images or pastebin.com to upload large text or error traces.
### **I spawned a spawner with /boss tools. I was wondering how to spawn the boss when it's enabled in the spawner? I waited minutes, and no bosses spawned. (/gamerule doMobspawning is set to true).**
Thank you. Please remove this text and write your actual question below.

**Comment by AirCraze** [comment]
The only error I get is: Unable to spawn {boss} at this location.

**Comment by kangarko** [comment]
There's likely another plugin blocking this such as Residence, WorldGuard, GriefPrevention etc.
