### ISSUE TITLE
1.16: Equipment not saving

### ISSUE THREAD

**Issue by PeterDorvay** [kangarko/Boss#889]
[Boss.zip](https://github.com/kangarko/Boss/files/6806442/Boss.zip)

I am trying to add equipment to my `bagel_test` boss. It is a husk riding a horse. I've also tried adding equipment to my `test` boss, which is also a husk, but it is not riding anything. After adding the equipment to the slots, if I go to edit drop chances by clicking on the chest in the equipment menu, the slots go blank and the items disappear. So far this happens with every boss I've tried.

Currently on Boss 3.10.6, running Tuinity 1.16.5 on a test server.

**Comment by kangarko** [comment]
I unfortunately cannot support all paper forks, try on vanilla paper first.
