### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by bublif** [kangarko/Boss#89]
Hello,
 I would like to buy your plugin, but first I would like to know if it´s possible that you could make for me some kind of ,,upgrade".

Here is what I need and what´s my problem:
Imagine, that you fight the boss with your friends, you kill him but unfortunetly enemy player rushed around and stole the drop.  I would like to prevent it. The best solution would be, that 3 players that have caused most damage will be able to grab it. No one else. Is it possible, or have I missed something and you have any kind of solution in that way?

2nd question:
- Is it compatible with MythicMobs Items?

Thank you for your time, sorry for my bad english :-D
bublif

**Comment by kangarko** [comment]
Hello bublif,

the feature where the killers with most damage will receive drops is on the Roadmap and will be implemented in the future. At the moment I cannot tell you when it happens, so you can either purchase Boss or wait till it's added.

Boss should work with MythicMobs items, when you place them to drops or equipment or wherever else.

Thank you for your interest.
