### ISSUE TITLE
1.16.5 - How do I make console run a command when the boss is killed?

### ISSUE THREAD

**Issue by HysteriaMC** [kangarko/Boss#892]
When the boss is killed, I would like to give players a crate key, so how do I make the console run a command for those players when the boss is killed?

**Comment by kangarko** [comment]
That's actually fairly easy, check this out: 

https://github.com/kangarko/Boss/wiki/Frequent-Questions-and-Tips#how-can-i-send-custom-messages-or-commands-when-a-boss-diesspawns
