### ISSUE TITLE
BOSS lags server 

### ISSUE THREAD

**Issue by AnLan1214090013** [kangarko/Boss#894]
`Boss::Task: org.mineacademy.boss.lib.fo.remain.CompRunnable.SafeRunnable (interval:1800) count(1)  total(0.30% 0.506s, 0.67% of tick)avg(506.41ms per - 0.34ms/0.00 per tick)`
It's my timings report and my tps drops to less than 10 because of this and I dont have very much mobs on server.
I am using paperspigot 1.12.2. How can i fix this?

**Comment by kangarko** [comment]
Please see https://github.com/kangarko/Boss/wiki/Common-Issues#boss-is-lagging-my-server
