### ISSUE TITLE
transform your plugin to MCBBS

### ISSUE THREAD

**Issue by xieyiyangshadow** [kangarko/Boss#896]
Hello,I'm have a server which use your plugin.It helps me a lot.
I want to transform your plugin to MCBBS [www.mcbbs.net] which is a chinese player society.
I'll link the download address to the original address on spigot.
THANKS!

**Comment by kangarko** [comment]
Yes you can, just link to the /resources tab on this plugin page, not spigot.

**Comment by xieyiyangshadow** [comment]
ok！Thank you!
