### ISSUE TITLE
1.16.5 (purpur) - Boss dismount issue

### ISSUE THREAD

**Issue by Outlander87** [kangarko/Boss#897]
1) Minecraft 1.16.5 - Server software : PurPur Build 1171

2) I have an issue with boss dismount, i've created two custom mobs:
- custom piglin brute
- custom zoglin 

The piglin brute spawns riding zoglin, the zoglin works fine but when the zoglin dies the dismounted piglin is a vanilla piglin, without any of my customization options. No Tagname, no effects, no skills etc.

3) what i've done:
- Create again bosses from scratch
- Resetting the plugin by deleting boss folder
- tried with older versions like 3.10.5

Boss folder attached below.
thanks

EDIT: i've found the cause of the issue, the mob spawns with all attributes, skills and effects. After few seconds the mob transforms in a zombiefied piglin and then he lost all the customization.

[Boss.zip](https://github.com/kangarko/Boss/files/7001282/Boss.zip)

**Comment by kangarko** [comment]
The transformation is not caused by our Boss plugin, it is either by some vanilla behavior I am not aware of or some other plugin of yours.
