### ISSUE TITLE
1.16.5: Error loading Boss v3.9.7, plugin is disabled!

### ISSUE THREAD

**Issue by iTzAleh** [kangarko/Boss#898]
![Screenshot_9](https://user-images.githubusercontent.com/89304194/130322075-cbfae9fc-87a2-4d97-949a-9d23098436ac.png)

When I start the plugin it gives me this error, how do I fix it?
[Desktop.zip](https://github.com/kangarko/Boss/files/7025514/Desktop.zip)  ((Plugin and folder))

**Comment by kangarko** [comment]
Remove Boss/data.db and it should load. Do not use PlugMan for reloading. Do not edit data.db afterwards.
