### ISSUE TITLE
Minecraft Version: Your Question Title

### ISSUE THREAD

**Issue by romero22b** [kangarko/Boss#899]
1.15.2: How to edit the attribute explosion power from a ghast boss?
I've created a ghast boss and i try to edit the explosion power with a spawn command and a fireball but i can't edit to make more than 1.

**Comment by kangarko** [comment]
If that is not possible through Boss > Settings > Attributes menu, then unfortunately we do not have the API for that since it is not available through the standard means of Bukkit.

**Comment by romero22b** [comment]
okk thanks
