### ISSUE TITLE
1.16: Butcher command not working

### ISSUE THREAD

**Issue by Zeatth** [kangarko/Boss#900]
Hi, when I use the /boss butcher * Illidan command (Illidan is my boss name)

It doesn't work and tell me to check the error.log file.

This is what is says: https://pastebin.com/NMUgQes6

I have tried several different ways to try solve this myself and had no luck but im still new to all this.

Any idea what im doing wrong?

**Comment by kangarko** [comment]
Thanks, will be patched in a few days.
