### ISSUE TITLE
1.17.1: Console Error Entity Reflection

### ISSUE THREAD

**Issue by LucidAPs** [kangarko/Boss#901]
Server: Purpur 1.17.1-R0.1-SNAPSHOT
Boss™ 3.10.7
https://nekobin.com/nuyaqofona

Mobs don't spawn at all.

**Comment by LucidAPs** [comment]
Boss error log
https://nekobin.com/midepuvidi

**Comment by LucidAPs** [comment]
Reverting to build prior to this https://github.com/PaperMC/Paper/pull/6457
Fixes the problem. Boss needs to be updated.

**Comment by kangarko** [comment]
Will be patched today.
