### ISSUE TITLE
Oraxen and Items adder support

### ISSUE THREAD

**Issue by Outlander87** [kangarko/Boss#902]
1) How it would benefit others? 
It will support famous plugins, so many people will be happy to customize their bosses

2) What would happen if we won't implement this feature? How's your server being affected? 
I wish to create custom bosses with custom textures, so if in the near future someone wants to make bosses with custom materials they'll can't

3) If suggesting something new - Can the old system be modified/improved instead?
Yes, just support non conventional items to be weared by bosses.

As i said i'm requesting to add support for non conventional items that plugins like item adder or oraxen uses to make custom items and custom textures.
For example oraxen default hats uses "PAPER" as material, but if i put the custom hat in the head slot of the boss the hat disappear after goning back to the previous menu.
Can you add this useful feature? Thanks

**Comment by kangarko** [comment]
Sorry, at present we're not adding suggestions to Boss but I appreciate it!
