### ISSUE TITLE
Boss ClassNotFoundException error

### ISSUE THREAD

**Issue by Brasspops** [kangarko/Boss#903]
Minecraft 1.17.1 paper
I just installed Boss on my server and I got this error in the console

22.09 00:12:07 [Server] INFO ______
22.09 00:12:07 [Server] INFO (____  \
22.09 00:12:07 [Server] INFO ____)  ) ___   ___  ___
22.09 00:12:07 [Server] INFO |  __  ( / _ \ /___)/___)
22.09 00:12:07 [Server] INFO | |__)  ) |_| |___ |___ |
22.09 00:12:07 [Server] INFO |______/ \___/(___/(___/
22.09 00:12:07 [Server] INFO Successfully registered expansion: boss
22.09 00:12:07 [Server] INFO !-----------------------------------------------------!
22.09 00:12:07 [Server] INFO Error while loading Boss dependencies!
22.09 00:12:07 [Server] INFO !-----------------------------------------------------!
22.09 00:12:07 [Server] INFO Boss 3.10.9 encountered a ClassNotFoundException! Please check your error.log and report this issue with the information in that file.
22.09 00:12:07 [Server] ERROR Error occurred while enabling Boss v3.10.9 (Is it up to date?)
My error log:
https://pastebin.com/RquuWH4B

How can I fix this issue?

**Comment by kangarko** [comment]
You have to fix all of the other errors as well as clean your plugins folder off from "Ambiguous plugin name" (that means having multiple file which are the same) and it should go away
