### ISSUE TITLE
1.17.1: Plugin have placeholders? 

### ISSUE THREAD

**Issue by NewJeb** [kangarko/Boss#904]
1) 1.17.1: Plugin have placeholders? 

2) I didn't find anything on the wiki or the PAPI wiki. The plugin has placeholders, I need a placeholder for the coordinates of the boss spawn. I want to make a message in a certain radius about the spawn of the boss, and for this I need its coordinates, because by default the coordinates are taken from the player's position, or if the command is executed via the console, then from 0 0 0

**Comment by kangarko** [comment]
No sorry we're not having PlaceholderAPI placeholders right now.
