### ISSUE TITLE
1.17.1: ReflectionException

### ISSUE THREAD

**Issue by ElFlyGod** [kangarko/Boss#905]
Boss keeps sending these errors in its errors.log file 

https://paste.helpch.at/iguqemarin.m

Looks to be related to our custom plugin FuseBossSpawner but the developer of the plugin confirmed this issue is not on our end.

**Comment by kangarko** [comment]
Try on plain PaperSpigot and use Boss https://github.com/kangarko/Boss/releases/tag/3.10.10

**Comment by ElFlyGod** [comment]
Still getting the error
