### ISSUE TITLE
Discord Boss

### ISSUE THREAD

**Issue by dinobossytnew** [kangarko/Boss#916]
My suggestion or recommendation is that you can connect to discord messages when a boss appears, name, comments that say as that appeared %boss%, something else would be their statistics in the form of

1) How would it benefit others? (Not just you, but 1,000 other people using the same plugin).
Well, to the servers where there is a survival rpg like mine or just survivals that like bosses it would be good to put it since all networks like discord.

2) What would happen if we don't implement this feature? how would your server be affected? well it wouldn't change much, it would just give a touch to servers with a lot of tryhards that like farmer and boss pvp.

3) If something new is suggested - Can the old system be modified/improved instead? yes of course obviously it's free.

**Comment by dinobossytnew** [comment]
thaks

**Comment by kangarko** [comment]
@dinobossytnew I can add this, is this a good image of how that would work?

A boss is spawned > You then select a Discord channel where you send a message with %boss_name% etc. variables.

Each Boss spawning rule can have a separate Discord channel to broadcast.

Thanks,
Matej

**Comment by dinobossytnew** [comment]
> @dinobossytnew I can add this, is this a good image of how that would work?
> 
> A boss is spawned > You then select a Discord channel where you send a message with %boss_name% etc. variables.
> 
> Each Boss spawning rule can have a separate Discord channel to broadcast.
> 
> Thanks, Matej

yeah thanks plise

**Comment by dinobossytnew** [comment]
it would be like 1 emblem

**Comment by kangarko** [comment]
Sorry, at the moment we're busy with our youtube series at youtube.com/kangarko, I dont have time for this right now

**Comment by dinobossytnew** [comment]
a.. ok xd :V

**Comment by kangarko** [comment]
I had some time so I added it! https://github.com/kangarko/Boss/wiki/Boss-Commands
