### ISSUE TITLE
Boss 4.0.4 on maven repo

### ISSUE THREAD

**Issue by SkytAsul** [kangarko/Boss#926]
Currently, only Boss v3.8.0 is available on the maven repo, as explained here: https://github.com/kangarko/Boss/wiki/Developer-API#importing-the-api
Is it possible to publish new versions please?

**Comment by kangarko** [comment]
Unfortunately it's not available for the time being, I have updated the importing instructions, you can just fill a form and I will add you!

**Comment by SkytAsul** [comment]
I do not want a license to download the plugin, I want to access a maven artifact.
There is two options for you if you don't want to publicly host the plugin for download:
1. Propose developers to apply to get private access to a maven repository with the artifacts
2. Host a minimal version of the plugin, with only the API code (it is not complicated to do thanks to maven modules)

**Comment by kangarko** [comment]
I could export it, but it has tons of links to our library Foundation that it uses, hence its better if you import the jar as systemPath dependency

**Comment by SkytAsul** [comment]
?? But Foundation _is_ available as a maven dependency on Jitpack... That's much easier to publish an artifact.
Also, the "systemPath" scope is deprecated for removal.

**Comment by kangarko** [comment]
Once we make an abstraction layer for API like in Boss3, I will make the API publicly available.
