### ISSUE TITLE
1.16.5: Limit not working? Dangerous bug!

### ISSUE THREAD

**Issue by SoraShiunin** [kangarko/Boss#927]
I don't know why but limits are not working and mobs keep spawning(No errors). It took me a while to figure out why my server was constantly crashing, then I noticed there were 300 bosses in one place. 
Might be compatibility bug, not tested in an empty server.
I am on boss 4.0.4

[Boss.zip](https://github.com/kangarko/Boss/files/7447588/Boss.zip)

This is havenzombie: 
![Screenshot_2189](https://user-images.githubusercontent.com/23641964/139557882-fa52ab35-324c-4ca8-b67f-bad2297b535b.png)
![Screenshot_2190](https://user-images.githubusercontent.com/23641964/139557883-96005879-48a0-4b70-acac-d8c0d41cfe6b.png)
![Screenshot_2188](https://user-images.githubusercontent.com/23641964/139557884-70c7767e-44bb-45bb-a6f3-7ed55a920349.png)

**Comment by kangarko** [comment]
Sorry I was not able to reproduce on a clean install: https://i.imgur.com/QGs6eTp.png

Set your Debug key to [spawning], remove all other bosses except for the troubled one you showed above (so that your console is not completely spammed and readable) and post me the debug log.

**Comment by SoraShiunin** [comment]
I believe its working properly, I just had the same result. But after server restart 2 more spawned, no debug message about it  in console.
![Screenshot_2262](https://user-images.githubusercontent.com/23641964/140323547-a9151cca-0217-4050-86b8-34cdfda6dc9e.png)
![Screenshot_2263](https://user-images.githubusercontent.com/23641964/140323552-b97b48f2-31c7-4e75-8458-29719e9b9fc1.png)

**Comment by SoraShiunin** [comment]
The ones that I can think of that can interfere are maybe: MythicMobs, Towny and StackMob(It has an option so it doesn't interact with named mobs). Those are the ones that interact with mobs.


AntiAC, ConsoleSpamFix, PlayerHeads, LuckPerms, NBTEditor, ProtocolLib, AdvancedPortals, InventoryRollback, ccNoSpecTeleport, MultiverseHardcore, CleanroomGenerator, PlaceholderAPI, Runecraft, ItemEditor, SirBlobmanCore (SirBlobmanAPI, XSeries), Votifier, LibsDisguises, InfiniteVouchers, EpicGuard, NashornPlus, Vault, BKCommonLib, HolographicDisplays, Multiverse-Core, VotingPlugin, MovingDevApi, FastAsyncWorldEdit (WorldEdit), RPGHealthPlus, PlayerReferrals, ClientDetector, WorldGuard, Multiverse-Inventories, Essentials, WorldGuard-Towny, XPBoost, AdvancedRegionMarket, RewardPRO, ChatFeelings, SpectatorMode, CommandSigns, BetterJails, TAB, EssentialsSpawn, EnjinMinecraftPlugin, StackMob, Parties, NPCDestinations_Rancher, LWC, Quests, MythicMobs, NexEngine, WorldGuardExtraFlags, GoldenCrates, PhatLoots, Multiverse-NetherPortals, CombatLogX, AdvancedEnchantments, BanItem, MarriageMaster, CMILib, Jobs, UltimateShops, ActionHealth, SimplePets, Citizens, mcMMO, NPC_Destinations, Duels, QuestsGUI, Towny, WolfyUtilities, SuperVanish, CitizensText, TownyNameUpdater, CustomCrafting, Sentinel, TownyChat, Shopkeepers, SiegeWar, MobArena, DiscordSRV, MobArenaExtension, ProjectKorra, ProjectAddons, JedCore, Hyperion, Spirits, BendingGUI, Multiverse-Portals, PlayerParticles, ProCosmetics, RollbackCore, Boss, ExtraHardMode, CoreProtect, SurvivalGames, LightCleaner, Codex

**Comment by kangarko** [comment]
Try uninstalling MythicMobs and StackMob, if either is removing our NBT tag then we think there are no Bosses and spawn more.

**Comment by SoraShiunin** [comment]
Sorry I forgot I had a thing to prevent console spam and now that I tested on local I had this error spamming the console:
 https://pastebin.com/5dD8gwRf
 
I have two questions/bugs while testing.
I thought the limit was per boss but its applying to all bosses(Via Spawn Rules)? Example:
Boss1 has limit 1
Boss2 is spawned.
Theres 1 boss in the server and its boss2.
But boss1 cannot spawn since it reached limit of 1? (But there are no boss1 in the world)

Multiple bosses cannot spawn in the same location in the same spawn rule if one boss limit is reached.
Will only spawn one boss type once a boss limit is reached of either mob.

**Comment by SoraShiunin** [comment]
So I was thinking of a suggestion to solve most if not all compatibility issues that may be related to the first "bug" posted.
Since the bossess still appear in /boss find. Would it be possible to force despawn/kill bosses over a timeframe, if there are some over the limit?

**Comment by kangarko** [comment]
The error is likely caused by reloading or other error during startup, check for these. We will fix the limits in the next version. Thanks for reporting!
