### ISSUE TITLE
Light Level Addition

### ISSUE THREAD

**Issue by Pandas0** [kangarko/Boss#928]
1) I believe this suggestion would benefit others by allowing more customization on bosses/custom mobs. It would allow users to select which 'Light Level' would be required for a boss to spawn. [For example, those that use it as a custom mobs plugin and not per-say 'bosses' can select to have bosses only spawn in areas with a light level under 8 like vanilla mobs.]

2) If this feature wouldn't be implemented, I would have no choice but to stop using the plugin on my server. I use the plugin for custom mobs that randomly spawn rather than 'bosses' and currently they are spawning anywhere regardless of the light level and my players are getting upset that they can no longer afk safely.

3) I don't believe there is anything on the old system that would be modified/improved to add this feature. I believe it is a completely new thing that would need to be coded and added to the 'Spawning' section.

**Comment by kangarko** [comment]
I will add this under the Torch icon in the next version!
