### ISSUE TITLE
1.16.5 question

### ISSUE THREAD

**Issue by dinobossytnew** [kangarko/Boss#929]
I have a question mr.kanguro do you know how to place the peaceful animals to attack and when the skin will be in the menu is that I can place the skin but when I put another egg, it is still without skin.

**Comment by dinobossytnew** [comment]
error https://www.toptal.com/developers/hastebin/uvinolinib.sql new 1.16.5 paper spigot and log bosses error.log

**Comment by kangarko** [comment]
I will fix the error.

You need to install Citizens and configure the Citizens behaviors in the menu.

To change skins simply rename your Boss using Alias option.
