### ISSUE TITLE
LibDiguises Support

### ISSUE THREAD

**Issue by Owizardo** [kangarko/Boss#93]
Hi there,
Just an idead I would to see some day. It would be great to see support for Diguises libs:
https://www.spigotmc.org/resources/libs-disguises.32453/ 

This is a feature available in Mythic Mobs that really the only thing holding me back from using boss as my primary custom mobs. Could this be something possible in the future?

**Comment by kangarko** [comment]
What would you like to disguise your Boss to, using that plugin?

**Comment by kangarko** [comment]
We are not planning to include this feature at the moment due to other priorities.
