### ISSUE TITLE
Minecraft Version 1.17.1: Issue errors

### ISSUE THREAD

**Issue by SRGBread** [kangarko/Boss#930]
Having issues with errors my server is pickin up from new boss update

Version 1.17.1

![Screenshot_8](https://user-images.githubusercontent.com/93486209/139594397-0e200f41-c279-400a-a8ed-a69afaf31c4f.png)

Idk if its whats causing my issue but i am not seeing the attribute items on the menu screen when trying to edit bosses could be completely seprate but wanted to voice that

**Comment by SRGBread** [comment]
also cant select targets for the bosses to attack idk if that has anything to do with it either just another issue

**Comment by kangarko** [comment]
I will fix the error thanks for reporting!

Attributes are right here: https://i.imgur.com/EejZDFE.png

What do you mean you cant select target? Let me know below.
