### ISSUE TITLE
1.17.1 Pathfinder and AI Targets aren't clickable

### ISSUE THREAD

**Issue by morphin06** [kangarko/Boss#932]
Using version of 1.17.1
With the latest boss
For pathfinder and ai Targets aren't clickable
https://prnt.sc/1y87sjv

Here is the console error https://pastebin.com/WZZQri7s

**Comment by morphin06** [comment]
Additional issue placeholder {reward_cost}
Doesn't work
https://prnt.sc/1y99eem

**Comment by kangarko** [comment]
Thanks will be fixed tonight!
