### ISSUE TITLE
1.16.5; Renaming Bosses does not work properly in-game.

### ISSUE THREAD

**Issue by RebelDs** [kangarko/Boss#934]
Hi. Recently upgraded to Boss 4. I can't seem to set names for my bosses using color codes and spaces. 

For example, the following input for aliases:
&7[&f&lLvl. &615&7] &fSome Name Here

returns "Invalid String". Function worked just fine in 3.9,7

**Comment by kangarko** [comment]
Thanks for reporting, I will increase the max length of the alias to 256 letters from the current limit of 24.
