### ISSUE TITLE
1.16.5: The Region Tool does not work at all.

### ISSUE THREAD

**Issue by RebelDs** [kangarko/Boss#937]
So I tried creating a region in order to set up my mob spawning (Since on Boss 3 I was doing that via spawners). Unfortunately, 
./boss region new does not work; all it does is give you an iron ax with some lore on usage, but the ax itself does nothing. Tried on gamemode 1, 0, all that. Can't define a region for the life of me.

I'd suggest re-adding the spawners back because it was an easier and more convenient alternative, and perhaps with the option to disguise them as a regular block. The current system seems a bit clunky to me.

**Comment by dinobossytnew** [comment]
Can you send me the boss and list of plugins, do you get any error message?

**Comment by dinobossytnew** [comment]
BOSS has its own log, would you like to pass it on?

**Comment by RebelDs** [comment]
Plugin list: 

Plugins (53): AdvancedRegionMarket, ArmorStandTools, AureliumSkills, BannerBoard, BeautyQuests, Boss, BungeeGuard, BuycraftX, Cartographer2, ChatGames, Citizens, ClearLag, CMI, CMIEInjector, CMILib, CommandNPC, Core, CraftEnhance, CrateReloaded, DeluxeMenus, DeluxeTags, Drop2Inventory, EliteMobs, EnderContainers, FastAsyncWorldEdit, GadgetsMenu, GSit, HeadDatabase, HolographicDisplays, HolographicExtension, InteractiveBooks, ItemEdit, LibsDisguises, LiteBans, LuckPerms, MMOHorses, MMOItems, MythicLib, NoUnicode, OreRegenerator, OriginalDonatorsCore, PlaceholderAPI, PlugMan, ProtocolLib, PyroFishingPro, Shopkeepers, TAB, TradeMe, Vault, ViaVersion, VoteParty, Votifier, WorldGuard

All of them updated to the latest version.

No error (even with debug) or any sort of feedback (in-game or console). The axe acts simply as a regular axe but with a custom name & lore.

**Comment by dinobossytnew** [comment]
okey my test wait plise

**Comment by dinobossytnew** [comment]
The bug is confirmed, it doesn't let me name the region nor name it when I put /boss region list it doesn't come out as created! @kangarko

**Comment by cobrex1** [comment]
I am also having the same issue, I cannot create the region using the region tool:

https://gyazo.com/2b6c10c2bcf63983ccb8031cb6f1b9c7

Although it shows the region points selected, doing the /region new [name] give the grey text reply

**Comment by kangarko** [comment]
Are you doing it right? 1) Get the tool, 2) Right click one block, left click the other, 3) Immediatelly type the region name to the chat.

**Comment by kangarko** [comment]
I removed that command and added an info message there instead, sorry about the confusion. Comment below if this wont work on the next version.

**Comment by cobrex1** [comment]
I am using Boss 4.0.7 on 1.17.1 Paper release 378. The picture below shows that I got the updated message in chat. I wanted to test this part also. Got the silver region tool axe. Left click, right click then I typed into chat [name] for the region. Nothing happened and the name just appeared in chat. The region create tool is not working.

**Comment by kangarko** [comment]
Thanks. Those yellow messages are not coming from Boss, looks like another plugin. I will change the region tool to emerald.
