### ISSUE TITLE
1.17.1: Boss riding reset on Plugin reload

### ISSUE THREAD

**Issue by Miryex** [kangarko/Boss#938]
The Boss riding resets on Plugin reload with /boss reload. In my case
I was making a stray boss, riding on a phantom (increased size). On reload
it is always resetting to none. Works with Wither skeletons though. 

side note: Potion effects don't save when upgrading from Boss 3 -> 4

Kind regards,

**Comment by kangarko** [comment]
Sorry I cannot reproduce, try on the next Boss version, and check if other plugins are not interfering. I have reloaded Boss and the Boss kept its riding, including already spawned bosses: https://i.imgur.com/Ti4RH8W.jpeg
