### ISSUE TITLE
Workable for 1.16.5

### ISSUE THREAD

**Issue by DanielDJ1613** [kangarko/Boss#939]
Haven't tried it or bought it yet, just for one reason. So I was wondering if this pluing is funcinvael for 1.16.5!
 If it is, I will be glad to hear thinews! Answer me as soon as possible.
 Thank you

**Comment by ElBananaa** [comment]
Hey,
I'm not sure to fully understand, but I guess you want to know if the plugin works with paper/spigot 1.16.X according to the title.
The full list of supported versions can either be found on the McMarket page: https://www.mc-market.org/resources/21619/
![image](https://user-images.githubusercontent.com/53318613/140628027-dbda481b-8ac5-4738-9a98-4542b86c038e.png)

Or on our wiki page: https://github.com/kangarko/Boss/wiki/Compatibility#minecraft-version

Anyways, the short answer is: Yes, it works on 1.16.x.

**Comment by kangarko** [comment]
It works on all versions between 1.7 and 1.17 including 1.16
