### ISSUE TITLE
loot tables help

### ISSUE THREAD

**Issue by Lucifer-Angels** [kangarko/Boss#94]
my friend bought ur plugin for the server we work on im the system admin for and im trying to set the boss drops up but there isnt a specfic way i can get them to drop they just drop on the floor

i dont suppose u could add a loot table where the prize he drops goes directly into ur inventory as well as allow drops for up to so many people and add chances of it dropping like 1st is 100% 2nd is 50% 3rd 25%
so forth and a way to brocast winners 

if u need a name to verify his spigot name is keejaybe and if u need his email i have it if its needed

**Comment by kangarko** [comment]
Hello,

currently the Drops menu specify items that will be dropped on the floor only.

The suggested functionality (to drop directly into player's inventory and split by the last damagers) is in the road-map and will be included in the next major update.
