### ISSUE TITLE
1.16.5: The Boss Limit is Global although it should be Individual

### ISSUE THREAD

**Issue by RebelDs** [kangarko/Boss#940]
The rule on the amount of bosses to be spawned is GLOBAL, though all things regarding it would point at it being INDIVIDUAL.

If I set two bosses with a limit of 10 per world, and the delay in their spawning to be 5 let's say, then the plugin will get to spawn 5 Boss No.1 and 5 Boss No.2 before stopping because it counts both bosses as being the same entity (though they have no similarity in name, id, type, etc).

I believe there should be an option for a GLOBAL limit that affects all bosses and an INDIVIDUAL limit that affects individual bosses, just like in the old versions.

**Comment by kangarko** [comment]
Was not a feature, but a bug actually. I have patched this and added a global option too!
