### ISSUE TITLE
Model Engine

### ISSUE THREAD

**Issue by dinobossytnew** [kangarko/Boss#947]
1) How it would benefit others? (Not just you, but 1,000s of others people using the same plugin.)
   Well, if you have the Model Engine you will be able to put unique models to the bosses without using the mythicmobs plugin which is heavier.

2) What would happen if we won't implement this feature? How's your server being affected?
I would have to migrate to mythicmobs to be able to use the model engine.

3) If suggesting something new - Can the old system be modified/improved instead?
I am clear that I give a recommendation as it will attract more buyers and more users on our servers due to the freedom of bosses.

**Comment by morphin06** [comment]
I am planning to suggest it this today, but i saw you already made it, Hope this will implement, because i am using Mythicmobs for custom model mobs at the same time with boss plugin , But if boss plugin support this, I can remove mm since its heavy.

**Comment by kangarko** [comment]
Thanks, but I do believe the engine itself is quite heavy as well. We have no plans on including this right now, but I am open doing this to the next major rewrite.

**Comment by dinobossytnew** [comment]
ok ty @kangarko 7w7
