### ISSUE TITLE
1.17.1: TnT/Fireball BLOCK-BREAK option not working

### ISSUE THREAD

**Issue by Miryex** [kangarko/Boss#948]
The Boss Skills Obsidian Bomb / Fireball Explosion BLOCK-BREAK option are not working for me. 
The Skills them self work are working fine. 
https://imgur.com/a/s8g2KGy
(I have tested it, using only the Boss Plugin)

**Comment by kangarko** [comment]
Duplicate of https://github.com/kangarko/Boss/issues/941, please do not create duplicated issue. I am investigating this.
