### ISSUE TITLE
Custom skills are disabled after restart

### ISSUE THREAD

**Issue by KlasterStormInc** [kangarko/Boss#95]
I added a custom skill via BossSkillRegistry, but when plugin enabled it says "Ignoring unknown skill 'ArrowScattering' for Boss Witch". 
Skill is available in menu. But it disabled for bosses, because they was loaded before skills registered. What should I do?

**Comment by kangarko** [comment]
Hello,

when is it disabled? Does it not work at all, or it is disabled after the server has been shut down and started again? What about /reload or /b reload?

**Comment by KlasterStormInc** [comment]
After shut down and start. And after /reload, /b reload too.

**Comment by KlasterStormInc** [comment]
As I understand "/b reload" removes all registered custom skills.
Is is possible to re-load only bosses after skills registration?

**Comment by kangarko** [comment]
You can listen to PluginEnableEvent and register the skills there, that would make it function upon /reload.

In the next version I have fixed the skills disappearing after /b reload.
