### ISSUE TITLE
[Outdated Plugin version & Awaiting upgrade aproval] Error in console (magma cube related)

### ISSUE THREAD

**Issue by ElFlyGod** [kangarko/Boss#950]
Getting this error https://paste.helpch.at/cehomiqike.sql
Using Boss v3.11.0 (Dont tell me to update without checking the issue)

Boss is the only plugin installed, using airplane 1.17.1 latest

I also need to be added on the buyers list on MCMarket because i bought it on spigot. 
Profile: https://www.mc-market.org/members/69017/

**Comment by ElBananaa** [comment]
> Getting this error https://paste.helpch.at/cehomiqike.sql Using Boss v3.11.0 (Dont tell me to update without checking the issue)
> 
> Boss is the only plugin installed, using airplane 1.17.1 latest
> 
> I also need to be added on the buyers list on MCMarket because i bought it on spigot. Profile: https://www.mc-market.org/members/69017/

Hey!

Please fill in the upgrade form on this link https://mineacademy.org/boss/ (Scroll down a bit then fill everything) to get the plugin in mcmarket.

As for your issue, once you gain access to the plugin (Kangarko will let you know by mail when it's done), update the plugin, and try again.

**Comment by kangarko** [comment]
Thanks, we will approve your upgrade asap. The cast exception should be solved, I believe we have a completely different approach to this. Either way, if there is anything else just let me know below.
