### ISSUE TITLE
1.17.1: "None" function not working

### ISSUE THREAD

**Issue by Miryex** [kangarko/Boss#951]
Setting a skill message to "none" doesn't remove the text anymore. It says in chat "none"

Kind regards,

**Comment by ElBananaa** [comment]
> Setting a skill message to "none" doesn't remove the text anymore. It says in chat "none"
> 
> Kind regards,

Hey!
Remove the content of the message instead of putting `none`.
So it should look like : `Notification: ''`, as example.

**Comment by Miryex** [comment]
Creates empty messages for me:
https://imgur.com/a/PExii7W

**Comment by Miryex** [comment]
Another bug, Bosses cant seem to spawn under Netherroof when using Random-Spawning (at least for me)

**Comment by ElBananaa** [comment]
> Creates empty messages for me: https://imgur.com/a/PExii7W

Oh, right, my bad. Could you try this format: `Notification: none`

**Comment by Miryex** [comment]
Uh, doesn't seem to fix it. I had set originally set it to 'none'
Both setting it to none or 'none' doesn't remove it. 
https://imgur.com/naYzuyL
https://imgur.com/o6R6ePA
https://imgur.com/aBX8unH

**Comment by kangarko** [comment]
@ElBananaa just a note, "none" and none are the same, there is no difference.

This is a bug, thanks for reporting, I will patch this! Regarding the spawning bug, I am afraid we cannot fix this at the moment, I will put this to the backlog.
