### ISSUE TITLE
1.17.1 - Regions do not spawn Bosses on entry

### ISSUE THREAD

**Issue by cobrex1** [kangarko/Boss#952]
1) 1.17.1 - paper release 386, Boss 4.0.8

2) I have created a region using the diamond tool (thank you for this fix) and set the rule for a Boss to spawn in the region on a player entering the region.

![2021-11-20_07 49 54](https://user-images.githubusercontent.com/44735826/142718962-d6e7887f-c456-4e87-b351-12277ebdd540.png)
 
When any player enters the region the boss should spawn, however, nothing happens, no Boss. I have tested with op'ed and non-op'ed players.

I have set the debug option to [spawning] and nothing appears in console - it is as if the event is not even triggered.

**Comment by kangarko** [comment]
Thanks, sorry for delays. I made you a quick video:

https://www.loom.com/share/83d41947b572472f8c0231919a22f928
