### ISSUE TITLE
Version 1.17.1 Boss 4.10: Delayed Commands on Spawned Mobs

### ISSUE THREAD

**Issue by chylerzg** [kangarko/Boss#960]
I have an invulnerable zombie that I want to die 15 seconds after being spawned. How should I go about doing this? I was considering maybe doing a command when the mob spawned but I realized the plugin doesn't support delayed commands in order for it to die in the 15 seconds needed. Thank you so much.

**Comment by chylerzg** [comment]
I found a temporary fix by giving the Zombie a certain amount of health and then giving it the health effect but I still want it to know if there is a better way to do it.

**Comment by kangarko** [comment]
Hmm, interesting. You can use an external plugin to time the command and then start the command when the Boss spawns. Really unique request, I am afraid we cannot serve you here, but is easy to do with a help of another plugin such as this one:

https://www.spigotmc.org/resources/delayed-command.44956/
