### ISSUE TITLE
1.16.5 - Reloading Chunks Respawns Boss.

### ISSUE THREAD

**Issue by SoraShiunin** [kangarko/Boss#962]
Hello, so following up on previous issues of bossess ignoring limit. I tested on a clean server with just FAWE, Essentials and Essentials Spawn. I recorded whats happening. It doesn't always happen and its incosistent but it does happen.
Basically reloading Chunks respawns bossess. On this recording I got it to spawn 1 over the limit, but sometimes way more than that spawn as long as the chunk is "refreshed". (Just now after server restart it also spawned another one, so I guess server shutting down also counts as a chunk "refresh")
Video to big to post: 
https://www.youtube.com/watch?v=scjR6rRL9GA&feature=youtu.be

Boss Folder: [Boss.zip](https://github.com/kangarko/Boss/files/7688462/Boss.zip)

**Comment by kangarko** [comment]
So sorry for the delay, going to investigate this asap. Typically a fix will be pushed in less than 24 hours.

**Comment by kangarko** [comment]
Fixed internally. Was a problem in our cache, which got reset each few seconds and within that period reported less Bosses than actually spawned. Thanks for your patience.
