### ISSUE TITLE
1.16.5 : Bossess ignoring limits and spawning in unloaded chunks

### ISSUE THREAD

**Issue by SoraShiunin** [kangarko/Boss#967]
Turns out the bossess were still mas spawning in the server so I investigated in a local with only these plugins:
![Screenshot_2404](https://user-images.githubusercontent.com/23641964/146427038-58fdbfc6-d2da-4508-8077-4d3eeee2432c.png)

For some reason bossess still spawn in unloaded chunks after a while and ignore the limit? 
Someone has to be online but they can be anywhere except in those chunks where the locations are and they will spawn.
Here is a video of it happening. 
https://youtu.be/oNWvG4F6eqc
At the start I show the limits then I stand still for a while very far from the area and they spawn after a while.
Here is the boss folder:
[Boss.zip](https://github.com/kangarko/Boss/files/7729609/Boss.zip)

**Comment by kangarko** [comment]
We had a report of this as of late, please confirm you're on the latest Boss version which should have patched this.

**Comment by kangarko** [comment]
If not then please set the Debug key in settings.yml to [spawning], restart the server and report console messages when demonstrating what you did in your YouTube video. It should say something along how many Bosses our plugin *thinks* are spawned and point out to potential errors.

**Comment by SoraShiunin** [comment]
Currently on 4.1.3 version. 
Looked fine, then I killed the bossess while they were unloaded and they started spawning over and over.
Even tho the limit is checked, they keep spawning, here is a paste of the console:
https://pastebin.com/bPxZB2EF

**Comment by kangarko** [comment]
Thanks, going to have a look in 24 hours

**Comment by kangarko** [comment]
I've added a "success" message to the debug spawning log because right now it only says when it failed to spawn but does not say when the spawning was successful.

Also I completely removed Boss spawn cache. Let me know how this problem goes in the next version!

**Comment by kangarko** [comment]
Closing to cleanup, let's continue below still.

**Comment by SoraShiunin** [comment]
I believe that fixed it. No issues in testing so far.

**Comment by SoraShiunin** [comment]
Hello, I updated boss from 4.1.5 to 4.1.8 and it started happening again(On MC 1.16.5). Seems to be the exact same thing, teleporting away/unloading chunk lets the boss spawn again and again. Loading the chunk stops it.

**Comment by kangarko** [comment]
Let's continue on https://github.com/kangarko/Boss/issues/984
