### ISSUE TITLE
2 New Features

### ISSUE THREAD

**Issue by BlackGamer000** [kangarko/Boss#97]
Hello everyone!

I'm Here to give 2 ideas For the Boss Plugin 

Ok so.... Let's start.

Idea 1: New Directory in the Boss Folder

This directory is Called CustomSkills and in This folder are inserted all the CustomSkills in .jar file for Integrate him in the Boss "Framework" 

When the Jar files are Inserted in the Folder With a Command /boss CSkills Configure You can open a GUI With all the new Skills to Configure it with This Properties:

Name Of the Skill
Default Messages to say When the Boss use their abilities.
Ability Description:

If there are Errors when You Load the Skills the Plugin Say some Ideas for fix in the Code Part.

2 Idea: Community Skills: With this Idea all the Users That Have buyed Boss can Submit some Custom Skills with the Description of the Skill etc. 

Hope these Ideas are Good. Bye c:

**Comment by kangarko** [comment]
Hello and thank you for the ideas!

For the first one, you can already create your own plugin and use it with Boss to create a custom skill. You can find more information about it in the wikipedia.

For the second one, seems great, a common place where users could submit their skills would be awesome.

**Comment by BlackGamer000** [comment]
Hi Kangarko! Thanks for the Response. :)

I forgot the particular details about the first Feature, I really meant a directory that does not count the skill as a plugin, but it is directly integrated into the plugin
