### ISSUE TITLE
1.17.1: When a Boss is summoned in an un-rendered chunk it causes issues

### ISSUE THREAD

**Issue by bipedd** [kangarko/Boss#970]
When trying to summon a boss in an un-rendered chunk it gives me this in the console: 
[19:58:55 INFO]: BOSS // Unable to spawn SupremeBoss in this location!
Something still spawns at the location but it's very weird, it'll spawn a wither skeleton (the mob type) without the name or glow and with vanilla health, still dropping items on death. Its own ability ends up just killing itself.

Video: https://imgur.com/a/5dhjP9c

**Comment by bipedd** [comment]
[Boss-2021-12-24T010507Z.tar.gz](https://github.com/kangarko/Boss/files/7772009/Boss-2021-12-24T010507Z.tar.gz)

My boss folder

**Comment by kangarko** [comment]
Thanks, I'll make the chunk force load in case it is not to spawn a boss.
