### ISSUE TITLE
1.18 API method change

### ISSUE THREAD

**Issue by PikaMug** [kangarko/Boss#971]
1) Please include your Minecraft version in your title:
_1.18_

2) Try to keep it simple and clear, providing us all information necessary to answer your question. You can use imgur.com to upload images or pastebin.com to upload large text or error traces.
_In newer versions of Boss, what is the equivalent of `BossDeathEvent#getBoss().getSettings().getCustomName()`?_

**Comment by kangarko** [comment]
Boss#getAlias :)
