### ISSUE TITLE
paper #133 MC 1.18.1 | issue: dungeons end stage using bossTM

### ISSUE THREAD

**Issue by JetString** [kangarko/Boss#974]
Boss version 4.1.7
Dungeons isn't recognizing the boss being killed in the end stage.
The log files clearly show the boss spawning and the boss being killed. however when killing the boss in question the dungeon does not end. There are no error logs.

In paper build #119 and boss 4.1.5 all of this worked.

I only could get version 4.1.7 to work deleting my original yaml files. Then copying back the bosses.

Notably! The boss in question was broken and i had an error in the console(some format error: ' ' . which i couldn't figure out, because seemingly there was no such error...

I had to delete and redo the boss, which I did. I also redid the stage in dungeons and reassigned the boss. Still the problem persists.

As I mentioned on discord this might be a problem with Dungeons itself, so I will also report the error there.

**Comment by kangarko** [comment]
What is the error? How does the "Dungeon" should recognize the Boss? If that is a plugin you will likely need to talk to the developer.

**Comment by JetString** [comment]
Ok, after testing further.
It turns out the changes in the upstream and therefor in the bossTM plugin simply have caused the need to re align also **yaml files** that are **not directly related** to bossTM. In my case I have to actually redo all the Dungeons that use bossTM's bosses as kill objectives.
I tested this simply creating a new dungeon and setting one of bossTM's bosses as a kill objective and it eventually worked.

**Comment by kangarko** [comment]
Thank you for sharing! Please make sure you're using the very latest Boss version from yesterday.
