### ISSUE TITLE
Songoda Site, brought Boss plugin

### ISSUE THREAD

**Issue by AlternativeSoap** [kangarko/Boss#976]
Hi, my problem is I just brought Boss from Songoda, but I can't download it. Is it even updated inside there?

My name is AlternativeSoap, and on Discord AlternativeSoap#7770

- My payment ID inside PayPal, so you know it's me. "57H16169D09381813"

**Comment by kangarko** [comment]
Can you check now please? Sometimes it takes longer to update.

**Comment by AlternativeSoap** [comment]
Nope, it still doesn't work. My account name is AlternativeSoap.

**Comment by kangarko** [comment]
@AlternativeSoap sorry for the delay, I just forcefully re-added you, should be good. Next time please email us for matej@mineacademy.org, this bug tracker is for technical help, for licensing issue we prefer email with fastest response time :)
