### ISSUE TITLE
1.18.1 release 133 and 136 - ClassCastException

### ISSUE THREAD

**Issue by cobrex1** [kangarko/Boss#977]
Updated a few of the Bosses we use in CoreArena, changing the drops the bosses give, reloaded and there appeared to be no issues. On server reboot Boss fails to load with the above message.

https://pastebin.com/j8MkUpD2

**Comment by cobrex1** [comment]
Following a little more testing, it is when player specific drops are defined in the GUI for the boss which then creates this error

**Comment by kangarko** [comment]
Please upload me your /boss debug and I'll have a look at your specific config. Sorry for the delay!

**Comment by kangarko** [comment]
Anyways, I fixed that!

**Comment by cobrex1** [comment]
Sorry Matej, I have been at a family funeral and only returned today so please accept my apology for not responding

**Comment by kangarko** [comment]
Okay no probs! :(

**Comment by cobrex1** [comment]
Thank you tested the latest and it works fine :)
