### ISSUE TITLE
Help Me Plugin boss License is inactive: Contact seller

### ISSUE THREAD

**Issue by MasterSongSoojin** [kangarko/Boss#978]
Mc-market
User : BlackWhile
[https://ibb.co/m59mPys](url)

**Comment by ElBananaa** [comment]
Hey,
If you lost your license, simply resubmit the upgrade form at https://mineacademy.org/chatcontrol-red#upgrade (you can submit it for other plugins there, too) and we'll approve it within 1-3 days maximum.
