### ISSUE TITLE
1.18.1: Failed to load boss MySlime from bosses

### ISSUE THREAD

**Issue by jonathan-lr** [kangarko/Boss#979]
2) Be clear: What is your current situation, the desired situation, and your problem?
Plugin fails to load after server restart. Assuming it is not something to do with the boss I created. Have tried to make bosses on multiple clean installs and still the same error occurs.

3) If needed - upload your plugin's folder here and any errors using pastebin.com
[Boss.zip](https://github.com/kangarko/Boss/files/7834652/Boss.zip)
Errors in the Boss.zip folder

**Comment by kangarko** [comment]
I'm terribly sorry for this, but Spigot introduced a breaking change without notice. We already have addressed it, however looks like your file got corrupted. You'd need to redownload https://github.com/kangarko/Boss/issues/975 and recreate the Boss

**Comment by jonathan-lr** [comment]
[Boss.zip](https://github.com/kangarko/Boss/files/7847769/Boss.zip)
The same issue occurs with the 4.1.7 release.

**Comment by kangarko** [comment]
I cannot reproduce on the upcoming version. Are you on Paper by the way? I am testing using this: https://i.imgur.com/O1r2PPf.png

Remove the file completely once again on the next version and let me know.

**Comment by jonathan-lr** [comment]
I am using spigot 1.18.1 
https://imgur.com/a/30Jv8kN

On a fresh install, the plugin will load correctly at first, and restarting the server is fine. Once a boss is created on restart the plugin doesn't load correctly.
[Boss.zip](https://github.com/kangarko/Boss/files/7853439/Boss.zip)

**Comment by kangarko** [comment]
Are you please able to use Paperspigot? https://papermc.io/downloads

Looks like you are not even using Spigot but CraftBukkit which may cause this.

**Comment by jonathan-lr** [comment]
Paperspigot works fine thanks for the info. Was 100% using spigot before was unaware it wasn't supported.

**Comment by kangarko** [comment]
It should be, but they've recently messed up with settings and introduced some breaking changes
