### ISSUE TITLE
Don't work Reinforcements

### ISSUE THREAD

**Issue by LeviPrime** [kangarko/Boss#98]
If I took boss in this menu, and kill (naturally) boss, new boss don't spawn :<

**Comment by kangarko** [comment]
Hello,

please post me your settings.yml file and your Boss' .yml file from /bosses folder both uploaded to pastebin.com

Also note that the spawning conditions such as lightning or region will apply for reinforcements, meaning if you spawn a boss from egg and you kill him, but the Boss should naturally only spawn in a certain region, no reinforcements will appear.

**Comment by LeviPrime** [comment]
When I kill boss console get this: 
![image](https://user-images.githubusercontent.com/38867032/39665829-65757c4c-50b3-11e8-9af5-0a2dc230f8f3.png)
AraxnaTwo is not pigman :D
And when I choose other bosses and enable reinformacements - text edit only name not type of mob .-.
Other settings don't edit, only adding new skills

**Comment by kangarko** [comment]
The debug messages should be fixed. I am closing this, but please comment below if your issue still persists and upload your settings.yml to pastebin.com.
