### ISSUE TITLE
1.16.5 (Bug Report and Question) 

### ISSUE THREAD

**Issue by jmancox330** [kangarko/Boss#982]
Question:
![image](https://user-images.githubusercontent.com/51308174/149587765-67c8429d-2803-43e7-aac9-a6bcac7bd05b.png)
Any way to disable this?

Bug:
The HP of slimes and magma cubes do not change with the max health option, instead with the slime size option. Getting no errors in console.

**Comment by kangarko** [comment]
Give yourself negative boss.use.inspect permission and this message won't show.

Regarding the health issue, this is a server side bug, not in Boss unfortunately.
