### ISSUE TITLE
1.18.1: Spawn limits not being respected

### ISSUE THREAD

**Issue by LurgenAU** [kangarko/Boss#984]
I'm seeing something odd - it doesn't look like the world spawning limit setting is being respected. Despite setting it very low (5), players are reporting large numbers of mobs accumulating in their areas. I also set the search radius for each custom mob to 40 blocks, with a max of 5 other mobs in the radius so the limits should be applying in at least two ways. Screenshots:
https://cdn.discordapp.com/attachments/926649488641237052/931643367413141524/2022-01-14_14.11.20.png
https://cdn.discordapp.com/attachments/926649488641237052/931643367782236170/2022-01-14_14.11.23.png
https://cdn.discordapp.com/attachments/899348065813676122/931702928316694559/unknown.png
[boss.zip](https://github.com/kangarko/Boss/files/7876427/boss.zip)

**Comment by LurgenAU** [comment]
Disabling the plugin on my server...
Boss // Removed 295 Bosses from world.
[Boss 4.1.6]: Command /boss butcher world took 70.31 ms

Players are starting to get really mad at me.

**Comment by SoraShiunin** [comment]
Dropping this here.
"Hello, I updated boss from 4.1.5 to 4.1.8 and it started happening again(On MC 1.16.5). Seems to be the exact same thing, teleporting away/unloading chunk lets the boss spawn again and again. Loading the chunk stops it."
https://github.com/kangarko/Boss/issues/967#issuecomment-1013637377

**Comment by kangarko** [comment]
Sorry to hear this...

So running /boss butcher will correctly recognize and remove the excessive bosses right?

**Comment by kangarko** [comment]
Please set Debug to [spawning-limit] in the next version. It is going to spit out console messages like these: 

![a](https://i.imgur.com/Gs7Z08Q.png)

Which gives us clue how Boss perceives the nearby bosses limit, I need to see this before continuing, was not able to reproduce this on my own :/

**Comment by LurgenAU** [comment]
/boss butcher does indeed correctly detect and remove the bosses, often zapping up to 200 of them at a time.

I enabled debug:
Debug:
- 'spawning'

I tried this, and 'spawning-limit', but neither are giving me anything on the console. Butcher is still demonstrating that there are monsters to kill

**Comment by kangarko** [comment]
Sorry for the delay! Could you do /boss debug command? I wanted to review the zip file above but it lacked general.txt which I want to see, going to investigate again in 24h.

**Comment by LurgenAU** [comment]
[debug.zip](https://github.com/kangarko/Boss/files/7930204/debug.zip)

**Comment by kangarko** [comment]
I do think this is caused by the BloodMoon plugin or WildStacker. Either one of those is corrupting our Boss functionality. You need to remove mob-altering plugins one-by-one to see which one is the cause, it's incompatible, I'm sorry.
