### ISSUE TITLE
API or access to jar

### ISSUE THREAD

**Issue by Rocologo** [kangarko/Boss#986]
Hi Kangarko

I am the developer of MobHunting (and BagOfGold) in the past I had added support for you Boss plugin, but after you have left SpigotMC I am not able to download the jar anymore to add support. 

After you have updated Boss the integration has broken and some of my users (and your) has asked me to add support for the new version of Boss.

Could I get a free upgrade of Boss or would you be able to add an API I could use? (I dont use Boss on my own server, so this is only for other server owners, which I guess has paid or got a free upgrade)

Kind regards
Rocologo

**Comment by Rocologo** [comment]
https://github.com/Rocologo/MobHunting/issues/730

**Comment by ElBananaa** [comment]
Hey!
Could you please provide us your mcmarket profile link (or your Songoda/Polymart ones if you'd rather)?
The plugin is not obfuscated so you can have a direct access to the API using the jar file. It'll also allow Kangarko to grant you access to it faster ^^

**Comment by Rocologo** [comment]
I have created an profile now: https://www.mc-market.org/members/340221/

**Comment by kangarko** [comment]
@Rocologo I've added you to MCMarket, you can now download Boss my friend!
