### ISSUE TITLE
1.18.1 Paper Server Boss4 with Citizen

### ISSUE THREAD

**Issue by Kurix777** [kangarko/Boss#989]
Hey Team,

i started to try create my own Boss NPC
I created it as NPC Player and gave him Equipment and activated the Citizen Settings.

i named the Boss like me Ingame as Kuratex ( went extremely Wrong because multiverse inventory ) so i switch to kuratex_boss1
Renamed him to Kuratex so boss npc gets my skin. My inventory worked so far. 

after i put in my Settings my Boss will Randomly spawn with just his Sword, sometimes without Sword and he never wears his Leather Armor. 
( i gave him 4 pieces leather armor ) but they dont show up

But when i choose what the NPC should Attack ( where the eggs menu opens ) i choose player an he Attacks and follows me for 3-4 Hits and then himself for like 3-4 Hit too and switches Back to me.

I want a npc citizen mob boss with my name if that works, if it confuses my server because a Player with the Name Kuratex exists and a NPC i give him another Name, but i noticed this behavior everytime i use citizen npc as ai config, he attacks himself then the players and then himself again 

What am i doing wrong? No errors in console when that happens also when it spawns the leather armor don‘t show up but no errors

**Comment by kangarko** [comment]
Can you please try using another name to avoid plugin conflicts? Will that resolve the issue?

**Comment by Kurix777** [comment]
Hey, so i tried again and gave him a Random Name, he still attacks himself with citizen plugin.
Now i see in the Server Console there is showing up 'Invalid entity rotation: NaN, discarding when that happens.

Sorry for Bad English not my native language.

any suggestions ?

**Comment by kangarko** [comment]
Sorry, I will fix that on my end in the next version!
