### ISSUE TITLE
Spawn limits not being respected - Unloaded Chunks

### ISSUE THREAD

**Issue by LucidAPs** [kangarko/Boss#991]
Uncontrollable boss spawning, completely crashed the server.
https://nekobin.com/gokidahadi

Bosses will bypass worldlimit spawning rules when I move away from the set location spawning, and they will continue to spawn forever until the server crashes. If I go back to the location spawning the bosses respect the worldlimit again and stop spawning.

Also I tried the despawn when far away setting and it didnt work, I also tried to enable all limit conditions and it didnt work. Mobs spawn uncontrollably when no players are around, through the location spawn feature.

Here is debuging, you can see that I hit the limit, then I go away and they start spawning again, then I do /back and they hit the limit again.
https://nekobin.com/nibaruwobe

I am using no mob alerting plugins, and even if it is something else I believe Boss has the responsibility here to fix this on its end!

Edit: I would like to also mention that this doesn't happen on version 3 of Boss.

**Comment by LucidAPs** [comment]
#984

**Comment by kangarko** [comment]
I need to see your /boss debug zip please.

**Comment by LucidAPs** [comment]
> I need to see your /boss debug zip please.
Here it is.
[debug.zip](https://github.com/kangarko/Boss/files/8015408/debug.zip)

**Comment by kangarko** [comment]
Please try this test version below. I made it so that bosses won't spawn in unloaded chunks. It will print a debug message when a spawn is ignored because the chunk is unloaded

[Boss-4.2.0.jar.zip](https://github.com/kangarko/Boss/files/8017465/Boss-4.2.0.jar.zip)

**Comment by LucidAPs** [comment]
> Please try this test version below. I made it so that bosses won't spawn in unloaded chunks. It will print a debug message when a spawn is ignored because the chunk is unloaded
> 
> [Boss-4.2.0.jar.zip](https://github.com/kangarko/Boss/files/8017465/Boss-4.2.0.jar.zip)

They still spawn, they start spawning as soon as the server starts even with no players online. And when I visit the chunks the limit is working like before
https://nekobin.com/niyohicaqa

**Comment by kangarko** [comment]
I have added an option Location_Spawn_Nearby_Player_Radius under "Spawning" key in settings.yml that will only run the Location spawnrule when at least one player is in the given radius, defaults to 30 blocks.

Otherwise it will print out the spawning debug message "Not running due to players not in nearby radius".

[Boss-4.2.0.jar.zip](https://github.com/kangarko/Boss/files/8021476/Boss-4.2.0.jar.zip)

**Comment by kangarko** [comment]
Thanks for your patience and submitting all the necessary info!
