### ISSUE TITLE
Your Suggestion Title

### ISSUE THREAD

**Issue by happylizard20** [kangarko/Boss#992]
Hello,

You already had an addon to the beatyquests plugin. However, this doesn't work anymore after you released the boss v4. I therefore hope that this feater comes back with the plugin beatyquests.
I think several servers are interested in this because it allows me to make really nice quests by making the 2 plugins work with each other.

If this feature doesn't get updated I'll have to look for another boss plugin and see if it works. But I find this boss plugin so easy and nice to create bosses.

The system that is now in the beatyquests is outdated and must therefore be renewed. According to the owner of the questsplugin, he has come to you before, but little has come of it.

In any case, I hope that it can be fixed and that I can continue with both plugins.

Kind regards,
Joel Deunk

**Comment by kangarko** [comment]
Thanks, I am willing to gift Boss4 license for free to anyone who can implement this, just apply at mineacademy.org/chatcontrol-red
