### ISSUE TITLE
1.16.5: Bosses are gone

### ISSUE THREAD

**Issue by happylizard20** [kangarko/Boss#994]
Hello,
I'm having a problem with the bosses I've created. I recently put a new version of boss in it and because of that all my bosses are no longer in the /boss menu
Even if I now create a boss and do /boss reload(or restart my server) it automatically disappears from the boss menu. the files are staying in the console bosses folder.
The version is 4.2.1 and restarting does not fix the problem.
![il;wkutfgysa](https://user-images.githubusercontent.com/81618499/153717699-0ac9e51c-d744-4142-8886-0278daa32e20.PNG)
![wuky,rfa](https://user-images.githubusercontent.com/81618499/153717700-15d2a95e-5fef-4dc0-9cd8-5aa8e754af0a.PNG)

Error Pastebin: https://pastebin.com/m2XzmBt9 
Zip:
[Boss.zip](https://github.com/kangarko/Boss/files/8053885/Boss.zip)

Can someone help me with this?

Kind regards,
Joel Deunk

**Comment by dinobossytnew** [comment]
dear, plise versión software paper, porpur , spigot
? and server?

**Comment by SoraShiunin** [comment]
Same here. 
https://pastebin.com/0ve4HtAN

**Comment by kangarko** [comment]
Use Paper for now, we're investigating this. Looks like things are changing in the way they're storing configuration and we need to either workaround it (again) or use our own system.

**Comment by SoraShiunin** [comment]
Its happening on paper too. My current server version is paper 1.18.1

**Comment by kangarko** [comment]
You need to reset your config unfortunately after switching since it has been corrupted by non-paper forks

**Comment by kangarko** [comment]
I will be working on the issue with non-Paper distributions, sorry for the inconvenience.
