### ISSUE TITLE
Get access to the API

### ISSUE THREAD

**Issue by SkytAsul** [kangarko/Boss#998]
Hello
I followed the procedure here to get access to Boss v4 API: https://github.com/kangarko/Boss/wiki/Developer-API#importing-the-api
Twice.
Got no response in two months.
My users are waiting for me to implement a Boss integration in my quests plugin. Please answer.

**Comment by ElBananaa** [comment]
Hey,
I'm sorry about the delays, I guess Kangarko missed your application.
Could you please provide your mcmarket profile link here?

**Comment by SkytAsul** [comment]
Sorry I never thinked about checking my profile to see if the resource has been added for me, as I never got confirmation by mail. I actually have an access to the plugin on mcmarket.
Thank you.
