### ISSUE TITLE
Version 1.18.1: Animal damage not working properly 

### ISSUE THREAD

**Issue by iludiz** [kangarko/Boss#999]
Whenever I try to make a passive mob's damage higher with the damage multiplier, it's damage doesn't change. The mob uses the given multiplier once, then never again.  I have tried to give it potion effects, to no avail.
Also the issue is the same with the skills, it uses it one of them once, then it continues killing without it.

**Comment by iludiz** [comment]
https://github.com/kangarko/Boss/files/8251937/debug.zip

The entity is recognized, but when I change the alias, the name appears twice above the mob.

Note: I have changed the version to 4.3.2, since I updated my server to 1.18.2.

**Comment by iludiz** [comment]
Update: Even hostile mobs, that don't use citizens, do not do any damage.
Without any armor on the player they give damage, however with full armor they do not damage the player. :(

**Comment by kangarko** [comment]
You're using the WildStacker plugin which may render our Bosses incompatible, plus using Purpur which we don't support officially. I recommend try using Paper instead of Purpur and try removing WildStacker for a test round to see if these problems persist.
